const assert=require('node:assert/strict'),fs=require('node:fs'),{calculate:c,defaults:d}=require('../engine.cjs');
const results=[];function test(label,fn){try{fn();results.push({label,status:'PASS'})}catch(e){results.push({label,status:'FAIL',error:e.message})}}const near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
const b=c(d),legacy=c({...d,areaMode:'solid',profile:'legacy',Lf:610,fsGround:2.5,fsBond:2.5,fhwa:false});
test('原版預設：三項極限能力與水平能力',()=>{near(legacy.ultimate,168.480236799918);near(legacy.ground,330.574086973986);near(legacy.grout,281.102956219009);near(legacy.horizontalCapacity,98.949772043216)});
test('範例 B：鋼絞線真實金屬面積及補充上限',()=>{near(b.At,6.909);near(b.steel,78.7626);near(b.T,67.5752885522204);assert.ok(b.pass)});
test('獨立 SI 驗算：力、握裹、抗拔及伸長',()=>{const q=JSON.parse(fs.readFileSync(__dirname+'/si-results.json'));near(b.T*9.80665,q.T_kN);near(b.ground*9.80665,q.ground_kN);near(b.grout*9.80665,q.grout_kN);near(b.steel*9.80665,q.steel_kN);near(b.elongation,q.delta_mm)});
test('低加壓砂土原式分支',()=>near(c({...d,method:'sand'}).ground,211.310198523403));
test('低加壓黏土原式分支',()=>near(c({...d,method:'clay'}).ground,198.344452184392));
test('直接容許應力不二次折減',()=>near(c({...d,stressBasis:'allowable',strength:10000}).steel,69.09));
test('原型實心面積與鋼絞線面積不可混用',()=>assert.ok(legacy.A>b.A*1.28));
test('軸力輸入不再次除 cosθ',()=>near(c({...d,loadMode:'axial',load:b.T}).T,b.T));
test('kgf／tf 換算不改結果',()=>near(c({...d,loadUnit:'kgf',load:63500}).T,b.T));
test('kN／tf 換算不改結果',()=>near(c({...d,loadUnit:'kN',load:622.722275}).T,b.T));
test('自由段幾何正確：交點同時滿足兩條直線',()=>{const t=d.theta*Math.PI/180,beta=b.beta*Math.PI/180;near(d.L1+b.slip*Math.sin(t),d.L2-b.slip*Math.cos(t)*Math.tan(beta));near(b.requiredLf,691.588255184243)});
test('自由段不足與等號邊界',()=>{assert.equal(c({...d,Lf:600}).checks.find(x=>x.key==='free').ok,false);assert.equal(c({...d,Lf:b.requiredLf}).checks.find(x=>x.key==='free').ok,true)});
test('外部滑動面交點不套平面公式',()=>{const r=c({...d,slipMode:'custom',slipDistance:850});near(r.requiredLf,1081.6);assert.equal(r.checks.find(x=>x.key==='free').ok,false)});
test('錨碇段 300cm 可等號通過',()=>assert.equal(c({...d,La:300}).checks.find(x=>x.key==='length').ok,true));
test('錨碇長度超過10m 不假報全設計已合格',()=>assert.ok(c({...d,La:1200}).warnings.some(x=>x.includes('線性'))));
test('錨碇中心距150cm、4D邊界',()=>{assert.equal(c({...d,D:37.5,spacing:150}).checks.find(x=>x.key==='spacing').ok,true);assert.equal(c({...d,D:40,spacing:150}).checks.find(x=>x.key==='spacing').ok,false)});
test('傾角 10° 及高傾角輸入界限',()=>{assert.equal(c({...d,theta:10}).checks.find(x=>x.key==='inclination').ok,false);assert.ok(c({...d,theta:90}).errors.length)});
test('最大試驗力超過80%能被獨立判出',()=>{const r=c({...d,testFactor:1.6});assert.equal(r.checks.find(x=>x.key==='test').ok,false);assert.equal(r.checks.find(x=>x.key==='steel').ok,true)});
test('長久安全係數下限',()=>{assert.equal(c({...d,period:'permanent'}).checks.find(x=>x.key==='factors').ok,false);assert.equal(c({...d,period:'permanent',fsSteel:2,fsGround:3,fsBond:3}).checks.find(x=>x.key==='factors').ok,true)});
test('減支數與增荷重應使強度失敗',()=>{assert.ok(!c({...d,number:4}).pass);assert.ok(!c({...d,load:200}).pass)});
test('空值、零值、分數支數與不合理深度阻擋',()=>{for(const patch of [{D:0},{load:NaN},{number:2.5},{L1:1200},{fsGround:0.5},{method:'bad'},{alpha:1.1,method:'clay'}])assert.ok(c({...d,...patch}).errors.length)});
test('FHWA試驗倍率1.33可等號通過、1.329不可',()=>{assert.ok(c({...d,testFactor:1.33}).checks.find(x=>x.key==='testMinimum').ok);assert.ok(!c({...d,testFactor:1.329}).checks.find(x=>x.key==='testMinimum').ok)});
test('試驗1.6T建議支數按80%極限上限向上取整',()=>assert.equal(c({...d,testFactor:1.6}).requiredN,8));
test('鎖定1.5T建議支數按70%極限上限向上取整',()=>assert.equal(c({...d,lockFactor:1.5}).requiredN,8));
test('鋼棒顯示02492適用範圍限制',()=>assert.ok(c({...d,areaMode:'solid'}).warnings.some(w=>w.includes('不包括鋼棒'))));
fs.writeFileSync(__dirname+'/numeric-results.json',JSON.stringify({count:results.length,passed:results.filter(x=>x.status==='PASS').length,results,exampleB:b},null,2));console.log(JSON.stringify(results,null,2));if(results.some(x=>x.status==='FAIL'))process.exit(1);
