/* Isolated footing, Taiwan kgf/cm units. No external dependencies. */
(function(root){'use strict';
const bars={4:{db:1.27,area:1.267},5:{db:1.59,area:1.986},6:{db:1.91,area:2.865},7:{db:2.22,area:3.871},8:{db:2.54,area:5.067},9:{db:2.87,area:6.469},10:{db:3.22,area:8.143},11:{db:3.58,area:10.07}};
const defaults={L:3,B:3,h:65,Df:1.3,cx:.6,cy:.6,ex:0,ey:0,cover:7.5,fc:280,fy:4200,barX:8,barY:8,sx:15,sy:15,lower:'x',gammaC:2.4,gammaS:1.8,qa:25,qaType:'gross',phiS:30,mu:.5,cohesion:0,passive:0,active:0,qs:0,fsSlide:1.5,fsOT:2,zw:100,gammaSat:2,lambdaMode:'auto',dMode:'average',pedestal:false,cases:[{name:'S1｜D + L',type:'S',N:180,Mx:0,My:0,Hx:0,Hy:0,wf:1,uf:1,qaFactor:1},{name:'U1｜1.2D + 1.6L',type:'U',N:250,Mx:0,My:0,Hx:0,Hy:0,wf:1.2,uf:1.2,qaFactor:1},{name:'U2｜1.4D',type:'U',N:133,Mx:0,My:0,Hx:0,Hy:0,wf:1.4,uf:1.4,qaFactor:1}]};
function rect(x0,x1,y0,y1){return [[x0,y0],[x1,y0],[x1,y1],[x0,y1]]}
function clip(poly,a,b,c){const out=[];if(!poly.length)return out;let p=poly.at(-1),vp=a*p[0]+b*p[1]+c;for(const q of poly){let vq=a*q[0]+b*q[1]+c;if((vq>=0)!==(vp>=0)){let t=vp/(vp-vq);out.push([p[0]+t*(q[0]-p[0]),p[1]+t*(q[1]-p[1])])}if(vq>=0)out.push(q);p=q;vp=vq}return out}
// Integrals [1,x,y,x²,xy,y²] by degree-two exact triangle quadrature.
function moments(p){let r=[0,0,0,0,0,0];if(p.length<3)return r;for(let i=1;i<p.length-1;i++){let t=[p[0],p[i],p[i+1]],A=Math.abs((t[1][0]-t[0][0])*(t[2][1]-t[0][1])-(t[2][0]-t[0][0])*(t[1][1]-t[0][1]))/2;for(let j=0;j<3;j++){let x=(4*t[j][0]+t[(j+1)%3][0]+t[(j+2)%3][0])/6,y=(4*t[j][1]+t[(j+1)%3][1]+t[(j+2)%3][1])/6;r[0]+=A/3;r[1]+=A*x/3;r[2]+=A*y/3;r[3]+=A*x*x/3;r[4]+=A*x*y/3;r[5]+=A*y*y/3}}return r}
function solve3(A,b){let m=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<3;i++){let k=i;for(let j=i+1;j<3;j++)if(Math.abs(m[j][i])>Math.abs(m[k][i]))k=j;[m[i],m[k]]=[m[k],m[i]];if(Math.abs(m[i][i])<1e-18)throw Error('接觸解奇異');let d=m[i][i];for(let j=i;j<4;j++)m[i][j]/=d;for(let k2=0;k2<3;k2++)if(k2!==i){let v=m[k2][i];for(let j=i;j<4;j++)m[k2][j]-=v*m[i][j]}}return m.map(r=>r[3])}
function pressure(L,B,N,Sx,Sy){if(N<=0)throw Error('有效垂直力 ≤ 0，無壓力接觸平衡。');if(Math.abs(Sx/N)>=L/2||Math.abs(Sy/N)>=B/2)throw Error('合力位於基底範圍外，無有限壓力接觸解。');let box=rect(-L/2,L/2,-B/2,B/2),target=[N,Sx,Sy],v=[N/(L*B),12*Sx/(B*L**3),12*Sy/(L*B**3)];function state(w){let poly=clip(box,w[1],w[2],w[0]),m=moments(poly),J=[[m[0],m[1],m[2]],[m[1],m[3],m[4]],[m[2],m[4],m[5]]],F=J.map(r=>r.reduce((s,x,i)=>s+x*w[i],0)),err=F.map((x,i)=>x-target[i]),norm=Math.hypot(err[0]/N,err[1]/(N*L),err[2]/(N*B));return{poly,m,J,F,err,norm}}let st=state(v),iterations=0,history=[{iteration:0,v:[...v],F:[...st.F],residual:st.norm,step:0}];for(;iterations<80&&st.norm>1e-10;iterations++){const beforeV=[...v],jacobian=st.J.map(row=>[...row]),error=[...st.err];let dv=solve3(st.J,st.err),step=1,ok=false;for(let k=0;k<30;k++){let nv=v.map((x,i)=>x-step*dv[i]),ns=state(nv);if(ns.norm<st.norm){v=nv;st=ns;history.push({iteration:iterations+1,v:[...v],F:[...st.F],residual:st.norm,step,beforeV,jacobian,error,delta:[...dv]});ok=true;break}step/=2}if(!ok)break}if(st.norm>1e-7)throw Error('壓力接觸未收斂，請調整幾何或偏心。');let q=box.map(([x,y])=>Math.max(0,v[0]+v[1]*x+v[2]*y));return{v,poly:st.poly,area:st.m[0],qmax:Math.max(...q),qmin:Math.min(...q),full:st.m[0]>L*B*(1-1e-9),residual:st.norm,iterations,F:st.F,box,history,moments:st.m,cornerQ:q}}
function pIntegral(p,poly){let m=moments(clip(poly,p.v[1],p.v[2],p.v[0])),v=p.v;return[v[0]*m[0]+v[1]*m[1]+v[2]*m[2],v[0]*m[1]+v[1]*m[3]+v[2]*m[4],v[0]*m[2]+v[1]*m[4]+v[2]*m[5]]}
function intersectRect(poly,b){return clip(clip(clip(clip(poly,1,0,-b[0]),-1,0,b[1]),0,1,-b[2]),0,-1,b[3])}
function flex(As,b,d,fc,fy){const beta=Math.max(.65,.85-.05*Math.max(0,fc-280)/70),ey=fy/2040000;let lo=0,hi=d;for(let j=0;j<80;j++){let c=(lo+hi)/2,eps=.003*(d-c)/c,steel=Math.min(fy,2040000*eps);if(.85*fc*b*beta*c>As*steel)hi=c;else lo=c;}const c=(lo+hi)/2,a=beta*c,et=.003*(d-c)/c,stress=Math.min(fy,2040000*et),phi=et>=ey+.003?.9:et<=ey?.65:.65+.25*(et-ey)/.003;return{As,a,c,et,phi,stress,beta,ey,b,d,fc,fy,lo,hi,iterations:80,balance:.85*fc*b*a-As*stress,capacity:Math.max(0,phi*As*stress*(d-a/2)/100000),ductile:et>=ey+.003-1e-10};}
function asReq(M,b,d,fc,fy,info){M=Math.abs(M);const done=(value,extra)=>{if(info)Object.assign(info,{M,b,d,fc,fy,value},extra);return value};if(M<1e-12)return done(0,{branch:'zero'});const beta=Math.max(.65,.85-.05*Math.max(0,fc-280)/70),ey=fy/2040000,amax=beta*.003*d/(ey+.006),maxAs=.85*fc*b*amax/fy,maxMoment=.9*maxAs*fy*(d-amax/2)/100000;if(maxMoment<M-1e-9)return done(Infinity,{branch:'limit',beta,ey,amax,maxAs,maxMoment});const disc=d*d-2*M*100000/(.9*.85*fc*b);return done(.85*fc*b*(d-Math.sqrt(Math.max(0,disc)))/fy,{branch:'finite',beta,ey,amax,maxAs,maxMoment,disc});}
function bandCount(n,s,lo,hi){let cnt=0;for(let j=0;j<n;j++){let pos=(j-(n-1)/2)*s/100;if(pos>=lo-1e-10&&pos<=hi+1e-10)cnt++}return cnt;}
function development(db,spacing,cover,fc,fy,available){const cb=Math.min(cover+db/2,spacing/2),ratio=Math.min(2.5,cb/db),psi=db<=1.91?.8:1,ld=Math.max(30,fy*psi*db/(3.5*Math.min(26.5,Math.sqrt(fc))*ratio));return{db,spacing,cover,fc,fy,cb,ratio,psi,raw:fy*psi*db/(3.5*Math.min(26.5,Math.sqrt(fc))*ratio),sqrtFc:Math.min(26.5,Math.sqrt(fc)),ld,available,ok:available>=ld};}
function validate(i){let errs=[];if(!i||typeof i!=='object'||Array.isArray(i))return ['案例資料須為物件'];if(!Array.isArray(i.cases))return ['荷載組合須為陣列'];if(i.cases.length>100)return ['荷載組合不可超過100列'];if(typeof i.pedestal!=='boolean')errs.push('柱自重選項格式無效');for(const k of ['L','B','h','Df','cx','cy','cover','fc','fy','sx','sy','gammaC','gammaS','qa','gammaSat','fsSlide','fsOT'])if(!Number.isFinite(i[k])||i[k]<=0)errs.push(k+' 必須為正數');for(const k of ['ex','ey','qs','cohesion','zw','phiS','passive','active','mu'])if(!Number.isFinite(i[k]))errs.push(k+' 必須為有限數值');if(i.L>100||i.B>100||i.h>500||i.Df>100||i.sx<2.5||i.sy<2.5)errs.push('本版尺寸上限 L、B、Df 100 m，h 500 cm；筋距至少2.5 cm');if(i.Df<i.h/100)errs.push('埋深 Df 不可小於基礎厚度');if(Math.abs(i.ex)+i.cx/2>i.L/2+1e-9||Math.abs(i.ey)+i.cy/2>i.B/2+1e-9)errs.push('柱斷面超出基礎邊界');if(i.fc<175||i.fc>700||i.fy<2800||i.fy>4200)errs.push('本版材料範圍：fc′ 175–700、fy 2800–4200 kgf/cm²');if(i.cover<7.5)errs.push('本版按接觸土壤澆置，淨保護層須 ≥ 7.5 cm');if(i.mu<0||i.mu>Math.min(.6,Math.tan(i.phiS*Math.PI/180))+1e-9)errs.push('底面摩擦係數不得超過 min(0.6, tanφ)');if(i.phiS<0||i.phiS>=45||i.passive<0||i.passive>1||i.active<0||i.active>1||i.qs<0||i.cohesion<0||i.zw<0||i.gammaSat<=1)errs.push('地盤參數超出允許範圍');if(!['x','y'].includes(i.lower)||!['gross','net'].includes(i.qaType)||!['auto','on'].includes(i.lambdaMode)||!['average','min'].includes(i.dMode))errs.push('案例選項格式無效');if(!bars[i.barX]||!bars[i.barY])errs.push('鋼筋號數不支援');else if(i.B*100<=2*i.cover+bars[i.barX].db||i.L*100<=2*i.cover+bars[i.barY].db)errs.push('基礎寬度不足以配置保護層與底筋');if(!Array.isArray(i.cases)||!i.cases.some(c=>c?.type==='S')||!i.cases.some(c=>c?.type==='U'))errs.push('至少需要一組使用與一組強度荷載');for(const c of i.cases||[]){if(!c||typeof c!=='object'){errs.push('荷載列格式無效');continue}if(typeof c.name!=='string'||c.name.length>80)errs.push('組合名稱格式無效');if(!['S','U'].includes(c.type)||!['N','Mx','My','Hx','Hy','wf','uf','qaFactor'].every(k=>Number.isFinite(c[k]))||c.wf<0||c.uf<0||c.qaFactor<=0)errs.push('荷載組合數值或類型無效')}return errs}
function calculate(input){let errors=validate(input);if(errors.length)return{errors};let i=JSON.parse(JSON.stringify(input));if(errors.length)return{errors};let bx=bars[i.barX],by=bars[i.barY],dx=i.h-i.cover-bx.db/2-(i.lower==='y'?by.db:0),dy=i.h-i.cover-by.db/2-(i.lower==='x'?bx.db:0),d=i.dMode==='min'?Math.min(dx,dy)/100:(dx+dy)/200;if(Math.min(dx,dy)<15)return{errors:['兩向有效深度須至少 15 cm']};let A=i.L*i.B,Ac=i.cx*i.cy,depth=i.Df-i.h/100,wet=Math.max(0,depth-i.zw),dry=depth-wet,soilPSF=i.gammaS*dry+i.gammaSat*wet+i.qs,ws=soilPSF*(A-Ac),wc=i.gammaC*A*i.h/100,wp=i.pedestal?i.gammaC*Ac*depth:0,U=Math.max(0,i.Df-i.zw)*A,cb=[i.ex-i.cx/2,i.ex+i.cx/2,i.ey-i.cy/2,i.ey+i.cy/2],box=rect(-i.L/2,i.L/2,-i.B/2,i.B/2),nx=Math.floor((i.B*100-2*i.cover-bx.db)/i.sx)+1,ny=Math.floor((i.L*100-2*i.cover-by.db)/i.sy)+1,Asx=nx*bx.area,Asy=ny*by.area,fx=flex(Asx,i.B*100,dx,i.fc,i.fy),fy=flex(Asy,i.L*100,dy,i.fc,i.fy),minx=.0018*i.B*100*i.h,miny=.0018*i.L*100*i.h,Ka=Math.tan((45-i.phiS/2)*Math.PI/180)**2,Kp=1/Ka,earthInt=i.gammaS*Math.min(i.Df,i.zw)**2/2+(i.gammaSat-1)*Math.max(0,i.Df-i.zw)**2/2+i.gammaS*Math.min(i.Df,i.zw)*Math.max(0,i.Df-i.zw),Ppx=i.passive*Kp*earthInt*i.B,Ppy=i.passive*Kp*earthInt*i.L,Pax=i.active*Ka*(earthInt+i.qs*i.Df)*i.B,Pay=i.active*Ka*(earthInt+i.qs*i.Df)*i.L;
let results=[];for(const c of i.cases){let w=c.wf,u=c.uf,N=c.N+w*(wc+ws+wp)-u*U,Sx=c.My+(c.N+w*wp-w*soilPSF*Ac)*i.ex,Sy=-c.Mx+(c.N+w*wp-w*soilPSF*Ac)*i.ey,entry={...c,Ntotal:N,Sx,Sy};try{let p=pressure(i.L,i.B,N,Sx,Sy);entry.p=p;let qallow=i.qaType==='gross'?i.qa:i.qa+(i.gammaS*Math.min(i.Df,i.zw)+(i.gammaSat-1)*Math.max(0,i.Df-i.zw));entry.qallow=qallow;entry.bearing=p.qmax/(qallow*c.qaFactor);let H=Math.hypot(Math.abs(c.Hx)+Pax,Math.abs(c.Hy)+Pay),res=i.mu*N+i.cohesion*p.area+(H>0?(Ppx*(Math.abs(c.Hx)+Pax)+Ppy*(Math.abs(c.Hy)+Pay))/H:0);entry.sliding={H,res,Pax,Pay,Ppx,Ppy};entry.fsSliding=H>0?res/H:Infinity;entry.ot=[];function overturn(size,offset,moment){return Math.min(...[-1,1].map(sign=>{let R=(Math.max(0,c.N)+w*wp)*(size/2-sign*offset)+w*(wc+ws)*size/2+sign*w*soilPSF*Ac*offset+Math.max(0,-sign*moment),O=Math.max(0,-c.N)*(size/2-sign*offset)+u*U*size/2+Math.max(0,sign*moment);entry.ot.push({size,offset,moment,sign,R,O,FS:O>0?R/O:Infinity});return O>0?R/O:Infinity}))}entry.fsOTx=overturn(i.L,i.ex,c.My);entry.fsOTy=overturn(i.B,i.ey,-c.Mx);entry.fsOT=Math.min(entry.fsOTx,entry.fsOTy);entry.exr=Sx/N;entry.eyr=Sy/N;
// Exact distributed net upward integrals, excluding downward overburden over column.
entry.integrals=[];function net(poly){let pr=pIntegral(p,poly),m=moments(poly),mc=moments(intersectRect(poly,cb)),uniform=u*U/A-w*(wc/A+soilPSF);const value=pr.map((x,j)=>x+uniform*m[j]+w*soilPSF*mc[j]);entry.integrals.push({poly:poly.map(v=>[...v]),contact:clip(poly,p.v[1],p.v[2],p.v[0]),qm:moments(clip(poly,p.v[1],p.v[2],p.v[0])),m,mc,pr,uniform,value});return value}
let all=net(box),sides=[];for(const [axis,sign,pos,dd,b] of [['x',-1,cb[0],dx/100,i.B],['x',1,cb[1],dx/100,i.B],['y',-1,cb[2],dy/100,i.L],['y',1,cb[3],dy/100,i.L]]){let poly=clip(box,axis==='x'?sign:0,axis==='y'?sign:0,-sign*pos),r=net(poly),M=sign*(r[axis==='x'?1:2]-pos*r[0]),sv=net(clip(box,axis==='x'?sign:0,axis==='y'?sign:0,-sign*(pos+sign*dd)))[0],as=axis==='x'?Asx:Asy,dcm=dd*100,rho=as/(b*100*dcm),ls=i.lambdaMode==='on'||!p.full?Math.min(1,Math.sqrt(2/(1+dcm/25))):1,Vc=Math.min(1.33,2.12*ls*Math.cbrt(rho))*Math.sqrt(i.fc)*b*100*dcm/1000,cap=axis==='x'?fx.capacity:fy.capacity;const asMeta={};sides.push({asMeta,axis,sign,pos,b,dcm,rho,as,Vc,net:r,cut:pos+sign*dd,sv,coefficient:Math.min(1.33,2.12*ls*Math.cbrt(rho)),axisCandidates:[1.33,2.12*ls*Math.cbrt(rho)],M,Vu:Math.abs(sv),capacity:cap,shearCap:.75*Vc,shearRatio:Math.abs(sv)/(.75*Vc),ratio:Math.abs(M)/cap,top:M<0,AsReq:asReq(M,b*100,dcm,i.fc,i.fy,asMeta),lambda:ls})}entry.sides=sides;
let bounds=[cb[0]-d/2,cb[1]+d/2,cb[2]-d/2,cb[3]+d/2],interior=bounds[0]>-i.L/2&&bounds[1]<i.L/2&&bounds[2]>-i.B/2&&bounds[3]<i.B/2;entry.punch={interior};if(interior){let a=i.cx+d,b=i.cy+d,bo=2*(a+b),inside=net(rect(...[bounds[0],bounds[1],bounds[2],bounds[3]])),V=all[0]-inside[0],Tx=all[1]-inside[1]-i.ex*V,Ty=all[2]-inside[2]-i.ey*V,Jy=d*a**3/6+a*d**3/6+d*b*a*a/2,Jx=d*b**3/6+b*d**3/6+d*a*b*b/2,gx=1-1/(1+2/3*Math.sqrt(a/b)),gy=1-1/(1+2/3*Math.sqrt(b/a)),vmax=Math.max(...[-1,1].flatMap(s=>[-1,1].map(t=>Math.abs(V/(bo*d)+gx*Tx*(s*a/2)/Jy+gy*Ty*(t*b/2)/Jx))))/10,ls=i.lambdaMode==='on'||!p.full?Math.min(1,Math.sqrt(2/(1+d*100/25))):1,beta=Math.max(i.cx,i.cy)/Math.min(i.cx,i.cy),vc=ls*Math.min(1.06,.53*(1+2/beta),.265*(2+40*d/bo))*Math.sqrt(i.fc),bandx=Math.min(i.B/2,cb[3]+1.5*i.h/100)-Math.max(-i.B/2,cb[2]-1.5*i.h/100),bandy=Math.min(i.L/2,cb[1]+1.5*i.h/100)-Math.max(-i.L/2,cb[0]-1.5*i.h/100),vdirect=Math.abs(V)/(bo*d)/10,high=vdirect>.75*.53*ls*Math.sqrt(i.fc),localX=high?5*vdirect*bandx*100*bo*100/(.75*40*i.fy):.0018*bandx*100*i.h,localY=high?5*vdirect*bandy*100*bo*100/(.75*40*i.fy):.0018*bandy*100*i.h,mBandX=(1-gx)*Math.abs(Tx),mBandY=(1-gy)*Math.abs(Ty),asBandX=bandCount(nx,i.sx,Math.max(-i.B/2,cb[2]-1.5*i.h/100),Math.min(i.B/2,cb[3]+1.5*i.h/100))*bx.area,asBandY=bandCount(ny,i.sy,Math.max(-i.L/2,cb[0]-1.5*i.h/100),Math.min(i.L/2,cb[1]+1.5*i.h/100))*by.area;entry.punch={interior,bounds,a,b,inside,all,beta,candidates:[1.06,.53*(1+2/beta),.265*(2+40*d/bo)],corners:[-1,1].flatMap(s=>[-1,1].map(t=>({x:s*a/2,y:t*b/2,direct:V/(bo*d)/10,mx:gx*Tx*(s*a/2)/Jy/10,my:gy*Ty*(t*b/2)/Jx/10,value:(V/(bo*d)+gx*Tx*(s*a/2)/Jy+gy*Ty*(t*b/2)/Jx)/10}))),V,Tx,Ty,bo,d,Jx,Jy,gx,gy,vmax,vc,capacity:.75*vc,ratio:vmax/(.75*vc),lambda:ls,bandx,bandy,localX,localY,asBandX,asBandY,bandCapX:flex(asBandX,bandx*100,dx,i.fc,i.fy).capacity,bandCapY:flex(asBandY,bandy*100,dy,i.fc,i.fy).capacity,mBandX,mBandY,high,vdirect};}
entry.netBalance=Math.abs(all[0]-(c.N+w*wp))/Math.max(1,Math.abs(c.N+w*wp));entry.flexRatio=Math.max(...sides.map(s=>s.ratio));entry.shearRatio=Math.max(...sides.map(s=>s.shearRatio));entry.needsTop=sides.some(s=>s.top&&Math.abs(s.M)>1e-6);entry.fail=c.type==='S'?(entry.bearing>1||entry.fsSliding<i.fsSlide||entry.fsOT<i.fsOT):(entry.flexRatio>1||entry.shearRatio>1||(interior&&entry.punch.ratio>1));}catch(e){entry.error=e.message;entry.fail=true}results.push(entry)}
const demandCandidates=[{axis:'x',name:'最少鋼筋量',value:minx},{axis:'y',name:'最少鋼筋量',value:miny}];let maxM={x:0,y:0},maxAs={x:minx,y:miny},short=i.L>=i.B?'y':'x',betaFoot=Math.max(i.L,i.B)/Math.min(i.L,i.B),distFactor=2*betaFoot/(betaFoot+1);for(const r of results.filter(r=>r.type==='U'&&!r.error)){for(const s of r.sides){maxM[s.axis]=Math.max(maxM[s.axis],Math.abs(s.M));demandCandidates.push({axis:s.axis,name:r.name+'｜'+s.axis+(s.sign<0?'−側':'＋側')+'抗彎',value:s.AsReq});maxAs[s.axis]=Math.max(maxAs[s.axis],s.AsReq)}if(r.punch.interior){r.punch.reqMetaX={};r.punch.reqMetaY={};const reqX=asReq(r.punch.mBandX,r.punch.bandx*100,dx,i.fc,i.fy,r.punch.reqMetaX)*i.B/r.punch.bandx,reqY=asReq(r.punch.mBandY,r.punch.bandy*100,dy,i.fc,i.fy,r.punch.reqMetaY)*i.L/r.punch.bandy,minX=r.punch.localX*i.B/r.punch.bandx,minY=r.punch.localY*i.L/r.punch.bandy;demandCandidates.push({axis:'x',name:r.name+'｜柱帶最少換算全寬',value:minX},{axis:'x',name:r.name+'｜柱帶彎矩換算全寬',value:reqX},{axis:'y',name:r.name+'｜柱帶最少換算全寬',value:minY},{axis:'y',name:r.name+'｜柱帶彎矩換算全寬',value:reqY});maxAs.x=Math.max(maxAs.x,minX,reqX);maxAs.y=Math.max(maxAs.y,minY,reqY)}}const rawMaxAs={...maxAs};maxAs[short]*=distFactor;
let spacingLimit=Math.min(2*i.h,45),spacingOK=i.sx<=spacingLimit&&i.sy<=spacingLimit&&i.sx-bx.db>=Math.max(2.5,bx.db)&&i.sy-by.db>=Math.max(2.5,by.db),reinforceOK=Asx>=maxAs.x&&Asy>=maxAs.y&&spacingOK&&fx.ductile&&fy.ductile;let devX=development(bx.db,i.sx,i.cover,i.fc,i.fy,(i.L/2-Math.abs(i.ex)-i.cx/2)*100-i.cover),devY=development(by.db,i.sy,i.cover,i.fc,i.fy,(i.B/2-Math.abs(i.ey)-i.cy/2)*100-i.cover);let localBandsOK=results.filter(c=>c.type==='U'&&!c.error&&c.punch.interior).every(c=>c.punch.asBandX>=c.punch.localX&&c.punch.asBandY>=c.punch.localY);reinforceOK=reinforceOK&&devX.ok&&devY.ok&&localBandsOK;
let review=results.some(r=>r.type==='U'&&!r.error&&(!r.punch.interior||r.needsTop||Math.abs(r.punch.Tx||0)>1e-7||Math.abs(r.punch.Ty||0)>1e-7))||results.some(r=>!r.error&&!r.p.full)||i.active>0||i.passive>0||i.cohesion>0,fail=results.some(r=>r.fail)||!reinforceOK;const out={errors:[],i,A,Ac,dx,dy,d,ws,wc,wp,U,soilPSF,Asx,Asy,nx,ny,fx,fy,minx,miny,maxM,maxAs,demandCandidates,rawMaxAs,short,distFactor,spacingLimit,spacingOK,reinforceOK,localBandsOK,devX,devY,Ka,Kp,Ppx,Ppy,Pax,Pay,results,review,fail,status:fail?'NG':review?'REVIEW':'PASS'};out.trace=trace(out);return out;}
// This renderer reads intermediate values recorded by calculate/pressure/flex.
// This renderer reads intermediate values recorded by calculate/pressure/flex.
function trace(r){
 const i=r.i,steps=[],n=v=>Number.isFinite(v)?Number(v.toPrecision(12)).toString():v===Infinity?'∞（無有限需求／容量）':'不可求得',vec=a=>a.map(n).join(', '),poly=a=>a.length?a.map(v=>'('+vec(v)+')').join(' → '):'空集合',add=(title,formula,substitution,result,unit='',condition='',source='')=>steps.push({title,formula,substitution,result:typeof result==='number'&&!Number.isFinite(result)?n(result):result,unit,condition,source});
 const rc='臺灣混凝土規範112年版（113年勘誤）https://www.nlma.gov.tw/filesys/file/EMMA/c1130219-1.pdf';
 function reqTrace(title,q){if(!q)return;add(title,'amax=β1×.003d/(εy+.006)；As,max=.85fc′b amax/fy；Mmax=.9As,max fy(d−amax/2)/100000；AsReq=.85fc′b[d−√max(0,d²−2M×100000/(.9×.85fc′b))]/fy',q.branch==='zero'?'|M|='+n(q.M)+' tf·m < 1e−12，需求採0':`M=${n(q.M)} tf·m；b=${n(q.b)} cm；d=${n(q.d)} cm；fc′=${q.fc}、fy=${q.fy} kgf/cm²；β1=${n(q.beta)}；εy=${n(q.ey)}；amax=${n(q.beta)}×.003×${n(q.d)}/(${n(q.ey)}+.006)=${n(q.amax)} cm；As,max=.85×${q.fc}×${n(q.b)}×${n(q.amax)}/${q.fy}=${n(q.maxAs)} cm²；Mmax=${n(q.maxMoment)} tf·m；${q.branch==='finite'?'判別式='+n(q.disc)+' cm²；平方根='+n(Math.sqrt(Math.max(0,q.disc)))+' cm；AsReq='+n(q.value)+' cm²':'M超過拉力控制上限，需求∞，不回傳虛構有限解'}`,n(q.value),'cm²',q.branch==='limit'?'拉力控制容量不敷，NG；不繼續開方。':'沿用原引擎拉力控制需求反解，所有值於asReq執行時保存。',rc+'，8.3.3、21.2.2、22.2');}
 const dep=i.Df-i.h/100,wet=Math.max(0,dep-i.zw),dry=dep-wet;
 add('面積、埋深與地下水','A=L B；Ac=cx cy；覆土厚度=Df−h/100；wet=max(0,覆土厚度−zw)；dry=覆土厚度−wet',`A=${i.L}×${i.B}=${n(r.A)} m²；Ac=${i.cx}×${i.cy}=${n(r.Ac)} m²；覆土=${i.Df}−${i.h}/100=${n(dep)} m；wet=max(0,${n(dep)}−${i.zw})=${n(wet)} m；dry=${n(dep)}−${n(wet)}=${n(dry)} m`,r.A,'m²','水的單位重固定1 tf/m³；土重與浮力使用不同係數，保留原引擎水位定義。');
 add('覆土、基腳與柱自重及浮力','soilPSF=γs dry+γsat wet+qs；Ws=soilPSF(A−Ac)；Wc=γc A h/100；Wp=γc Ac depth（勾選時）；U=max(0,Df−zw) A',`soilPSF=${i.gammaS}×${n(dry)}+${i.gammaSat}×${n(wet)}+${i.qs}=${n(r.soilPSF)} tf/m²；Ws=${n(r.soilPSF)}×(${n(r.A)}−${n(r.Ac)})=${n(r.ws)} tf；Wc=${i.gammaC}×${n(r.A)}×${i.h}/100=${n(r.wc)} tf；柱重${i.pedestal?'啟用':'不另加'}：Wp=${n(r.wp)} tf；U=max(0,${i.Df}−${i.zw})×${n(r.A)}=${n(r.U)} tf`,r.wc+r.ws+r.wp,'tf','覆土附載不施加在柱 footprint 上；N是否包含埋置柱重由輸入勾選決定。');
 const bx=bars[i.barX],by=bars[i.barY];
 add('鋼筋查表、有效深度、支數與面積','d=h−cover−db/2−另一向下層db；n=floor[(全寬cm−2cover−db)/s]+1；As=n Ab',`bars 表 #${i.barX} 列：db欄=${bx.db} cm、area欄=${bx.area} cm²；#${i.barY} 列：db=${by.db} cm、area=${by.area} cm²。dx=${i.h}−${i.cover}−${bx.db}/2−${i.lower==='y'?by.db:0}=${n(r.dx)} cm；dy=${i.h}−${i.cover}−${by.db}/2−${i.lower==='x'?bx.db:0}=${n(r.dy)} cm；沖切d=${i.dMode==='min'?'min(dx,dy)/100':'(dx+dy)/200'}=${n(r.d)} m；nx=floor[(${i.B}×100−2×${i.cover}−${bx.db})/${i.sx}]+1=${r.nx}；ny=floor[(${i.L}×100−2×${i.cover}−${by.db})/${i.sy}]+1=${r.ny}；Asx=${r.nx}×${bx.area}=${n(r.Asx)}；Asy=${r.ny}×${by.area}=${n(r.Asy)}`,`${n(r.Asx)} / ${n(r.Asy)}`,'cm²','支數向下取整後加1；畫面小數僅顯示，判斷使用完整精度。鋼筋名義資料沿用既有 engine bars 表。');
 const earth=i.gammaS*Math.min(i.Df,i.zw)**2/2+(i.gammaSat-1)*Math.max(0,i.Df-i.zw)**2/2+i.gammaS*Math.min(i.Df,i.zw)*Math.max(0,i.Df-i.zw);
 add('主被動土壓係數及積分','Ka=tan²(45°−φ/2)；Kp=1/Ka；earthInt=γs min(Df,zw)²/2+(γsat−1)max(0,Df−zw)²/2+γs min(Df,zw)max(0,Df−zw)',`Ka=tan²(45−${i.phiS}/2)=${n(r.Ka)}；Kp=1/${n(r.Ka)}=${n(r.Kp)}；earthInt=${i.gammaS}×${n(Math.min(i.Df,i.zw))}²/2+(${i.gammaSat}−1)×${n(Math.max(0,i.Df-i.zw))}²/2+${i.gammaS}×${n(Math.min(i.Df,i.zw))}×${n(Math.max(0,i.Df-i.zw))}=${n(earth)} tf/m；Ppx=${i.passive}×${n(r.Kp)}×${n(earth)}×${i.B}=${n(r.Ppx)} tf；Ppy=${n(r.Ppy)} tf；Pax=${i.active}×${n(r.Ka)}×(${n(earth)}+${i.qs}×${i.Df})×${i.B}=${n(r.Pax)} tf；Pay=${n(r.Pay)} tf`,`${n(r.Ppx)} / ${n(r.Ppy)} / ${n(r.Pax)} / ${n(r.Pay)}`,'tf','沿用Rankine與輸入採用比例；啟用主被動或黏著時仍標示REVIEW。');
 for(const c of r.results){
  const prefix=c.name+'｜';
  add(prefix+'本次組合與基底合力','Ntotal=N+wf(Wc+Ws+Wp)−uf U；Sx=My+(N+wf Wp−wf soilPSF Ac)ex；Sy=−Mx+(N+wf Wp−wf soilPSF Ac)ey',`用途=${c.type}；N=${c.N} tf；Mx=${c.Mx}、My=${c.My} tf·m；Hx=${c.Hx}、Hy=${c.Hy} tf；wf=${c.wf}、uf=${c.uf}、qa倍率=${c.qaFactor}。Ntotal=${c.N}+${c.wf}×(${n(r.wc)}+${n(r.ws)}+${n(r.wp)})−${c.uf}×${n(r.U)}=${n(c.Ntotal)} tf；Sx=${c.My}+(${c.N}+${c.wf}×${n(r.wp)}−${c.wf}×${n(r.soilPSF)}×${n(r.Ac)})×${i.ex}=${n(c.Sx)} tf·m；Sy=−(${c.Mx})+(${c.N}+${c.wf}×${n(r.wp)}−${c.wf}×${n(r.soilPSF)}×${n(r.Ac)})×${i.ey}=${n(c.Sy)} tf·m`,c.Ntotal,'tf',c.error?'無有效接觸解：'+c.error:'My對應∫qx；−Mx對應∫qy；全部內力採同列組合。');
  if(c.error)continue;
  const p=c.p;
  add(prefix+'無拉力壓力平面與接觸幾何','q=max(0,a+bx+cy)；初值=[N/(LB),12Sx/(BL³),12Sy/(LB³)]；Jv=[N,Sx,Sy]；Newton vnew=v−step J⁻¹error',`a,b,c=${vec(p.v)}（tf/m², tf/m³, tf/m³）；接觸多邊形m：${poly(p.poly)}；[∫1,∫x,∫y,∫x²,∫xy,∫y²]=[${vec(p.moments)}]；四角[−X−Y,+X−Y,+X+Y,−X+Y] q=[${vec(p.cornerQ)}] tf/m²；接觸面積=${n(p.area)} m² / ${n(r.A)} m²；迭代=${p.iterations}；∫[q,qx,qy]=[${vec(p.F)}]；目標=[${vec([c.Ntotal,c.Sx,c.Sy])}]`,p.qmax,'tf/m²',`qmin=${n(p.qmin)}；${p.full?'全接觸':'部分接觸，脫離區q=0並重新平衡'}；正規化殘差=${n(p.residual)}；停止norm≤1e−10或80次；回傳有效解norm≤1e−7。幾何積分採三角形三點二次精確積分。`);
  for(const h of p.history)add(prefix+'接觸迭代 '+h.iteration,'vnew=v−step J⁻¹error；norm=√[(errorN/N)²+(errorSx/NL)²+(errorSy/NB)²]',`step=${n(h.step)}；${h.beforeV?`前次v=[${vec(h.beforeV)}]；J各列=[${h.jacobian.map(vec).join('; ')}]；error=[${vec(h.error)}]；解JΔ=error所得Δ=[${vec(h.delta)}]；`:"初值由完整底面積與慣性公式直接求得；"}v=[${vec(h.v)}]；積分合力=[${vec(h.F)}]；目標=[${vec([c.Ntotal,c.Sx,c.Sy])}]`,h.residual,'','每次線搜尋最多30次，每次step減半；只記錄實際接受的步長，0是初始試解。');
  add(prefix+'地盤承載與滑動','qa,gross=qa；qa,net=qa+γs min(Df,zw)+(γsat−1)max(0,Df−zw)；bearing=qmax/(qallow倍率)；H=√[(|Hx|+Pax)²+(|Hy|+Pay)²]；R=μN+ca Acontact+(Ppx Hx′+Ppy Hy′)/H',`qa採${i.qaType}，qallow=${n(c.qallow)} tf/m²；bearing=${n(p.qmax)}/(${n(c.qallow)}×${c.qaFactor})=${n(c.bearing)}；H=√[(${Math.abs(c.Hx)}+${n(r.Pax)})²+(${Math.abs(c.Hy)}+${n(r.Pay)})²]=${n(c.sliding.H)} tf；R=${i.mu}×${n(c.Ntotal)}+${i.cohesion}×${n(p.area)}+土壓沿H投影=${n(c.sliding.res)} tf；FS=${n(c.sliding.res)}/${n(c.sliding.H)}=${n(c.fsSliding)}`,n(c.fsSliding),'',`用途${c.type}，${c.type==='S'?`承載比≤1，FS滑動≥${i.fsSlide}`:'此組合不納入地盤/穩定合格判定'}；H=0時FS=∞（無水平需求）。`);
  c.ot.forEach((o,j)=>add(prefix+`傾覆 ${j<2?'X':'Y'} ${o.sign<0?'負':'正'}側`,'R=(max(0,N)+wfWp)(size/2−sign offset)+wf(Wc+Ws)size/2+sign wf soilPSF Ac offset+max(0,−sign M)；O=max(0,−N)(size/2−sign offset)+uf U size/2+max(0,sign M)',`size=${o.size} m；offset=${o.offset} m；M=${o.moment} tf·m；sign=${o.sign}；R=${n(o.R)} tf·m；O=${n(o.O)} tf·m；FS=R/O=${n(o.FS)}`,n(o.FS),'',`兩側取min，再取兩向min=${n(c.fsOT)}；${c.type==='S'?'須≥'+i.fsOT:'不納入U組判定'}。O=0時∞。`));
  c.integrals.forEach((t,j)=>{const label=j===0?'全底面':j<=8?`${Math.floor((j-1)/2)+1}號側 ${j%2?'柱面彎矩':'柱面外d剪力'}`:'沖切周界內';add(prefix+'淨反力積分｜'+label,'∫[q,qx,qy]=[aA+b∫x+c∫y,a∫x+b∫x²+c∫xy,a∫y+b∫xy+c∫y²]；net=壓力積分+uniform[∫1,∫x,∫y]+wf soilPSF柱區相交積分',`積分區域m：${poly(t.poly)}；壓力有效相交m：${poly(t.contact)}；接觸六積分=[${vec(t.qm)}]；全區六積分=[${vec(t.m)}]；柱區六積分=[${vec(t.mc)}]；壓力∫[q,qx,qy]=[${vec(t.pr)}]；uniform=uf U/A−wf(Wc/A+soilPSF)=${c.uf}×${n(r.U)}/${n(r.A)}−${c.wf}×(${n(r.wc)}/${n(r.A)}+${n(r.soilPSF)})=${n(t.uniform)} tf/m²；net=[${vec(t.value)}]`,vec(t.value),'tf, tf·m, tf·m','積分幾何與中間數值在實際net呼叫時保存；先裁掉q<0，均佈向下荷重保留全區，再扣柱區覆土。');});
  for(const s of c.sides){const name=s.axis.toUpperCase()+(s.sign<0?'−側':'＋側');add(prefix+name+'柱面彎矩、d剪力與兩式容量','M=sign(淨反力一階矩−柱面座標×淨反力)；Vu=|柱面外d積分|；ρ=As/(bwd)；λs=min[1,√(2/(1+d/25))]或1；Vc=min(1.33,2.12λsρ^(1/3))√fc′bwd/1000',`柱面=${n(s.pos)} m；d剪力座標=${n(s.cut)} m；M=${s.sign}×(${n(s.net[s.axis==='x'?1:2])}−${n(s.pos)}×${n(s.net[0])})=${n(s.M)} tf·m；Vu=|${n(s.sv)}|=${n(s.Vu)} tf；ρ=${n(s.as)}/(${s.b}×100×${n(s.dcm)})=${n(s.rho)}；λs=${n(s.lambda)}；候選係數=[${vec(s.axisCandidates)}]，min=${n(s.coefficient)}；Vc=${n(s.coefficient)}×√${i.fc}×${s.b}×100×${n(s.dcm)}/1000=${n(s.Vc)} tf；φVc=.75×${n(s.Vc)}=${n(s.shearCap)} tf；剪力比=${n(s.Vu)}/${n(s.shearCap)}=${n(s.shearRatio)}；抗彎比=|${n(s.M)}|/${n(s.capacity)}=${n(s.ratio)}；AsReq=${n(s.AsReq)} cm²`,s.shearRatio,'',`使用比≤1；${s.top?'反向彎矩，底筋不可代替上筋，標REVIEW':'底面受拉'}；${i.lambdaMode==='on'||!p.full?'納入尺寸效應':'全接觸且auto，採λs=1'}。`,rc+'，表22.5.5.1(c)：Av=0、Nu=0列；兩候選取小。');reqTrace(prefix+name+'抗彎需求反解',s.asMeta);}
  const z=c.punch;
  if(!z.interior){add(prefix+'沖切適用性','周界柱面外d/2，必須位於基腳內部','非內柱：周界到達邊界','REVIEW','','保留原引擎行為，邊角柱不輸出假合格。',rc+'，22.6.4');continue;}
  add(prefix+'沖切周界、力與力矩','a=cx+d；b=cy+d；b0=2(a+b)；V=全底net−周界內net；Tx=全底Mx−內Mx−ex V；Ty=全底My−內My−ey V',`d=${n(z.d)} m；a=${i.cx}+${n(z.d)}=${n(z.a)}；b=${i.cy}+${n(z.d)}=${n(z.b)} m；bounds=[${vec(z.bounds)}] m；b0=2×(${n(z.a)}+${n(z.b)})=${n(z.bo)} m；V=${n(z.all[0])}−${n(z.inside[0])}=${n(z.V)} tf；Tx=${n(z.all[1])}−${n(z.inside[1])}−${i.ex}×${n(z.V)}=${n(z.Tx)} tf·m；Ty=${n(z.all[2])}−${n(z.inside[2])}−${i.ey}×${n(z.V)}=${n(z.Ty)} tf·m`,z.V,'tf','周界內含柱區覆土修正，使用同一net積分。',rc+'，22.6.4、8.4.4.2');
  add(prefix+'沖切慣性與不平衡彎矩分配','Jy=d a³/6+a d³/6+d b a²/2；Jx=d b³/6+b d³/6+d a b²/2；γx=1−1/(1+⅔√(a/b))；γy=1−1/(1+⅔√(b/a))',`Jy=${n(z.d)}×${n(z.a)}³/6+${n(z.a)}×${n(z.d)}³/6+${n(z.d)}×${n(z.b)}×${n(z.a)}²/2=${n(z.Jy)} m⁴；Jx=${n(z.d)}×${n(z.b)}³/6+${n(z.b)}×${n(z.d)}³/6+${n(z.d)}×${n(z.a)}×${n(z.b)}²/2=${n(z.Jx)} m⁴；γx=1−1/(1+⅔√(${n(z.a)}/${n(z.b)}))=${n(z.gx)}；γy=1−1/(1+⅔√(${n(z.b)}/${n(z.a)}))=${n(z.gy)}`,`${n(z.Jx)} / ${n(z.Jy)}`,'m⁴','此偏心傳遞仍依既有工具範圍標REVIEW。',rc+'，8.4.4.2');
  z.corners.forEach((v,j)=>add(prefix+'沖切角點 '+(j+1),'v=[V/(b0d)+γx Tx x/Jy+γy Ty y/Jx]/10',`x=${n(v.x)}、y=${n(v.y)} m；直接=${n(v.direct)}；X梯度=${n(v.mx)}；Y梯度=${n(v.my)} kgf/cm²；v=${n(v.direct)}+${n(v.mx)}+${n(v.my)}=${n(v.value)}；|v|=${n(Math.abs(v.value))}`,v.value,'kgf/cm²','tf/m²除10轉kgf/cm²；四角絕對值最大控制。'));
  add(prefix+'沖切三式取小與判定','vc=λs min[1.06,.53(1+2/βc),.265(2+40d/b0)]√fc′；φvc=.75vc；ratio=vmax/φvc',`βc=max(${i.cx},${i.cy})/min(${i.cx},${i.cy})=${n(z.beta)}；λs=${n(z.lambda)}；三候選係數=[${vec(z.candidates)}]；採min=${n(Math.min(...z.candidates))}；vc=${n(z.lambda)}×${n(Math.min(...z.candidates))}×√${i.fc}=${n(z.vc)} kgf/cm²；φvc=.75×${n(z.vc)}=${n(z.capacity)}；vmax=max(${z.corners.map(v=>n(Math.abs(v.value))).join(',')})=${n(z.vmax)}；ratio=${n(z.vmax)}/${n(z.capacity)}=${n(z.ratio)}`,z.ratio,'','使用比≤1；內柱αs=40。',rc+'，表22.6.5.2：非預力、無剪力筋三列取小；βc柱長短比；αs內柱列40。');
  reqTrace(prefix+'X柱帶彎矩需求反解',z.reqMetaX);reqTrace(prefix+'Y柱帶彎矩需求反解',z.reqMetaY);
  add(prefix+'高沖切柱帶、實際筋量與彎矩需求','vuv=|V|/(b0d)/10；high=vuv>.75×.53λs√fc′；高應力As,min=5 vuv bslab b0/(.75×40fy)，否則.0018 bslab h；Mband=(1−γv)|T|',`vuv=${n(z.vdirect)}；分界=.75×.53×${n(z.lambda)}×√${i.fc}=${n(.75*.53*z.lambda*Math.sqrt(i.fc))} kgf/cm²；high=${z.high}；柱帶X/Y=${n(z.bandx)}/${n(z.bandy)} m（柱邊各延1.5h，受基脚邊界截斷）；最少AsX=${z.high?`5×${n(z.vdirect)}×${n(z.bandx)}×100×${n(z.bo)}×100/(.75×40×${i.fy})`:`.0018×${n(z.bandx)}×100×${i.h}`}=${n(z.localX)} cm²；最少AsY=${z.high?`5×${n(z.vdirect)}×${n(z.bandy)}×100×${n(z.bo)}×100/(.75×40×${i.fy})`:`.0018×${n(z.bandy)}×100×${i.h}`}=${n(z.localY)} cm²；實配逐支位置在柱帶內計數×單支面積：AsX/Y=${n(z.asBandX)}/${n(z.asBandY)} cm²；MbandX=(1−${n(z.gx)})×|${n(z.Tx)}|=${n(z.mBandX)}；MbandY=(1−${n(z.gy)})×|${n(z.Ty)}|=${n(z.mBandY)} tf·m；柱帶容量=${n(z.bandCapX)}/${n(z.bandCapY)} tf·m`,`${n(z.localX)} / ${n(z.localY)}`,'cm²','柱帶實配≥柱帶最少；不平衡彎矩局部上下筋完整設計仍需REVIEW。',rc+'，8.6.1.2、8.4.4.2');
 }
 for(const [axis,f,min,total,dev] of [['X',r.fx,r.minx,r.maxAs.x,r.devX],['Y',r.fy,r.miny,r.maxAs.y,r.devY]]){
  add(axis+'底筋應變相容與折減','β1=max(.65,.85−.05max(0,fc′−280)/70)；εy=fy/Es；.85fc′bβ1c=As min(fy,Esεt)；εt=.003(d−c)/c；φ限於.65至.9；φMn=φAs fs(d−a/2)/100000',`As=${n(f.As)} cm²；b=${n(f.b)} cm；d=${n(f.d)} cm；Es=2040000 kgf/cm²；β1=${n(f.beta)}；εy=${n(f.ey)}；二分80次初始[0,d]，末範圍[${n(f.lo)},${n(f.hi)}] cm；c=${n(f.c)}；a=${n(f.beta)}×${n(f.c)}=${n(f.a)} cm；εt=.003×(${n(f.d)}−${n(f.c)})/${n(f.c)}=${n(f.et)}；fs=min(${i.fy},2040000×${n(f.et)})=${n(f.stress)} kgf/cm²；力平衡殘差=${n(f.balance)} kgf；φ=${n(f.phi)}；φMn=${n(f.phi)}×${n(f.As)}×${n(f.stress)}×(${n(f.d)}−${n(f.a)}/2)/100000=${n(f.capacity)} tf·m`,f.capacity,'tf·m',`εt≥εy+.003=${n(f.ey+.003)}：${f.ductile?'拉力控制':'不符合梁板拉力控制'}；完整精度，不以顯示四捨五入判定。`,rc+'，21.2.2、22.2');
  add(axis+'全寬配筋需求包絡','As,min=.0018 b h；AsReq=(.85fc′b/fy)[d−√(d²−2|M|100000/(.9×.85fc′b))]；max各組合與柱帶需求，再對短向乘2β/(β+1)',`As,min=${n(min)} cm²；${r.results.filter(c=>c.type==='U'&&!c.error).flatMap(c=>c.sides.filter(s=>s.axis===axis.toLowerCase()).map(s=>c.name+(s.sign<0?'−':'＋')+'M='+n(s.M)+' → AsReq='+n(s.AsReq))).join('；')}；β=${n(Math.max(i.L,i.B)/Math.min(i.L,i.B))}；短向=${r.short.toUpperCase()}；增量=${n(r.distFactor)}；同向候選：${r.demandCandidates.filter(v=>v.axis===axis.toLowerCase()).map(v=>v.name+':'+n(v.value)).join('; ')} cm²；未增量最大=${n(r.rawMaxAs[axis.toLowerCase()])} cm²；最終全寬需求=${n(total)} cm²；實配=${n(f.As)} cm²`,total,'cm²','原引擎拉力控制需求過大時回∞，不捏造有限解；柱帶按全寬/柱帶寬比例換算。',rc+'，8.6.1、13.3.3.3');
  add(axis+'直線伸展','cb=min(cover+db/2,s/2)；ratio=min(2.5,cb/db)；ψs=db≤1.91?.8:1；ld=max[30,fyψs db/(3.5min(26.5,√fc′)ratio)]',`db=${dev.db} cm；s=${dev.spacing} cm；cb=min(${dev.cover}+${dev.db}/2,${dev.spacing}/2)=${n(dev.cb)} cm；ratio=min(2.5,${n(dev.cb)}/${dev.db})=${n(dev.ratio)}；ψs=${dev.psi}；√fc′上限後=${n(dev.sqrtFc)}；原算式=${n(dev.raw)} cm；ld=max(30,${n(dev.raw)})=${n(dev.ld)} cm；提供=(${axis==='X'?i.L:i.B}/2−|${axis==='X'?i.ex:i.ey}|−${axis==='X'?i.cx:i.cy}/2)×100−${i.cover}=${n(dev.available)} cm`,dev.ld,'cm',`提供${dev.ok?'≥':'<'}需求；Ktr=0、ψt=ψe=λ=1、不折減超量筋。`,rc+'，25.4.2.4、25.4.2.5');
 }
 add('間距及整體判定','s≤min(2h,45)；s−db≥max(2.5,db)；As≥需求、拉力控制、柱帶、伸展及各用途檢核',`s上限=min(2×${i.h},45)=${n(r.spacingLimit)} cm；X淨距=${i.sx}−${bx.db}=${n(i.sx-bx.db)} ≥ ${n(Math.max(2.5,bx.db))}；Y淨距=${i.sy}−${by.db}=${n(i.sy-by.db)} ≥ ${n(Math.max(2.5,by.db))}；spacingOK=${r.spacingOK}；reinforceOK=${r.reinforceOK}；localBandsOK=${r.localBandsOK}；fail=${r.fail}；review=${r.review}`,r.status,'','PASS僅表示所列項目；NG表示數值不滿足；REVIEW仍需專案核定。邊柱、反向、偏心傳遞、部分接触或土壓有利作用保留原標示。');
 return steps;
}

const API={bars,defaults,rect,clip,moments,pressure,pIntegral,flex,asReq,validate,calculate};root.Footing=API;if(typeof module!=='undefined')module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);

