'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const F=require('./engine.cjs');
let count=0,records=[],maxResidual=0;
function close(name,got,want,tol=1e-8){assert(Number.isFinite(got),name+' is not finite');assert(Math.abs(got-want)<=tol*Math.max(1,Math.abs(want)),`${name}: ${got} != ${want}`);count++;}
function check(name,fn){fn();records.push(name);}
const clone=o=>JSON.parse(JSON.stringify(o));
// Independent one-dimensional integration: solve the positive y-interval analytically,
// then Simpson-integrate along x. Does not call engine polygon clipping/integration.
function reference(p,L,B,n=4096){let out=[0,0,0,0];const [a,b,c]=p.v,dx=L/n;for(let j=0;j<=n;j++){let x=-L/2+j*dx,lo=-B/2,hi=B/2,z=a+b*x;if(Math.abs(c)<1e-16){if(z<=0)continue;}else if(c>0)lo=Math.max(lo,-z/c);else hi=Math.min(hi,-z/c);if(hi<=lo)continue;let Q=z*(hi-lo)+c*(hi*hi-lo*lo)/2,Y=z*(hi*hi-lo*lo)/2+c*(hi**3-lo**3)/3,k=j===0||j===n?1:j%2?4:2;out[0]+=k*Q;out[1]+=k*x*Q;out[2]+=k*Y;out[3]+=k*(hi-lo)}return out.map(v=>v*dx/3)}
check('均佈土壓 / 一、二階矩解析解',()=>{for(const [L,B,N] of [[3,3,180],[4,3,200],[2.7,5.3,487]]){let p=F.pressure(L,B,N,0,0);close('qmax',p.qmax,N/(L*B));close('qmin',p.qmin,N/(L*B));close('area',p.area,L*B);close('force',p.F[0],N);}});
check('全接觸雙向偏心解析角點',()=>{for(let j=0;j<40;j++){let L=2+j*.13,B=3+j*.09,N=80+j*7,ex=.04*L,ey=-.05*B,p=F.pressure(L,B,N,N*ex,N*ey),q0=N/(L*B);close('qmax',p.qmax,q0*(1+6*.04+6*.05));close('qmin',p.qmin,q0*(1-6*.04-6*.05));}});
check('單軸部分接觸三角形解析解 / 正負X、Y',()=>{for(const axis of ['x','y'])for(const sign of [-1,1])for(const eRatio of [.18,.25,.36,.45,.49]){const L=4,B=3,N=200,size=axis==='x'?L:B,width=axis==='x'?B:L,e=sign*eRatio*size,length=3*(size/2-Math.abs(e)),p=F.pressure(L,B,N,axis==='x'?N*e:0,axis==='y'?N*e:0);close('area triangle',p.area,width*length,1e-7);close('q triangle',p.qmax,2*N/(width*length),1e-7);close('qmin triangle',p.qmin,0);}});
check('80組雙向偏心 / 獨立積分平衡與不承拉',()=>{let seed=971;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};for(let j=0;j<80;j++){let L=2+rnd()*6,B=2+rnd()*6,N=30+rnd()*500,ex=(rnd()-.5)*.8*L,ey=(rnd()-.5)*.8*B,p=F.pressure(L,B,N,N*ex,N*ey),v=reference(p,L,B);close('reference force',v[0],N,2e-6);close('reference M_y',v[1],N*ex,2e-6);close('reference M_x',v[2],N*ey,2e-6);maxResidual=Math.max(maxResidual,p.residual);assert(p.qmin>=0);count++;}});
check('置中基腳自重、有效深度、柱面Mu、單向Vu與新版Vc',()=>{let i=clone(F.defaults),r=F.calculate(i),c=r.results.find(c=>c.type==='U');assert.equal(r.status,'PASS');count++;let A=i.L*i.B,wc=i.gammaC*A*i.h/100,ws=i.gammaS*(i.Df-i.h/100)*(A-i.cx*i.cy),qu=(c.N+c.wf*(wc+ws))/A,qnet=qu-c.wf*(wc/A+i.gammaS*(i.Df-i.h/100));close('Wc',r.wc,wc);close('Ws',r.ws,ws);close('qnet balance',c.netBalance,0);close('dx',r.dx,56.23);close('dy',r.dy,53.69);for(const s of c.sides){let len=s.axis==='x'?(i.L-i.cx)/2:(i.B-i.cy)/2,b=s.axis==='x'?i.B:i.L,d=s.axis==='x'?r.dx:r.dy,As=s.axis==='x'?r.Asx:r.Asy,rho=As/(b*100*d),vc=.75*Math.min(1.33,2.12*Math.cbrt(rho))*Math.sqrt(i.fc)*b*100*d/1000;close('Mu independent',s.M,qnet*b*len*len/2);close('Vu independent',s.Vu,qnet*b*Math.max(0,len-d/100));close('Vc independent',s.shearCap,vc);}});
check('沖切周界、扣除內部反力、三式容量及高沖切最小量',()=>{const i=clone(F.defaults),r=F.calculate(i),c=r.results[1],p=c.punch,a=i.cx+r.d,b=i.cy+r.d,bo=2*(a+b),qnet=(c.N-c.wf*i.gammaS*(i.Df-i.h/100)*i.cx*i.cy)/r.A,V=qnet*(r.A-a*b),vd=V/(bo*r.d)/10,vc=.75*Math.min(1.06,.53*(1+2),.265*(2+40*r.d/bo))*Math.sqrt(i.fc);close('bo',p.bo,bo);close('Vu2',p.V,V);close('vu',p.vdirect,vd);close('phi vc',p.capacity,vc);close('ratio',p.ratio,vd/vc);assert(p.high);count++;close('min As high',p.localX,5*vd*p.bandx*100*bo*100/(.75*40*i.fy));});
check('底筋伸展25.4.2.4、矩形短向全寬增量及較小d選項',()=>{let i=clone(F.defaults),r=F.calculate(i);close('Ld',r.devX.ld,4200*2.54/(3.5*Math.sqrt(280)*2.5));close('available Ld',r.devX.available,112.5);i.L=4;i.h=80;let rect=F.calculate(i);close('short factor',rect.distFactor,8/7);assert.equal(rect.short,'y');count++;i.dMode='min';r=F.calculate(i);close('min punching d',r.d,Math.min(r.dx,r.dy)/100);});
check('地下水獨立係數 / 有效土壓與淨反力平衡',()=>{let i=clone(F.defaults);i.zw=.2;i.cases.forEach(c=>c.uf=.9);const r=F.calculate(i),A=i.L*i.B,depth=i.Df-i.h/100,ws=(i.gammaS*.2+i.gammaSat*(depth-.2))*(A-i.cx*i.cy);close('wet Ws',r.ws,ws);close('uplift',r.U,(i.Df-i.zw)*A);for(const c of r.results){close('N total',c.Ntotal,c.N+c.wf*(r.wc+r.ws)-.9*r.U);close('net equilibrium',c.netBalance,0)}});
check('ACI官方範例：柱面Mu、d剪力與d/2沖切幾何（只比較需求）',()=>{let i=clone(F.defaults);Object.assign(i,{L:12*.3048,B:12*.3048,h:30*2.54,Df:1,cx:24*.0254,cy:24*.0254,cover:3*2.54,dMode:'min'});i.cases=[{name:'S',type:'S',N:735*.45359237,Mx:0,My:0,Hx:0,Hy:0,wf:0,uf:0,qaFactor:1},{name:'U',type:'U',N:960*.45359237,Mx:0,My:0,Hx:0,Hy:0,wf:0,uf:0,qaFactor:1}];const r=F.calculate(i),c=r.results[1],q=960/144;close('source d in',r.dy/2.54,25.5);close('source Mu kip-ft',c.sides[2].M/(.45359237*.3048),q*12*5*5/2);close('source Vu kip',c.sides[2].Vu/.45359237,q*12*(5-25.5/12));close('source bo in',c.punch.bo/.0254,198);close('source Vu punching kip',c.punch.V/.45359237,q*(144-(49.5/12)**2));});
check('材料／幾何／JSON／荷載錯誤與無接觸不假合格',()=>{for(const alter of [i=>i.h=10,i=>i.L=0,i=>i.cover=1,i=>i.fc=100,i=>i.sx=.5,i=>i.cases='oops',i=>i.cases=[null],i=>i.cases[0].N=NaN,i=>i.pedestal='yes']){const i=clone(F.defaults);alter(i);assert(F.calculate(i).errors.length);count++;}for(const [N,My] of [[-1000,0],[10,1000]]){let i=clone(F.defaults);i.cases[0].N=N;i.cases[0].My=My;const r=F.calculate(i);assert.equal(r.status,'NG');assert(r.results[0].error);count++;}let i=clone(F.defaults);i.h=35;assert.equal(F.calculate(i).status,'NG');count++;i=clone(F.defaults);i.ex=1.15;const r=F.calculate(i);assert(r.review);assert(!r.results[1].punch.interior);count++;});
const r=F.calculate(F.defaults);const summary={date:'2026-10-05',checks:count,groups:records,maxContactResidual:maxResidual,defaultResult:{status:r.status,wc:r.wc,ws:r.ws,serviceQ:r.results[0].p.qmax,dx:r.dx,dy:r.dy,Asx:r.Asx,Asy:r.Asy,U1:{Mu:r.results[1].sides[0].M,shearRatio:r.results[1].shearRatio,punchRatio:r.results[1].punch.ratio},ld:r.devX.ld},sources:['https://www.nlma.gov.tw/filesys/file/EMMA/c1130219-1.pdf','https://www.nlma.gov.tw/filesys/file/EMMA/a1120620.pdf','https://www.concrete.org/Portals/0/Files/PDF/318-Example-1_RF_R1.pdf'],scope:'Algorithm and listed checks only; no complete geotechnical, seismic or local connection design approval'};
fs.writeFileSync(__dirname+'/validation-results.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
