const A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),R=require('./core.js');
const s={name:'C1',mode:'normal',environment:'inside',b:60,h:60,fc:280,fy:4200,fyt:4200,Es:2040000,cover:4,agg:2,bar:'D25',tie:'D13',nx:4,ny:4,s:10,L:300,kx:1,ky:1,frame:'braced',ratioX:-1,ratioY:-1,second:false};
const checks=[],numbers={},close=(a,b,t=1e-7)=>A(Math.abs(a-b)<t,`${a} != ${b}`),test=(name,fn)=>{fn();checks.push(name)},g=R.geometry(s);
test('逐根淨力與兩方向力矩加總回復核心結果',()=>{for(const theta of [0,.37,1.57,3.47])for(const c of [8,20,70]){const w=R.state(s,g,theta,c,true);close(w.concrete+w.rows.reduce((a,p)=>a+p.Fs,0)/1000,w.P/1000);close(w.concreteMx+w.rows.reduce((a,p)=>a+p.netMx,0)/100000,w.Mx/100000);close(w.concreteMy+w.rows.reduce((a,p)=>a+p.netMy,0)/100000,w.My/100000);w.rows.forEach(p=>close(p.steelForce-p.concreteForce,p.Fs));}});
test('半圓占用面積及形心修正獨立公式',()=>{const c=(30-g.bars[0].x)/.85,w=R.state(s,g,0,c,true),p=w.rows[0];close(p.subArea,p.a/2);close(p.first,(p.a/2)*(4*(p.d/2)/(3*Math.PI)));close(p.netMy,p.a*p.fs*p.x-.85*s.fc*(p.a/2*p.x+p.first));numbers.halfCircle={Aci:p.subArea,Q:p.first};});
test('邊界交點插值、同軸力及D/C可重算',()=>{const c=R.section(s,{P:300,Mx:20,My:10}),b=c.boundary;A(b);close(b.start.dp,300,1e-6);close(b.end.dp,300,1e-6);close(b.mx,b.start.mx+b.t*(b.end.mx-b.start.mx));close(b.my,b.start.my+b.t*(b.end.my-b.start.my));close(b.mx*b.uy-b.my*b.ux,0);close(c.capacity,b.mx*b.ux+b.my*b.uy);close(c.ratio,Math.hypot(20,10)/c.capacity);numbers.boundary={t:b.t,capacity:c.capacity,ratio:c.ratio};});
const sandbox={RCC:R,fmt:(v,n=2)=>Number.isFinite(v)?Number(v).toFixed(n):String(v),esc:s=>String(s).replace(/</g,'&lt;'),table:(headers,rows)=>JSON.stringify({headers,rows})};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/audit-ui.js','utf8'),sandbox);
test('純軸力、邊界無解與耐震明細分支可產生',()=>{for(const [z,l] of [[s,{name:'axial',P:300,Mx:0,My:0,Vx:0,Vy:0}],[s,{name:'over',P:900,Mx:20,My:10,Vx:20,Vy:10}],[{...s,mode:'seismic'}, {name:'high',P:500,Mx:20,My:10,Vx:20,Vy:10}]]){const r=R.evaluate(z,[l]);sandbox.r=r;sandbox.c=r.cases[0];const html=vm.runInContext('detailedAudit(r,c)',sandbox);A(html.includes('5.8'));A(!html.includes('undefined'));A(!html.includes('NaN'));if(z.mode==='seismic')A(html.includes('5.9'));}});
fs.writeFileSync(__dirname+'/audit-validation.json',JSON.stringify({version:'1.3.1',date:'2026-10-05',checks,numbers},null,2));console.log(checks.join('\n'));
