/* Read-only calculation audit. Numbers come from the evaluated geometry and boundary states. */
function detailedAudit(r,c){
 const s=r.s,g=r.g,w=c.witness,f=(v,n=6)=>fmt(v,n),types=new Map();
 g.bars.forEach(p=>{const a=types.get(p.bar)||{N:0,Ai:p.a,Ast:0};a.N++;a.Ast+=p.a;types.set(p.bar,a)});
 let h='<h3 class="section-gap">5. 逐步核算與代入明細</h3><p class="notice">以下採本次實際座標、材料及所選載重組合。壓力為正、拉力為負；座標x/y由斷面中心起算，輸入X/Y由左下角起算。數值顯示約整，計算與加總採完整精度。</p>';
 h+='<h4>5.1 主筋面積與座標換算</h4><div class="table-wrap">'+table(['筋徑','根數 N','單根 Ai（cm²）','N × Ai（cm²）'],[...types].map(([k,a])=>[k,a.N,f(a.Ai,4),f(a.Ast,6)]))+'</div><div class="formula">Ast = '+[...types].map(([k,a])=>a.N+'×'+f(a.Ai,4)).join(' + ')+' = '+f(g.Ast)+' cm²<br>Ag = '+s.b+'×'+s.h+' = '+f(g.Ag)+' cm²；ρ = '+f(g.Ast)+'/'+f(g.Ag)+' = '+f(g.Ast/g.Ag*100,6)+' %<br>xᵢ = Xᵢ − b/2 = Xᵢ − '+f(s.b/2,3)+'；yᵢ = Yᵢ − h/2 = Yᵢ − '+f(s.h/2,3)+' cm<br>整排第j根：Xⱼ = X₁ + j(X₂−X₁)/(N−1)，Yⱼ同理，j=0…N−1；N=1只取起點。<br>多層生成：o₁=cover+dt+db₁/2；oₖ=oₖ₋₁+(dbₖ₋₁+dbₖ)/2+淨距ₖ。拖曳後以目前實際座標計算。</div>';
 const ety=s.fy/s.Es,beta=RCC.beta(s.fc);
 h+='<h4>5.2 材料參數與軸力界限</h4><div class="formula">εcu = 0.003；Es = '+s.Es+' kgf/cm²；εty = '+s.fy+'/'+s.Es+' = '+f(ety,8)+'<br>β₁ = max(0.65, min(0.85, 0.85−0.05×('+s.fc+'−280)/70)) = '+f(beta,6)+'<br>等值混凝土壓應力 = 0.85fc′ = 0.85×'+s.fc+' = '+f(.85*s.fc,3)+' kgf/cm²<br>P₀=[0.85fc′(Ag−Ast)+fyAst]/1000 = '+f(c.P0)+' tf<br>最大設計軸壓 φPn,max=0.80×0.65×P₀ = '+f(c.Pmax)+' tf<br>最大設計軸拉量值 φPnt=0.90×fy×Ast/1000 = '+f(c.Tmax)+' tf<br>檢查 −'+f(c.Tmax)+' ≤ Pu='+f(c.load.P)+' ≤ '+f(c.Pmax)+' tf：'+(c.axialOK?'通過':'未通過')+'</div>';
 if(w){
  const nx=Math.cos(w.theta),ny=Math.sin(w.theta),top=Math.abs(nx)*s.b/2+Math.abs(ny)*s.h/2,q=top-w.a,rows=w.rows;
  const sf=rows.reduce((a,p)=>a+p.steelForce,0)/1000,cf=rows.reduce((a,p)=>a+p.concreteForce,0)/1000,nf=rows.reduce((a,p)=>a+p.Fs,0)/1000,smx=rows.reduce((a,p)=>a+p.netMx,0)/100000,smy=rows.reduce((a,p)=>a+p.netMy,0)/100000;
  h+='<h4>5.3 中性軸、應變相容與鋼筋應力</h4><p class="muted">固定Pu以120個壓縮法向角建立邊界，每角以65次二分迭代求c，使φPn≈Pu。此表採鄰近需求方向的一個邊界解，最終D/C另以兩個邊界點插值求得。</p><div class="formula">θ = '+f(w.theta*180/Math.PI)+'°；nx=cosθ='+f(nx,8)+'；ny=sinθ='+f(ny,8)+'<br>極壓纖維投影 top=|nx|b/2+|ny|h/2 = '+f(top)+' cm<br>c = '+f(w.c,8)+' cm；a=β₁c = '+f(beta)+'×'+f(w.c,8)+' = '+f(w.a,8)+' cm<br>zᵢ=nx·xᵢ+ny·yᵢ；dᵢ=top−zᵢ；εsᵢ=0.003(1−dᵢ/c)<br>fsᵢ=max(−fy,min(fy,Es·εsᵢ))，壓筋正、拉筋負。<br>εt=max(0,−εsᵢ) = '+f(w.et,8)+'；拉力控制界限 εty+0.003 = '+f(ety+.003,8)+'<br>φ=0.65+0.25×max(0,min(1,(εt−εty)/0.003)) = '+f(w.phi,8)+'</div>';
  h+='<h4>5.4 壓力塊與逐筋力矩積分</h4><div class="formula">壓力塊保留 nx·x+ny·y ≥ top−a = '+f(q,8)+' 的柱斷面。<br>壓力塊毛面積 Ac='+f(w.concreteArea)+' cm²；毛壓力 Cc=0.85fc′Ac/1000 = '+f(w.concrete)+' tf<br>毛混凝土 Mnx,c='+f(w.concreteMx)+'、Mny,c='+f(w.concreteMy)+' tf·m（斷面中心取矩）<br>鋼筋淨力 Fᵢ=Ai·fsᵢ−0.85fc′·Aci；Aci為該筋位於壓力塊內的占用面積。<br>部分圓筋：r=db/2，t=max(−1,min(1,(top−a−zᵢ)/r))<br>Aci=Ai[acos(t)−t√(1−t²)]/π；Qᵢ=Ai/(πr²)×(2/3)r³(1−t²)^(3/2)<br>Mnx,ᵢ=[Ai·fsᵢ·yᵢ−0.85fc′(Aci·yᵢ+Qᵢ·ny)]/100000<br>Mny,ᵢ=[Ai·fsᵢ·xᵢ−0.85fc′(Aci·xᵢ+Qᵢ·nx)]/100000<br>Qᵢ處理圓筋僅部分進入壓力塊時的占用混凝土形心；全部進入或全部在外時Qᵢ=0。</div>';
  h+='<div class="table-wrap audit-bars">'+table(['筋號／層','筋徑','Ai cm²','X / Y cm','x / y cm','dᵢ cm','εs','fs kgf/cm²'],rows.map((p,i)=>[i+1+(p.layer?' / L'+p.layer:''),p.bar,f(p.a,4),f(p.x+s.b/2,4)+' / '+f(p.y+s.h/2,4),f(p.x,4)+' / '+f(p.y,4),f(p.depth),f(p.eps,8),f(p.fs,3)]))+'</div>';
  h+='<p class="muted">對應上述筋號的力與力矩（以斷面中心取矩）：</p><div class="table-wrap audit-bars">'+table(['筋號','Aci cm²','Qᵢ cm³','鋼筋力 tf','扣除混凝土 tf','淨力 tf','淨Mnx tf·m','淨Mny tf·m'],rows.map((p,i)=>[i+1,f(p.subArea),f(p.first),f(p.steelForce/1000),f(p.concreteForce/1000),f(p.Fs/1000),f(p.netMx/100000),f(p.netMy/100000)]))+'</div>';
  h+='<h4>5.5 合力加總、單位換算與強度折減</h4><div class="formula">Σ鋼筋力 = '+f(sf)+' tf；Σ占用混凝土扣除 = '+f(cf)+' tf；Σ鋼筋淨力 = '+f(nf)+' tf<br>Pn = Cc+ΣFᵢ = '+f(w.concrete)+' + ('+f(nf)+') = '+f(w.P/1000)+' tf<br>Mnx = Mnx,c+ΣMnx,ᵢ = '+f(w.concreteMx)+' + ('+f(smx)+') = '+f(w.Mx/100000)+' tf·m<br>Mny = Mny,c+ΣMny,ᵢ = '+f(w.concreteMy)+' + ('+f(smy)+') = '+f(w.My/100000)+' tf·m<br>1 tf=1000 kgf；1 tf·m=100000 kgf·cm。<br>φPn = '+f(w.phi,8)+'×'+f(w.P/1000)+' = '+f(w.dp)+' tf；與Pu殘差='+f(w.dp-c.load.P,9)+' tf<br>φMnx = '+f(w.mx)+'、φMny = '+f(w.my)+' tf·m</div>';
 }else h+='<p class="muted">本組合未選取鄰近需求方向的邊界應變解：純軸力／純拉端點或超出可計算包絡時，以軸力界限及需求點是否位於包絡判定；不虛列逐筋應變表。</p>';
 h+='<h4>5.6 固定Pu雙向邊界交點與D/C</h4>';
 const b=c.boundary;
 if(b){
  const p=b.start,z=b.end,cp=p.mx*b.uy-p.my*b.ux,cz=z.mx*b.uy-z.my*b.ux;
  h+='<div class="formula">需求 |Mu|=√('+f(c.load.Mx)+'²+'+f(c.load.My)+'²) = '+f(Math.hypot(c.load.Mx,c.load.My))+' tf·m<br>需求單位方向 u=(Mx,My)/|Mu| = ('+f(b.ux,8)+', '+f(b.uy,8)+')<br>邊界A：θ='+f(p.theta*180/Math.PI)+'°，(φMnx,φMny)=('+f(p.mx)+', '+f(p.my)+')<br>邊界B：θ='+f(z.theta*180/Math.PI)+'°，(φMnx,φMny)=('+f(z.mx)+', '+f(z.my)+')<br>叉積 kA=Ax·uy−Ay·ux = '+f(cp,8)+'；kB = '+f(cz,8)+'<br>插值 t=kA/(kA−kB) = '+f(b.t,8)+'<br>交點 R=A+t(B−A) = ('+f(b.mx)+', '+f(b.my)+') tf·m<br>需求方向容量 Rc=R·u = '+f(c.capacity)+' tf·m<br>D/C=|Mu|/Rc = '+f(Math.hypot(c.load.Mx,c.load.My))+'/'+f(c.capacity)+' = '+f(c.ratio,8)+'</div>';
 }else h+='<div class="formula">|Mu| = '+f(Math.hypot(c.load.Mx,c.load.My))+' tf·m；容量 = '+f(c.capacity)+' tf·m；D/C = '+f(c.ratio,8)+'。純軸力時D/C採Pu/φPn,max（壓力）或|Pu|/φPnt（拉力）。沒有有效包絡時標示未通過。</div>';
 h+='<p class="muted">座標配置另檢查實際需求點位於完整Mx–My包絡內；非對稱配筋在原點不位於包絡內時，不能僅凭外側射線容量判通過。本組彎矩／軸力判定：'+(c.pass?'通過':'未通過')+'。</p>';
 h+='<h4>5.7 兩方向剪力的公式代入</h4>';
 for(const [dir,v] of [['X',c.sx],['Y',c.sy]]){
  const ax=Math.min(c.load.P*1000/(6*g.Ag),.05*s.fc),vcmax=1.33*Math.sqrt(s.fc)*v.bw*v.d/1000,zero=s.mode==='seismic'||(s.layout==='custom'&&v.Av<v.Avmin),rho=(dir==='X'?g.edgeAsX:g.edgeAsY)/(v.bw*v.d),ls=Math.min(1,Math.sqrt(2/(1+v.d/25)));
  h+='<div class="formula">'+dir+'向：bw='+f(v.bw,3)+' cm；d='+f(v.d,3)+' cm；s='+f(s.s,3)+' cm<br>fyt採計=min('+s.fyt+', '+(s.mode==='seismic'?5600:4200)+') = '+v.fytUsed+' kgf/cm²<br>Av='+v.legs+'×'+RCC.BARS[s.tie].a+' = '+f(v.Av)+' cm²<br>Av,min=max(0.2√'+s.fc+',3.5)×'+v.bw+'×'+s.s+'/'+v.fytUsed+' = '+f(v.Avmin)+' cm²<br>軸壓項=min(Pu×1000/(6Ag),0.05fc′) = '+f(ax)+' kgf/cm²<br>'+(zero?'本分支保守採 Vc=0。':v.Av>=v.Avmin?'Vc,raw=[0.53√'+s.fc+'+('+f(ax)+')]×'+v.bw+'×'+v.d+'/1000；截限0～'+f(vcmax)+' tf。':'λs=min(1,√[2/(1+d/25)])='+f(ls)+'；ρw='+f(rho,8)+'<br>Vc,raw=(2.12λs·ρw^(1/3)·√fc′+軸壓項)bw·d/1000，截限0～'+f(vcmax)+' tf。')+'<br>Vc='+f(v.Vc)+' tf；Vs=Av×fyt×d/s/1000 = '+f(v.Av)+'×'+v.fytUsed+'×'+v.d+'/'+s.s+'/1000 = '+f(v.Vs)+' tf<br>Vs,max=2.12√fc′bw·d/1000 = '+f(2.12*Math.sqrt(s.fc)*v.bw*v.d/1000)+' tf<br>φVn=0.75 min(Vc+Vs,Vc+Vs,max) = '+f(v.cap)+' tf<br>|Vu|/φVn='+f(v.demand)+'/'+f(v.cap)+' = '+f(v.ratio,8)+'；s='+s.s+' ≤ 剪力間距上限 '+f(v.shearS,3)+' cm：'+(s.s<=v.shearS+1e-8?'符合':'不符')+'<br>剪力筋不足時檢查門檻 Vu＞0.75×0.265√fc′bw·d/1000 = '+f(.75*.265*Math.sqrt(s.fc)*v.bw*v.d/1000)+' tf；本向剪力結果：'+(v.pass?'通過':'未通過')+'</div>';
 }
 h+='<div class="formula">rx='+f(c.sx.ratio,8)+'；ry='+f(c.sy.ratio,8)+'（此處r為剪力D/C）<br>若rx、ry均＞0.5，交互作用=(rx+ry)/1.5；否則採max(rx,ry)。<br>本組交互作用比值='+f(c.shearInteraction,8)+' ≤ 1：'+(c.shearInteraction<=1+1e-8?'通過':'未通過')+'</div>';
 let pair=null;for(let i=0;i<g.bars.length;i++)for(let j=i+1;j<g.bars.length;j++){const p=g.bars[i],q=g.bars[j],gap=Math.hypot(p.x-q.x,p.y-q.y)-(p.d+q.d)/2,req=Math.max(4,1.5*Math.max(p.d,q.d),4*s.agg/3),margin=gap-req;if(!pair||margin<pair.margin)pair={i:i+1,j:j+1,gap,req,margin,di:p.d,dj:q.d};}
 h+='<h4>5.8 淨距、箍筋與長細篩選</h4><div class="formula">各對主筋淨距 sᵢⱼ=√[(xᵢ−xⱼ)²+(yᵢ−yⱼ)²]−(dbᵢ+dbⱼ)/2<br>要求 sᵢⱼ≥max(4,1.5×max(dbᵢ,dbⱼ),4dagg/3)。同層與跨層均檢查。<br>'+(pair?'最小裕度的主筋對：第'+pair.i+'／'+pair.j+'根；淨距='+f(pair.gap)+' cm，要求=max(4,1.5×'+f(Math.max(pair.di,pair.dj),4)+',4×'+s.agg+'/3)='+f(pair.req)+' cm；裕度='+f(pair.margin)+' cm。<br>':'')+'一般柱箍筋配置間距上限=min(16db,min,48dt,b,h)=min('+f(16*g.minDb)+','+f(48*g.dt)+','+s.b+','+s.h+') cm。<br>箍筋垂直淨距=s−dt='+s.s+'−'+g.dt+'='+f(s.s-g.dt)+' cm，要求≥4dagg/3='+f(4*s.agg/3)+' cm。<br>迴轉半徑 rx=h/√12='+f(s.h/Math.sqrt(12))+'、ry=b/√12='+f(s.b/Math.sqrt(12))+' cm<br>kxℓu/rx='+s.kx+'×'+s.L+'/'+f(s.h/Math.sqrt(12))+'='+f(r.det.slx)+'；限值='+f(r.det.limX,3)+'<br>kyℓu/ry='+s.ky+'×'+s.L+'/'+f(s.b/Math.sqrt(12))+'='+f(r.det.sly)+'；限值='+f(r.det.limY,3)+'<br>無側移限值=min(40,34+12M₁/M₂)；有側移限值22。超限須外部完成二階分析，勾選確認不會放大內力。</div>';
 if(s.mode==='seismic'){
  const maxP=Math.max(...r.loads.map(l=>l.P),0),kf=Math.max(s.fc/1750+.6,1),kn=g.bars.length/(g.bars.length-2),a=.3*(g.Ag/r.det.Ach-1)*s.fc/s.fyt,b=.09*s.fc/s.fyt,z=r.det.high?.2*kf*kn*maxP*1000/(s.fyt*r.det.Ach):0,cr=Math.max(a,b,z),so=Math.max(10,Math.min(15,10+(35-g.hx)/3)),bl=s.fy<=4200?6:s.fy<=5000?5.5:5;
  h+='<h4>5.9 特殊抗彎矩構架的圍束代入</h4><div class="formula">Ach=('+s.b+'−2×'+s.cover+')('+s.h+'−2×'+s.cover+')='+f(r.det.Ach)+' cm²<br>最大組合Pu='+f(maxP)+' tf；0.3Agfc′/1000='+f(.3*g.Ag*s.fc/1000)+' tf；高軸力條件：'+(r.det.high?'成立':'不成立')+'<br>kf=max(fc′/1750+0.6,1)='+f(kf)+'；kn=N/(N−2)='+g.bars.length+'/('+g.bars.length+'−2)='+f(kn)+'<br>R₁=0.3(Ag/Ach−1)fc′/fyt='+f(a,8)+'；R₂=0.09fc′/fyt='+f(b,8)+'<br>R₃=0.2kfknPu×1000/(fytAch)，僅高軸力時計入 = '+f(z,8)+'<br>R=max(R₁,R₂,R₃)='+f(cr,8)+'<br>Ash,x要求=R·s·(h−2cover)='+f(r.det.reqX)+' cm²；配置='+g.legsX+'×'+RCC.BARS[s.tie].a+'='+f(r.det.AshX)+' cm²<br>Ash,y要求=R·s·(b−2cover)='+f(r.det.reqY)+' cm²；配置='+g.legsY+'×'+RCC.BARS[s.tie].a+'='+f(r.det.AshY)+' cm²<br>so=max(10,min(15,10+(35−hx)/3))='+f(so)+' cm<br>本版耐震間距上限=min(一般限值,min(b,h)/4,'+bl+'db,min,so)='+f(r.det.smax)+' cm<br>ℓo≥max(b,h,ℓu/6,45)='+f(r.det.lo)+' cm；本版全高同一箍筋間距。接頭、強柱弱梁、錨定與容量剪力另計。</div>';
 }
 h+='<p class="notice">本組強度項目：'+(c.allPass?'通過':'未通過')+'；配置細則：'+(r.det.pass?'通過':'未通過／待確認')+'；所有載重組合及細則總結果：'+(r.pass?'本版實作項目通過':'本版實作項目有未通過／待處理')+'。資料来源與適用範圍見操作說明。</p>';
 return h;
}

