const A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const pw=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
(async()=>{const cr=(await import('../qa-tools/node_modules/@sparticuz/chromium/build/index.js')).default,b=await pw.chromium.launch({executablePath:await cr.executablePath(),args:cr.args,headless:true}),ctx=await b.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await ctx.setOffline(true);const p=await ctx.newPage(),errors=[],requests=[],checks=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url())});await p.goto('file://'+path.resolve(__dirname,'dist/index.html'));const ready=async(page=p)=>{await page.waitForFunction(()=>pm3dModel&&!pm3dStale&&!pm3dJob);await page.waitForTimeout(80)};await ready();await p.locator('.pm3d-advanced summary').click();A.equal(await p.evaluate(()=>pm3dModel.points),1740);A.equal(await p.evaluate(()=>pm3dHits.length),2);A((await p.locator('#pm3dReadout').innerText()).includes('0.3844'));checks.push('離線自動生成設計3D曲面、2個載重點及D/C');
await p.locator('#pm3dCanvas').scrollIntoViewIfNeeded();const box=await p.locator('#pm3dCanvas').boundingBox(),yaw=await p.evaluate(()=>pm3dYaw);await p.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await p.mouse.down();await p.mouse.move(box.x+box.width*.5+55,box.y+box.height*.5+25,{steps:5});await p.mouse.up();A(Math.abs(await p.evaluate(()=>pm3dYaw)-yaw)>.1);const z=await p.evaluate(()=>pm3dZoom);await p.mouse.wheel(0,-140);await p.waitForTimeout(80);A(await p.evaluate(()=>pm3dZoom)>z);checks.push('實際滑鼠旋轉與滾輪縮放');
for(const view of ['top','x','y','iso']){await p.locator('#pm3dView').selectOption(view);await p.waitForTimeout(50);A.equal(await p.evaluate(()=>pm3dZoom),1);}await p.locator('#pm3dCanvas').focus();await p.keyboard.press('ArrowRight');A(await p.evaluate(()=>pm3dYaw)>-.72);await p.keyboard.press('+');A(await p.evaluate(()=>pm3dZoom)>1);await p.keyboard.press('0');A.equal(await p.evaluate(()=>pm3dZoom),1);checks.push('四種視角、鍵盤旋轉縮放與重設');
await p.locator('#pm3dCase').selectOption('1');await p.waitForTimeout(80);A.equal(await p.evaluate(()=>selected),1);A((await p.locator('#pm3dReadout').innerText()).includes('0.6472'));const hit=await p.evaluate(()=>pm3dHits.find(v=>v.case===0));await p.locator('#pm3dCanvas').scrollIntoViewIfNeeded();const cb=await p.locator('#pm3dCanvas').boundingBox();await p.mouse.click(cb.x+hit.x,cb.y+hit.y);await p.waitForTimeout(100);A.equal(await p.evaluate(()=>selected),0);await p.locator('#pm3dAll').uncheck();await p.waitForTimeout(80);A.equal(await p.evaluate(()=>pm3dHits.length),1);await p.locator('#pm3dAll').check();await p.locator('#pm3dSlice').uncheck();await p.locator('#pm3dStyle').selectOption('wire');await p.locator('#pm3dStyle').selectOption('surface');await p.locator('#pm3dSlice').check();checks.push('載重選單、圖面點選、全部點及切片／線框切換');
await p.locator('#pm3dQuality').selectOption('high');await ready();A.equal(await p.evaluate(()=>pm3dModel.points),5400);await p.locator('#pm3dQuality').selectOption('standard');await ready();checks.push('精細曲面5400點與標準曲面1740點');
const pngEvent=p.waitForEvent('download');await p.locator('#pm3dPNG').click();const png=await pngEvent,pngPath=path.resolve(__dirname,'pm3d-export.png');await png.saveAs(pngPath);A.equal(fs.readFileSync(pngPath).subarray(1,4).toString(),'PNG');checks.push('下載目前視角PNG');
await p.locator('#b').fill('');await p.waitForFunction(()=>result===null);A.equal(await p.evaluate(()=>pm3dModel),null);A(await p.locator('#pm3dPNG').isDisabled());A.equal(await p.locator('#pm3dReadout').innerText(),'');await p.locator('#exampleSmall').click();await ready();checks.push('輸入無效清空3D與需求結果，範例復原');
await p.locator('#fc').fill('350');await p.locator('#fc').fill('420');await p.waitForFunction(()=>result?.s.fc===420&&pm3dModel&&!pm3dJob&&!pm3dStale);A.equal(await p.evaluate(()=>JSON.parse(pm3dModel.key)[2]),420);await p.locator('#exampleSmall').click();await ready();checks.push('快速修改材料時取消舊曲面，只顯示最新條件');
await p.locator('#layout').selectOption('layers');await ready();A.equal(await p.evaluate(()=>result.g.bars.length),24);await p.locator('#layerExample').click();await ready();A.equal(await p.evaluate(()=>result.g.bars.length),36);A(Math.abs(await p.evaluate(()=>pm3dModel.Pmax-result.cases[0].Pmax))<1e-7);checks.push('2層與3層主筋曲面依實際座標重建');
const offlineEvent=p.waitForEvent('download');await p.locator('#offlineTop').click();const offline=await offlineEvent,offlinePath=path.resolve(__dirname,'pm3d-offline.html');await offline.saveAs(offlinePath);const p2=await ctx.newPage();p2.on('pageerror',e=>errors.push(e.message));await p2.goto('file://'+offlinePath);await ready(p2);A.equal(await p2.evaluate(()=>result.g.bars.length),36);A.equal(await p2.evaluate(()=>pm3dModel.points),1740);checks.push('下載單檔離線版再開啟，自動重建3D與多層座標');
await p.locator('#surfaceCard').screenshot({path:path.resolve(__dirname,'pm3d-desktop.png')});
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});await p.waitForTimeout(80);const size=await p.evaluate(()=>({w:document.documentElement.clientWidth,sw:document.documentElement.scrollWidth}));A(size.sw<=size.w+1,JSON.stringify(size));checks.push(width+'px立體圖與工具列無全頁水平溢出')}
await p.setViewportSize({width:390,height:844});await p.locator('#surfaceCard').screenshot({path:path.resolve(__dirname,'pm3d-mobile.png')});
await p.locator('#exampleSmall').click();await ready();const before=await p.evaluate(()=>result.inputSnapshot),docEvent=p.waitForEvent('download');await p.locator('#docxTop').click();const doc=await docEvent,docPath=path.resolve(__dirname,'pm3d-regression.docx');await doc.saveAs(docPath);A.equal(fs.readFileSync(docPath).subarray(0,2).toString(),'PK');A.equal(await p.evaluate(()=>result.inputSnapshot),before);checks.push('保留最新原生可編輯DOCX匯出與輸入快照');
const mobile=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobile.setOffline(true);const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto('file://'+path.resolve(__dirname,'dist/index.html'));await ready(mp);await mp.locator('#pm3dCanvas').scrollIntoViewIfNeeded();const mb=await mp.locator('#pm3dCanvas').boundingBox(),cdp=await mobile.newCDPSession(mp),scroll=await mp.evaluate(()=>scrollY),myaw=await mp.evaluate(()=>pm3dYaw),ax=mb.x+mb.width*.4,ay=mb.y+200;
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:ax,y:ay,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:ax+40,y:ay+20,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});A(Math.abs(await mp.evaluate(()=>pm3dYaw)-myaw)>.1);A.equal(await mp.evaluate(()=>scrollY),scroll);checks.push('手機真實單指旋轉、不誤捲動');
const oldZoom=await mp.evaluate(()=>pm3dZoom);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:mb.x+70,y:ay,id:1},{x:mb.x+160,y:ay,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:mb.x+40,y:ay,id:1},{x:mb.x+190,y:ay,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});A(await mp.evaluate(()=>pm3dZoom)>oldZoom);checks.push('手機真實雙指縮放');
A.equal(errors.length,0,JSON.stringify(errors));A.equal(requests.length,0);checks.push('零執行錯誤與零外部資源請求');fs.writeFileSync(__dirname+'/surface-ui-validation.json',JSON.stringify({version:'1.4.0',date:'2026-10-07',checks,errors,requests},null,2));console.log(checks.join('\n'));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
