function traceDetail(s,g,values){const {minClear,rho,bcx,bcy,Ach,generalS,barLimit,so,smax,kn,kf,high,confRatio,reqX,reqY,rx,ry,slx,sly,limX,limY,checks}=values,t=[];const add=(title,formula,substitution,result,unit='',condition='',source='臺灣112年混凝土規範含113勘誤；既有核心')=>t.push({title,formula,substitution,result,unit,condition,source});
 add('配筋與主筋淨距','ρ=Ast/Ag；淨距要求=max(4,1.5db,max,4dagg/3)',`${g.Ast}/${g.Ag}；max(4,1.5×${g.maxDb},4×${s.agg}/3)`,`ρ=${rho}；最小要求=${minClear}`,'cm','混合筋徑／跨層逐對間距以原geometry判定','10.6、25.2.3');
 add('箍筋一般間距','sg=min(16db,min,48dt,b,h)',`min(${16*g.minDb},${48*g.dt},${s.b},${s.h})`,generalS,'cm','','25.7.2.1');
 add('耐震間距候選','smax=min(sg,min(b,h)/4,kbar db,min,so)；so=clamp(10+(35-hx)/3,10,15)',`sg=${generalS}；短邊/4=${Math.min(s.b,s.h)/4}；kbar=${barLimit}×${g.minDb}；so=${so}`,smax,'cm',`mode=${s.mode}；一般模式只採sg`,'18.4.5.3');
 add('核心圍束面積','bcx=b-2cover；bcy=h-2cover；Ach=bcx bcy',`${s.b}-2×${s.cover}=${bcx}；${s.h}-2×${s.cover}=${bcy}`,Ach,'cm²','僅箍筋需求，不增加斷面承載強度');
 add('圍束三候選最大值','ρconf=max(.3(Ag/Ach-1)fc/fyt,.09fc/fyt,high?.2kf kn Pmax/(fyt Ach):0)',`候選=${.3*(g.Ag/Ach-1)*s.fc/s.fyt},${.09*s.fc/s.fyt},${high?.2*kf*kn*values.maxP*1000/(s.fyt*Ach):0}；kf=${kf}；kn=${kn}；高軸力=${high}`,confRatio,'',`high比較：${values.maxP}×1000>.3×${g.Ag}×${s.fc}`,'表18.4.5.4，候選欄原引擎採最大值');
 add('箍筋面積需求','Ash,x,req=ρconf s bcy；Ash,y,req=ρconf s bcx',`${confRatio}×${s.s}×${bcy}；${confRatio}×${s.s}×${bcx}`,`X=${reqX}；Y=${reqY}`,'cm²',`實配X=${values.AshX}；Y=${values.AshY}`);
 add('長細篩選','rx=h/√12,ry=b/√12；λx=kxL/rx,λy=kyL/ry',`rx=${rx},ry=${ry}；${s.kx}×${s.L}/${rx}；${s.ky}×${s.L}/${ry}`,`λx=${slx},λy=${sly}`,'',`限值X=${limX},Y=${limY}；無側移min(40,34+12M1/M2)；有側移22；勾選second只確認外部內力，不替引擎放大`,'6.2.5');
 checks.forEach(c=>add('構造檢核 '+c.name,c.limit,`${c.value} ${c.unit}`,c.pass?'通過':c.info?'外部二階分析已確認':'未通過','',c.info?'超限但外部二階效應已確認':'保留原引擎容差與判定',c.ref));return t;}
function traceSection(s,c,angles){const t=[];const add=(title,formula,substitution,result,unit='',condition='',source='同一次RCC.section，臺灣112年混凝土規範')=>t.push({title,formula,substitution,result,unit,condition,source}),g=c.g,l=c.load||{};
 add('材料係數上下限','β1=clamp(.85-.05(fc-280)/70,.65,.85)；εy=fy/Es',`clamp(.85-.05×(${s.fc}-280)/70,.65,.85)；${s.fy}/${s.Es}`,`β1=${beta(s.fc)}；εy=${s.fy/s.Es}`,'','允許betaOverride驗算時保留原覆盖值');
 add('名義軸壓及設計上下限','P0=[.85fc(Ag-Ast)+fyAst]/1000；Pmax=.8×.65P0；Tmax=.9fyAst/1000',`[.85×${s.fc}×(${g.Ag}-${g.Ast})+${s.fy}×${g.Ast}]/1000`, `P0=${c.P0}；Pmax=${c.Pmax}；Tmax=${c.Tmax}`,'tf',`Pu=${l.P}；軸力界限通過=${c.axialOK}`);
 const w=c.witness;if(w){add('實際鄰近邊界求解','固定θ，以65次二分使φPn=Pu',w.solverHistory.map(z=>`i=${z.i},lo=${z.lo},hi=${z.hi},c=${z.c},φPn=${z.dp},更新=${z.branch}`).join('\n'),w.c,'cm',`角度=${w.theta} rad；角度樣本=${angles}；最終殘差=${w.dp-l.P} tf，求解接受容差1e-5max(1,|Pu|)`);
 add('壓力塊與折減','a=β1c；top=|nx|b/2+|ny|h/2；φ=.65+.25clamp((εt-εy)/.003,0,1)',`θ=${w.theta}；a=${w.a}；c=${w.c}；εt=${w.et}`,w.phi,'',`保留半平面nx x+ny y≥top-a；Ac=${w.concreteArea}；毛壓力=${w.concrete} tf`);
 w.rows.forEach((bar,i)=>add(`逐筋 ${i+1}${bar.layer?' 層'+bar.layer:''}`, 'ε=.003(1-d/c)；fs=clamp(Es ε,-fy,fy)；F=Ai fs-.85fc Aci',`bar=${bar.bar}；x=${bar.x},y=${bar.y},Ai=${bar.a},d=${bar.depth}；ε=${bar.eps}；fs=${bar.fs}；Aci=${bar.subArea}；Q=${bar.first}`,`鋼筋力=${bar.steelForce},扣除混凝土=${bar.concreteForce},淨力=${bar.Fs}；Mx=${bar.netMx},My=${bar.netMy}`,'kgf／kgf·cm','圓筋占用面積t=clamp((top-a-z)/(db/2),-1,1)，Aci=Ai[acos(t)-t√(1-t²)]/π；形心Q修正納入兩軸力矩'));
 add('斷面合力','Pn=Cc+ΣFi；Mn,c+ΣMi；φPn=φPn',`毛混凝土=${w.concrete} tf；Σ筋=${w.rows.reduce((a,b)=>a+b.Fs,0)/1000} tf；Pn=${w.P/1000}；Mnx=${w.Mx/100000},Mny=${w.My/100000}`,`φPn=${w.dp}；φMnx=${w.mx}；φMny=${w.my}`,'tf／tf·m','kgf→tf除1000；kgf·cm→tf·m除100000');}
 if(c.boundary){const b=c.boundary,cp=b.start.mx*b.uy-b.start.my*b.ux,cr=b.end.mx*b.uy-b.end.my*b.ux;add('包絡插值控制','t=kA/(kA-kB)；R=A+t(B-A)；Rc=R·u',`A=(${b.start.mx},${b.start.my}),B=(${b.end.mx},${b.end.my})；u=(${b.ux},${b.uy})；kA=${cp},kB=${cr}；t=${b.t}`,c.capacity,'tf·m',`交點R=(${b.mx},${b.my})；取需求正向最大交點`);}
 add('軸彎判定','D/C=|Mu|/Rc；純軸力採Pu/Pmax或|Pu|/Tmax',`Pu=${l.P},Mx=${l.Mx},My=${l.My}；容量=${c.capacity}`,String(c.ratio),'',`通過=${c.pass}；custom實際需求點inside=${c.inside},originInside=${c.originInside}；不是只看外側射線；無有效解不虛列逐筋表`);return t;}
