/* v1.6 narrated tutorial, embedded transcript and contextual parameter help. */
const tutorialVideo=$('tutorialVideo');
let tutorialPrepared=false,tutorialPendingSeek=null,tutorialCaptionsOn=$('tutorialCaptions').getAttribute('aria-pressed')!=='false',tutorialMediaError=false;
const tutorialChapterData=(TUTORIAL_DATA.chapters||[]).map((c,i)=>({...c,start:Number(c.start??c.time??0),title:c.title||c.name||'章節 '+(i+1)}));
const tutorialCueData=(TUTORIAL_DATA.cues||tutorialChapterData.flatMap(c=>c.cues||[{start:c.start,end:c.end,text:c.text||''}])).filter(c=>Number.isFinite(Number(c.start))&&Number.isFinite(Number(c.end))&&Number(c.end)>Number(c.start));
const tutorialClock=t=>Number.isFinite(t)?String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0'):'—';
function setAnalysisState(state){const el=$('analysisState'),bar=el.closest('.overview-shortcuts');bar.classList.toggle('pending',state==='pending');bar.classList.toggle('invalid',state==='invalid');el.textContent=state==='pending'?'資料已變更，正在重新計算；舊結果暫不可作報告。':state==='invalid'?'輸入資料需修正，尚無可使用的結果。':'斷面結果已更新；3D 曲面與切片另顯示建立進度。';}
function tutorialStatus(text,error=false){$('tutorialStatus').textContent=text;$('tutorialStatus').classList.toggle('error',error);}
function tutorialPrepare(){if(tutorialPrepared)return;tutorialPrepared=true;tutorialVideo.poster=tutorialVideo.dataset.poster;const track=$('tutorialTrack');if(location.protocol!=='file:'){track.src=track.dataset.src;track.addEventListener('load',()=>{if(track.track)track.track.mode='hidden';});}for(const t of tutorialVideo.textTracks)t.mode='hidden';}
function tutorialViewChanged(view){if(view==='tutorial')tutorialPrepare();else if(!tutorialVideo.paused)tutorialVideo.pause();}
function tutorialUpdate(){const t=tutorialVideo.currentTime||0,c= tutorialChapterData.findLast? tutorialChapterData.findLast(c=>c.start<=t):tutorialChapterData.filter(c=>c.start<=t).at(-1);document.querySelectorAll('#tutorialChapters button').forEach(b=>b.setAttribute('aria-current',b.dataset.chapter===(c?.id||'')?'true':'false'));const cue=tutorialCueData.find(x=>t>=Number(x.start)&&t<Number(x.end));$('tutorialCaptionText').hidden=!tutorialCaptionsOn||!cue||!cue.text;$('tutorialCaptionText').textContent=cue?.text||'';const duration=Number.isFinite(tutorialVideo.duration)?tutorialVideo.duration:TUTORIAL_DATA.duration;$('tutorialPosition').textContent=tutorialClock(t)+(duration?' / '+tutorialClock(duration):'');if(duration)$('tutorialDuration').textContent=tutorialClock(duration);}
function tutorialSeek(time){if(!Number.isFinite(time)||time<0)return;tutorialPrepare();if(innerWidth<=1000)tutorialVideo.parentElement.scrollIntoView({block:'start'});tutorialPendingSeek=time;tutorialMediaError=false;if(tutorialVideo.readyState>=1){tutorialVideo.currentTime=Math.min(time,Number.isFinite(tutorialVideo.duration)?Math.max(0,tutorialVideo.duration-.1):time);tutorialPendingSeek=null;tutorialStatus('已跳到 '+tutorialClock(time)+'；按播放開始。影片有中文旁白，可自行調整音量。');tutorialUpdate();}else{tutorialStatus('正在載入影片以跳到 '+tutorialClock(time)+'；載入完成後按播放開始。');tutorialVideo.preload='metadata';tutorialVideo.load();}}
$('tutorialChapters').innerHTML=tutorialChapterData.map((c,i)=>'<button data-time="'+c.start+'" data-chapter="'+esc(c.id)+'" aria-current="'+(i===0?'true':'false')+'"><span class="chapter-time">'+tutorialClock(c.start)+'</span><span class="chapter-name">'+esc(c.title)+'</span></button>').join('');
$('tutorialTranscript').innerHTML=tutorialChapterData.map(c=>'<article class="tutorial-transcript"><h4><span>'+esc(c.title)+'</span><button data-time="'+c.start+'">'+tutorialClock(c.start)+' 跳至影片</button></h4><p>'+esc(c.text||(c.cues||[]).map(x=>x.text).join(' '))+'</p></article>').join('');
for(const id of ['tutorialChapters','tutorialTranscript'])$(id).onclick=e=>{const b=e.target.closest('button[data-time]');if(b)tutorialSeek(Number(b.dataset.time));};
tutorialVideo.addEventListener('loadedmetadata',()=>{for(const t of tutorialVideo.textTracks)t.mode='hidden';if(tutorialPendingSeek!==null)tutorialSeek(tutorialPendingSeek);else tutorialUpdate();});tutorialVideo.addEventListener('timeupdate',tutorialUpdate);tutorialVideo.addEventListener('seeked',tutorialUpdate);tutorialVideo.addEventListener('play',()=>{tutorialMediaError=false;tutorialStatus('播放中；可點章節查詢。若無旁白，請取消靜音並調整裝置音量。');});tutorialVideo.addEventListener('pause',()=>{if(!tutorialMediaError)tutorialStatus('已暫停；可閱讀逐字稿或切換章節，再按播放繼續。');});tutorialVideo.addEventListener('ended',()=>tutorialStatus('教學播放完成。可依章節重看，或使用載入教學範例練習。'));tutorialVideo.addEventListener('volumechange',()=>{if(!tutorialMediaError)tutorialStatus(tutorialVideo.muted||tutorialVideo.volume===0?'目前為靜音；取消播放器靜音並調整裝置音量即可聽見中文旁白。':'中文旁白已開啟；可依需要調整播放器及裝置音量。');});tutorialVideo.addEventListener('error',()=>{tutorialMediaError=true;tutorialPendingSeek=null;tutorialStatus('影片暫時無法載入。請確認完整離線包含 assets 資料夾，或在線上頁面重試／另下載 MP4；下方逐字稿與計算功能仍可使用。',true);});
$('tutorialSpeed').onchange=()=>{tutorialVideo.playbackRate=Number($('tutorialSpeed').value);tutorialStatus('播放速度：'+$('tutorialSpeed').selectedOptions[0].textContent+'。');};$('tutorialCaptions').onclick=()=>{tutorialCaptionsOn=!tutorialCaptionsOn;$('tutorialCaptions').setAttribute('aria-pressed',String(tutorialCaptionsOn));$('tutorialCaptions').textContent='字幕：'+(tutorialCaptionsOn?'開啟':'關閉');tutorialUpdate();};
function tutorialOpen(){setView('tutorial');$('viewTitle').setAttribute('tabindex','-1');$('viewTitle').focus({preventScroll:true});$('tutorialPanel').scrollIntoView({block:'start'});}
for(const id of ['tutorialTop','quickTutorial','guideTutorial','tutorialGuideBottom'])$(id).onclick=tutorialOpen;
$('tutorialToGuide').onclick=()=>setView('guide');$('tutorialLoadExample').onclick=()=>{example();setView('overview');};$('tutorialCodeBasis').onclick=()=>{setView('guide');$('codeBasisCard').scrollIntoView({block:'start'});};$('quickDetail').onclick=()=>{setView('detail');$('viewTitle').setAttribute('tabindex','-1');$('viewTitle').focus({preventScroll:true});};$('quick3D').onclick=()=>{setView('overview');if(!$('surfaceCard').classList.contains('pm3d-maximized'))$('pm3dMaximize').click();$('pm3dCanvas').focus({preventScroll:true});};
// Official review metadata is embedded at build time; source links remain user-initiated.
if(Array.isArray(REGULATION_REVIEW.rows)&&REGULATION_REVIEW.rows.length){$('codeBasisTable').innerHTML=table(['規範／項目','條文與實作判讀'],REGULATION_REVIEW.rows.map(x=>[esc(x.title||x.item||x.name),esc(x.detail||x.status||x.description)]));}
const parameterList=Array.isArray(PARAMETER_DATA)?PARAMETER_DATA:(PARAMETER_DATA.parameters||[]);
function parameterCard(p){return '<h3>'+esc(p.label)+' <span class="audit-meta">'+esc(p.id)+'</span></h3><dl class="parameter-facts"><dt>適用模式</dt><dd>'+esc(p.applies||'全部模式')+'</dd><dt>定義／方向</dt><dd>'+esc(p.definition)+'</dd><dt>單位</dt><dd>'+esc(p.unit)+'</dd><dt>允許／合理範圍</dt><dd>'+esc(p.range||'依該欄位選項及工程核定條件輸入')+'</dd><dt>資料來源</dt><dd>'+esc(p.source)+'</dd><dt>可照填範例</dt><dd>'+esc(p.example||'請搭配程式內教學範例及核定圖說')+'</dd><dt>核對重點</dt><dd>'+esc(p.commonMisuse||p.applies||'')+'</dd></dl>';}
function parameterRender(query=''){const normalize=t=>t.toLowerCase().replace(/[ₗ]/g,'l').replace(/[_\s′]/g,''),q=normalize(query.trim()),list=parameterList.filter(p=>normalize([p.id,p.label,p.definition,p.source,p.unit].join(' ')).includes(q));$('parameterCount').textContent='顯示 '+list.length+' / '+parameterList.length+' 項';$('parameterEntries').innerHTML=list.map(p=>'<article class="parameter-entry" id="parameter-'+esc(p.id)+'">'+parameterCard(p)+'</article>').join('');if(!list.length)$('parameterEntries').innerHTML='<p class="muted">沒有符合的項目，請改用中文名稱、符號或單位搜尋。</p>';}
function parameterOpen(id){const p=parameterList.find(p=>p.id===id);if(!p)return;const dialog=$('parameterDialog');$('parameterDialogBody').innerHTML=parameterCard(p);dialog.dataset.currentParameterId=id;dialog.showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button[data-parameter-id]');if(b){e.preventDefault();parameterOpen(b.dataset.parameterId);}});
$('parameterClose').onclick=()=>$('parameterDialog').close();$('parameterAll').onclick=()=>{const id=$('parameterDialog').dataset.currentParameterId;$('parameterDialog').close();setView('guide');$('parameterSearch').value=id;parameterRender(id);$('parameterDictionary').scrollIntoView({block:'start'});};$('parameterSearch').oninput=()=>parameterRender($('parameterSearch').value);$('parameterClear').onclick=()=>{$('parameterSearch').value='';parameterRender();$('parameterSearch').focus();};$('quickParameters').onclick=()=>{setView('guide');$('parameterDictionary').scrollIntoView({block:'start'});$('parameterSearch').focus({preventScroll:true});};
for(const p of parameterList){const input=$(p.id);if(!input)continue;const label=document.querySelector('label[for="'+p.id+'"]')||input.closest('label');if(label&&!label.querySelector('[data-parameter-id]')){const b=document.createElement('button');b.type='button';b.className='parameter-help';b.dataset.parameterId=p.id;b.textContent='ⓘ';b.setAttribute('aria-label',p.label+'：定義與資料來源');label.appendChild(b);}input.setAttribute('aria-describedby',[input.getAttribute('aria-describedby')||'', 'parameterHelpHint'].join(' ').trim());}
parameterRender();tutorialVideo.playbackRate=Number($('tutorialSpeed').value)||1;tutorialUpdate();
// Dynamic layer fields and coordinate table headers need the same contextual definitions.
function parameterEnrichDynamic(){document.querySelectorAll('#layerEditor [data-field]').forEach(input=>{const id='layerConfig.'+input.dataset.field,label=document.querySelector('label[for="'+input.id+'"]');if(label&&!label.querySelector('[data-parameter-id]')){const b=document.createElement('button');b.type='button';b.className='parameter-help';b.dataset.parameterId=id;b.textContent='ⓘ';b.setAttribute('aria-label',label.textContent+'：定義與來源');label.appendChild(b);}});document.querySelectorAll('#customBarEditor thead th').forEach((th,i)=>{if(i<1||i>6||th.querySelector('[data-parameter-id]'))return;const id=['','bar','n','x1','y1','x2','y2'][i],b=document.createElement('button');b.type='button';b.className='parameter-help';b.dataset.parameterId='customBars.'+id;b.textContent='ⓘ';b.setAttribute('aria-label',th.textContent+'：定義與來源');th.appendChild(b);});}
new MutationObserver(parameterEnrichDynamic).observe($('layerEditor'),{childList:true,subtree:true});new MutationObserver(parameterEnrichDynamic).observe($('customBarEditor'),{childList:true,subtree:true});parameterEnrichDynamic();
