/* v1.6 narrated tutorial and parameter UX checks, plus calculation/export regressions. */
const A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const pw=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
(async()=>{
const browser=await pw.chromium.launch({executablePath:'/tmp/chromium',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage'],headless:true});
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'rc-tutorial-ui-')),errors=[],externalRequests=[],checks=[];let server,mediaVerified=false;
const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await ctx.newPage();
const observe=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!/^http:\/\/127\.0\.0\.1:/.test(r.url()))externalRequests.push(r.url());});};observe(page);
const ready=async p=>{await p.waitForFunction(()=>typeof result!=='undefined'&&result&&pm3dModel&&!pm3dStale&&!pm3dJob,{},{timeout:60000});};
const snap=async(p=page)=>p.evaluate(()=>({input:result.inputSnapshot,ratios:result.cases.map(c=>c.ratio)}));
const download=async selector=>{const [d]=await Promise.all([page.waitForEvent('download'),page.locator(selector).click()]);const f=path.join(scratch,d.suggestedFilename());await d.saveAs(f);return f;};
try{
const mediaOnly=process.env.RC_TUTORIAL_MEDIA_ONLY==='1';
if(mediaOnly){const old=JSON.parse(fs.readFileSync(path.join(__dirname,'tutorial-ui-validation.json'),'utf8'));checks.push(...old.checks.slice(0,17));}
else{
await page.goto('file://'+path.resolve(__dirname,'dist/index.html'));await ready(page);const original=await snap();
A(Math.abs(original.ratios[0]-.384387)<1e-5);A(Math.abs(original.ratios[1]-.647230)<1e-5);A.equal(await page.evaluate(()=>pm3dModel.points),1740);A.equal(await page.evaluate(()=>TUTORIAL_DATA.chapters.length),8);A.equal(await page.locator('#parameterEntries article').count(),52);
const initialRequests=await page.evaluate(()=>performance.getEntriesByType('resource').map(x=>x.name));A.equal(initialRequests.filter(x=>/\.mp4|\.jpg|\.vtt/.test(x)).length,0);checks.push('首頁計算與1740點曲面正確，52項字典已嵌入，首次不載入媒體');
await page.locator('[data-parameter-id=cover]').click();A(await page.locator('#parameterDialog').evaluate(e=>e.open));A.match(await page.locator('#parameterDialogBody').innerText(),/最外箍筋外緣/);A.match(await page.locator('#parameterDialogBody').innerText(),/6.54/);await page.keyboard.press('Escape');A.equal(await page.locator('#parameterDialog').evaluate(e=>e.open),false);checks.push('欄位旁參數對話框列定義、單位、範圍、來源與範例，Esc關閉');
const secondBefore=await page.locator('#second').isChecked();await page.locator('[data-parameter-id=second]').click();A.equal(await page.locator('#second').isChecked(),secondBefore);A.match(await page.locator('#parameterDialogBody').innerText(),/不/);await page.locator('#parameterClose').click();checks.push('外部二階分析說明按鈕不誤切換確認核取');
await page.locator('#quickParameters').click();A(await page.locator('#guidePanel').isVisible());await page.locator('#parameterSearch').fill('保護層');A((await page.locator('#parameterEntries article').count())>=1);await page.locator('#parameterSearch').fill('nₗ');A.equal(await page.locator('#parameterEntries article').count(),1);await page.locator('#parameterClear').click();A.equal(await page.locator('#parameterEntries article').count(),52);A.match(await page.locator('#codeBasisTable').innerText(),/21\.2\.4\.1/);A.match(await page.locator('#codeBasisTable').innerText(),/核心周邊/);checks.push('搜尋中文及nₗ符號、清除查詢、12項規範矩陣可閱讀');
await page.locator('#guideTutorial').click();A(await page.locator('#tutorialPanel').isVisible());A.equal(await page.locator('#workspace').isVisible(),false);A.equal(await page.locator('#tutorialChapters button').count(),8);A.equal(await page.locator('#tutorialTranscript article').count(),8);A.equal(await page.locator('#tutorialVideo').getAttribute('preload'),'none');A.equal(await page.locator('#tutorialVideo').getAttribute('autoplay'),null);A(await page.locator('#tutorialVideo').evaluate(v=>v.playsInline));checks.push('影片導覽、8章與逐字稿，手機inline播放且無自動播放');
await page.locator('#tutorialSpeed').selectOption('1.5');A.equal(await page.locator('#tutorialVideo').evaluate(v=>v.playbackRate),1.5);await page.locator('#tutorialCaptions').click();A.equal(await page.locator('#tutorialCaptions').getAttribute('aria-pressed'),'false');await page.locator('#tutorialCaptions').click();A.equal(await page.locator('#tutorialCaptions').getAttribute('aria-pressed'),'true');A.deepEqual(await snap(),original);checks.push('播放速度與字幕開關有效，教學控制不修改專案計算');
await page.evaluate(()=>{tutorialVideo.muted=true;});await page.waitForFunction(()=>$('tutorialStatus').textContent.includes('靜音'));A.match(await page.locator('#tutorialStatus').innerText(),/靜音/);await page.evaluate(()=>{tutorialVideo.muted=false;});await page.waitForFunction(()=>$('tutorialStatus').textContent.includes('旁白'));A.match(await page.locator('#tutorialStatus').innerText(),/旁白/);checks.push('靜音／旁白狀態有明確說明');
await page.locator('#tutorialToGuide').click();A(await page.locator('#guidePanel').isVisible());await page.locator('.nav [data-view=overview]').click();await page.locator('#quickDetail').click();A(await page.locator('#detailPanel').isVisible());await page.locator('.nav [data-view=overview]').click();await page.locator('#quick3D').click();A(await page.locator('#surfaceCard').evaluate(e=>e.classList.contains('pm3d-maximized')));await page.keyboard.press('Escape');checks.push('總覽捷徑正確切換計算明細與3D大工作台，Esc返回');
await page.locator('#fc').fill('');A.match(await page.locator('#analysisState').innerText(),/重新計算/);await page.waitForTimeout(350);A.match(await page.locator('#analysisState').innerText(),/需修正/);await page.locator('#fc').fill('280');await ready(page);A.match(await page.locator('#analysisState').innerText(),/已更新/);A.deepEqual(await snap(),original);checks.push('輸入變更／無效／恢復狀態正確，恢復後D/C相同');
await page.locator('#layout').selectOption('custom');await ready(page);A.equal(await page.locator('#nl').inputValue(),'4');A(await page.locator('[data-parameter-id="customBars.n"]').count()>0);const supportBefore=await page.locator('#supported').isChecked();await page.locator('[data-parameter-id=supported]').click();A.equal(await page.locator('#supported').isChecked(),supportBefore);A.match(await page.locator('#parameterDialogBody').innerText(),/有效/);await page.keyboard.press('Escape');await page.locator('#nl').fill('8');await ready(page);A.equal(await page.evaluate(()=>read().nl),8);checks.push('實際配筋新nl與旁註輸入、動態座標表說明、側撐說明不切換勾選');
await page.locator('#exampleSmall').click();await ready(page);const exampleSnapshot=await snap();const offline=await download('#offlineTop'),offlineText=fs.readFileSync(offline,'utf8');A.match(offlineText,/影片離線播放請使用完整離線包/);A.match(offlineText,/const PARAMETER_DATA/);const p2=await ctx.newPage();observe(p2);await p2.goto('file://'+offline);await ready(p2);A.deepEqual(await snap(p2),exampleSnapshot);A.equal(await p2.locator('#parameterEntries article').count(),52);await p2.close();checks.push('單一HTML保存後重開仍計算、參數與逐字稿齊全，明確說明影片需完整包');
const docx=await download('#docxTop');A.equal(fs.readFileSync(docx).subarray(0,2).toString(),'PK');A.deepEqual(await snap(),exampleSnapshot);checks.push('原生DOCX可下載且專案計算未變');
for(const w of [320,390,768,1440]){await page.setViewportSize({width:w,height:1000});await page.locator('#tutorialTop').click();A(await page.locator('#tutorialPanel').isVisible());A(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));A.equal(await page.locator('#tutorialVideo').getAttribute('playsinline'),'');const hs=await page.locator('#tutorialChapters button').evaluateAll(x=>x.map(e=>e.getBoundingClientRect().height));A(hs.every(h=>h>=42));await page.locator('#tutorialToGuide').click();A(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('.nav [data-view=overview]').click();await page.locator('[data-parameter-id=cover]').click();A(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(__dirname,'tutorial-qa-'+w+'.png')});await page.keyboard.press('Escape');checks.push(w+'px影片、章節、參數字典與對話框無全頁溢位／章節按鈕≥42px');}
const manual=fs.readFileSync(path.join(__dirname,'dist/manual.html'),'utf8');A.equal((manual.match(/class="parameter-entry"/g)||[]).length,52);A.match(manual,/21\.2\.4\.1/);A.match(manual,/核心周邊有效側撐/);checks.push('獨立操作說明HTML靜態包含52項參數與規範實作矩陣');
}
const media=path.join(__dirname,'dist/assets/rc-column-tutorial-v1.6.mp4');
if(fs.existsSync(media)){
const base=path.resolve(__dirname,'dist');server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname),f=path.join(base,pathname);if(!f.startsWith(base)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);res.end();return;}const stat=fs.statSync(f),type=f.endsWith('.mp4')?'video/mp4':f.endsWith('.vtt')?'text/vtt':f.endsWith('.jpg')?'image/jpeg':'text/html';res.setHeader('Content-Type',type);res.setHeader('Accept-Ranges','bytes');const range=req.headers.range;if(range){const m=range.match(/bytes=(\d+)-(\d*)/),start=+m[1],end=m[2]?Math.min(+m[2],stat.size-1):stat.size-1;res.writeHead(206,{'Content-Length':end-start+1,'Content-Range':`bytes ${start}-${end}/${stat.size}`});fs.createReadStream(f,{start,end}).pipe(res);}else{res.writeHead(200,{'Content-Length':stat.size});fs.createReadStream(f).pipe(res);}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,p3=await ctx.newPage();observe(p3);await p3.goto(origin+'/index.html');await ready(p3);await p3.locator('#tutorialTop').click();await p3.locator('#tutorialChapters button[data-chapter=inputs]').click();await p3.waitForFunction(()=>tutorialVideo.readyState>=1&&tutorialPendingSeek===null,{},{timeout:30000});const start=await p3.evaluate(()=>TUTORIAL_DATA.chapters[1].start);A(Math.abs(await p3.locator('#tutorialVideo').evaluate(v=>v.currentTime)-start)<.25);A(await p3.locator('#tutorialVideo').evaluate(v=>v.paused));checks.push('真實MP4載入metadata後章節精確跳轉，跳章不自動播放');
await p3.locator('#tutorialVideo').evaluate(v=>v.play());await p3.waitForTimeout(1800);A(await p3.locator('#tutorialVideo').evaluate(v=>v.currentTime)>start+.5);A(await p3.locator('#tutorialCaptionText').isVisible());A.match(await p3.locator('#tutorialCaptionText').innerText(),/./);await p3.locator('#tutorialSpeed').selectOption('1.25');A.equal(await p3.locator('#tutorialVideo').evaluate(v=>v.playbackRate),1.25);await p3.locator('#tutorialCaptions').click();A.equal(await p3.locator('#tutorialCaptionText').isVisible(),false);await p3.locator('#tutorialToGuide').click();A(await p3.locator('#tutorialVideo').evaluate(v=>v.paused));checks.push('真實影片播放前進、嵌入字幕同步、速度與字幕控制、離開教學自動暫停');
await p3.locator('#guideTutorial').click();await p3.route('**/rc-column-tutorial-v1.6.mp4*',route=>route.fulfill({status:404,body:''}));await p3.locator('#tutorialVideo').evaluate(v=>{v.src='assets/rc-column-tutorial-v1.6.mp4?missing=1';v.load();});await p3.waitForFunction(()=>tutorialMediaError,{},{timeout:15000});A.match(await p3.locator('#tutorialStatus').innerText(),/完整離線/);A(await p3.locator('#tutorialTranscript').isVisible());checks.push('影片載入錯誤保留逐字稿、計算與合理完整包說明');await p3.close();mediaVerified=true;
// Real file:// playback needs no VTT request; HTML captions are embedded.
const p4=await ctx.newPage();await p4.setViewportSize({width:390,height:844});observe(p4);await p4.goto('file://'+path.resolve(__dirname,'dist/index.html'));await ready(p4);await p4.locator('#tutorialTop').click();await p4.locator('#tutorialChapters button[data-chapter=inputs]').click();await p4.waitForFunction(()=>tutorialVideo.readyState>=1&&tutorialPendingSeek===null,{},{timeout:30000});await p4.locator('#tutorialVideo').evaluate(v=>v.play());await p4.waitForTimeout(1000);A(await p4.locator('#tutorialCaptionText').isVisible());A.equal(await p4.locator('#tutorialTrack').getAttribute('src'),null);const mobileVideo=await p4.locator('#tutorialVideo').boundingBox();A(mobileVideo.y>=0&&mobileVideo.y+mobileVideo.height<=844);A(await p4.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('390px完整包file://真實播放與繁中字幕正常，跳章帶回播放器且不依賴跨檔VTT讀取');await p4.close();
}else if(process.env.RC_TUTORIAL_MEDIA_REQUIRED==='1'){throw new Error('最終測試需要完整影片assets');}
A.deepEqual(errors,[]);A.deepEqual(externalRequests,[]);checks.push('全部新操作零JavaScript錯誤，無外部網路請求');
const record={version:'1.6.0-PRO',date:'2026-10-09',checks,mediaVerified,numbers:{parameters:52,chapters:8,duration:JSON.parse(fs.readFileSync(path.join(__dirname,'tutorial-chapters.json'),'utf8')).duration,mediaBytes:fs.existsSync(media)?fs.statSync(media).size:0,mediaSha256:fs.existsSync(media)?require('node:crypto').createHash('sha256').update(fs.readFileSync(media)).digest('hex'):null},notes:mediaVerified?['真實HTTP與file://媒體播放均經驗證。']:['暫未有影片assets，已驗其餘UI；最終須以RC_TUTORIAL_MEDIA_REQUIRED=1重跑。']};fs.writeFileSync(path.join(__dirname,'tutorial-ui-validation.json'),JSON.stringify(record,null,2));console.log(JSON.stringify(record,null,2));
}finally{if(server)await new Promise(r=>server.close(r));await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
