(function(){
 'use strict';
 const style=document.createElement('style');style.textContent='.rw-trace{overflow-wrap:anywhere}.rw-trace summary{cursor:pointer;font-weight:700;padding:10px}.rw-trace article{padding:14px;border-bottom:1px solid #d7e1eb}.rw-trace pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.8 system-ui}.rw-trace .trace-result{font-weight:700}.rw-trace details{border:1px solid #d7e1eb;border-radius:8px;margin:10px 0}@media print{.rw-trace details>div{display:block!important}.rw-trace details{break-inside:auto}.rw-trace article{break-inside:avoid}}';document.head.append(style);
 const btn=$('word-report')||document.createElement('button');btn.id='word-report';btn.textContent='匯出 Word 計算書';if(!btn.isConnected)$('report').insertAdjacentElement('afterend',btn);
 const note=$('word-status')||document.createElement('span');note.id='word-status';note.setAttribute('role','status');note.textContent='';if(!note.isConnected)btn.insertAdjacentElement('afterend',note);
 const exportState=()=>{btn.disabled=!result||traceStale||exportBusy;};
 window.setExportState=exportState;
 function traceHTML(r){let groups=new Map();for(const s of r.trace){const group=s.title.startsWith('牆身 ')?'牆身全部斷面及組合':s.title.startsWith('牆趾')?'牆趾全部組合及容量':s.title.startsWith('牆踵')?'牆踵全部組合及容量':s.title.includes('：強度組合')||s.title.match(/^\d/)?'強度組合、作用力及接觸':s.title.startsWith('地震')||s.title.startsWith('常時')?'使用組合、穩定及接觸':'係數、重量、配筋與其他計算';if(!groups.has(group))groups.set(group,[]);groups.get(group).push(s);}
 return '<div class="rw-trace"><h3>由本次實際引擎保存的詳細計算</h3><p>共 '+r.trace.length+' 筆運算紀錄；原始計算以完整浮點數執行，顯示12位有效數字，未對設計值額外取整。數值積分依實際切點分段，每段12小區間、5點Gauss求積。彎矩／剪力分開取包絡，沒有把兩種控制組合混當單一工況。</p>'+[...groups].map(([title,steps])=>'<details><summary>'+esc(title)+'（'+steps.length+' 筆）</summary><div>'+steps.map(s=>'<article><h4>'+esc(s.title)+'</h4><pre>公式：'+esc(s.formula)+'\n代入：'+esc(s.substitution)+'</pre><p class="trace-result">結果：'+esc(s.result)+(s.unit?' '+esc(s.unit):'')+'</p><p>條件及限制：'+esc(s.condition||'依本工具明列條件')+'</p><p class="muted">來源：'+esc(s.source)+'</p></article>').join('')+'</div></details>').join('')+'</div>';
 }
 const oldRender=render;render=function(r){oldRender(r);for(const root of [$('steps'),$('report-values')])for(const t of root.querySelectorAll('table')){if(!t.parentElement.classList.contains('tablewrap')){const wrap=document.createElement('div');wrap.className='tablewrap';t.before(wrap);wrap.append(t);}}$('steps').insertAdjacentHTML('beforeend',traceHTML(r));exportState();};
 const oldUpdate=update;update=function(){try{oldUpdate();}finally{exportState();}};
 // Both page printing and Word use the exact same immutable calculation snapshot.
 function snapshot(){if(!result||traceStale)throw Error('請等待本次有效輸入重新計算後匯出。');const r=result,project=$('project').value||'擋土牆';
 const labels=new Map();for(const el of document.querySelectorAll('label[for]'))labels.set(el.htmlFor,el.textContent.trim());
 const units={H:'m',Tt:'m',Tb:'m',toe:'m',heel:'m',Tf:'m',haunch:'m',length:'m',batter:'V/H',Hw:'m',Hp:'m',alpha:'°',phi:'°',delta:'°',phiBase:'°',phiFront:'°',gamma:'tf/m³',gammaSat:'tf/m³',gammaFront:'tf/m³',concrete:'tf/m³',qa:'tf/m²',qaE:'tf/m²',surcharge:'tf/m²',cBase:'tf/m²',fc:'kgf/cm²',fy:'kgf/cm²',cover:'cm',coverBase:'cm',aggregate:'cm',keyW:'m',keyH:'m',keyX:'m'};
 const inputs=Object.entries(r.p).map(([key,value])=>{const el=$(key),shown=el?.tagName==='SELECT'?el.selectedOptions[0].textContent:value;return {label:(labels.get(key)||el?.closest('label')?.textContent.trim()||key)+' ['+key+']',value:shown,unit:units[key]||(/^space/.test(key)?'cm':/^bar/.test(key)?'#':'無因次／選項')};});
 let svg=drawing(r).match(/<svg[\s\S]*?<\/svg>/)[0].replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" ');
 const report={valid:true,stale:false,title:project+'－擋土牆詳細計算書',summary:'當次輸入快照；'+new Date().toLocaleString('zh-TW')+'；'+(r.localPass?'本版檢核通過；整體及詳圖另核':'有不通過或待補核項目')+'。原公式保持不變，包含全部使用與強度組合、各牆身斷面、趾踵及止滑榫。',inputs,steps:r.trace,diagram:{svg,width:530,height:449,caption:'依本次輸入繪製的擋土牆斷面、幾何尺寸、水位與土壓作用面；示意圖非施工圖。'},conclusions:[...r.cases.map(c=>c.name+'：FS滑='+fmt(c.slide,6)+'，FS傾='+fmt(c.over,6)+'；'+(c.pass?'本項通過':'未通過／需處理')+(c.error?'；'+c.error:'')),...r.stems.map((s,i)=>'牆身斷面'+(i+1)+'：控制'+s.control+'；Mu='+fmt(s.M,6)+' tf·m/m；Vu='+fmt(s.V,6)+' tf/m；'+(s.ok?'所列RC項目通過':'所列RC項目未通過')),...r.foot.map(s=>(s.side==='Toe'?'牆趾':'牆踵')+'：控制'+s.control+'；'+(s.ok&&!s.reversal?'所列RC項目通過':'未通過／反向筋另核')),...r.warnings,'整體滑動、液化、沉陷、排水可靠性、錨定、接頭、施工階段與母構材須另核。']};
 return structuredClone(report);
 }
 async function compactWord(report){report=structuredClone(report);CalculationDocx.validate(report);const d=globalThis.docx;
 const p=(text,opts={})=>new d.Paragraph({children:[new d.TextRun({text:String(text??''),font:'Microsoft JhengHei',size:19,color:'000000'})],spacing:{after:60},...opts});
 const heading=t=>p(t,{heading:d.HeadingLevel.HEADING_1,keepNext:true});
 const makeTable=(heads,rows,widths)=>new d.Table({width:{size:100,type:d.WidthType.PERCENTAGE},columnWidths:widths,rows:[heads,...rows].map((row,i)=>new d.TableRow({tableHeader:i===0,children:row.map((text,j)=>new d.TableCell({width:{size:widths[j],type:d.WidthType.DXA},margins:{top:70,bottom:70,left:90,right:90},shading:i===0?{fill:'E8EEF4'}:undefined,children:String(text??'').split('\n').map(t=>p(t))}))}))});
 const children=[p(report.title,{heading:d.HeadingLevel.TITLE}),p(report.summary),p('完整引擎紀錄 '+report.steps.length+' 筆；同一公式僅列一次，各實際運算以可編輯表格逐列保存。浮點計算未取整，顯示12位有效數字。數值積分按實際切點分段，每段12小區間、5點Gauss求積；表列區間與分段累加值來自原求積累加器。'),heading('本次輸入與單位'),makeTable(['參數','值','單位'],report.inputs.map(i=>[i.label,i.value,i.unit]),[4000,3300,1700]),p('')];
 const groups=new Map();for(const s of report.steps){if(!groups.has(s.formula))groups.set(s.formula,[]);groups.get(s.formula).push(s);}
 let groupIndex=0;for(const [formula,steps]of groups){children.push(heading((++groupIndex)+'. '+steps[0].title.replace(/：.*/,'')),p('實際執行公式：'+formula),makeTable(['工況／運算','數值代入、條件及來源','結果'],steps.map(s=>[s.title,s.substitution+'\n條件：'+s.condition+'\n來源：'+s.source,String(s.result)+(s.unit?' '+s.unit:'')]),[1800,5200,2000]),p(''));}
 children.push(heading('本次斷面及作用示意圖'));const diag=report.diagram,url=URL.createObjectURL(new Blob([diag.svg],{type:'image/svg+xml'}));let png;
 try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('本次圖示無法轉換'));img.src=url;});const canvas=document.createElement('canvas');canvas.width=1060;canvas.height=898;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);png=new Uint8Array(await(await new Promise(resolve=>canvas.toBlob(resolve,'image/png'))).arrayBuffer());}finally{URL.revokeObjectURL(url);}
 children.push(new d.Paragraph({children:[new d.ImageRun({type:'svg',data:new TextEncoder().encode(diag.svg),fallback:{type:'png',data:png},transformation:{width:diag.width,height:diag.height},altText:{title:diag.caption,description:diag.caption,name:'retaining-wall-snapshot'}})],alignment:d.AlignmentType.CENTER}),p(diag.caption),heading('結果、判定與限制'),...report.conclusions.map(c=>p(c)));
 const wordDocument=new d.Document({creator:'Engineering Calculator',title:report.title,styles:{default:{document:{run:{font:'Microsoft JhengHei',size:19,color:'000000'}}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1000,bottom:1000,left:1000,right:1000}}},children}]});return new Uint8Array(await d.Packer.toArrayBuffer(wordDocument));
 }
 btn.onclick=async()=>{if(exportBusy)return;try{const report=snapshot();exportBusy=true;exportState();note.textContent='正在建立 Word 計算書…';const bytes=await compactWord(report);download(bytes,'擋土牆_詳細計算書.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');note.textContent='Word 計算書已建立（本次輸入快照）。';}catch(e){note.textContent=e.message;toast(e.message);}finally{exportBusy=false;exportState();}};
 // Never save a transient export-disabled state in an offline copy.
 const oldOffline=$('offline').onclick;$('offline').onclick=()=>{if(traceStale||!result)return toast('請等待本次有效輸入重新計算。');const was=btn.disabled,oldNote=note.textContent;btn.disabled=false;note.textContent='';try{oldOffline();}finally{btn.disabled=was;note.textContent=oldNote;}};
 window.RetainingWallReport={snapshot,traceHTML,compactWord,getResult:()=>result,getStale:()=>traceStale};
 if(result){render(result);}exportState();
})();
