/* v2: internal units m, kN, kPa except RC section mm, MPa. Pure functions. */
const AdvancedPile=(()=>{
 const finite=(x,n)=>{if(!Number.isFinite(x))throw Error(n+'需填有效數字');return x;};
 const range=(x,a,b,n)=>{finite(x,n);if(x<a||x>b)throw Error(n+`限 ${a}～${b}`);return x;};
 const area=d=>Math.PI*d*d/4;
 function solve(A,b){const n=b.length,a=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++)if(Math.abs(a[i][k])>Math.abs(a[p][k]))p=i;if(Math.abs(a[p][k])<1e-12)throw Error('分析矩陣不穩定，請檢查支承與土壤勁度');[a[k],a[p]]=[a[p],a[k]];for(let i=k+1;i<n;i++){const t=a[i][k]/a[k][k];for(let j=k+1;j<=n;j++)a[i][j]-=t*a[k][j];a[i][k]=0;}}const x=Array(n).fill(0);for(let i=n-1;i>=0;i--){let v=a[i][n];for(let j=i+1;j<n;j++)v-=a[i][j]*x[j];x[i]=v/a[i][i];}return x;}
 function section(s,D){range(D,.3,4,'RC樁徑 m');for(const k of ['fc','fy','fyt','cover','bar','ties','spacing','outerSpacing','n','Pu','Mx','My','Vu','e','reinforced','denseLength','inflection'])finite(s[k],k);range(s.fc,21,70,'混凝土MPa');range(s.fy,280,550,'主筋MPa');range(s.fyt,280,550,'箍筋MPa');if(s.Pu>.3*area(D*1000)*s.fc/1000&&s.seismic==='III')throw Error('高軸壓第三類地盤需完整柱圍束條件專項；本版不提供合格判定');range(s.n,6,100,'主筋根數');if(!Number.isInteger(s.n)||s.n%2)throw Error('單向P–M配置採偶數支對稱主筋');if(s.My!==0)throw Error('本頁只計單向Mu，雙軸需求須另行分析');range(s.bar,19,57,'主筋直徑mm');range(s.ties,13,32,'箍筋直徑mm');range(s.cover,75,200,'淨保護層mm');range(s.spacing,25,300,'密區間距mm');range(s.outerSpacing,25,600,'一般區間距mm');range(s.e,0,500,'附加偏心mm');range(s.reinforced,.1,100,'配筋長度m');range(s.denseLength,.1,100,'密區長度m');range(s.inflection,0,100,'反曲點深度m');range(s.Vu,0,1e6,'Vu kN');if(!['none','I','III'].includes(s.seismic))throw Error('耐震地盤選項錯誤');
 const d=D*1000,R=d/2,r=R-s.cover-s.ties-s.bar/2;if(r<=0)throw Error('主筋配置超出斷面');const Ag=area(d),As=s.n*area(s.bar),ratio=As/Ag,clear=2*r*Math.sin(Math.PI/s.n)-s.bar;const b1=Math.max(.65,.85-.05*Math.max(0,s.fc-28)/7),bars=Array.from({length:s.n},(_,i)=>r*Math.cos(2*Math.PI*i/s.n)),P0=(.85*s.fc*(Ag-As)+s.fy*As)/1000;
 // Exact circle segment concrete area / first moment; deduct displaced concrete at bars.
 function point(c){const a=Math.min(d,b1*c),t=R-a,root=Math.sqrt(Math.max(0,R*R-t*t)),Ac=R*R*Math.acos(Math.max(-1,Math.min(1,t/R)))-t*root,Qc=2/3*root**3;let P=.85*s.fc*Ac,M=.85*s.fc*Qc;for(const y of bars){const eps=.003*(c-(R-y))/c,fs=Math.max(-s.fy,Math.min(s.fy,200000*eps)),F=area(s.bar)*(fs-(y>=t?.85*s.fc:0));P+=F;M+=F*y;}const et=Math.max(0,.003*((R-Math.min(...bars))-c)/c),phi=.65+.25*Math.max(0,Math.min(1,(et-s.fy/200000)/.003));return {c,a,Ac,et,phi,P:P/1000,M:Math.abs(M)/1e6,Pd:phi*P/1000,Md:phi*Math.abs(M)/1e6};}
 const points=[{Pd:-.9*s.fy*As/1000,Md:0,c:0,phi:.9,et:Infinity}];for(let i=0;i<=360;i++)points.push(point(d*.00001*Math.pow(1e7,i/360)));points.sort((a,b)=>a.Pd-b.Pd);
 const axialCap=.55*P0; // Table13.4.3.2, no column 0.80 cap (22.4.2.4 excluded for deep foundations).
 let cap=0,at=null;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(s.Pu>=a.Pd&&s.Pu<=b.Pd&&b.Pd>a.Pd){const w=(s.Pu-a.Pd)/(b.Pd-a.Pd),v=a.Md+w*(b.Md-a.Md);if(v>cap){cap=v;at=b;}}}
 const demand=Math.hypot(s.Mx,s.My)+Math.abs(s.Pu)*s.e/1000;
 // Specified uniform bar orientation, one bar on compression face; single bending plane.
 const strengthOK=s.Pu<=axialCap&&s.Pu>=points[0].Pd&&demand<=cap+1e-9;
 const core=d-2*s.cover,Ach=area(core),rho=4*area(s.ties)/(core*s.spacing),rhoReq=s.seismic==='none'?0:(s.seismic==='III'?1:.5)*.12*s.fc/s.fyt,maxSpacing=Math.min(d/4,100,(s.fy<=420?6:s.fy<=490?5.5:5)*s.bar),maxOuter=Math.min(d/2,s.seismic==='none'?600:300,s.seismic==='none'?16*s.bar:12*s.bar,48*s.ties),requiredDense=Math.max(D,s.inflection/3,.45,s.seismic==='I'?3*D:s.seismic==='III'?7*D:0),minReinf=s.L;
 const effective=.8*d,Av=2*area(s.ties),Vs=Av*s.fyt*effective/Math.max(s.spacing,s.outerSpacing)/1000,Vmax=.66*Math.sqrt(s.fc)*d*effective/1000,Vdesign=.75*Math.min(Vs,Vmax); // Vc=0 conservative; circular d=0.8D per22.5.2.2.
 const detailOK=ratio>=.005&&ratio<=.08&&clear>=Math.max(40,1.5*s.bar)&&s.spacing<=maxSpacing&&s.outerSpacing<=maxOuter&&rho>=rhoReq&&s.denseLength>=Math.min(s.L,requiredDense)&&s.reinforced>=minReinf;
 return {Ag,As,ratio,clear,b1,P0,axialCap,cap,demand,strengthOK,at,points,rho,rhoReq,maxSpacing,maxOuter,requiredDense,minReinf,effective,Av,Vs,Vdesign,shearOK:s.Vu<=Vdesign,detailOK,OK:strengthOK&&s.Vu<=Vdesign&&detailOK};
 }
 function group(g,p,r,ls){if(p.mode!=='current'||!r.fsOK)throw Error('群樁需現行模式且安全係數符合');if(p.db!==p.d)throw Error('群樁模組目前限等斷面，擴底需專項分析');for(const k of ['nx','ny','sx','sy','N','Mx','My','eta','qbBlock'])finite(g[k],k);range(g.nx,1,10,'X樁數');range(g.ny,1,10,'Y樁數');if(!Number.isInteger(g.nx)||!Number.isInteger(g.ny))throw Error('樁數須整數');if(g.nx*g.ny<2)throw Error('群樁至少2支');range(g.sx,p.d,30,'X間距');range(g.sy,p.d,30,'Y間距');range(g.eta,.1,1,'群樁摩擦折減');range(g.qbBlock,0,1e6,'塊體端承kPa');if(!['sand','clay'].includes(g.soil))throw Error('群樁土性錯誤');
 const n=g.nx*g.ny,B=(g.nx-1)*g.sx+p.d,W=(g.ny-1)*g.sy+p.d,A=B*W,U=2*(B+W),L=p.tip-p.head,spacing=Math.max(2.5*p.d,p.type==='bored'?p.d+1:.75),coords=[];for(let i=0;i<g.nx;i++)for(let j=0;j<g.ny;j++)coords.push({x:(i-(g.nx-1)/2)*g.sx,y:(j-(g.ny-1)/2)*g.sy});const xx=coords.reduce((s,c)=>s+c.x*c.x,0),yy=coords.reduce((s,c)=>s+c.y*c.y,0);if((xx===0&&g.My!==0)||(yy===0&&g.Mx!==0))throw Error('單排樁無法以軸力偶抵抗該方向彎矩');let z=0,T=0,eff=0;const parts=[];ls.forEach((l,i)=>{const a=Math.max(z,p.head),b=Math.min(z+l.h,p.tip);if(b>a){const tau=g.tau[i];range(tau,0,1e5,'第'+(i+1)+'層群樁外圍抗剪強度');T+=tau*(b-a);const dry=Math.max(0,Math.min(b,p.water)-a),wet=Math.max(0,b-Math.max(a,p.water));eff+=l.gamma*dry+(l.sat-9.80665)*wet;parts.push({a,b,tau,contribution:U*tau*(b-a)});}z+=l.h;});
 const sumGross=n*(g.eta*r.qs/p.fs+r.qb/p.fb),blockGross=U*T/p.fs+A*g.qbBlock/p.fb,net=(g.soil==='clay'?Math.min(sumGross,blockGross):sumGross)-n*(r.weight+p.down),soilWeight=Math.max(0,A-n*r.geo.A)*eff,blockPull=soilWeight+n*r.weight+U*T/p.fu,pull=Math.min(n*r.uplift,blockPull),reactions=coords.map((c,i)=>({...c,id:i+1,P:g.N/n+(yy?g.Mx*c.y/yy:0)+(xx?g.My*c.x/xx:0)})),individual=reactions.every(c=>c.P>=0?c.P<=r.net:-c.P<=r.uplift),spacingOK=(g.nx===1||g.sx>=spacing)&&(g.ny===1||g.sy>=spacing),sandEvidence=g.soil==='clay'||g.eta<1||p.type==='driven'||g.contact;
 const equilibrium={N:reactions.reduce((s,c)=>s+c.P,0),Mx:reactions.reduce((s,c)=>s+c.P*c.y,0),My:reactions.reduce((s,c)=>s+c.P*c.x,0)};
 return {n,B,W,A,U,L,spacing,spacingOK,sumGross,blockGross,net,pull,blockPull,soilWeight,parts,reactions,individual,sandEvidence,equilibrium,OK:spacingOK&&sandEvidence&&individual&&(g.N>=0?g.N<=net:-g.N<=pull)};
 }
 function settlement(a,p,r,g,gr){const L=p.tip-p.head;for(const k of ['load','tipFraction','alpha','Cp','Ep','limit','raftDepth','groupLimit'])finite(a[k],k);range(a.load,0,1e7,'沉陷工作載重kN');range(a.tipFraction,0,1,'工作端承比例');range(a.alpha,0,1,'軸向分布係數');range(a.Cp,.001,.5,'Cp');range(a.Ep,1000,100000,'樁材E MPa');range(a.limit,.1,1000,'容許單樁沉陷mm');range(a.groupLimit,.1,1000,'容許群樁沉陷mm');range(a.raftDepth,0,L,'等似底面距樁頭深度');if(r.tip.qb<=0)throw Error('端承極限壓力需大於零，Vesic式才適用');const Qb=a.load*a.tipFraction,Qs=a.load-Qb,Cs=(.93+.16*Math.sqrt(L/p.d))*a.Cp,elastic=(Qb+a.alpha*Qs)*L/(r.geo.A*a.Ep*1000),end=a.Cp*Qb/(p.d*r.tip.qb),shaft=Cs*Qs/(L*r.tip.qb),single=(elastic+end+shaft)*1000;const soil=r.tip.trace?.soil||'sand',bounds=p.type==='bored'?(soil==='clay'?[.03,.06]:[.09,.18]):(soil==='clay'?[.02,.03]:[.02,.04]),CpOK=a.Cp>=bounds[0]&&a.Cp<=bounds[1];
 if(!gr)throw Error('請先完成群樁有效輸入');if(g.N<0)throw Error('群樁沉陷目前限淨受壓');const B=gr.B,W=gr.W,rows=[];let depth=0,immediate=0,consolidation=0;for(const row of a.rows){range(row.h,.01,1000,'壓縮層厚度');range(row.M,1,1e7,'拘束模數kPa');range(row.sig,.1,1e7,'初始有效應力');range(row.e0,.01,10,'初始孔隙比');range(row.Cc,0,10,'Cc');range(row.Cr,0,row.Cc,'Cr');range(row.pc,row.sig,1e7,'預壓密壓力');const z=depth+row.h/2,ds=g.N/((B+z)*(W+z)),si=ds*row.h/row.M;let sc=0;if(row.consolidate){const fin=row.sig+ds,low=Math.min(fin,row.pc);sc=row.h/(1+row.e0)*(row.Cr*Math.log10(low/row.sig)+row.Cc*Math.log10(Math.max(fin,row.pc)/row.pc));}immediate+=si;consolidation+=sc;rows.push({...row,z,ds,si:si*1000,sc:sc*1000});depth+=row.h;}if(!rows.length)throw Error('需填等似底面以下壓縮層');const pile=g.N/gr.n*(a.tipFraction+a.alpha*(1-a.tipFraction))*L/(r.geo.A*a.Ep*1000),total=(pile+immediate+consolidation)*1000,eccentric=Math.abs(g.Mx)+Math.abs(g.My)>1e-9;
 return {Qb,Qs,Cs,elastic:elastic*1000,end:end*1000,shaft:shaft*1000,single,CpOK,CpBounds:bounds,singleOK:single<=a.limit&&a.load<=r.net&&CpOK&&p.mode==='current'&&r.fsOK,pile:pile*1000,immediate:immediate*1000,consolidation:consolidation*1000,total,rows,depth,eccentric,groupOK:total<=a.groupLimit&&!eccentric&&gr.OK};
 }
 const gauss=[[-.8611363115940526,.3478548451374538],[-.3399810435848563,.6521451548625461],[.3399810435848563,.6521451548625461],[.8611363115940526,.3478548451374538]];
 function lateral(a,p){const L=p.tip-p.head;for(const k of ['E','eiRatio','H','M','pm','count','limit','steps'])finite(a[k],k);range(a.E,1000,100000,'E MPa');range(a.eiRatio,.05,1,'有效EI比');range(a.pm,.05,1,'p multiplier');range(a.count,1,100,'共同側向樁數');range(a.steps,20,120,'側向元素數');if(!Number.isInteger(a.count)||!Number.isInteger(a.steps))throw Error('元素數與樁數需整數');range(a.limit,.1,1000,'容許側移mm');if(!['free','fixed'].includes(a.head)||!['free','fixed'].includes(a.toe))throw Error('樁頭/樁端邊界錯誤');if(a.head==='fixed'&&a.M!==0)throw Error('固定轉角的樁頭M由反力求得，輸入力矩請填0');if(a.H===0&&a.M===0)throw Error('側向載重與力矩不可同為0');let z=0;const soil=a.rows.map(row=>{range(row.h,.01,500,'側向層厚度');range(row.kh,0,1e7,'kh kN/m³');range(row.pult,.001,1e7,'pult kN/m');const v={...row,a:z,b:z+row.h};z+=row.h;return v;});if(z<L-1e-8)throw Error('側向土層未涵蓋樁頭至樁端全長');const I=p.shape==='circle'?Math.PI*p.d**4/64:p.d**4/12,EI=a.E*1000*I*a.eiRatio,N=a.steps,nd=2*(N+1),h=L/N,K=Array.from({length:nd},()=>Array(nd).fill(0)),F=Array(nd).fill(0);F[0]=a.H/a.count;F[1]=a.M/a.count;const elements=[];
 for(let e=0;e<N;e++){const ids=[2*e,2*e+1,2*e+2,2*e+3],Ke=[[12,6*h,-12,6*h],[6*h,4*h*h,-6*h,2*h*h],[-12,-6*h,12,-6*h],[6*h,2*h*h,-6*h,4*h*h]].map(row=>row.map(v=>v*EI/h**3)),Ks=Array.from({length:4},()=>Array(4).fill(0)),segments=[e*h,(e+1)*h,...soil.flatMap(l=>[l.a,l.b]).filter(v=>v>e*h+1e-8&&v<(e+1)*h-1e-8)].sort((a,b)=>a-b);const integration=[];for(let j=1;j<segments.length;j++){const mid=(segments[j]+segments[j-1])/2,len=(segments[j]-segments[j-1])/2;for(const [q,w] of gauss){const pos=mid+len*q,t=(pos-e*h)/h,l=soil.find(l=>pos>=l.a&&pos<l.b)||soil.at(-1),shape=[1-3*t*t+2*t**3,h*(t-2*t*t+t**3),3*t*t-2*t**3,h*(-t*t+t**3)],k=l.kh*p.d*a.pm;for(let x=0;x<4;x++)for(let y=0;y<4;y++)Ks[x][y]+=k*shape[x]*shape[y]*w*len;integration.push({z:pos,w:w*len,k,shape,pult:l.pult*a.pm});}}for(let x=0;x<4;x++)for(let y=0;y<4;y++)K[ids[x]][ids[y]]+=Ke[x][y]+Ks[x][y];elements.push({ids,integration});}
 const fixed=new Set();if(a.head==='fixed')fixed.add(1);if(a.toe==='fixed'){fixed.add(nd-2);fixed.add(nd-1);}const free=Array.from({length:nd},(_,i)=>i).filter(i=>!fixed.has(i)),d=Array(nd).fill(0),v=solve(free.map(i=>free.map(j=>K[i][j])),free.map(i=>F[i]));free.forEach((id,i)=>d[id]=v[i]);const reaction=K.map((row,i)=>row.reduce((sum,k,j)=>sum+k*d[j],0)-F[i]);const rows=[];let soilForce=0,soilMoment=0,ratio=0;
 for(let e=0;e<N;e++){const el=elements[e],u=el.ids.map(i=>d[i]);for(const q of el.integration){const y=q.shape.reduce((s,n,i)=>s+n*u[i],0),force=q.k*y;soilForce+=force*q.w;soilMoment+=force*q.w*q.z;ratio=Math.max(ratio,Math.abs(force)/q.pult);}for(let j=0;j<=4;j++){if(e&&j===0)continue;const t=j/4,N2=[(-6+12*t)/h**2,(-4+6*t)/h,(6-12*t)/h**2,(-2+6*t)/h],N3=[12/h**3,6/h**2,-12/h**3,6/h**2],shape=[1-3*t*t+2*t**3,h*(t-2*t*t+t**3),3*t*t-2*t**3,h*(-t*t+t**3)];rows.push({z:(e+t)*h,y:shape.reduce((s,n,i)=>s+n*u[i],0)*1000,M:EI*N2.reduce((s,n,i)=>s+n*u[i],0),V:EI*N3.reduce((s,n,i)=>s+n*u[i],0)});}}
 // Recover M,V by integrated equilibrium, enforcing exact free-end boundary values.
 for(const row of rows){let Rp=0,Rm=0;for(let e=0;e<N&&e*h<row.z;e++){const lo=e*h,hi=Math.min((e+1)*h,row.z),u=elements[e].ids.map(i=>d[i]),cuts=[lo,hi,...soil.flatMap(l=>[l.a,l.b]).filter(z=>z>lo&&z<hi)].sort((a,b)=>a-b);for(let j=1;j<cuts.length;j++){const mid=(cuts[j]+cuts[j-1])/2,half=(cuts[j]-cuts[j-1])/2;for(const [q,w] of gauss){const z=mid+half*q,t=(z-lo)/h,l=soil.find(l=>z>=l.a&&z<l.b)||soil.at(-1),ns=[1-3*t*t+2*t**3,h*(t-2*t*t+t**3),3*t*t-2*t**3,h*(-t*t+t**3)];const force=l.kh*a.pm*p.d*ns.reduce((sum,n,i)=>sum+n*u[i],0);Rp+=force*w*half;Rm+=force*(row.z-z)*w*half;}}}row.M=-(F[1]+reaction[1])+(F[0]+reaction[0])*row.z-Rm;row.V=F[0]+reaction[0]-Rp;for(const l of soil.filter(l=>row.z>=l.a-1e-9&&row.z<=l.b+1e-9))ratio=Math.max(ratio,Math.abs(l.kh*p.d*a.pm*row.y/1000)/(l.pult*a.pm));}
 const maxY=Math.max(...rows.map(r=>Math.abs(r.y))),maxM=Math.max(...rows.map(r=>Math.abs(r.M))),maxV=Math.max(...rows.map(r=>Math.abs(r.V))),forceResidual=soilForce-(F[0]+reaction[0]+reaction[nd-2]),momentResidual=soilMoment-(F[1]+reaction[1]+reaction[nd-1]+reaction[nd-2]*L);
 return {EI,I,h,rows,headY:d[0]*1000,rotation:d[1],headMoment:reaction[1],toeForce:reaction[nd-2],toeMoment:reaction[nd-1],maxY,maxM,maxV,ratio,soilForce,soilMoment,forceResidual,momentResidual,OK:maxY<=a.limit&&ratio<=1};
 }
 return {section,group,settlement,lateral,solve};
})();
if(typeof module!=='undefined')module.exports=AdvancedPile;
