/* Advanced workspaces, all parameters persist in cases and single-file offline exports. */
(function(){
document.querySelectorAll('[data-tab="structure"],[data-tab="group"],[data-tab="settlement"],[data-tab="lateral"],#panel-structure,#panel-group,#panel-settlement,#panel-lateral,#advanced-manual').forEach(el=>el.remove());
const titles={structure:'06　樁身配筋',group:'07　群樁分析',settlement:'08　沉陷分析',lateral:'09　側向分析'};
const models={structure:{fc:28,fy:420,fyt:420,cover:75,bar:25.4,ties:13,spacing:75,outerSpacing:150,n:16,Pu:1500,Mx:200,My:0,Vu:100,e:20,reinforced:10,denseLength:7,inflection:3,seismic:'III'},group:{nx:2,ny:2,sx:3,sy:3,N:2400,Mx:300,My:200,eta:.8,qbBlock:540,soil:'sand',contact:false,tau:[20]},settlement:{load:600,tipFraction:.4,alpha:.67,Cp:.09,Ep:25000,limit:25,raftDepth:6.667,groupLimit:25,rows:[{h:4,M:20000,sig:100,e0:.8,Cc:.25,Cr:.05,pc:150,consolidate:true},{h:6,M:30000,sig:160,e0:.7,Cc:.2,Cr:.04,pc:200,consolidate:true}]},lateral:{E:25000,eiRatio:.5,H:200,M:0,pm:.7,count:4,limit:10,steps:40,head:'fixed',toe:'free',rows:[{h:4,kh:10000,pult:100},{h:6,kh:20000,pult:200}]}};
const fields={structure:[['fc','混凝土 f′c','MPa','28','材料規格／試驗；21～70 MPa，普通重混凝土。'],['fy','主筋 fy','MPa','420','鋼筋材質證明，280～550 MPa。'],['fyt','箍筋 fyt','MPa','420','橫向鋼筋材質證明。'],['n','主筋根數','支','16','施工配筋圖，圓周均勻配置，至少6支。'],['bar','主筋實際直徑','mm','25.4','鋼筋尺寸表，例如D25名目直徑25.4 mm；面積按πdb²/4。'],['cover','箍筋外緣淨保護層','mm','75','樁身施工圖；不小於75 mm，勿填至主筋中心。'],['ties','箍筋直徑','mm','13','施工圖，至少13 mm。採圓形閉合箍筋。'],['spacing','密區箍筋間距','mm','75','施工圖；於樁頭／塑鉸／土層界面配置。'],['outerSpacing','一般區箍筋間距','mm','150','施工圖；剪力檢核保守採兩區較大間距。'],['Pu','因數化軸力 Pu','kN','1500','結構強度載重組合；正壓負拉。勿用地盤容許載重直接代入。'],['Mx','因數化單向彎矩 Mu','kN·m','200','結構分析單一彎曲平面；含樁土互制效應，本版不計雙軸互制。'],['Vu','因數化剪力 Vu','kN','100','結構強度載重組合；可由側向頁結果乘相符載重因子後輸入。'],['e','另加施工偏心','mm','20','施工偏差評估；附加|Pu|e，已有相同偏心請填0以免重複。'],['reinforced','連續配筋長度','m','10','樁頭向下長度；本版耐震與受拉採全長配置保守檢核。'],['denseLength','樁頭密箍區長度','m','7','第一二類地盤至少3D，第三類至少7D，並考慮反曲點。'],['inflection','反曲點距樁頭深度','m','3','結構／樁土分析，供基礎5.6.3密區長度取大。'],['seismic','耐震設計地盤類別','—','select','依耐震規範地質判定。I為第一／二類，III為第三類；非耐震案件選none。',{none:'不適用耐震',I:'第一／二類地盤',III:'第三類地盤'}]],group:[['nx','X方向樁數','支',2,'規則矩形樁帽配置圖，1～10支。'],['ny','Y方向樁數','支',2,'規則矩形配置，全群至少2支。'],['sx','X中心間距','m',3,'樁位施工圖；不是樁外緣淨距。'],['sy','Y中心間距','m',3,'樁位施工圖。單排不計該方向間距檢核。'],['N','樁帽工作軸力 N','kN',2400,'含樁帽自重之服務載重，正壓負拉，作用於群樁幾何中心。'],['Mx','樁帽工作彎矩 Mx','kN·m',300,'繞X軸，對應ΣPi yi。各樁假設相同軸向勁度。'],['My','樁帽工作彎矩 My','kN·m',200,'繞Y軸，以ΣPi xi為正號定義。'],['eta','群樁摩擦折減 η','—',.8,'依地質／試樁評估；只折減Qs，非規範固定常數。'],['qbBlock','塊體極限端承壓力 qb,G','kPa',540,'地質設計依群樁寬度、埋深與下伏弱層評估；不可直接照抄單樁端承。黏土比較必填。'],['soil','群樁承載地盤','—','select','依群樁承載機制判定，非僅依最上層。',{sand:'砂土地盤（折減單樁和）',clay:'黏土地盤（與塊體取小）'}],['contact','確認樁帽與土不分離','—','select','鑽掘砂土且η=1時需具備基礎5.4.2解說條件；本版不另加樁帽土承載。',{false:'尚未確認',true:'已有設計證據'}]],settlement:[['load','單樁沉陷工作載重','kN',600,'服務載重，含已評估自重／負摩擦影響；依試樁匹配工作荷重。'],['tipFraction','工作荷重端承分配比例 βb','—',.4,'載重試驗／t-z與q-z分析，不是極限Qb/Qu；0～1。'],['alpha','摩擦分布係數 αs','—',.67,'基礎解5.5-3；矩形約0.5，向下增加三角形約0.67。與黏著α不同。'],['Cp','Vesic 端承經驗係數 Cp','—',.09,'基礎表解5.5-1：鑽掘砂0.09～0.18、黏土0.03～0.06；打入砂0.02～0.04、黏土0.02～0.03。依試樁校正。'],['Ep','樁材彈性模數 Ep','MPa',25000,'材料試驗／設計規範；此為沉陷樁身軸向E。'],['limit','容許單樁沉陷','mm',25,'上部結構與設備容許變位，基礎5.5.4無一律25mm要求。'],['raftDepth','等似墩底面距樁頭','m',6.667,'基礎圖解5.5-3由傳力機制判斷；均質摩擦群樁常用2L/3示範，點承於樁端。'],['groupLimit','容許群樁平均沉陷','mm',25,'上部結構變位要求；偏心／差異沉陷另分析。']],lateral:[['E','樁材彈性模數 E','MPa',25000,'材料試驗或設計規範。'],['eiRatio','有效 EI／毛斷面 EI','—',.5,'結構分析開裂勁度評估；0.5僅示範，非固定規範折減。'],['H','同方向總水平力 H','kN',200,'服務載重；單樁count=1、同型群樁總力由count等分，正負皆可。'],['M','同方向總樁頭力矩 M','kN·m',0,'自由轉角邊界適用；固定轉角時填0，由分析求反力矩。'],['count','共同承受側向力樁數','支',4,'同型同勁度同樁頭邊界假設；不含扭矩／不同排遮蔽差異。'],['pm','地盤反力折減 p-multiplier','—',.7,'側向試樁／群樁分析；同時折減kh與pult，0.7只是示範。'],['limit','容許側向變位','mm',10,'基礎5.5.4：由上部構造需求；1%D或15mm僅解說經驗，非自動法定值。'],['steps','Euler 梁元素數','個',40,'40先算，80比較收斂；每節點位移與轉角二自由度。'],['head','樁頭轉角邊界','—','select','依樁帽與樁連接勁度，固定只鎖轉角不鎖水平位移。',{fixed:'轉角固定 θ=0',free:'轉角自由（指定力矩）'}],['toe','樁端邊界','—','select','通常自由；固定需有岩盤嵌固證據。',{free:'自由端 M=V=0',fixed:'固定端 y=θ=0'}]]};
let results={},errors={};
const originalTab=tab;tab=function(key){originalTab(key);const adv=!!titles[key];document.getElementById('metrics').hidden=adv;document.getElementById('status').hidden=adv;document.getElementById('unit').closest('label').hidden=adv;document.getElementById('mode-tag').textContent=adv?'分項設計／請核對適用範圍':(document.getElementById('mode').value==='current'?'112年規範／軸向推估':'原程式比較');};
const nav=document.querySelector('aside nav'),main=document.querySelector('main');
for(const [key,title] of Object.entries(titles)){NAMES[key]=title.slice(3);const b=document.createElement('button');b.dataset.tab=key;b.textContent=title;b.onclick=()=>{tab(key);renderAll();};nav.append(b);const sec=document.createElement('section');sec.id='panel-'+key;sec.hidden=true;sec.innerHTML=`<div class="card noprint"><div class="layer-header"><h2>${esc(NAMES[key])}</h2><button data-reset="${key}" class="primary">載入本頁範例</button></div><p class="muted">樁徑、施工方式及樁長沿用「樁體與載重」，本頁有獨立載重與資料。內部 kN / m；結構 mm / MPa。</p><div class="notice" id="adv-scope-${key}"></div><div class="grid">${fields[key].map(([id,label,unit,value,help,opts])=>`<label class="field">${label} <small>${unit}</small>${opts?`<select data-adv="${key}" data-key="${id}">${Object.entries(opts).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select>`:`<input type="number" step="any" inputmode="decimal" data-adv="${key}" data-key="${id}">`}<span>${help}</span></label>`).join('')}</div><div id="adv-extra-${key}"></div></div><div class="card"><h2>計算結果與過程</h2><div id="adv-result-${key}" aria-live="polite"></div><div class="tools noprint"><button data-report="${key}">匯出本頁 Word</button><button data-csv="${key}">匯出本頁 CSV</button></div></div></section>`;main.insertBefore(sec,document.querySelector('footer'));}
const scopes={structure:'場鑄實心圓樁、均勻單圈主筋、單向P–M強度設計；純壓另採RC表13.4.3.2 φ=0.55上限。保守Vc=0。未含長柱P–Δ、扭矩、雙軸、液化與錨定搭接。',group:'規則矩形、剛性樁帽、相同單樁勁度。工作載重分配與群樁塊體承載／拉拔比較；不含樁帽板強度與負摩擦中性面。',settlement:'單樁依基礎解5.5-3～7 Vesic概估；群樁依5.5.2等似墩＋2:1應力擴散、拘束模數與一維壓密。此為最終平均沉陷，不計時間與差異沉陷。',lateral:'分層線彈性Winkler＋Euler梁元素；土層採割線kh，檢查pult但不截斷反力。超出pult即拒絕判為通過，須另以非線性p-y驗證。群樁限相同勁度等分H，排間效應由輸入折減。'};
for(const key in titles)document.getElementById('adv-scope-'+key).textContent=scopes[key];
function fill(){for(const el of document.querySelectorAll('[data-adv]'))el.value=String(models[el.dataset.adv][el.dataset.key]);extra();}
function extra(){document.getElementById('adv-extra-group').innerHTML='<h3>群樁外圍土壤抗剪強度（沿用鑽探層界）</h3><p>τ為土壤抗剪強度kPa，非樁土黏著αSu；砂土依有效應力與摩擦強度評估，黏土採Su。用於群樁塊體及拉拔外圍。</p><div class="grid">'+layers.map((l,i)=>`<label class="field">第${i+1}層 ${esc(l.name)} τ <small>kPa</small><input type="number" step="any" data-tau="${i}" value="${models.group.tau[i]??20}"><span>資料來源：土壤試驗與群樁破壞機制評估。</span></label>`).join('')+'</div>';
models.group.tau=layers.map((_,i)=>models.group.tau[i]??20);
const defs={settlement:[['h','厚度','m'],['M','即時拘束模數 M','kPa'],['sig','初始σ′0','kPa'],['e0','孔隙比 e0','—'],['Cc','壓縮指數 Cc','—'],['Cr','再壓縮指數 Cr','—'],['pc','預壓密σ′p','kPa']],lateral:[['h','厚度','m'],['kh','水平地盤反力 kh','kN/m³'],['pult','單位長度極限反力 pult','kN/m']]};
for(const key of ['settlement','lateral']){document.getElementById('adv-extra-'+key).innerHTML=`<h3>${key==='settlement'?'等似墩底面以下壓縮層':'樁頭向下側向土層'}</h3><p>${key==='settlement'?'按等似底面以下新基準向下累加，來自更深鑽探／壓密試驗；改底面位置後須重新核對下伏土層與σ′0。M僅採即時部分，Cc/Cr採另計壓密部分，勿重複同一試驗變形；σ′0含原有覆土，不含新增∆σ。':'h由樁頭起向下累加；kh為壓力／位移係數，p=kh×樁徑×y，pult為每m樁長之極限反力。kh、pult由側向試樁／p-y割線分析，不能由SPT自動套固定值。'}</p>`+models[key].rows.map((row,i)=>`<article class="layer"><div class="layer-header"><h3>第${i+1}層</h3><button data-del="${key}" data-i="${i}">刪除</button></div><div class="grid">${defs[key].map(([id,label,unit])=>`<label class="field">${label} <small>${unit}</small><input type="number" step="any" data-row="${key}" data-i="${i}" data-key="${id}" value="${row[id]}"></label>`).join('')}${key==='settlement'?`<label class="field">另計最終壓密<select data-row="${key}" data-i="${i}" data-key="consolidate"><option value="true" ${row.consolidate?'selected':''}>是（Cc/Cr與M分開）</option><option value="false" ${!row.consolidate?'selected':''}>否（僅M）</option></select></label>`:''}</div></article>`).join('')+`<button data-add-row="${key}">新增土層</button>`;}
}
function read(){document.querySelectorAll('[data-adv]').forEach(el=>{const m=models[el.dataset.adv],k=el.dataset.key;m[k]=el.tagName==='SELECT'?(k==='contact'?el.value==='true':el.value):(el.value.trim()===''?NaN:Number(el.value));});document.querySelectorAll('[data-tau]').forEach(el=>models.group.tau[+el.dataset.tau]=el.value.trim()===''?NaN:Number(el.value));document.querySelectorAll('[data-row]').forEach(el=>models[el.dataset.row].rows[+el.dataset.i][el.dataset.key]=el.tagName==='SELECT'?el.value==='true':el.value.trim()===''?NaN:Number(el.value));}
function badge(ok){return `<strong class="${ok?'ok':'bad'}">${ok?'本項檢核通過':'NG／待補證據'}</strong>`;}
function t(headers,rows){return '<div class="scroll"><table>'+table(headers,rows)+'</table></div>';}
function plot(rows,x,y,xlabel,ylabel){const w=650,h=320,maxX=Math.max(...rows.map(r=>Math.abs(r[x])),1e-6),maxY=Math.max(...rows.map(r=>r[y]),1e-6);return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${xlabel}與${ylabel}"><path d="M80 25V270H610" stroke="#8195a5" fill="none"/><polyline fill="none" stroke="#146b98" stroke-width="3" points="${rows.map(r=>`${80+Math.abs(r[x])/maxX*510},${25+r[y]/maxY*245}`).join(' ')}"/><text x="85" y="306" font-size="14">${xlabel}：0～${f(maxX,2)}</text><text x="310" y="306" font-size="14">${ylabel}：0～${f(maxY,2)}</text></svg>`;}
function sectionDiagram(s,D){const R=110,r=(D*500-s.cover-s.ties-s.bar/2)/(D*500)*R;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 300" role="img" aria-label="本次圓樁單圈配筋"><circle cx="160" cy="135" r="110" fill="#edf3f7" stroke="#536a7c"/><circle cx="160" cy="135" r="${(D*500-s.cover)/(D*500)*R}" fill="none" stroke="#146b98"/>${Array.from({length:s.n},(_,i)=>`<circle cx="${160+r*Math.sin(2*Math.PI*i/s.n)}" cy="${135-r*Math.cos(2*Math.PI*i/s.n)}" r="4" fill="#12243b"/>`).join('')}<text x="320" y="75" font-size="17">${s.n} 支 × ${s.bar}mm 主筋</text><text x="320" y="115" font-size="17">樁徑 ${D}m ／ 淨保護層 ${s.cover}mm</text><text x="320" y="155" font-size="17">箍筋 ${s.ties}mm</text><text x="320" y="195" font-size="17">密區 ${s.spacing} ／ 一般 ${s.outerSpacing}mm</text><text x="45" y="280" font-size="14">彎曲平面沿圖示上下；實際錨定與彎鉤須依施工圖</text></svg>`;}
function groupDiagram(r){const scale=400/Math.max(r.B,r.W),cx=300,cy=235;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 520" role="img" aria-label="本次群樁配置與軸力"><rect x="${cx-r.B*scale/2}" y="${cy-r.W*scale/2}" width="${r.B*scale}" height="${r.W*scale}" fill="#edf3f7" stroke="#536a7c"/>${r.reactions.map(c=>`<circle cx="${cx+c.x*scale}" cy="${cy-c.y*scale}" r="${params().d*scale/2}" fill="${c.P<0?'#f8dede':'#d1e7f4'}" stroke="#146b98"/><text x="${cx+c.x*scale}" y="${cy-c.y*scale+5}" text-anchor="middle" font-size="13">${c.id}: ${f(c.P,0)}</text>`).join('')}<text x="40" y="485" font-size="15">B=${f(r.B,2)}m × W=${f(r.W,2)}m；樁力kN；+X向右／+Y向上</text></svg>`;}
function renderAll(){read();results={};errors={};if(!last){for(const b of document.querySelectorAll('[data-report],[data-csv]'))b.disabled=true;for(const key in titles){errors[key]='請先修正樁體／鑽探輸入';document.getElementById('adv-result-'+key).textContent=errors[key];}return;}
const {p,r}=last;
for(const key of Object.keys(titles)){try{let v;if(key==='structure'){if(p.type!=='bored'||p.shape!=='circle'||p.db!==p.d)throw Error('樁身配筋目前限場鑄等徑實心圓樁');v=AdvancedPile.section({...models.structure,L:p.tip-p.head,flexLength:p.tip-p.head},p.d);}if(key==='group')v=AdvancedPile.group(models.group,p,r,layers);if(key==='settlement')v=AdvancedPile.settlement(models.settlement,p,r,models.group,results.group);if(key==='lateral')v=AdvancedPile.lateral(models.lateral,p);results[key]=v;const el=document.getElementById('adv-result-'+key);if(key==='structure')el.innerHTML=badge(v.OK)+sectionDiagram(models.structure,p.d)+t(['檢核','需求／配置','能力／下限','結果'],[['主筋面積 As',f(v.As,1)+' mm²',f(.005*v.Ag,1)+' mm²',badge(v.ratio>=.005)],['軸力／彎矩',f(models.structure.Pu)+' kN ／ '+f(v.demand)+' kN·m','φPn純壓上限 '+f(v.axialCap)+' kN；本軸力φMn '+f(v.cap)+' kN·m',badge(v.strengthOK)],['剪力（Vc=0）',f(models.structure.Vu)+' kN',f(v.Vdesign)+' kN',badge(v.shearOK)],['主筋淨距',f(v.clear,1)+' mm','≥max(40,1.5db)',badge(v.clear>=Math.max(40,1.5*models.structure.bar))],['密區／一般間距',models.structure.spacing+'／'+models.structure.outerSpacing+' mm','≤'+f(v.maxSpacing,1)+'／'+f(v.maxOuter,1)+' mm',badge(models.structure.spacing<=v.maxSpacing&&models.structure.outerSpacing<=v.maxOuter)],['密區體積比 ρs',f(v.rho*100,3)+'%','≥'+f(v.rhoReq*100,3)+'%',badge(v.rho>=v.rhoReq)],['密區長度',models.structure.denseLength+' m','≥'+f(Math.min(models.structure.L||p.tip-p.head,v.requiredDense),3)+' m',badge(models.structure.denseLength>=Math.min(p.tip-p.head,v.requiredDense))],['連續配筋長度',models.structure.reinforced+' m','≥'+f(v.minReinf,3)+' m（本版全長配置）',badge(models.structure.reinforced>=v.minReinf)]])+`<h3>應變相容法</h3><div class="mono">Ag=πD²/4=${f(v.Ag)} mm²；As=nπdb²/4=${f(v.As)} mm²\nβ1=${f(v.b1)}；εcu=0.003；Es=200000 MPa\nCc=0.85f′c Ac；Fs=As,i[clamp(Esεi,±fy)−塊內0.85f′c]\nPn=ΣF；Mn=|ΣFyi|；φ=0.65～0.90（εt與fy/Es判定）\n純壓上限=0.55[0.85f′c(Ag−As)+fyAs]=${f(v.axialCap)} kN\nP–M數值曲線內插；彎曲方向通過一支主筋，均布對稱單圈；只供單向彎曲\nVs=2At fyt(0.8D)/max(s密,s一般)=${f(v.Vs)} kN\nφVn=0.75 min(Vs,0.66√f′c bw d)=${f(v.Vdesign)} kN\nρs=4At/(Dcore s)；耐震密區≥${f(v.rhoReq*100,3)}%</div><p>純壓φ=0.55為已知地層及良好施工品質上限；未採一般柱0.80P0。普通閉合箍筋採壓力控制φ=0.65。錨定、搭接、彎鉤、局部圍束與長柱仍列專項。</p>`;
if(key==='group')el.innerHTML=badge(v.OK)+groupDiagram(v)+t(['項目','值'],[['樁數／最小間距',v.n+' 支 ／ '+f(v.spacing)+' m '+badge(v.spacingOK)],['折減單樁容許和',f(v.sumGross)+' kN'],['塊體容許支承',f(v.blockGross)+' kN（黏土取小）'],['群樁淨壓力能力',f(v.net)+' kN'],['群樁拉拔能力',f(v.pull)+' kN'],['最不利單樁壓／拉',f(Math.max(...v.reactions.map(c=>c.P)))+'／'+f(Math.min(...v.reactions.map(c=>c.P)))+' kN '+badge(v.individual)],['砂土η=1之證據',badge(v.sandEvidence)]])+t(['樁號','x m','y m','Pi kN','地盤需求'],v.reactions.map(c=>[c.id,f(c.x),f(c.y),f(c.P),badge(c.P>=0?c.P<=r.net:-c.P<=r.uplift)]))+`<div class="mono">Pi=N/n+Mx yi/Σy²+My xi/Σx²\nΣPi=${f(v.equilibrium.N)}；ΣPiyi=${f(v.equilibrium.Mx)}；ΣPixi=${f(v.equilibrium.My)}\nB=${v.B}；W=${v.W}；UG=2(B+W)=${v.U}\nQa,Σ=n(ηQs/FS1+Qb/FS2)=${f(v.sumGross)} kN\nQa,塊=UGΣτiLi/FS1+BGWGqb,G/FS2=${f(v.blockGross)} kN\n淨壓力=採用Qa−n(W′p+輸入負摩擦需求)=${f(v.net)} kN\nRat=min(nRa,土樁有效重量+UGΣτiLi/FS拉拔)=${f(v.pull)} kN</div>`;
if(key==='settlement')el.innerHTML=badge(v.singleOK&&v.groupOK)+t(['沉陷分量','mm'],[['單樁樁身縮短 Ws',f(v.elastic)],['單樁端承 Wpp',f(v.end)],['單樁摩擦 Wps',f(v.shaft)],['單樁總量',f(v.single)+' '+badge(v.singleOK)],['Cp適用範圍',v.CpBounds.join('～')+' '+badge(v.CpOK)],['群樁樁身平均縮短',f(v.pile)],['群樁即時土壤變形',f(v.immediate)],['群樁最終壓密',f(v.consolidation)],['群樁最終平均總量',f(v.total)+' '+badge(v.groupOK)]])+`<p class="notice">${v.eccentric?'目前群樁彎矩不為0：僅顯示平均概估，不提供群樁沉陷通過判定，需分析傾斜與差異沉陷。':'群樁使用均佈中心荷重，仍須評估建築差異沉陷。'} 等似底面地表深度=${f(p.head+models.settlement.raftDepth)}m；分析其下 ${f(v.depth)}m，不自動截斷影響層。</p>`+t(['壓縮層','層中深度m（新基準）','∆σ kPa','即時mm','壓密mm'],v.rows.map((c,i)=>[i+1,f(c.z),f(c.ds),f(c.si),f(c.sc)]))+`<div class="mono">工作Qb=${f(v.Qb)}kN；Qs=${f(v.Qs)}kN\nWs=(Qb+αsQs)L/(AEp)=${f(v.elastic)}mm\nWpp=CpQb/(Dqb,極限)=${f(v.end)}mm\nCs=[0.93+0.16√(L/D)]Cp=${f(v.Cs)}\nWps=CsQs/(Lqb,極限)=${f(v.shaft)}mm\n群樁∆σ(z)=N/[(B+z)(W+z)]（2垂直:1水平）\nSi=Σ∆σi Hi/Mi；Sc=ΣHi/(1+e0)[Cr log10(min(σ′f,σ′p)/σ′0)+Cc log10(max(σ′f,σ′p)/σ′p)]\n群樁S=平均樁身縮短+Si+Sc=${f(v.total)}mm</div>`;
if(key==='lateral')el.innerHTML=badge(v.OK)+t(['項目','值'],[['EI',f(v.EI)+' kN·m²'],['樁頭位移／轉角',f(v.headY)+' mm ／ '+f(v.rotation,6)+' rad'],['最大位移',f(v.maxY)+' mm'],['最大彎矩／剪力',f(v.maxM)+' kN·m ／ '+f(v.maxV)+' kN'],['固定樁頭反力矩',f(v.headMoment)+' kN·m'],['最大反力／pult',f(v.ratio,4)+' '+badge(v.ratio<=1)],['水平／力矩平衡殘差',f(v.forceResidual,6)+' kN ／ '+f(v.momentResidual,6)+' kN·m']])+plot(v.rows,'y','z','位移絕對值 mm','深度 m')+`<div class="mono">EI=E×1000×I×有效EI比\nEI y'''' + kh D pm y =0\nKe=EI/l³·Euler梁4×4矩陣\nKsoil=∫(khDpm)NᵀN dz；四點Gauss，土層界面分段\nK u=F；每支H=${f(models.lateral.H/models.lateral.count)}kN\np=khDpm y；需|p|≤pult pm\nM=EI y''；V=EI y'''；40→80元素確認收斂\n本版未納入軸壓幾何勁度P–Δ、非線性p-y、地震運動互制與樁帽被動土壓</div>`+t(['深度m','位移mm','M kN·m','V kN'],v.rows.filter((_,i)=>i%4===0||i===v.rows.length-1).map(c=>[f(c.z),f(c.y),f(c.M),f(c.V)]));
}catch(e){errors[key]=e.message;document.getElementById('adv-result-'+key).innerHTML='<div class="notice bad">'+esc(e.message)+'。不顯示前次結果。</div>';}}
for(const b of document.querySelectorAll('[data-report],[data-csv]'))b.disabled=!results[b.dataset.report||b.dataset.csv];if(document.querySelector('[data-tab].active'))tab(document.querySelector('[data-tab].active').dataset.tab);}
const defaults=structuredClone(models);
document.querySelector('main').addEventListener('input',e=>{if(e.target.matches('[data-adv],[data-row],[data-tau]'))renderAll();});document.querySelector('main').addEventListener('change',e=>{if(e.target.matches('select[data-adv],select[data-row]'))renderAll();});
document.querySelector('main').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reset){models[b.dataset.reset]=structuredClone(defaults[b.dataset.reset]);fill();renderAll();notify('本頁範例已載入；樁徑／樁長沿用目前案件');}if(b.dataset.addRow){const key=b.dataset.addRow;if(models[key].rows.length>=12)return notify('最多12層');models[key].rows.push(structuredClone(defaults[key].rows[0]));extra();renderAll();}if(b.dataset.del){const key=b.dataset.del;if(models[key].rows.length<=1)return notify('至少保留1層');models[key].rows.splice(+b.dataset.i,1);extra();renderAll();}if(b.dataset.csv){const key=b.dataset.csv,r=results[key];if(r)download('\ufeff'+tCSV(key,r),'基樁_'+key+'.csv','text/csv;charset=utf-8');}if(b.dataset.report){const key=b.dataset.report;try{if(!results[key])throw Error('無有效結果');await CalculationDocx.download(advReport(key),'基樁_'+NAMES[key]+'.docx');}catch(err){notify(err.message);}}});
function tCSV(key,r){let rows;if(key==='lateral')rows=[['深度(m)','位移(mm)','M(kN m)','V(kN)'],...r.rows.map(c=>[c.z,c.y,c.M,c.V])];else if(key==='group')rows=[['樁號','x(m)','y(m)','P(kN)'],...r.reactions.map(c=>[c.id,c.x,c.y,c.P])];else if(key==='settlement')rows=[['層中深度(m)','應力增量(kPa)','即時沉陷(mm)','壓密沉陷(mm)'],...r.rows.map(c=>[c.z,c.ds,c.si,c.sc])];else rows=[['設計軸力(kN)','設計彎矩(kN m)'],...r.points.map(c=>[c.Pd,c.Md])];return rows.map(row=>row.join(',')).join('\r\n');}
function advReport(key){const r=results[key],inputs=[];Object.entries(models[key]).forEach(([label,value])=>inputs.push({label,value:typeof value==='object'?JSON.stringify(value):value,unit:''}));const el=document.getElementById('adv-result-'+key);return {title:'基樁 '+NAMES[key]+' 詳細計算書',summary:scopes[key],valid:!!r,inputs,steps:[{title:'本次計算、公式與判定',formula:el.innerText,substitution:'所有數值使用未取整運算；詳見下列輸入及規範對照',result:r?.OK??(r?.singleOK&&r?.groupOK),unit:'本項檢核',condition:scopes[key],source:'基礎112年5.4、5.5、5.6.3；RC112年13.4、18.10、21.2、22.2、22.5'}],diagram:key==='structure'?{svg:sectionDiagram(models.structure,params().d),width:620,height:300,caption:'本次單圈主筋與箍筋示意'}:key==='group'?{svg:groupDiagram(r),width:600,height:520,caption:'本次樁位與軸力分配，尺寸及單位同本頁'}:undefined,conclusions:[scopes[key],'單項符合不代表全工程設計合格。']};}
const originalCase=caseData;caseData=function(){validateAdvanced(models);const c=originalCase();c.advanced=structuredClone(models);return c;};
function validateAdvanced(c){if(!c)return;for(const key in titles){const m=c[key];if(!m)continue;if(typeof m!=='object'||Array.isArray(m))throw Error('進階案件格式錯誤');for(const [k,v] of Object.entries(defaults[key])){if(m[k]===undefined)continue;const x=m[k];if(Array.isArray(v)){if(!Array.isArray(x)||x.length<1||x.length>(k==='tau'?20:12))throw Error('進階土層數量錯誤');if(k==='tau'){if(x.some(n=>!Number.isFinite(n)))throw Error('τ格式錯誤');}else for(const row of x)for(const [rk,rv] of Object.entries(v[0]))if(typeof row[rk]!==typeof rv||(typeof rv==='number'&&!Number.isFinite(row[rk])))throw Error('進階土層格式錯誤');}else if(typeof x!==typeof v||(typeof v==='number'&&!Number.isFinite(x)))throw Error('進階參數格式錯誤');}}}
const originalApply=apply;apply=function(c){validateAdvanced(c.advanced);originalApply(c);for(const key in titles){models[key]={...structuredClone(defaults[key]),...(c.advanced?.[key]||{})};}fill();renderAll();};
const originalLayerUI=layerUI;layerUI=function(){originalLayerUI();extra();};
const originalRun=run;run=function(){originalRun();if(layers.length!==models.group.tau.length)extra();renderAll();};
const originalReport=pileReport;pileReport=function(snapshot){const report=originalReport(snapshot);report.summary+='；另附四項進階分析。';for(const key in titles){if(results[key]){const ar=advReport(key);report.inputs.push(...ar.inputs.map(i=>({...i,label:NAMES[key]+' '+i.label})));report.steps.push(...ar.steps.map(s=>({...s,title:NAMES[key]+' '+s.title})));report.conclusions.push(scopes[key]);}else report.conclusions.push(NAMES[key]+'未完成：'+(errors[key]||'尚未分析'));}return report;};
try{const saved=JSON.parse(document.getElementById('case-data').textContent);validateAdvanced(saved?.advanced);if(saved?.advanced)for(const key in titles)models[key]={...models[key],...saved.advanced[key]};}catch{}
fill();renderAll();
for(const id of ['save','offline']){const handler=document.getElementById(id).onclick;document.getElementById(id).onclick=()=>{try{handler();}catch(e){notify('請先修正進階輸入：'+e.message);}}}
const help=document.createElement('div');help.id='advanced-manual';help.className='card';help.innerHTML='<h2>四項進階功能：輸入與驗算範例</h2><p>先載入現行SPT範例（D=1m、L=10m），各進階頁點「載入本頁範例」。示範數值不代表現場設計參數。</p><ol><li>樁身：f′c=28MPa、fy=420MPa、16支直徑25.4mm、淨保護層75mm、13mm箍筋，密75／一般150mm、Pu=1500kN、Mu=200kN·m、Vu=100kN、另加偏心20mm。確認主筋、P–M、剪力與密區分別判定。</li><li>群樁：2×2、間距3m、N=2400kN、Mx=300、My=200kN·m。四樁反力為516.667、416.667、583.333、883.333？請以本頁實際平衡驗算表為準；每樁位置及符號由圖示表示。</li><li>沉陷：工作載重600kN、βb=0.4、αs=0.67、Cp=0.09、Ep=25000MPa。群樁平均概估需先在群樁頁將Mx、My設0，才可判定平均沉陷；壓縮層從等似底面向下，不是重複原地表層界。</li><li>側向：E=25000MPa、EI比0.5、H=200kN、4支、pm=0.7、固定轉角、自由樁端。4m層kh=10000/pult=100，6m層kh=20000/pult=200。40與80元素比較，再將相符強度組合之M、V輸入樁身頁。</li><li>四項可儲存於同一JSON及單檔離線HTML；各頁可匯出Word與CSV。全局Word附所有有效模組與未完成項目。</li></ol><h3>模型選擇與資料要求</h3><p>kh、pult、η、Cp、工作端承分配、M、Cc、Cr及預壓密壓力均需工址證據，不能由示範值宣告合格。差異沉陷、承台剪力／沖切、非線性p-y、地震運動互制、錨定搭接與試樁列為專項。</p>';
help.innerHTML=help.innerHTML.replace('516.667、416.667、583.333、883.333？請以本頁實際平衡驗算表為準','516.667、616.667、583.333、683.333 kN（順序依圖示）'); // arithmetic cross-check below verified in tests.
document.getElementById('panel-manual').append(help);
tab('settings');
window.pileAdvanced={models,results:()=>results,errors:()=>errors,render:renderAll,fields};
})();
