const $=id=>document.getElementById(id),NAMES={settings:'樁體與載重',layers:'鑽探土層',results:'結果與曲線',manual:'操作說明',verification:'公式與驗算'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PARAMS=['d','db','tip','head','water','gp','load','pull','down','fs','fb','fu','fw','step'];
const common={name:'砂土',h:12,soil:'sand',method:'spt',gamma:18,sat:20,n:20,su:60,k:.5,delta:20,phi:30,alpha:.5,nq:10,nc:9,ng:0,crit:8,dense:1};let layers=[{...common}],last=null;
function params(){const p=Object.fromEntries(PARAMS.map(k=>[k,Number($(k).value)]));for(const k of PARAMS)if($(k).value.trim()==='')p[k]=NaN;for(const k of ['mode','type','shape','condition','safety'])p[k]=$(k).value;p.project=$('project').value;for(const k of ['load','pull','down'])p[k]*=G;return p;}
function unit(v){return v/($('unit').value==='tf'?G:$('unit').value==='kgf'?G/1000:1);}
function f(v,d=3){return Number(v).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});}
function force(v){return f(unit(v))+' '+$('unit').value;}
function notify(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').hidden=true,4000);}
function tab(t){for(const k in NAMES)$('panel-'+k).hidden=k!==t;for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('active',b.dataset.tab===t);$('view-title').textContent=NAMES[t];}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>tab(b.dataset.tab);
const defs={h:['厚度','m','地質柱狀圖土層厚度，深度自動累加'],gamma:['天然單位重 γ','kN/m³','地質報告水位以上單位重'],sat:['飽和單位重 γsat','kN/m³','填飽和重，程式自動扣水'],n:['SPT N','次','現場標準貫入試驗代表值'],su:['不排水強度 Su','kPa','UU／CU／單壓或現地試驗'],alpha:['黏著係數 α','—','地質設計／試樁；現行模式自行確認'],nc:['端承係數 Nc','—','地質設計；深黏土通常9'],k:['側向壓力係數 K','—','施工法與試樁評估'],delta:['介面摩擦角 δ','°','樁土介面資料'],phi:['土壤摩擦角 φ','°','原程式詳細法查表26～40°'],nq:['端承係數 Nq','—','現行參數法需有地質設計依據'],ng:['端承係數 Nγ','—','0表示忽略此項；需設計評估'],crit:['臨界深度','m','地表以下；0為不限制']};
function layerUI(){let z=0;$('layers').innerHTML=layers.map((l,i)=>{const a=z;z+=l.h;const mode=$('mode').value;const numeric=['h','gamma','sat',...(l.method==='spt'?['n']:l.soil==='clay'?['su',...(mode==='current'?['alpha','nc']:[])]:l.method==='typical'?[]:mode==='current'?['k','delta','nq','ng','crit']:['k','delta','phi'])];const options=mode==='current'?[['spt','SPT 法（砂土）'],['static','土層參數法']]:[['spt','原 SPT 簡易法'],['static','原 φ 查表詳細法'],['typical','原密度典型法']];return `<article class="layer"><div class="layer-header"><h3>第 ${i+1} 層 <span class="tag">${f(a,2)}～${f(z,2)} m</span></h3><button data-remove="${i}" aria-label="刪除第${i+1}層">刪除土層</button></div><div class="grid"><label class="field">土層名稱<input data-i="${i}" data-k="name" value="${esc(l.name)}"></label><label class="field">土性<select data-i="${i}" data-k="soil"><option value="sand" ${l.soil==='sand'?'selected':''}>砂性土</option><option value="clay" ${l.soil==='clay'?'selected':''}>黏性土</option></select></label><label class="field">計算法<select data-i="${i}" data-k="method">${options.map(([v,t])=>`<option value="${v}" ${l.method===v?'selected':''}>${t}</option>`).join('')}</select></label>${numeric.map(k=>`<label class="field" title="${defs[k][2]}">${defs[k][0]} <small>${defs[k][1]}</small><input type="number" step="any" data-i="${i}" data-k="${k}" value="${l[k]}"><span>${defs[k][2]}</span></label>`).join('')}${mode==='legacy'&&l.soil==='sand'&&l.method!=='spt'?`<label class="field">原程式相對密度<select data-i="${i}" data-k="dense"><option value="0" ${l.dense===0?'selected':''}>鬆</option><option value="1" ${l.dense===1?'selected':''}>中</option><option value="2" ${l.dense===2?'selected':''}>密</option></select></label>`:''}</div></article>`;}).join('');$('profile-depth').textContent=`鑽探總深度：${f(z,2)} m。至多20層。`;for(const el of $('layers').querySelectorAll('[data-i]')){el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{const k=el.dataset.k;layers[+el.dataset.i][k]=['name','soil','method'].includes(k)?el.value:el.value===''?NaN:Number(el.value);if(k==='method'||k==='soil')layerUI();run();});}for(const b of $('layers').querySelectorAll('[data-remove]'))b.onclick=()=>{layers.splice(+b.dataset.remove,1);layerUI();run();};}
function chart(r,p){const w=620,h=440,left=105,right=575,top=35,bottom=390,max=Math.max(p.load,p.pull,...r.curve.map(t=>Math.max(t.net,t.uplift)),1)*1.1,x=v=>left+v/max*(right-left),y=z=>top+z/p.tip*(bottom-top);let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="土層及深度承載曲線"><rect width="620" height="440" fill="white"/>`;for(let i=0;i<=4;i++){const val=max*i/4;svg+=`<line x1="${x(val)}" y1="${top}" x2="${x(val)}" y2="${bottom}" stroke="#dbe4ec"/><text x="${x(val)}" y="${bottom+22}" font-size="12" text-anchor="middle" fill="#536a7c">${f(unit(val),0)}</text>`;}const ls=boundaries(layers);ls.forEach((l,i)=>{if(l.a>=p.tip)return;svg+=`<rect x="16" y="${y(l.a)}" width="53" height="${y(Math.min(l.b,p.tip))-y(l.a)}" fill="${l.soil==='sand'?'#e9d59c':'#afc5dc'}" stroke="white"/><text x="42" y="${y(l.a)+16}" font-size="12" text-anchor="middle">${i+1}</text>`;});for(let i=0;i<=5;i++){const z=p.tip*i/5;svg+=`<text x="100" y="${y(z)+4}" font-size="12" text-anchor="end">${f(z,1)}</text>`;}const path=k=>r.curve.map(t=>`${x(t[k])},${y(t.z)}`).join(' ');svg+=`<line x1="${x(p.load)}" y1="${top}" x2="${x(p.load)}" y2="${bottom}" stroke="#b73236" stroke-dasharray="5 5"/><polyline points="${path('net')}" fill="none" stroke="#146b98" stroke-width="3"/><polyline points="${path('uplift')}" fill="none" stroke="#08684f" stroke-width="2"/><circle cx="${x(r.net)}" cy="${y(r.z)}" r="5" fill="#146b98"/><text x="300" y="434" font-size="14" text-anchor="middle">承載力（${$('unit').value}）</text><text x="15" y="18" font-size="13">深度 m</text>`;if(p.water<=p.tip)svg+=`<line x1="16" x2="${right}" y1="${y(p.water)}" y2="${y(p.water)}" stroke="#269bd0" stroke-dasharray="3 5"/><text x="${right}" y="${y(p.water)-5}" text-anchor="end" font-size="12" fill="#146b98">地下水位</text>`;return svg+'</svg>';}
function table(headers,rows){return `<thead><tr>${headers.map(t=>`<th>${esc(t)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody>`;}
function run(){try{last=null;const p=params();const current=p.mode==='current';$('safety').disabled=current;if(current){$('safety').value='separate';p.safety='separate';}$('fw').disabled=current||p.safety!=='whole';$('mode-tag').textContent=current?'112 年版規範 · 公式推估':'原程式比較 · 修正版';const r=calculate(p,layers);last={p,r};$('error').hidden=true;const valid=current&&r.fsOK,pressure=r.net>=p.load,pull=r.uplift>=p.pull;const status=pressure?'需求範圍通過':'NG · 壓力超載';$('metrics').innerHTML=[['淨壓力可用量',force(r.net),`<em class="${pressure?'ok':'bad'}">${status}</em>`],['地盤拉拔推估',force(r.uplift),`<em class="${!r.upliftOK?'bad':pull?'ok':'bad'}">${!r.upliftOK?'擴底：待專項分析':pull?'需求範圍通過':'NG · 拉拔超載'}</em>`],['樁尖極限 Qb',force(r.qb),'端點支承分量'],['樁周極限 Qs',force(r.qs),'沿樁長分層累加']].map(([t,v,s])=>`<div class="metric"><small>${t}</small><strong>${v}</strong><em>${s}</em></div>`).join('');$('status').textContent=`${valid?'規範安全係數符合':'規範係數符合未成立'} · ${r.scope}`;$('chart').innerHTML=chart(r,p);$('report-inputs').innerHTML='<p>'+esc(p.project)+'</p><table>'+table(['樁體輸入','值'],Object.entries(p).map(([k,v])=>[esc(k),esc(v)]))+'</table><table>'+table(['土層','厚度','土性／法','γ／γsat','N／Su','α／Nc','K／δ／Nq／Nγ','臨界深度'],layers.map(l=>[esc(l.name),l.h,esc(l.soil+'/'+l.method),l.gamma+'/'+l.sat,l.n+'/'+l.su,l.alpha+'/'+l.nc,l.k+'/'+l.delta+'/'+l.nq+'/'+l.ng,l.crit]))+'</table>';$('summary').innerHTML=`<p><strong>${esc(p.project)}</strong> · 樁尖 ${f(p.tip,2)} m</p><p>樁身面積 ${f(r.geo.A,4)} m² ／ 樁底面積 ${f(r.geo.Ab,4)} m²<br>樁周長 ${f(r.geo.U,4)} m</p><p>${esc(r.tip.info||'端點層 SPT N='+soilAt(p.tip,boundaries(layers)).n)}</p><p>端承壓力 qb = ${f(r.tip.qb)} kPa<br>地盤容許支承力 Qa = ${force(r.gross)}<br>樁身浮重 W′p = ${force(r.weight)}<br>負摩擦附加需求 = ${force(p.down)}<br>樁頭壓力／拉力需求 = ${force(p.load)} ／ ${force(p.pull)}</p><p>FS₁／FS₂／拉拔 = ${p.fs} ／ ${p.fb} ／ ${p.fu}</p>`;$('warnings').innerHTML=r.warnings.map(s=>`<div class="notice">${esc(s)}</div>`).join('');$('scope').textContent=r.scope;$('parts').innerHTML=table(['土層','計入深度 m','平均 fs kPa','極限摩擦力 '+$('unit').value],r.parts.map(t=>[esc(t.name),`${f(t.a,2)}～${f(t.b,2)}`,f(t.fs),f(unit(t.qs))]));$('curve').innerHTML=table(['深度 m','Qb','Qs','Qa','浮重','淨壓力','拉拔推估'].map((s,i)=>i?s+' '+$('unit').value:s),r.curve.map(t=>[f(t.z,2),...['qb','qs','gross','weight','net','uplift'].map(k=>f(unit(t[k])))]));}catch(e){$('error').hidden=false;$('error').textContent=e.message;$('metrics').innerHTML='';$('status').textContent='輸入尚未完成；不顯示過期結果。';for(const id of ['chart','summary','warnings','scope','parts','curve'])$(id).innerHTML='';}}
$('add').onclick=()=>{if(layers.length>=20)return notify('最多20層');layers.push({...common,name:'新增土層',h:2});layerUI();run();};
function factors(){const a=$('condition').value==='normal'?[2.5,3.5,5]:$('condition').value==='short'?[1.8,2.5,3]:[1.2,1.5,2.4];['fs','fb','fu'].forEach((k,i)=>$(k).value=a[i]);}
for(const k of PARAMS.concat(['project','type','shape','safety']))$(k).addEventListener('input',run);$('condition').onchange=()=>{factors();run();};$('mode').onchange=()=>{if($('mode').value==='current'){layers=layers.map(l=>({...l,method:l.method==='typical'?'static':l.method}));factors();}layerUI();run();};$('unit').onchange=run;
function caseData(){const p=params();for(const k of ['load','pull','down'])p[k]/=G;return {format:'PileWorkbench',version:1,p,layers:structuredClone(layers),unit:$('unit').value};}
function apply(c){if(c?.format!=='PileWorkbench'||c.version!==1||!Array.isArray(c.layers)||c.layers.length<1||c.layers.length>20||!c.p)throw Error('案件格式錯誤');const p={...c.p};for(const k of ['load','pull','down'])p[k]*=G;validate(p,c.layers);calculate(p,c.layers);for(const k of [...PARAMS,'mode','type','shape','condition','safety','project']){if(!$(k))continue;$(k).value=c.p[k];}$('unit').value=['tf','kN','kgf'].includes(c.unit)?c.unit:'tf';layers=structuredClone(c.layers);layerUI();run();}
function download(text,name,mime){const u=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}
$('save').onclick=()=>{if(!last)return notify('請先修正輸入');download(JSON.stringify(caseData(),null,2),'基樁案件.json','application/json');};$('open').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('案件檔限2 MB');apply(JSON.parse(await file.text()));notify('案件已載入');}catch(e){notify('案件未載入：'+e.message);}finally{$('file').value='';}};
$('offline').onclick=()=>{if(!last)return notify('請先修正輸入');const doc=document.documentElement.cloneNode(true);doc.querySelector('#case-data').textContent=JSON.stringify(caseData()).replace(/</g,'\\u003c');doc.querySelector('#toast').hidden=true;doc.querySelector('#example-menu')?.remove();download('<!doctype html>\n'+doc.outerHTML,'基樁分析工作台_離線版.html','text/html;charset=utf-8');notify('離線版已下載，含目前案件');};$('print').onclick=()=>{if(!last)return notify('請先修正輸入');window.print();};$('csv').onclick=()=>{if(!last)return;const rows=[['深度(m)','Qb('+$('unit').value+')','Qs','Qa','浮重','淨壓力','拉拔推估'],...last.r.curve.map(t=>[t.z,...['qb','qs','gross','weight','net','uplift'].map(k=>unit(t[k]))])];download('\ufeff'+rows.map(r=>r.join(',')).join('\r\n'),'基樁深度結果.csv','text/csv;charset=utf-8');};
$('example').onclick=()=>{const old=$('example-menu');if(old){old.remove();return;}const d=document.createElement('div');d.id='example-menu';d.className='card noprint';d.innerHTML='<h2>範例選擇</h2><div class="tools"><button data-eg="spt">現行 SPT 手算範例</button><button data-eg="clay">現行黏土參數範例</button><button data-eg="legacy">原程式四層 SPT 範例</button></div><p>載入將替換目前輸入；需保留時先儲存案件。</p>';$('panel-settings').prepend(d);tab('settings');d.querySelectorAll('[data-eg]').forEach(b=>b.onclick=()=>{const p={d:1,db:1,tip:10,head:0,water:2,gp:24,load:200,pull:30,down:0,fs:2.5,fb:3.5,fu:5,fw:2.5,step:.5,mode:'current',type:'bored',shape:'circle',condition:'normal',safety:'separate',project:'單樁 SPT 手算範例'};let ls=[{...common}];if(b.dataset.eg==='clay'){p.project='黏土參數法範例';p.load=50;p.pull=20;ls=[{...common,name:'黏土 Su=60',soil:'clay',method:'static',su:60,alpha:.5,nc:9}];}if(b.dataset.eg==='legacy'){p.project='原程式四層 SPT 範例';p.mode='legacy';p.tip=6.5;p.fb=2.5;p.fu=6;ls=[.9,2.5,.5,2.6].map((h,i)=>({...common,h,n:[7,13,20,32][i],name:'原範例砂層 '+(i+1)}));}apply({format:'PileWorkbench',version:1,p,layers:ls,unit:'tf'});d.remove();notify('範例已載入');});};
try{const saved=JSON.parse($('case-data').textContent);if(saved)apply(saved);else{layerUI();run();}}catch(e){layerUI();run();notify('內嵌案件無法載入：'+e.message);}
