/* PileWorkbench 1.0 — kN, m, kPa internally. */
const G=9.80665;
const alphaTable=[1,1,1,1,1,.912,.783,.702,.621,.564,.516,.477,.443,.413,.388,.37,.354,.339,.33,.321,.319];
function interp(x,xs,ys){if(x<xs[0]||x>xs.at(-1))throw Error('查表數值超出資料範圍');for(let i=1;i<xs.length;i++)if(x<=xs[i])return ys[i-1]+(ys[i]-ys[i-1])*(x-xs[i-1])/(xs[i]-xs[i-1]);return ys.at(-1);}
function alpha(su){return interp(su,alphaTable.map((_,i)=>i*10),alphaTable);}
function nc(r){return r>=4?9:interp(r,[0,1,2,3,4],[6.3,7.6,8.3,8.8,9]);}
function geometry(p){return p.shape==='circle'?{A:Math.PI*p.d*p.d/4,Ab:Math.PI*p.db*p.db/4,U:Math.PI*p.d}:{A:p.d*p.d,Ab:p.db*p.db,U:4*p.d};}
function boundaries(ls){let z=0;return ls.map(l=>{const a=z;z+=l.h;return {...l,a,b:z};});}
function soilAt(z,ls){return ls.find(l=>z>=l.a-1e-9&&z<l.b-1e-9)||ls.at(-1);}
function stress(z,p,ls){let s=0;for(const l of ls){const b=Math.min(z,l.b);if(b<=l.a)break;const dry=Math.max(0,Math.min(b,p.water)-l.a);s+=dry*l.gamma+Math.max(0,b-Math.max(l.a,p.water))*(l.sat-G);}return s;}
function averagedN(z,p,ls){const a=z-(p.type==='driven'?4:1)*p.d,b=z+p.d;if(a<0||b>ls.at(-1).b+1e-8)throw Error('樁尖平均 N 值範圍 '+a.toFixed(2)+'～'+b.toFixed(2)+' m 未被鑽探資料涵蓋');let sum=0;for(const l of ls){const dz=Math.max(0,Math.min(b,l.b)-Math.max(a,l.a));if(dz>0&&l.soil!=='sand')throw Error('樁尖平均 N 值範圍包含非砂性土，請改用參數法');sum+=dz*l.n;}return {value:Math.min(50,sum/(b-a)),a,b};}
function validate(p,layers){if(!['current','legacy'].includes(p.mode)||!['bored','driven'].includes(p.type)||!['circle','square'].includes(p.shape)||!['normal','short','ultimate'].includes(p.condition)||!['separate','whole'].includes(p.safety))throw Error('分析選項格式錯誤');if(p.tip>500)throw Error('樁尖深度限500 m');const nums=['d','db','tip','head','water','gp','load','pull','down','fs','fb','fu','fw','step'];for(const k of nums)if(!Number.isFinite(p[k]))throw Error('請填入有效數字：'+k);if(p.d<=0||p.db<p.d||p.tip<=p.head||p.head<0||p.water<0||p.step<.05||p.step>5||p.gp<=G||[p.load,p.pull,p.down].some(x=>x<0)||[p.fs,p.fb,p.fu,p.fw].some(x=>x<1))throw Error('請檢查尺寸、深度、載重與安全係數；步距限 0.05～5 m');if(p.db>2*p.d)throw Error('有效樁底直徑不得超過樁身直徑兩倍（5.3.1）');if(!layers.length||layers.length>20)throw Error('請提供 1～20 個土層');let depth=0;for(const l of layers){if(!['sand','clay'].includes(l.soil)||!['spt','static','typical'].includes(l.method)||![0,1,2].includes(l.dense)||typeof l.name!=='string')throw Error('土層格式錯誤');for(const k of ['h','gamma','sat','n','su','k','delta','phi','alpha','nq','nc','ng','crit'])if(!Number.isFinite(l[k]))throw Error('土層欄位不得空白');if(l.h>1000||l.h<=0||l.gamma<=0||l.sat<=G||l.n<0||l.su<0||l.k<0||l.delta<0||l.delta>=90||l.phi<0||l.phi>=90||l.nq<0||l.nc<0||l.ng<0||l.crit<0||l.alpha<.25||l.alpha>1)throw Error('土層參數超出有效範圍');if(p.mode==='current'&&l.method==='spt'&&l.soil==='clay')throw Error('112 年規範 SPT 法僅限砂性土；黏土須改用參數法');if(p.mode==='legacy'&&l.method!=='spt'&&l.soil==='clay'&&l.su>200)throw Error('原程式 α 查表限 Su=0～200 kPa；請用現行參數法');if(p.mode==='legacy'&&l.method==='static'&&l.soil==='sand'&&(l.phi<26||l.phi>40))throw Error('原程式 φ 表有效範圍限 26～40°');depth+=l.h;}if(p.tip>depth+1e-8)throw Error('樁尖深度超過鑽探土層深度');}
function local(z,p,ls,l=soilAt(z,ls),forTip=false){let fs,qb,sv=stress(z,p,ls),info='',trace={z,method:l.method,soil:l.soil,mode:p.mode,n:l.n,su:l.su,rawStress:sv};if(l.method==='spt'){fs=(l.soil==='clay'?.27*l.n:Math.min(l.n/3,15))*G;let n=l.n;if(forTip&&p.mode==='current'){const avg=averagedN(z,p,ls);n=avg.value;info=`N̄=${n.toFixed(3)}（${avg.a.toFixed(2)}～${avg.b.toFixed(2)} m）`;}trace.frictionN=l.n;trace.n=n;trace.fsRaw=l.soil==='clay'?.27*l.n:l.n/3;trace.fsCap=l.soil==='clay'?null:15;trace.tipCoefficient=p.type==='bored'?7.5:30;trace.nCap=50;qb=(p.type==='bored'?7.5:30)*Math.min(n,50)*G;}else if(l.soil==='clay'){const a=p.mode==='legacy'?alpha(l.su):l.alpha;const c=p.mode==='legacy'?nc(z/p.d):l.nc;trace.alpha=a;trace.nc=c;trace.ratio=z/p.d;fs=a*l.su;qb=c*l.su;info=`α=${a.toFixed(3)}，Nc=${c.toFixed(3)}`;}else{let nq=l.nq,k=l.k,delta=l.delta,cap=l.crit;if(p.mode==='legacy'){const i=l.dense;cap=[6,8,15][i]*p.d;if(l.method==='typical'){k=(p.type==='driven'?[.8,1,1.5]:[.3,.5,.8])[i];nq=(p.type==='driven'?[60,100,180]:[25,60,100])[i];}else nq=interp(l.phi,[26,28,30,31,33,34,35,36,37,38,39,40],p.type==='driven'?[10,15,21,24,29,35,42,50,62,77,86,120]:[5,8,10,12,14,17,21,25,30,38,43,60]);}
trace.nq=nq;trace.k=k;trace.delta=delta;trace.cap=cap;trace.stressDepth=cap>0?Math.min(z,cap):z;trace.ng=l.ng;trace.gammaEffective=z>p.water?l.sat-G:l.gamma;sv=stress(cap>0?Math.min(z,cap):z,p,ls);fs=(p.mode==='legacy'&&l.method==='typical')?k*sv:k*sv*Math.tan(delta*Math.PI/180);qb=sv*nq+(p.mode==='current'?.5*(z>p.water?l.sat-G:l.gamma)*p.db*l.ng:0);info=`σ′=${sv.toFixed(3)} kPa，Nq=${nq.toFixed(3)}`;}return {fs,qb,sv,info,trace};}
function atDepth(z,p,layers){const ls=boundaries(layers),geo=geometry(p),parts=[];let qs=0;for(const l of ls){const a=Math.max(l.a,p.head),b=Math.min(l.b,z);if(b<=a)continue;const breaks=[a,b];if(p.water>a&&p.water<b)breaks.push(p.water);let crit=l.crit;if(p.mode==='legacy'&&l.soil==='sand'&&l.method!=='spt')crit=[6,8,15][l.dense]*p.d;if(crit>a&&crit<b)breaks.push(crit);breaks.sort((a,b)=>a-b);let q=0;const segments=[];for(let i=1;i<breaks.length;i++){const x=breaks[i-1],y=breaks[i];const sample=local((x+y)/2,p,ls,l),contribution=sample.fs*geo.U*(y-x);q+=contribution;segments.push({a:x,b:y,dz:y-x,mid:(x+y)/2,...sample,contribution});}qs+=q;parts.push({name:l.name,a,b,fs:q/(geo.U*(b-a)),qs:q,segments});}
const tip=local(z,p,ls,soilAt(z,ls),true),qb=tip.qb*geo.Ab;const dry=Math.max(0,Math.min(z,p.water)-p.head),wet=Math.max(0,z-Math.max(p.head,p.water));const weight=geo.A*(dry*p.gp+wet*(p.gp-G));const gross=p.mode==='legacy'&&p.safety==='whole'?(qs+qb)/p.fw:qs/p.fs+qb/p.fb;const net=Math.max(0,gross-weight-p.down);const uplift=qs/p.fu+weight;return {z,qs,qb,weight,gross,net,uplift,tip,parts,geo,dry,wet};}
function calculate(p,layers){validate(p,layers);const r=atDepth(p.tip,p,layers),ls=boundaries(layers),curve=[];const first=p.head+p.step;for(let z=first;z<p.tip-1e-8;z+=p.step){try{curve.push(atDepth(z,p,layers));}catch(e){if(!/平均 N/.test(e.message))throw e;}}curve.push(r);const warnings=[];if(p.mode==='legacy')warnings.push('原程式比較：不代表符合現行規範；已修正積分、單位與查表邊界。');const minima=p.condition==='normal'?[2.5,3.5,5]:p.condition==='short'?[1.8,2.5,3]:[1.2,1.5,2.4];if(p.mode==='current'&&[p.fs,p.fb,p.fu].some((x,i)=>x<minima[i]))warnings.push('安全係數低於表 5.3-1／5.3-3 推估公式最小值；本次不得判為規範係數符合。');if(p.db>p.d)warnings.push('擴底樁：自重僅計等斷面樁身，需另補擴底體積；拉拔破壞模式未完成，不提供拉拔合格判定（5.3.2）。');if(p.mode==='current'&&layers.some(l=>l.method==='typical'))throw Error('現行模式請選 SPT 或參數法');if(layers.some(l=>l.soil==='sand'&&l.method==='static'&&l.crit===0))warnings.push('砂土參數法未設定臨界深度；須有試樁或工程評估依據。');const scope='本區僅判定單樁地盤軸向推估；樁身、群樁、沉陷及側向請至對應工作區完成。液化、負摩擦中性面、樁帽與試樁仍需專項檢核。';return {...r,curve,warnings,scope,minima,fsOK:[p.fs,p.fb,p.fu].every((x,i)=>x>=minima[i]),upliftOK:p.db===p.d};}
if(typeof module!=='undefined')module.exports={calculate,atDepth,alpha,nc,geometry,G};


