/* Same-engine trace: no independent capacity calculation. */
function pileReport(snapshot){
 const {p,r,layers:ls}=snapshot,steps=[],num=x=>Number(x).toPrecision(12),add=(title,formula,substitution,result,unit='',condition='',source='')=>steps.push({title,formula,substitution,result,unit,condition,source});
 const source=p.mode==='current'?'112年建築物基礎構造設計規範 5.3.1、表5.3-1/2及5.3.2、表5.3-3 https://www.nlma.gov.tw/ch/legislation/regsearch/962':'20121009 pile.zip / PileCapacityAnalysis.vb 修正版比較；非現行規範符合判定';
 const inputs=Object.entries(p).map(([label,value])=>({label,value,unit:['d','db','tip','head','water','step'].includes(label)?'m':['load','pull','down'].includes(label)?'kN':label==='gp'?'kN/m³':''}));
 ls.forEach((l,i)=>Object.entries(l).forEach(([k,value])=>inputs.push({label:`土層${i+1} ${k}`,value,unit:['h','crit'].includes(k)?'m':['gamma','sat'].includes(k)?'kN/m³':k==='su'?'kPa':['delta','phi'].includes(k)?'°':''})));
 add('截面幾何',p.shape==='circle'?'A=πD²/4；Ab=πDb²/4；U=πD':'A=D²；Ab=Db²；U=4D',`D=${p.d} m；Db=${p.db} m；A=${num(r.geo.A)} m²；Ab=${num(r.geo.Ab)} m²`,r.geo.U,'m','未取整；顯示值保留12位有效數字，判定使用全精度',source);
 const bounds=boundaries(ls);
 function effective(depth,title){let accum=0;bounds.forEach((l,i)=>{const b=Math.min(depth,l.b);if(b<=l.a)return;const dry=Math.max(0,Math.min(b,p.water)-l.a),wet=Math.max(0,b-Math.max(l.a,p.water)),q=dry*l.gamma+wet*(l.sat-G);accum+=q;add(`${title} 第${i+1}層有效應力貢獻`,'Δσ′=Δz乾γ+Δz濕(γsat−γw)',`${dry}×${l.gamma}+${wet}×(${l.sat}−${G})=${num(q)}；累計=${num(accum)}`,q,'kPa',`地表至取樣深度 ${depth} m；本層 ${l.a}–${b} m`);});}
 function localStep(v,title,isTip=false){const t=v.trace;
  if(t.method==='spt'){
   if(isTip&&p.mode==='current'){const av=averagedN(t.z,p,bounds);let sum=0;bounds.forEach((l,i)=>{const dz=Math.max(0,Math.min(av.b,l.b)-Math.max(av.a,l.a));if(dz){sum+=dz*l.n;add(`樁尖平均N 第${i+1}層`,'加權貢獻=重疊厚度×N',`${dz}×${l.n}`,dz*l.n,'m·次',`取樣範圍 ${av.a}–${av.b} m`);}});add('樁尖平均N及上限','N̄=min(50,ΣΔzN/(b−a))',`min(50,${num(sum)}/(${av.b}−${av.a}))`,av.value,'次',p.type==='driven'?'上4D／下1D':'上下各1D',source);}
   add(title+'單位摩擦','fs='+ (t.soil==='clay'?'0.27N×9.80665':'min(N/3,15)×9.80665'),t.soil==='clay'?`0.27×${t.frictionN}×${G}`:`min(${t.frictionN}/3,15)×${G}`,v.fs,'kPa',t.soil==='clay'?'舊SPT黏土經驗式，非現行法':'15 tf/m²上限',source);
   if(isTip)add('樁尖單位端承','qb=C×min(N,50)×9.80665',`${t.tipCoefficient}×min(${t.n},50)×${G}`,v.qb,'kPa',`C=${t.tipCoefficient}；${p.type}`,source);
  }else if(t.soil==='clay'){
   if(p.mode==='legacy'){const ai=Math.min(19,Math.floor(t.su/10)),ax=ai*10,aw=(t.su-ax)/10;add(title+'α查表代入','α=α₀+(α₁−α₀)w',`${alphaTable[ai]}+(${alphaTable[ai+1]}−${alphaTable[ai]})×(${t.su}−${ax})/10；w=${aw}`,t.alpha,'','列 Su='+ax+' / '+(ax+10)+' kPa；欄α',source);const rows=alphaTable.map((a,i)=>`${i*10}:${a}`).join('；');add(title+'α原表','α線性內插',`Su=${t.su}；表列 Su(kPa):α = ${rows}`,t.alpha,'',`Su範圍0–200；每10kPa列；依Su相鄰兩列內插`,source);if(t.ratio<4){const ni=Math.floor(t.ratio),ny=[6.3,7.6,8.3,8.8,9];add(title+'Nc查表代入','Nc=Nc₀+(Nc₁−Nc₀)(z/D−r₀)',`${ny[ni]}+(${ny[ni+1]}−${ny[ni]})×(${t.ratio}−${ni})`,t.nc,'',`列z/D=${ni}/${ni+1}；欄Nc`,source);}add(title+'Nc原表','Nc=z/D≥4 ? 9 : 線性內插',`z/D=${t.ratio}；列 0:6.3、1:7.6、2:8.3、3:8.8、4:9`,t.nc,'','4以上取9',source);}
   add(title+'黏土摩擦','fs=αSu',`${t.alpha}×${t.su}`,v.fs,'kPa','α來自當次所選現行輸入或舊表',source);if(isTip)add('黏土端承','qb=NcSu',`${t.nc}×${t.su}`,v.qb,'kPa','Nc來自當次分支',source);
  }else{
   effective(t.stressDepth,title);add(title+'有效應力上限','z採用=臨界深度>0 ? min(z,臨界深度) : z',`z=${t.z}；臨界=${t.cap}；採用深度=${t.stressDepth}`,v.sv,'kPa',`mode=${p.mode}；method=${t.method}；Nq=${t.nq}；K=${t.k}；δ=${t.delta}°`,source);
   if(p.mode==='legacy'&&t.method==='typical'){const l=soilAt(t.z,bounds),ks=p.type==='driven'?[.8,1,1.5]:[.3,.5,.8],ns=p.type==='driven'?[60,100,180]:[25,60,100];add(title+'典型法係數表','依施工方式及鬆／中／密列選取K、Nq、臨界深度',`密度索引=${l.dense}；K列=${ks.join('/')}；Nq列=${ns.join('/')}；臨界倍數列=6/8/15；所選臨界=${[6,8,15][l.dense]}×D(${p.d})=${t.cap}`,t.k,'','當次施工='+p.type+'；索引0/1/2對應鬆/中/密',source);}if(p.mode==='legacy'&&t.method==='static'){const xs=[26,28,30,31,33,34,35,36,37,38,39,40],ys=p.type==='driven'?[10,15,21,24,29,35,42,50,62,77,86,120]:[5,8,10,12,14,17,21,25,30,38,43,60];const l=soilAt(t.z,bounds),j=Math.max(1,xs.findIndex(x=>x>=l.phi)),i=Math.max(0,j-1);add(title+'Nq原表內插','Nq=Nq₀+(Nq₁−Nq₀)(φ−φ₀)/(φ₁−φ₀)',`表列 φ:Nq ${xs.map((x,k)=>x+':'+ys[k]).join('；')}；本次φ=${l.phi}；列${i+1}/${j+1}；${ys[i]}+(${ys[j]}−${ys[i]})×(${l.phi}−${xs[i]})/(${xs[j]}−${xs[i]})`,t.nq,'','只採完整對應26–40°表列',source);}
   add(title+'砂土摩擦',p.mode==='legacy'&&t.method==='typical'?'fs=Kσ′':'fs=Kσ′tan(δ)',`${t.k}×${num(v.sv)}`+(p.mode==='legacy'&&t.method==='typical'?'':`×tan(${t.delta}×π/180)`),v.fs,'kPa','舊典型法不含tanδ；其餘分支依引擎',source);
   if(isTip)add('砂土端承',p.mode==='current'?'qb=σ′Nq+0.5γ′DbNγ':'qb=σ′Nq',`${num(v.sv)}×${t.nq}`+(p.mode==='current'?`+0.5×${t.gammaEffective}×${p.db}×${t.ng}`:''),v.qb,'kPa','當次分支與係數',source);
  }
 }
 r.parts.forEach((part,i)=>{part.segments.forEach((s,j)=>{localStep(s,`第${i+1}層第${j+1}段`);add(`第${i+1}層第${j+1}段摩擦積分`,'ΔQs=fs(z中)×U×Δz',`${num(s.fs)}×${num(r.geo.U)}×(${s.b}−${s.a})`,s.contribution,'kN',`取样z=${s.mid} m；按水位／臨界深度／土層分段，線性應力採中點精確積分`);});add(`第${i+1}層摩擦小計`,'Qs層=ΣΔQs',part.segments.map(s=>num(s.contribution)).join('+'),part.qs,'kN');});
 localStep(r.tip,'樁尖',true);add('總摩擦','Qs=ΣQs層',r.parts.map(s=>num(s.qs)).join('+'),r.qs,'kN');add('總端承','Qb=qb×Ab',`${num(r.tip.qb)}×${num(r.geo.Ab)}`,r.qb,'kN');
 add('樁身浮重','W′p=A[γpL乾+(γp−γw)L濕]',`${num(r.geo.A)}×[${p.gp}×${r.dry}+(${p.gp}−${G})×${r.wet}]`,r.weight,'kN','等斷面樁身；擴底體積未計');
 add('安全折減',p.mode==='legacy'&&p.safety==='whole'?'Qa=(Qs+Qb)/FS全體':'Qa=Qs/FS摩擦+Qb/FS端承',p.mode==='legacy'&&p.safety==='whole'?`(${num(r.qs)}+${num(r.qb)})/${p.fw}`:`${num(r.qs)}/${p.fs}+${num(r.qb)}/${p.fb}`,r.gross,'kN',`推估最低FS=${r.minima.join(' / ')}；本次FS=${p.fs}/${p.fb}/${p.fu}；係數符合=${r.fsOK}`,source);
 add('淨壓力','R淨=max(0,Qa−W′p−負摩擦附加需求)',`max(0,${num(r.gross)}−${num(r.weight)}−${p.down})`,r.net,'kN',`與需求${p.load} kN全精度比較：${r.net>=p.load?'需求檢核通過':'NG'}`);
 add('拉拔推估','Ra=Qs/FS拉拔+W′p',`${num(r.qs)}/${p.fu}+${num(r.weight)}`,r.uplift,'kN',r.upliftOK?`需求${p.pull} kN：${r.uplift>=p.pull?'需求檢核通過':'NG'}`:'擴底拉拔模式未完成，不提供合格判定');
 add('顯示與換算','tf=kN/9.80665；kgf=kN×1000/9.80665',`淨壓力 ${num(r.net)} / ${G}`,r.net/G,'tf','UI顯示3位小數；運算及判定未取整');
 return {title:'基樁詳細計算報告',summary:`${p.project}；${p.mode==='current'?'現行112年規範推估':'原程式比較'}。${r.scope}`,valid:true,inputs,steps,diagram:{svg:pileDiagram(snapshot),width:560,height:340,caption:'本次土層、水位、樁頭與樁尖，摩擦及端承方向示意；寬度示意非比例'},conclusions:[...r.warnings,r.scope,`淨壓力需求檢核：${r.net>=p.load?'通過':'NG'}。規範係數符合：${p.mode==='current'&&r.fsOK}；不代表完整基樁設計合格。`]};
}
function pileDiagram({p,r,layers:ls}){const y=z=>40+260*z/Math.max(p.tip,boundaries(ls).at(-1).b),e=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 560 340" role="img" aria-label="基樁分層受力尺寸示意"><defs><marker id="a" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#166083"/></marker></defs><rect width="560" height="340" fill="white"/>${boundaries(ls).map((l,i)=>`<rect x="30" y="${y(l.a)}" width="480" height="${y(l.b)-y(l.a)}" fill="${l.soil==='sand'?'#faf0d0':'#e7eef6'}"/><text x="40" y="${y(l.a)+16}" font-size="12">${i+1} ${e(l.name)} ${l.a}–${l.b}m</text>`).join('')}<rect x="250" y="${y(p.head)}" width="45" height="${y(p.tip)-y(p.head)}" fill="#d0d9df" stroke="#333"/><path d="M272 10V${y(p.head)}" stroke="#166083" marker-end="url(#a)"/><text x="305" y="25" font-size="13">P=${(p.load/G).toFixed(3)} tf</text><line x1="25" x2="510" y1="${y(p.water)}" y2="${y(p.water)}" stroke="#1887c0" stroke-dasharray="5 3"/><text x="340" y="${y(p.water)-4}" font-size="12">水位 ${p.water}m</text><text x="305" y="${y(p.head)+14}" font-size="12">樁頭 ${p.head}m；D=${p.d}m</text><text x="305" y="${y(p.tip)+14}" font-size="12">樁尖 ${p.tip}m；Db=${p.db}m</text><path d="M230 ${y((p.head+p.tip)/2)+20}v-35 M315 ${y((p.head+p.tip)/2)+20}v-35 M272 ${y(p.tip)+25}v-20" stroke="#166083" marker-end="url(#a)"/><text x="320" y="${y((p.head+p.tip)/2)}" font-size="12">Qs=${(r.qs/G).toFixed(3)}tf ↑</text><text x="40" y="325" font-size="12">Qb=${(r.qb/G).toFixed(3)}tf；W′p=${(r.weight/G).toFixed(3)}tf</text></svg>`;}
function renderTrace(snapshot){const report=pileReport(snapshot);$('trace-diagram').innerHTML=report.diagram.svg;$('trace-steps').innerHTML=report.steps.map((s,i)=>`<details ${i<1?'open':''}><summary>${i+1} ${esc(s.title)}</summary><p>${esc(s.formula)}</p><p style="overflow-wrap:anywhere">${esc(s.substitution)}</p><p>＝ ${esc(s.result)} ${esc(s.unit)}</p><p>${esc(s.condition)}</p><small>${esc(s.source)}</small></details>`).join('');$('export-docx').disabled=false;}
