'use strict';
const $=id=>document.getElementById(id),C=SlopeCore,SCENES={normal:'常時',rain:'暴雨／最高水位',seismic:'地震'};
let result=null,worker=null,dirty=true,lastModel=null,oldUnits='kn',soilMulti=false,flipped=true,view={x:0,y:0,w:900,h:500},toastTimer,lastCrestX=null;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=id=>{const x=$(id).value;if(x.trim()==='')throw Error($(id).previousElementSibling?.textContent+'不可空白');const n=Number(x);if(!Number.isFinite(n))throw Error(id+' 必須為數字');return n;};
const factor=()=>$('units').value==='tf'?C.gw:1;
const fmt=(n,d=3)=>Number.isFinite(n)?n.toFixed(d):'—';
const sourceOf=m=>m.profile==='custom'?m.customSource:m.profile==='foundation-global'?'建築物基礎構造設計規範112年版 §7.4.4（113年1月1日生效；僅套用地盤整體穩定門檻）':'水土保持技術規範 §73（114年5月7日版本）';
const uStress=()=>$('units').value==='tf'?'tf/m²':'kPa',uForce=()=>$('units').value==='tf'?'tf/m':'kN/m';
function notify(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4200);}
function page(name){for(const n of ['analysis','examples','help','verify'])$('page-'+n).hidden=name!==n;for(const b of document.querySelectorAll('.nav [data-page]'))b.classList.toggle('active',b.dataset.page===name);}
for(const b of document.querySelectorAll('[data-page]'))b.addEventListener('click',()=>page(b.dataset.page));
function syncSoil(){const tr=$('layers').tBodies[0].rows[0];if(!tr)return;for(const k of ['name','bottom','c','phi','gamma','sat']){const x=$('soil-'+k),v=tr.querySelector('[data-key='+k+']').value;x.value=v;if($('slider-'+k)){$('slider-'+k).max=(k==='phi'?55:k==='c'?100:30)/(k==='phi'?1:factor());$('slider-'+k).value=v;}}$('single-soil').hidden=soilMulti;$('multi-soil').hidden=!soilMulti;$('soil-single').classList.toggle('active',!soilMulti);$('soil-multi').classList.toggle('active',soilMulti);for(const [id,source]of [['q-slider','q'],['water-normal-slider','waterNormal'],['water-rain-slider','waterRain'],['kh-slider','kh'],['kv-slider','kv']])$(id).value=$(source).value;$('q-slider').max=100/factor();}
$('soil-single').onclick=()=>{if($('layers').tBodies[0].rows.length>1){notify('目前有多層材料；請先移除多餘土層，再切換單層。');return;}soilMulti=false;syncSoil();};$('soil-multi').onclick=()=>{soilMulti=true;syncSoil();};
function syncFields(){const wm=$('waterMode').value;for(const [cls,on]of [['water-depth',wm==='depth'],['water-line',wm==='line'],['water-ru',wm==='ru'],['manual-circle',$('mode').value==='manual'],['simple-geometry',$('geometryMode').value==='simple'],['coordinates-geometry',$('geometryMode').value==='coordinates']])for(const x of document.querySelectorAll('.'+cls))x.hidden=!on;$('custom-fields').hidden=$('profile').value!=='custom';$('gammaWater').disabled=wm==='dry'||wm==='ru';const ts=['sw-permanent','foundation-global'].includes($('profile').value)?[1.5,1.2,1.1]:$('profile').value==='sw-temporary'?[1.2,1.1,1]:[val('targetNormal'),val('targetRain'),val('targetSeismic')];$('target-note').textContent='常時 '+fmt(ts[0],2)+'｜暴雨 '+fmt(ts[1],2)+'｜地震 '+fmt(ts[2],2)+($('profile').value==='foundation-global'?'；採嚴格大於。僅套用基礎規範§7.4.4門檻，需另建模牆體及補強。':'；水保預設依114年5月7日版本第73條。');for(const x of document.querySelectorAll('.stress-unit'))x.textContent=uStress();for(const x of document.querySelectorAll('.weight-unit'))x.textContent=$('units').value==='tf'?'tf/m³':'kN/m³';syncSoil();}
function addLayer(l){if($('layers').tBodies[0].rows.length>=12){notify('最多 12 個土層');return;}const tr=document.createElement('tr');tr.innerHTML=['name','bottom','c','phi','gamma','sat'].map((k,i)=>'<td><input class="'+(i?'':'name')+'" data-key="'+k+'" '+(i?'type="number" step="any"':'maxlength="40"')+' aria-label="土層 '+({name:'名稱',bottom:'層底高程 m',c:'有效凝聚力',phi:'有效摩擦角 度',gamma:'天然單位重',sat:'飽和單位重'}[k])+'"></td>').join('')+'<td><button class="remove" aria-label="移除此土層">×</button></td>';
for(const x of tr.querySelectorAll('input'))x.value=x.dataset.key==='name'?l.name:l[x.dataset.key]/(['c','gamma','sat'].includes(x.dataset.key)?factor():1);tr.querySelector('.remove').onclick=()=>{if($('layers').tBodies[0].rows.length<=1){notify('至少保留一個土層');return;}tr.remove();if($('layers').tBodies[0].rows.length===1)soilMulti=false;markDirty();};$('layers').tBodies[0].append(tr);}
function syncGeometry(source='load'){
if(source==='height-slider')$('height').value=$('height-slider').value;
if(source==='horizontal-slider')$('horizontalLength').value=$('horizontal-slider').value;
if(source==='beta-slider')$('beta').value=$('beta-slider').value;
const h=Number($('height').value),horizontal=source==='horizontalLength'||source==='horizontal-slider';
if(source==='beta'||source==='beta-slider')$('ratio').value=fmt(1/Math.tan(Number($('beta').value)*Math.PI/180),12);
if(horizontal)$('ratio').value=$('horizontalLength').value.trim()?fmt(Number($('horizontalLength').value)/h,12):'';
const ratio=Number($('ratio').value),run=h*ratio,beta=Math.atan(1/ratio)*180/Math.PI;
if(!horizontal)$('horizontalLength').value=Number.isFinite(run)?fmt(run,9).replace(/\.?0+$/,''):'';
if(source!=='beta'&&source!=='beta-slider')$('beta').value=Number.isFinite(beta)?fmt(beta,7):'';
$('beta-slider').value=$('beta').value;$('height-slider').min=.1;$('height-slider').max=Math.max(40,source==='load'?0:Number($('height-slider').max)||0,Math.min(500,h||40));$('height-slider').value=$('height').value;
const slider=$('horizontal-slider'),length=Number($('horizontalLength').value),min=h/Math.tan(80*Math.PI/180),max=h/Math.tan(5*Math.PI/180),valid=h>=.1&&h<=500&&length>0&&length>=min-1e-7&&length<=max+1e-7;
slider.min=valid?Math.min(Math.ceil(min*1000)/1000,length):Math.ceil(Math.max(.001,min||.001)*1000)/1000;
slider.max=valid?Math.max(Math.floor(max*1000)/1000,length):Math.max(Number(slider.min)+.001,max||1);
slider.value=$('horizontalLength').value;slider.disabled=!valid;slider.setAttribute('aria-valuetext',fmt(length,3)+' 公尺');
$('horizontal-range').textContent=h>=.1&&h<=500?'可拖曳 '+fmt(min,3)+'～'+fmt(max,3)+' m（坡角 5～80°）。':'請先填有效坡高，再調整水平長度。';
}
function simpleGround(){const V=val('height'),H=val('horizontalLength'),r=val('ratio'),toe=val('toeLength'),crest=val('crestLength'),y=val('datum');if(V<.1||V>500||H<=0||r<.01||toe<=0||crest<=0)throw Error('坡高 V 需 0.1–500 m；水平長 H、坡比與外延長度須為正');const beta=Math.atan(1/r)*180/Math.PI;if(beta<5-1e-7||beta>80+1e-7)throw Error('標準坡角 β 需 5–80°；請調整水平長 H 或坡高 V');if(Math.abs(H-V*r)>1e-7*Math.max(1,H))throw Error('水平長 H 與坡高／坡比不一致，請重新輸入');return [[-toe,y],[0,y],[H,y+V],[H+crest,y+V]];}
function topPlatform(ground){if(!Array.isArray(ground)||ground.length<2)return null;const end=ground.at(-1);let i=ground.length-2;while(i>=0&&Math.abs(ground[i][1]-end[1])<1e-8)i--;const start=ground[i+1];return end[0]-start[0]>1e-8?{a:start[0],b:end[0],y:end[1]}:null;}
function syncLoadPlacement(reset=false){
const ground=$('geometryMode').value==='simple'?simpleGround():C.parsePoints($('ground').value);if(ground.length<3||ground.some((p,i)=>!p.every(Number.isFinite)||i&&(p[0]<=ground[i-1][0]||p[1]<ground[i-1][1]-1e-8)))throw Error('地表需至少 3 點，x 嚴格遞增、y 由低至高且不下降');const platform=topPlatform(ground),follow=$('q-follow').checked;
if(!platform){if(reset)lastCrestX=null;$('q-position-note').textContent='目前剖面沒有水平坡頂平台。固定 x 可施加於自訂地表；跟隨模式須先建立水平平台。';return;}
if(follow&&!reset&&lastCrestX!==null&&Math.abs(platform.a-lastCrestX)>1e-9){for(const id of ['qa','qb'])if($(id).value.trim()&&Number.isFinite(Number($(id).value)))$(id).value=fmt(Number($(id).value)+platform.a-lastCrestX,9).replace(/\.?0+$/,'');}
lastCrestX=platform.a;const a=Number($('qa').value),b=Number($('qb').value);
$('q-position-note').textContent=(follow?'跟隨坡頂平台':'固定工址 x')+'：平台 x='+fmt(platform.a,3)+'～'+fmt(platform.b,3)+' m；距坡頂 '+fmt(a-platform.a,3)+' m；載重寬 '+fmt(b-a,3)+' m。';
}
function readModel(){const f=factor(),ground=$('geometryMode').value==='simple'?simpleGround():C.parsePoints($('ground').value);if($('geometryMode').value==='simple')$('ground').value=ground.map(p=>p.map(v=>fmt(v,6)).join(',')).join('\n');const m={name:$('project').value||'未命名剖面',units:$('units').value,geometry:{mode:$('geometryMode').value,height:val('height'),ratio:val('ratio'),toe:val('toeLength'),crest:val('crestLength'),datum:val('datum')},method:$('method').value,profile:$('profile').value,targets:[val('targetNormal'),val('targetRain'),val('targetSeismic')],strict:$('strict').value==='1',customSource:$('customSource').value,ground,layers:Array.from($('layers').tBodies[0].rows).map(tr=>Object.fromEntries(Array.from(tr.querySelectorAll('input')).map(x=>{const k=x.dataset.key;if(k==='name')return [k,x.value];if(!x.value.trim())throw Error('土層參數不可空白');const n=Number(x.value);return [k,n*(['c','gamma','sat'].includes(k)?f:1)];}))),waterMode:$('waterMode').value,waterNormal:val('waterNormal'),waterRain:val('waterRain'),ruNormal:val('ruNormal'),ruRain:val('ruRain'),waterLine:$('waterMode').value==='line'?C.parsePoints($('waterLine').value):[],rainLine:$('waterMode').value==='line'?C.parsePoints($('rainLine').value):[],gammaWater:val('gammaWater')*f,q:val('q')*f,qa:val('qa'),qb:val('qb'),qFollowCrest:$('q-follow').checked,kh:val('kh'),kv:val('kv'),slices:val('slices'),density:val('density'),minSpan:val('minSpan'),maxDepth:val('maxDepth'),arcMin:val('arcMin'),arcMax:val('arcMax'),mode:$('mode').value,circle:{cx:val('cx'),cy:val('cy'),r:val('radius')}};if(m.qFollowCrest&&m.q>0){const platform=topPlatform(ground);if(!platform)throw Error('跟隨載重需要水平坡頂平台；請建立平台，或取消跟隨並指定作用座標');if(m.qa<platform.a-1e-8||m.qb>platform.b+1e-8)throw Error('q 作用區間須完整位於坡頂平台 x='+fmt(platform.a,3)+'～'+fmt(platform.b,3)+' m；請增加坡頂外延或調整載重起訖，不會自動縮小載重寬');}return C.validate(m);}
function fillModel(m){$('units').value=m.units||'kn';oldUnits=$('units').value;const f=factor();$('project').value=m.name;for(const k of ['method','profile','waterMode','waterNormal','waterRain','ruNormal','ruRain','qa','qb','kh','kv','slices','density','minSpan','maxDepth','arcMin','arcMax','mode'])$(k).value=m[k];$('gammaWater').value=fmt(m.gammaWater/f,7);$('q').value=fmt(m.q/f,7);$('ground').value=m.ground.map(p=>p.join(',')).join('\n');$('waterLine').value=(m.waterLine?.length?m.waterLine:m.ground.map(p=>[p[0],p[1]-m.waterNormal])).map(p=>p.join(',')).join('\n');$('rainLine').value=(m.rainLine?.length?m.rainLine:m.ground.map(p=>[p[0],p[1]-m.waterRain])).map(p=>p.join(',')).join('\n');$('strict').value=m.strict?'1':'0';$('customSource').value=m.customSource||'';[m.targets?.[0]||1.5,m.targets?.[1]||1.2,m.targets?.[2]||1.1].forEach((v,i)=>$( ['targetNormal','targetRain','targetSeismic'][i]).value=v);if(m.circle){$('cx').value=m.circle.cx;$('cy').value=m.circle.cy;$('radius').value=m.circle.r;}const g=m.geometry||{mode:'coordinates',height:10,ratio:1.5,toe:15,crest:25,datum:0};$('geometryMode').value=g.mode;for(const [k,key]of [['height','height'],['ratio','ratio'],['toeLength','toe'],['crestLength','crest'],['datum','datum']])$(k).value=g[key];$('beta').value=fmt(Math.atan(1/Number($('ratio').value))*180/Math.PI,7);syncGeometry();const platform=topPlatform(m.ground);$('q-follow').checked=m.qFollowCrest??Boolean(platform&&m.qa>=platform.a-1e-8&&m.qb<=platform.b+1e-8);syncLoadPlacement(true);$('layers').tBodies[0].innerHTML='';for(const l of m.layers)addLayer(l);soilMulti=m.layers.length>1;syncFields();markDirty();}
function example(name){const m={name:'10 m 土坡教學範例',units:'kn',geometry:{mode:'simple',height:10,ratio:1.5,toe:15,crest:25,datum:0},ground:[[-15,0],[0,0],[15,10],[40,10]],layers:[{name:'均質土層',bottom:-20,c:10,phi:30,gamma:18,sat:20}],method:'bishop',profile:'sw-permanent',targets:[1.5,1.2,1.1],customSource:'',strict:false,waterMode:'depth',waterNormal:4,waterRain:0,ruNormal:.15,ruRain:.35,waterLine:[],rainLine:[],gammaWater:C.gw,q:10,qa:17,qb:30,kh:.1,kv:.05,slices:60,density:14,minSpan:3,maxDepth:20,arcMin:.3,arcMax:3,mode:'search',circle:{cx:0,cy:15,r:16}};if(name==='bench'){m.name='12 m 分階土坡教學範例';m.geometry.mode='coordinates';m.ground=[[-10,0],[0,0],[9,6],[12,6],[21,12],[45,12]];m.layers=[{name:'上層土',bottom:5,c:8,phi:28,gamma:18,sat:20},{name:'下層土',bottom:-20,c:22,phi:32,gamma:19,sat:21}];m.qa=24;m.qb=36;m.maxDepth=25;}
if(name==='reference'){m.name='PDF材料示範（非原A–A剖面）';m.units='tf';m.geometry.mode='coordinates';m.layers=[{name:'回填層（示範水平界面）',bottom:8,c:0,phi:30,gamma:1.96*C.gw,sat:2.06*C.gw},{name:'砂頁岩等效土（示範）',bottom:-20,c:3*C.gw,phi:33,gamma:2.45*C.gw,sat:2.55*C.gw}];m.q=0;m.kh=.13;m.kv=.07;m.waterNormal=.5;m.waterRain=0;}
return m;}
for(const b of document.querySelectorAll('[data-example]'))b.onclick=()=>{fillModel(example(b.dataset.example));page('analysis');notify('已載入完整範例；請執行分析。');};
function markDirty(){if(worker){worker.terminate();worker=null;busy(false);notify('輸入已變更，已停止原分析。');}dirty=true;result=null;lastModel=null;$('run-status').textContent='輸入已變更，待重新分析';try{syncLoadPlacement();syncFields();const m=readModel();lastModel=m;draw(m);$('notice').className='notice';$('notice').textContent='目前為輸入模型預覽。請執行三工況分析後查看 FS。';}catch(e){$('notice').className='notice error';$('notice').textContent=e.message;draw(null);}renderResults();}
const numericalInputs=['height','ratio','beta','horizontalLength','height-slider','beta-slider','horizontal-slider'];
document.addEventListener('input',e=>{if(!e.target.closest('.inputs-column'))return;const id=e.target.id;if(e.target.dataset.soil){$('layers').tBodies[0].rows[0].querySelector('[data-key='+e.target.dataset.soil+']').value=e.target.value;}if(e.target.dataset.soilSlider){$('layers').tBodies[0].rows[0].querySelector('[data-key='+e.target.dataset.soilSlider+']').value=e.target.value;}const sliderMap={'q-slider':'q','water-normal-slider':'waterNormal','water-rain-slider':'waterRain','kh-slider':'kh','kv-slider':'kv'};if(sliderMap[id])$(sliderMap[id]).value=e.target.value;if(numericalInputs.includes(id))syncGeometry(id);if(e.target.tagName!=='SELECT')markDirty();});
document.addEventListener('change',e=>{if(e.target.closest('.inputs-column')&&e.target.tagName==='SELECT'&&e.target.id!=='units')markDirty();});
$('units').onchange=()=>{const oldF=oldUnits==='tf'?C.gw:1,newF=factor();for(const id of ['q','gammaWater'])$(id).value=fmt(Number($(id).value)*oldF/newF,8);for(const x of $('layers').querySelectorAll('tbody input'))if(['c','gamma','sat'].includes(x.dataset.key))x.value=fmt(Number(x.value)*oldF/newF,8);oldUnits=$('units').value;markDirty();};
$('add-layer').onclick=()=>{const trs=$('layers').tBodies[0].rows,last=Number(trs[trs.length-1].querySelector('[data-key=bottom]').value);addLayer({name:'新增土層',bottom:last-10,c:10,phi:30,gamma:18,sat:20});soilMulti=true;markDirty();};
function busy(on){$('run-btn').disabled=on;$('run-btn').innerHTML=on?'<span class="loading" aria-hidden="true"></span>搜尋分析中…':'執行三工況分析';$('cancel-btn').hidden=!on;}
$('cancel-btn').onclick=()=>{worker?.terminate();worker=null;busy(false);$('run-status').textContent='已停止，請重新執行';notify('已停止分析');};
$('run-btn').onclick=()=>{try{const m=readModel();lastModel=m;result=null;dirty=true;renderResults();busy(true);$('run-status').textContent='各工況獨立搜尋；地震另比較 ±kv';const code=$('engine-source').textContent+'\nself.onmessage=e=>{try{self.postMessage({ok:true,data:SlopeCore.run(e.data)})}catch(err){self.postMessage({ok:false,error:err.message})}};';const url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=e=>{worker.terminate();worker=null;busy(false);if(!e.data.ok){$('notice').className='notice error';$('notice').textContent=e.data.error;return;}result=e.data.data;dirty=false;renderResults();draw(result.model);$('run-status').textContent='分析完成 · '+result.results.reduce((s,r)=>s+r.count,0).toLocaleString()+' 組候選';$('notice').className='notice';$('notice').textContent='分析完成。請確認最小 FS 所在工況、負有效法向力標示及搜尋限制。';try{localStorage.setItem('slope-workbench.last-project.v1',JSON.stringify({schema:1,model:m}));}catch{}};worker.onerror=e=>{worker?.terminate();worker=null;busy(false);$('notice').className='notice error';$('notice').textContent='分析工作執行失敗：'+e.message;};worker.postMessage(m);}catch(e){busy(false);$('notice').className='notice error';$('notice').textContent=e.message;}};
function assessment(r){if(!r.best)return {text:'無有效結果',kind:'review'};const b=r.best,pass=r.strict?b.fs>r.target:b.fs>=r.target;if(!pass)return {text:'未達門檻',kind:'fail'};if(b.negative)return {text:'需檢討張裂',kind:'review'};return {text:'達門檻（本模型）',kind:''};}
function current(){return result?.results.find(r=>r.scenario===$('scenario').value)||null;}
function renderResults(){const m=lastModel,ts=m?C.targets(m):[1.5,1.2,1.1];$('metrics').innerHTML=['normal','rain','seismic'].map((s,i)=>{const r=result?.results[i],a=r?assessment(r):{text:'待分析',kind:'wait'};return '<div class="metric '+a.kind+'"><div class="metric-head"><span>'+SCENES[s]+'</span><span class="pill '+a.kind+'">'+a.text+'</span></div><div class="metric-value">'+fmt(r?.best?.fs)+'</div><small>FS '+(r?.strict?'&gt;':'≥')+' '+fmt(r?.target||ts[i],2)+'</small></div>';}).join('');
const r=current(),b=r?.best;if(!b){$('result-details').innerHTML='<div><span>分析狀態</span><strong>'+(result?'本工況無有效結果':'尚未分析')+'</strong></div>';for(const id of ['summary','formulas','slices','search'])$('result-'+id).innerHTML='<p class="muted">'+(result?'此工況未取得有效圓弧。請檢查幾何、層底、曲率與搜尋限制。':'輸入資料後執行分析，這裡會顯示完整計算資料。')+'</p>';if(result)$('result-search').innerHTML='<div class="search-log">'+esc(JSON.stringify(r?.errors,null,2))+'</div>';return;}
const f=factor(),a=assessment(r),c=b.circle;
$('result-details').innerHTML=[['圓心 (cx, cy)',fmt(c.cx,2)+', '+fmt(c.cy,2)+' m'],['半徑 R',fmt(c.r,2)+' m'],['實際切片數',b.rows.length],['有效候選／總數',r.valid.toLocaleString()+' / '+r.count.toLocaleString()],['力矩相對殘差',b.residual.toExponential(2)],['垂直地震 kv',r.scenario==='seismic'?fmt(b.kv,3):'0.000']].map(([k,v])=>'<div><span>'+k+'</span><strong>'+v+'</strong></div>').join('');
$('result-summary').innerHTML='<h3>'+SCENES[r.scenario]+'｜<span class="pill '+a.kind+'">'+a.text+'</span></h3><p>分析方法：'+(m.method==='bishop'?'Bishop 簡化法':'Fellenius 普通切片法')+'。FS='+fmt(b.fs,6)+'；要求 '+(r.strict?'&gt;':'≥')+' '+fmt(r.target,2)+'。</p><p>臨界圓弧地表出口 x='+fmt(c.a,3)+' m、入口 x='+fmt(c.b,3)+' m；最大垂直滑動深度 '+fmt(b.maxDepth,3)+' m。'+(m.mode==='search'?'最低值來自指定範圍的網格搜尋與三次局部細化。':'結果僅代表指定圓弧，不是搜尋全坡的最低值。')+'</p><p>相同圓弧的 Fellenius FS='+fmt(b.ordinary,6)+'，此比對值不代表 Fellenius 已獨立搜尋的最低值。</p>'+(b.negative?'<div class="hint warn">有 '+b.negative+' 片有效法向力 N′&lt;0。數值保留並可查看，但須另檢討張裂／接觸模型，不作達門檻結論。</div>':'')+(r.scenario==='seismic'?'<div class="hint warn">擬靜態簡化分析；Bishop 未滿足完整水平力平衡。地震設計需依案件要求另以完整平衡法與破壞機制複核。</div><p>±kv 分析：'+b.variants.map(v=>'kv='+fmt(v.kv,3)+' → FS='+fmt(v.fs,6)).join('；')+'。q 不含水平慣性。</p>':'')+'<div class="hint">'+('門檻來源：'+esc(sourceOf(m)))+'　判定採未四捨五入的 FS。</div>';
let Fhtml=m.method==='bishop'?'<div class="formula">mα = cosα + sinα·tanφ′/FS<br>N′ = [V − u·b − c′·l·sinα/FS] / mα<br>R抗剪 = c′·l + N′·tanφ′<br>FS = ΣR抗剪 / D（迭代求解）</div>':'<div class="formula">N′ = V·cosα − kh·W·sinα − u·l<br>R抗剪 = c′·l + N′·tanφ′<br>FS = ΣR抗剪 / D</div>';
const s=b.rows.find(x=>x.W===Math.max(...b.rows.map(x=>x.W)))||b.rows[0],Rsum=b.rows.reduce((sum,s)=>sum+s.R,0);
$('result-formulas').innerHTML='<p>所有內部計算採 kN、m、kPa；畫面顯示單位 '+uForce()+'。單位剖面寬度為 1 m。</p><div class="formula">Q = q·Δx<br>V = (1−kv)·W + Q<br>l = b/cosα<br>D = Σ[V·sinα + kh·W·(cy−yG)/R]<br>u = γw·max(yw−yb,0)，或 u=ru·W/b</div>'+Fhtml+'<p>其中 W 為土體重量；Q 為垂直外載；yG 為逐層積分的土體重心；α 為底面向右上升的角度。地下水造成的浮力透過 u 反映，W 使用天然／飽和總單位重。</p><div class="formula">ΣR抗剪='+fmt(Rsum/f,6)+' '+uForce()+'<br>D='+fmt(b.D/f,6)+' '+uForce()+'<br>FS='+fmt(Rsum/f,6)+' / '+fmt(b.D/f,6)+' = '+fmt(b.fs,6)+'</div><h3>第 '+s.i+' 片代入範例</h3><p>b='+fmt(s.b,4)+' m；l='+fmt(s.l,4)+' m；α='+fmt(s.alpha*180/Math.PI,4)+'°；W='+fmt(s.W/f,4)+' '+uForce()+'；Q='+fmt(s.Q/f,4)+' '+uForce()+'。</p><p>u='+fmt(s.u/f,4)+' '+uStress()+'；c′='+fmt(s.c/f,4)+' '+uStress()+'；φ′='+fmt(s.phi,3)+'°；V='+fmt(s.V/f,4)+' '+uForce()+'。</p><p>'+(m.method==='bishop'?'mα='+fmt(s.m,6)+'；':'')+'N′='+fmt(s.ne/f,6)+' '+uForce()+'；R抗剪='+fmt(s.R/f,6)+' '+uForce()+'。逐片細節請切換「切片明細」。</p>'+iterationTable(b,f);
$('result-slices').innerHTML=sliceSummary(r,m,f)+'<details><summary>展開其他受力與基底材料明細</summary><p class="muted">力單位 '+uForce()+'；應力 '+uStress()+'；N′ 為有效法向力。紅色 N′ 需檢討張裂。</p><div class="table-wrap">'+sliceTable(b.rows,f)+'</div></details>';
const labels={span:'小於最小跨度','upper-arc':'端點不在圓弧下半部',geometry:'圓弧穿出土體／層底／底面過陡',depth:'超過最大深度',driving:'驅動力矩非正',convergence:'迭代未收斂','m-alpha':'Bishop 最終 mα < 0.2',residual:'力矩殘差過大'};
const errors=Object.entries(r.errors).map(([k,n])=>(labels[k]||k)+'：'+n.toLocaleString()).join('\n');
$('result-search').innerHTML='<p>模式：'+(m.mode==='search'?'地表端點 × 曲率網格＋三次局部細化':'指定圓弧與地表交點')+'；搜尋密度 '+m.density+'；目標切片 '+m.slices+'。</p><p>地表 x 範圍 '+fmt(m.ground[0][0],2)+'～'+fmt(m.ground.at(-1)[0],2)+' m；最小跨度 '+m.minSpan+' m；最大深度 '+m.maxDepth+' m；圓心距/弦長比 '+m.arcMin+'～'+m.arcMax+'。</p><div class="search-log">總候選：'+r.count+'\n有效候選：'+r.valid+'\n排除紀錄：\n'+esc(errors||'無')+'</div><div class="hint warn">網格加密與範圍擴大後應再比對；局部最低值不等同全域最低值。各工況均獨立尋找最低值，顯示的圓弧可能不同。</div><div class="table-wrap"><table><thead><tr><th>候選 FS</th><th>出口 x</th><th>入口 x</th><th>半徑 m</th></tr></thead><tbody>'+r.top.map(t=>'<tr><td class="num">'+fmt(t.fs,6)+'</td><td class="num">'+fmt(t.circle.a,3)+'</td><td class="num">'+fmt(t.circle.b,3)+'</td><td class="num">'+fmt(t.circle.r,3)+'</td></tr>').join('')+'</tbody></table></div>';
}
function iterationTable(b,f){if(!b.history?.length)return '<p>本方法不需迭代。</p>';return '<h3>迭代收斂完整紀錄</h3><p>起始 FS='+b.initial+'；Fnext=(F+Fraw)/2；收斂 |Fraw−F|&lt;10⁻⁸ max(1,F)。最後以收斂 Fraw 重算受力。</p><div class="table-wrap"><table><thead><tr><th>步</th><th>F 當步</th><th>Σ抗剪</th><th>Fraw</th><th>Fnext</th><th>差值</th></tr></thead><tbody>'+b.history.map(h=>'<tr>'+[h.iteration,fmt(h.F,9),fmt(h.sum/f,6),fmt(h.raw,9),fmt(h.next,9),h.difference.toExponential(3)].map(v=>'<td class="num">'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function sliceSummary(r,m,f){
const b=r.best,kh=r.scenario==='seismic'?m.kh:0,force=m.units==='tf'?'tf':'kN',stress=m.units==='tf'?'tf/m²':'kPa',drive=s=>s.V*Math.sin(s.alpha)+kh*s.W*(b.circle.cy-s.yg)/b.circle.r,total=k=>b.rows.reduce((v,s)=>v+(k==='D'?drive(s):s[k]),0),D=total('D'),R=total('R'),W=total('W');
return '<h3>詳細切片計算過程（實際 '+b.rows.length+' 片）</h3><p class="muted">以 1 m 剖面寬度列總力；h 為切片中點地表至滑動面的垂直高度。W 採分層 Gauss 積分，不直接以單一 γ×b×h 取代。切片按計算座標 x 遞增編號，圖面鏡射不改編號。</p><div class="table-wrap"><table><thead><tr>'+['切片 #','寬度 b (m)','高度 h (m)','總重 W ('+force+')','底角 α (°)','水壓 u ('+stress+')','驅動項 Dᵢ ('+force+')','抗滑力 Rᵢ ('+force+')'].map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+b.rows.map(s=>'<tr>'+[s.i,fmt(s.b,4),fmt(s.top-s.y,4),fmt(s.W/f,4),fmt(s.alpha*180/Math.PI,4),fmt(s.u/f,4),fmt(drive(s)/f,4),fmt(s.R/f,4)].map(v=>'<td class="num">'+v+'</td>').join('')+'</tr>').join('')+'</tbody><tfoot><tr><th>合計</th><td></td><td></td><th class="num">'+fmt(W/f,6)+'</th><td></td><td></td><th class="num">'+fmt(D/f,6)+'</th><th class="num">'+fmt(R/f,6)+'</th></tr></tfoot></table></div><div class="formula">ΣR = '+fmt(R/f,6)+' '+force+'；ΣD = '+fmt(D/f,6)+' '+force+'<br>FS = ΣR / ΣD = '+fmt(R/f,6)+' / '+fmt(D/f,6)+' = '+fmt(R/D,9)+'</div><p class="muted">Dᵢ=Vᵢ sinαᵢ+kh Wᵢ(cy−yGᵢ)/R；Rᵢ=c′ᵢlᵢ+N′ᵢtanφ′ᵢ。負驅動項保留正負號；表格四捨五入，FS 以完整精度計算。</p>';
}
function sliceTable(rows,f){return '<table><thead><tr>'+['片','x (m)','b (m)','l (m)','α (°)','W','Q','u','c′','φ′ (°)','N′','mα','抗剪 R','基底層'].map(k=>'<th>'+k+'</th>').join('')+'</tr></thead><tbody>'+rows.map(s=>'<tr>'+[s.i,fmt(s.x),fmt(s.b),fmt(s.l),fmt(s.alpha*180/Math.PI),fmt(s.W/f),fmt(s.Q/f),fmt(s.u/f),fmt(s.c/f),fmt(s.phi),fmt(s.ne/f),fmt(s.m,6),fmt(s.R/f),esc(s.layer)].map((v,i)=>'<td class="'+(i!==13?'num':'')+'"'+(i===10&&s.ne<0?' style="color:#b7453c"':'')+'>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
for(const b of document.querySelectorAll('[data-result]'))b.onclick=()=>{for(const id of ['summary','formulas','slices','search'])$('result-'+id).hidden=id!==b.dataset.result;for(const x of document.querySelectorAll('[data-result]')){x.classList.toggle('active',x===b);x.setAttribute('aria-selected',String(x===b));}};
$('scenario').onchange=()=>{renderResults();draw(result?.model||lastModel);};$('show-candidates').onchange=$('show-details').onchange=()=>draw(result?.model||lastModel);
function draw(m){if(!m){$('plot').innerHTML='<text x="450" y="240" text-anchor="middle" fill="#647985" font-size="20">請修正輸入資料後預覽剖面</text>';return;}const r=current(),b=r?.best,g=m.ground,lo=g[0][0],hi=g.at(-1)[0],minY=Math.min(g[0][1]-5,b?b.circle.cy-b.circle.r:g[0][1]-5),maxY=g.at(-1)[1],scale=Math.min(600/(hi-lo),360/(maxY-minY)),px=x=>60+(flipped?hi-x:x-lo)*scale,right=60+(hi-lo)*scale,py=y=>425-(y-minY)*scale;
const poly=p=>p.map((t,i)=>(i?'L':'M')+fmt(px(t[0]),2)+','+fmt(py(t[1]),2)).join(' '),groundPath=poly(g),close=groundPath+' L'+px(hi)+',425 L'+px(lo)+',425 Z';let svg='<title>邊坡地表、水平土層、水位與'+SCENES[$('scenario').value]+'圓弧</title><defs><linearGradient id="slip-fill" x1="'+(flipped?'0%':'100%')+'" y1="0%" x2="'+(flipped?'100%':'0%')+'" y2="0%"><stop offset="0%" stop-color="#e2a574" stop-opacity=".45"/><stop offset="100%" stop-color="#b4d878" stop-opacity=".45"/></linearGradient><clipPath id="soil-clip"><path d="'+close+'"/></clipPath><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10z" fill="#9d7340"/></marker></defs><rect width="900" height="500" fill="#fcfdfd"/>';
for(let i=0;i<=8;i++){const x=lo+(hi-lo)*i/8;svg+='<path d="M'+px(x)+' 42V425" stroke="#e4ecef" stroke-dasharray="3 5"/><text x="'+px(x)+'" y="450" font-size="12" text-anchor="middle" fill="#738793">'+fmt(x,1)+'</text>';}
for(let i=0;i<=6;i++){const y=minY+(maxY-minY)*i/6;svg+='<path d="M60 '+py(y)+'H'+right+'" stroke="#e4ecef" stroke-dasharray="3 5"/><text x="49" y="'+(py(y)+4)+'" font-size="12" text-anchor="end" fill="#738793">'+fmt(y,1)+'</text>';}
const colors=['#e8ddc8','#d7e2d4','#e0d0ba','#ccdfe4','#e4d6d9'];let top=maxY;for(let i=0;i<m.layers.length;i++){const l=m.layers[i],low=Math.max(minY,l.bottom);svg+='<rect x="60" y="'+py(top)+'" width="'+(right-60)+'" height="'+Math.max(0,py(low)-py(top))+'" fill="'+colors[i%colors.length]+'" clip-path="url(#soil-clip)"/>';if(low>minY)svg+='<path d="M60 '+py(low)+'H'+right+'" stroke="#9fae9d" stroke-dasharray="6 4" clip-path="url(#soil-clip)"/>';top=l.bottom;}
svg+='<path d="'+groundPath+'" fill="none" stroke="#167567" stroke-width="3"/>';
if(m.waterMode!=='dry'&&m.waterMode!=='ru'){const pts=Array.from({length:151},(_,i)=>{const x=lo+(hi-lo)*i/150;return [x,C.waterY(m,x,$('scenario').value)];});svg+='<path d="'+poly(pts)+'" fill="none" stroke="#3587bd" stroke-width="2" stroke-dasharray="7 4" clip-path="url(#soil-clip)"/>';}
function arc(c,color,width,opacity=1){const pts=Array.from({length:151},(_,i)=>{const x=c.a+(c.b-c.a)*i/150;return [x,C.bottom(c,x)];});return '<path d="'+poly(pts)+'" fill="none" stroke="'+color+'" stroke-width="'+width+'" opacity="'+opacity+'"/>';}
if(b){if($('show-candidates').checked)for(const t of r.top)svg+=arc(t.circle,'#c24a3c',1,.16);const c=b.circle;for(const s of b.rows)svg+='<path d="M'+px(s.x1)+' '+py(C.interp(g,s.x1))+'V'+py(C.bottom(c,s.x1))+'" stroke="#746f63" stroke-width=".8" opacity=".5"/>';const massGround=[[c.a,C.interp(g,c.a)],...g.filter(p=>p[0]>c.a&&p[0]<c.b),[c.b,C.interp(g,c.b)]];const arcBack=Array.from({length:101},(_,i)=>{const x=c.b-(c.b-c.a)*i/100;return [x,C.bottom(c,x)];});svg+='<path d="'+poly([...massGround,...arcBack])+'Z" fill="url(#slip-fill)"/>';svg+=arc(c,'#c24a3c',3.5);svg+='<circle cx="'+px(c.a)+'" cy="'+py(C.interp(g,c.a))+'" r="4" fill="#c24a3c"/><circle cx="'+px(c.b)+'" cy="'+py(C.interp(g,c.b))+'" r="4" fill="#c24a3c"/>';}
if(m.q>0){for(let i=0;i<=5;i++){const x=m.qa+(m.qb-m.qa)*i/5,y=C.interp(g,x);svg+='<path d="M'+px(x)+' '+(py(y)-35)+'V'+(py(y)-5)+'" stroke="#9d7340" stroke-width="1.5" marker-end="url(#arrow)"/>';}svg+='<text x="'+px((m.qa+m.qb)/2)+'" y="'+(py(C.interp(g,(m.qa+m.qb)/2))-44)+'" text-anchor="middle" fill="#9d7340" font-size="12">q='+fmt(m.q/factor(),2)+' '+uStress()+'</text>';}
if($('show-details').checked){const V=g.at(-1)[1]-g[0][1],xd=flipped?80:right-20;svg+='<path d="M'+xd+' '+py(g.at(-1)[1])+'V'+py(g[0][1])+'M'+(xd-5)+' '+py(g.at(-1)[1])+'h10M'+(xd-5)+' '+py(g[0][1])+'h10" stroke="#476671"/><text transform="translate('+(xd+15)+' '+py((g.at(-1)[1]+g[0][1])/2)+') rotate(-90)" font-size="13" text-anchor="middle" fill="#476671">V='+fmt(V,2)+' m</text>';if(m.geometry?.mode==='simple'){const toe=g[1],crest=g[2],H=crest[0]-toe[0],beta=Math.atan2(crest[1]-toe[1],H)*180/Math.PI,yd=466,x1=px(toe[0]),x2=px(crest[0]);svg+='<text x="'+(x1+(flipped?35:-35))+'" y="'+(py(toe[1])-12)+'" font-size="12" text-anchor="'+(flipped?'start':'end')+'" fill="#476671">β='+fmt(beta,1)+'°</text><path d="M'+x1+' '+(yd-6)+'V'+(yd+6)+'M'+x1+' '+yd+'H'+x2+'M'+x2+' '+(yd-6)+'V'+(yd+6)+'" stroke="#167567" stroke-width="1.5"/><rect x="'+((x1+x2)/2-65)+'" y="'+(yd-10)+'" width="130" height="20" rx="4" fill="#fcfdfd"/><text x="'+((x1+x2)/2)+'" y="'+(yd+4)+'" font-size="13" text-anchor="middle" fill="#167567">H='+fmt(H,2)+' m</text>';}
}
const state=r?assessment(r):{text:'待分析',kind:'wait'},color=state.kind==='fail'?'#b7453c':state.kind==='review'?'#966b20':'#167567';svg+='<g id="plot-fs-label" role="group" aria-label="'+SCENES[$('scenario').value]+' 安全係數 '+fmt(b?.fs,6)+'"><rect x="686" y="58" width="195" height="218" rx="10" fill="#ffffff" stroke="'+color+'" stroke-width="1.5"/><text x="701" y="83" font-size="13" fill="#476671">'+SCENES[$('scenario').value]+' · 滑動面</text><text x="701" y="127" font-size="30" font-weight="700" fill="'+color+'">FS '+fmt(b?.fs,3)+'</text><text x="701" y="153" font-size="13" fill="#476671">要求 '+(r?.strict?'&gt;':'≥')+' '+fmt(r?.target||C.targets(m)[['normal','rain','seismic'].indexOf($('scenario').value)],2)+'</text><text x="701" y="179" font-size="13" fill="'+color+'">'+state.text+'</text><text x="701" y="205" font-size="12" fill="#647985">'+(b?'Cx = '+fmt(b.circle.cx,2)+' m':'執行分析後顯示 FS')+'</text><text x="701" y="228" font-size="12" fill="#647985">'+(b?'Cy = '+fmt(b.circle.cy,2)+' m':'')+'</text><text x="701" y="251" font-size="12" fill="#647985">'+(b?'R = '+fmt(b.circle.r,2)+' m':'')+'</text></g>';
if($('show-details').checked&&m.geometry?.mode==='simple'){
const toe=g[1],crest=g[2],H=crest[0]-toe[0],height=crest[1]-toe[1],L=Math.hypot(H,height),p0=[px(toe[0]),py(toe[1])],p1=[px(crest[0]),py(crest[1])],left=p0[0]<p1[0]?p0:p1,end=p0[0]<p1[0]?p1:p0,dx=end[0]-left[0],dy=end[1]-left[1],len=Math.hypot(dx,dy),nx=dy/len,ny=-dx/len,off=27,sx=left[0]+nx*off,sy=left[1]+ny*off,ex=end[0]+nx*off,ey=end[1]+ny*off,mx=(sx+ex)/2,my=(sy+ey)/2,angle=Math.atan2(dy,dx)*180/Math.PI;
svg+='<g id="slope-length-dimension"><path d="M'+left[0]+' '+left[1]+'L'+(left[0]+nx*35)+' '+(left[1]+ny*35)+'M'+end[0]+' '+end[1]+'L'+(end[0]+nx*35)+' '+(end[1]+ny*35)+'" stroke="#647985" stroke-dasharray="4 4"/><path d="M'+sx+' '+sy+'L'+ex+' '+ey+'M'+(sx-nx*5)+' '+(sy-ny*5)+'L'+(sx+nx*5)+' '+(sy+ny*5)+'M'+(ex-nx*5)+' '+(ey-ny*5)+'L'+(ex+nx*5)+' '+(ey+ny*5)+'" stroke="#476671"/><g transform="translate('+mx+' '+my+') rotate('+angle+')"><rect x="-66" y="-12" width="132" height="23" rx="3" fill="#fcfdfd"/><text x="0" y="4" text-anchor="middle" font-size="13" fill="#476671">L = '+fmt(L,2)+' m</text></g></g>';
const radius=Math.min(23,len*.18),beta=Math.atan2(height,H),arcPoints=Array.from({length:15},(_,i)=>{const a=(flipped?Math.PI:0)+(flipped?1:-1)*beta*i/14;return [p0[0]+radius*Math.cos(a),p0[1]+radius*Math.sin(a)];});svg+='<path d="'+arcPoints.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ')+'" fill="none" stroke="#476671" stroke-width="1.2"/>';
if(m.waterMode!=='dry'&&m.waterMode!=='ru'){const yw=C.waterY(m,crest[0],$('scenario').value),hw=Math.max(0,crest[1]-yw);if(hw>1e-8){const xw=flipped?105:right-46,ywPlot=Math.min(425,py(yw));svg+='<g id="water-depth-dimension"><path d="M'+xw+' '+py(crest[1])+'V'+ywPlot+'M'+(xw-4)+' '+py(crest[1])+'h8M'+(xw-4)+' '+ywPlot+'h8" stroke="#3587bd" stroke-width="1.5"/><text transform="translate('+(xw+11)+' '+((py(crest[1])+ywPlot)/2)+') rotate(-90)" font-size="12" text-anchor="middle" fill="#2876a7">Hw = '+fmt(hw,2)+' m'+(py(yw)>425?'（超出圖框）':'')+'</text></g>';}}
}
svg+='<path d="M60 42V425H'+right+'" fill="none" stroke="#bccdd3"/><text x="'+(right-10)+'" y="492" text-anchor="end" fill="#647985" font-size="13">水平距離 x (m)</text><text x="60" y="26" fill="#647985" font-size="12">高程 y (m)</text>';$('plot').innerHTML=svg;$('plot').setAttribute('viewBox',[view.x,view.y,view.w,view.h].join(' '));}
function zoom(k){const nw=view.w*k,nh=view.h*k;if(nw<225||nw>1800)return;view.x+=(view.w-nw)/2;view.y+=(view.h-nh)/2;view.w=nw;view.h=nh;$('plot').setAttribute('viewBox',[view.x,view.y,view.w,view.h].join(' '));}
$('flip-btn').onclick=()=>{flipped=!flipped;$('flip-btn').setAttribute('aria-pressed',String(flipped));draw(result?.model||lastModel);};
$('zoom-in').onclick=()=>zoom(.8);$('zoom-out').onclick=()=>zoom(1.25);$('zoom-reset').onclick=()=>{view={x:0,y:0,w:900,h:500};draw(result?.model||lastModel);};let pointer=null;$('plot').onpointerdown=e=>{pointer={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};$('plot').setPointerCapture(e.pointerId);};$('plot').onpointermove=e=>{if(!pointer)return;const rect=$('plot').getBoundingClientRect();view.x=pointer.vx-(e.clientX-pointer.x)*view.w/rect.width;view.y=pointer.vy-(e.clientY-pointer.y)*view.h/rect.height;$('plot').setAttribute('viewBox',[view.x,view.y,view.w,view.h].join(' '));};$('plot').onpointerup=$('plot').onpointercancel=()=>pointer=null;
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function ensureResult(){if(!result||dirty)throw Error('請先執行目前輸入的分析，再輸出計算結果。');return result;}
function guarded(fn){return ()=>{try{fn();}catch(e){notify(e.message);}};}
$('save-btn').onclick=guarded(()=>{const m=readModel();download(JSON.stringify({schema:1,app:'SlopeWorkbench',version:'1.1.1',savedAt:new Date().toISOString(),model:m},null,2),'邊坡專案.json','application/json;charset=utf-8');notify('專案已下載');});
$('import-btn').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2e6)throw Error('請選擇 2 MB 以下的專案檔');const data=JSON.parse(await file.text());if(data.schema!==1||!data.model)throw Error('不是支援的邊坡專案格式');C.validate(data.model);fillModel(data.model);page('analysis');notify('已開啟專案，請執行分析');}catch(e){notify(e.message);}e.target.value='';};
$('offline-btn').onclick=guarded(()=>{const m=readModel(),doc=document.documentElement.cloneNode(true);doc.querySelector('#project-data').textContent=JSON.stringify(m).replace(/</g,'\\u003c');doc.querySelector('#video-holder').innerHTML='<p>外部教學需網路。<a href="https://www.youtube.com/watch?v=WJplLLHTVXU" target="_blank" rel="noopener">開啟參考影片</a></p>';doc.querySelector('#toast').hidden=true;const video=doc.querySelector('#operation-video');if(video)video.outerHTML='<p>本程式操作影片已包含在完整離線 ZIP。單檔版需網路播放：<a href="https://jerry597640-droid.github.io/engineering-calculator-hub/slope-stability/assets/operation-tw-female.mp4">台灣女性旁白操作影片</a></p>';for(const a of doc.querySelectorAll('a[href^="./assets/"],a[href="./slope-offline-v1.1.zip"]'))a.href='https://jerry597640-droid.github.io/engineering-calculator-hub/slope-stability/'+a.getAttribute('href').slice(2);download('<!doctype html>\n'+doc.outerHTML,'邊坡穩定分析_離線版_v1.1.1.html','text/html;charset=utf-8');notify('已下載單檔離線版，內含目前輸入');});
function reportHTML(){const out=ensureResult(),m=out.model,f=factor(),source=sourceOf(m);let html='<h1>'+esc(m.name)+'</h1><p>邊坡穩定分析紀錄 v1.1.1 · '+esc(new Date().toLocaleString('zh-TW'))+'</p><p>方法：'+(m.method==='bishop'?'Bishop 簡化法':'Fellenius 普通切片法')+'；1 m 剖面寬度；結果僅適用輸入模型與搜尋範圍。</p><p>門檻來源：'+esc(source)+'</p><h2>三工況檢核</h2><table><tr><th>工況</th><th>FS</th><th>要求</th><th>判讀</th><th>候選有效／總數</th></tr>'+out.results.map(r=>'<tr><td>'+SCENES[r.scenario]+'</td><td>'+fmt(r.best?.fs,6)+'</td><td>'+(r.strict?'&gt;':'≥')+fmt(r.target,2)+'</td><td>'+assessment(r).text+'</td><td>'+r.valid+'/'+r.count+'</td></tr>').join('')+'</table><h2>模型輸入</h2><p>q='+fmt(m.q/f)+' '+uStress()+'，x='+m.qa+'～'+m.qb+' m；kh='+m.kh+'；|kv|='+m.kv+'；水模式='+esc(m.waterMode)+'；常時水深='+m.waterNormal+' m；暴雨水深='+m.waterRain+' m；常時 ru='+m.ruNormal+'；暴雨 ru='+m.ruRain+'；γw='+fmt(m.gammaWater/f,6)+'。</p><p>目標切片數='+m.slices+'；搜尋密度='+m.density+'；最小跨度='+m.minSpan+' m；最大深度='+m.maxDepth+' m；圓心距／弦長='+m.arcMin+'～'+m.arcMax+'；模式='+m.mode+'。</p><table><tr><th>土層</th><th>層底 m</th><th>c′ '+uStress()+'</th><th>φ′ °</th><th>γ</th><th>γsat</th></tr>'+m.layers.map(l=>'<tr>'+[esc(l.name),l.bottom,fmt(l.c/f),l.phi,fmt(l.gamma/f),fmt(l.sat/f)].map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</table><pre>地表座標 (m)\n'+esc(m.ground.map(p=>p.join(',')).join('\n'))+'</pre>';
if(m.geometry?.mode==='simple'){const H=m.ground[2][0]-m.ground[1][0],V=m.ground[2][1]-m.ground[1][1];html+='<p>標準坡：坡高 V='+fmt(V,6)+' m；水平長 H='+fmt(H,6)+' m（不含外延）；V:H=1:'+fmt(H/V,6)+'；β='+fmt(Math.atan2(V,H)*180/Math.PI,6)+'°。</p>';}
if(m.waterMode==='line')html+='<pre>常時水位線\n'+esc(m.waterLine.map(p=>p.join(',')).join('\n'))+'\n暴雨水位線\n'+esc(m.rainLine.map(p=>p.join(',')).join('\n'))+'</pre>';
html+='<h2>目前工況剖面圖：'+SCENES[$('scenario').value]+'</h2>'+$('plot').outerHTML.replace(/viewBox="[^"]*"/,'viewBox="0 0 900 500"')+'<h2>計算公式</h2><p>V=(1−kv)W+Q；D=Σ[V sinα + kh W(cy−yG)/R]；FS=Σ[c′l+N′tanφ′]/D。Bishop：N′=[V−ub−c′l sinα/FS]/[cosα+sinα tanφ′/FS]。Fellenius：N′=V cosα−khW sinα−ul。Bishop 迭代不包含完整水平力平衡，q 不含水平慣性。</p>';
for(const r of out.results){const b=r.best;html+='<h2>'+SCENES[r.scenario]+'計算明細</h2>';if(!b){html+='<p>無有效圓弧。'+esc(JSON.stringify(r.errors))+'</p>';continue;}html+='<p>FS='+fmt(b.fs,8)+'；圓心=('+fmt(b.circle.cx,6)+','+fmt(b.circle.cy,6)+') m；R='+fmt(b.circle.r,6)+' m；入口/出口 x='+fmt(b.circle.b,6)+'/'+fmt(b.circle.a,6)+' m；深度='+fmt(b.maxDepth,6)+' m。</p><p>kv='+b.kv+'；迭代='+b.iterations+'；力矩相對殘差='+b.residual.toExponential(4)+'；負 N′切片='+b.negative+'；±kv='+esc(JSON.stringify(b.variants))+'</p><p>排除紀錄：'+esc(JSON.stringify(r.errors))+'</p>'+sliceSummary(r,m,f)+sliceTable(b.rows,f)+iterationTable(b,f);}
html+='<h2>適用範圍與來源</h2><p>二維土坡、水平地層、圓弧滑動、有效應力與靜水壓簡化。未分析非圓弧弱面、順向坡岩塊、補強構材、液化、暫態滲流及外部積水。負有效法向力需另檢討；網格搜尋不保證全域最低 FS。</p><p>官方規範：<a href="https://law.moa.gov.tw/LawContent.aspx?id=FL014521">農業部水土保持技術規範</a>；公式驗證：<a href="https://www.rocscience.com/help/slide2/verification-theory/verification-manuals">Rocscience 官方手算資料</a>。</p>';
return '<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(m.name)+'計算紀錄</title><style>body{max-width:1100px;margin:35px auto;padding:0 22px;font:14px/1.8 system-ui,sans-serif;color:#193241}h1{font-size:26px}h2{font-size:18px;border-bottom:1px solid #ccd9df;margin-top:30px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:7px;border:1px solid #d9e2e6}th{background:#eef4f5}pre{white-space:pre-wrap}svg{width:100%;height:auto}a{color:#167567}@media print{body{margin:0;padding:0}thead{display:table-header-group}tr{break-inside:avoid}svg{max-height:400px}}</style>'+html+'</html>';}
$('report-btn').onclick=guarded(()=>download(reportHTML(),'邊坡穩定分析_計算紀錄.html','text/html;charset=utf-8'));
$('csv-btn').onclick=guarded(()=>{const out=ensureResult(),f=factor(),rows=[['工況','切片','x(m)','b(m)','l(m)','alpha(deg)','W('+uForce()+')','Q('+uForce()+')','u('+uStress()+')','c('+uStress()+')','phi(deg)','N_effective('+uForce()+')','m_alpha','Resistance('+uForce()+')','基底土層','高度h(m)','驅動項('+uForce()+')']];for(const r of out.results)for(const s of r.best?.rows||[])rows.push([SCENES[r.scenario],s.i,s.x,s.b,s.l,s.alpha*180/Math.PI,s.W/f,s.Q/f,s.u/f,s.c/f,s.phi,s.ne/f,s.m,s.R/f,s.layer,s.top-s.y,(s.V*Math.sin(s.alpha)+(r.scenario==='seismic'?out.model.kh:0)*s.W*(r.best.circle.cy-s.yg)/r.best.circle.r)/f]);const safe=x=>{let s=String(x??'');if(/^[=+@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};download('\ufeff'+rows.map(row=>row.map(safe).join(',')).join('\r\n'),'邊坡穩定分析_切片明細.csv','text/csv;charset=utf-8');});
$('svg-btn').onclick=guarded(()=>{if(!lastModel)throw Error('請先修正模型資料');const svg=$('plot').cloneNode(true);svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('viewBox','0 0 900 500');download('<?xml version="1.0" encoding="UTF-8"?>\n'+svg.outerHTML,'邊坡剖面.svg','image/svg+xml;charset=utf-8');});
$('print-btn').onclick=guarded(()=>{const html=reportHTML(),w=window.open('','_blank');if(!w)throw Error('請允許此頁開啟列印視窗');w.onload=()=>{w.focus();w.print();};w.document.write(html);w.document.close();});
function verify(){const rows=C.benchmarks();$('benchmark-results').innerHTML='<table><tr><th>公開七切片案例</th><th>原資料 FS</th><th>程式 FS</th><th>容許差</th><th>核對</th></tr>'+rows.map(r=>'<tr><td>'+r.name+'</td><td>'+fmt(r.expected)+'</td><td>'+fmt(r.actual,6)+'</td><td>'+r.tolerance+'</td><td><span class="pill '+(r.pass?'':'fail')+'">'+(r.pass?'通過':'未通過')+'</span></td></tr>').join('')+'</table>';}
$('verify-btn').onclick=()=>{verify();notify('已重新執行乾、濕坡核心核對');};
if($('video-btn'))$('video-btn').onclick=()=>{$('video-holder').style.padding='0';$('video-holder').innerHTML='<iframe title="使用者提供的邊坡穩定參考影片" src="https://www.youtube-nocookie.com/embed/WJplLLHTVXU" loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';};
let initial=example('basic');try{const seed=JSON.parse($('project-data').textContent);if(seed){C.validate(seed);initial=seed;}}catch{}fillModel(initial);page('analysis');verify();

async function svgPNG(svg){const blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob);try{const img=new Image();img.src=url;await new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(Error('剖面圖轉換失敗'));});const canvas=document.createElement('canvas');canvas.width=1800;canvas.height=1000;const ctx=canvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,1800,1000);ctx.drawImage(img,0,0,1800,1000);const png=await new Promise(ok=>canvas.toBlob(ok,'image/png'));if(!png)throw Error('剖面 PNG 產生失敗');return new Uint8Array(await png.arrayBuffer());}finally{URL.revokeObjectURL(url);}}
$('word-btn').onclick=async()=>{const button=$('word-btn');try{const out=ensureResult(),old=$('scenario').value,svgs={};button.disabled=true;button.textContent='產生詳細計算書…';try{for(const r of out.results){if(!r.best)continue;$('scenario').value=r.scenario;draw(out.model);const svg=$('plot').cloneNode(true);svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('viewBox','0 0 900 500');svgs[r.scenario]=svg.outerHTML;}}finally{$('scenario').value=old;draw(out.model);}const images={};for(const [key,svg]of Object.entries(svgs))images[key]=await svgPNG(svg);download(SlopeDocx.create(out,{images}),'邊坡穩定分析_詳細計算書.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');notify('已匯出真正的 Word .docx 詳細計算書');}catch(e){notify(e.message);}finally{button.disabled=false;button.textContent='匯出詳細 Word 計算書';}};
$('calc-json-btn').onclick=guarded(()=>download(JSON.stringify(ensureResult(),null,2),'邊坡穩定分析_完整計算資料.json','application/json;charset=utf-8'));
