/* RC Wall Workbench 1.0 — Taiwan mks units: cm, kgf, kgf/cm².
   Rectangular cast-in-place, normal-weight, nonprestressed solid wall.
   Compression polygon integration, linear strain compatibility, discrete bars. */
(function(root){'use strict';
const ES=2040000,DB={D10:[.953,.7133],D13:[1.27,1.267],D16:[1.59,1.986],D19:[1.91,2.865],D22:[2.22,3.871],D25:[2.54,5.067],D29:[2.87,6.469],D32:[3.22,8.143],D36:[3.58,10.07]};
const defaults={name:'SW-01 / 示範剪力牆',mode:'special',L:400,t:30,H:1200,hu:300,hn:1200,cover:4,env:'inside',fc:280,fy:4200,fyh:4200,vbar:'D16',sv:20,hbar:'D16',sh:20,layers:2,endbar:'D25',endn:8,endlen:60,Pu:180,Mi:180,Mo:0,Vi:40,Vo:0,VeH:40,Vuns:0,seismic:'linear',phiRule:'conservative',k:1,axialMethod:'section',walltype:'bearing',second:false,anchor:false,detail:false,material:false,lateral:false,boundary:false};
function bars(p){const v=DB[p.vbar],e=DB[p.endbar],h=DB[p.hbar],c=p.cover+h[0]+v[0]/2,ce=p.cover+h[0]+e[0]/2;let out=[];
const num=Math.ceil((p.L-2*c)/p.sv)+1;for(let i=0;i<num;i++)for(let j=0;j<p.layers;j++)out.push({x:-p.L/2+c+(p.L-2*c)*i/(num-1),y:p.layers===1?0:(j===0?-1:1)*(p.t/2-c),a:v[1],dia:v[0],kind:'web'});
if(p.endn){let xs=[],per=p.endn/2;for(let j=0;j<per;j++){let best=ce,bestgap=-1;for(let x=ce;x<=p.endlen-e[0]/2;x+=.1){let gap=Infinity;for(const b of out.filter(b=>b.y>=0))gap=Math.min(gap,Math.hypot((-p.L/2+x)-b.x,(p.t/2-ce)-b.y)-(e[0]+b.dia)/2);for(const q of xs)gap=Math.min(gap,Math.abs(x-q)-e[0]);if(gap>bestgap){bestgap=gap;best=x;}}xs.push(best);}for(const sign of [-1,1])for(const x of xs)for(const face of [-1,1])out.push({x:sign*(-p.L/2+x),y:face*(p.t/2-ce),a:e[1],dia:e[0],kind:'end'});}return out;}
function validate(p){let e=[];const pos=['L','t','H','hu','hn','cover','fc','fy','fyh','sv','sh','endlen'];for(const key of pos)if(!Number.isFinite(p[key])||p[key]<=0)e.push(key+' 必須為有限正數');for(const key of ['Pu','Mi','Mo','Vi','Vo','VeH','Vuns'])if(!Number.isFinite(p[key]))e.push(key+' 必須為有限數字');
if(!['general','special'].includes(p.mode))e.push('牆類型錯誤');if(!DB[p.vbar]||!DB[p.hbar]||!DB[p.endbar])e.push('鋼筋規格錯誤');if(![1,2].includes(p.layers))e.push('鋼筋層數必須為1或2');if(!Number.isInteger(p.endn)||p.endn<0||p.endn>80||p.endn%2)e.push('每端附加筋須為0–80的偶數');if(p.endlen>p.L/2)e.push('端部配筋區不可超過牆長的一半');if(p.fy>5600||p.fyh>5600)e.push('本版鋼筋強度限5600 kgf/cm²以下');if(p.fc>700)e.push('本版混凝土強度限700 kgf/cm²以下');if(p.H<p.hu)e.push('全牆高不得小於未支撐高度');if(p.hn<p.H)e.push('建築高度 hn 不得小於全牆高度');if(p.L/p.sv>800)e.push('分布筋数量過多，請檢查尺寸與間距');if(p.L<=p.t)e.push('牆長須大於牆厚');
if(DB[p.vbar]&&DB[p.hbar]&&DB[p.endbar]){const c=p.cover+DB[p.hbar][0]+Math.max(DB[p.vbar][0],p.endn?DB[p.endbar][0]:0)/2;if(2*c>=p.t||2*c>=p.L)e.push('保護層及鋼筋尺寸無法容納於斷面');if(p.endn&&p.endlen<2*c)e.push('端部配筋區不足容納附加筋');if(p.sv<DB[p.vbar][0]+2.5||p.sh<DB[p.hbar][0]+2.5)e.push('鋼筋淨距不足2.5 cm；須另檢核骨材尺寸');}return e;}
function polygon(L,t,nx,ny,threshold){let pts=[[-L/2,-t/2],[L/2,-t/2],[L/2,t/2],[-L/2,t/2]],res=[];for(let i=0;i<4;i++){let a=pts[i],b=pts[(i+1)%4],da=nx*a[0]+ny*a[1]-threshold,db=nx*b[0]+ny*b[1]-threshold;if(da>=0)res.push(a);if((da>=0)!=(db>=0)){let f=da/(da-db);res.push([a[0]+f*(b[0]-a[0]),a[1]+f*(b[1]-a[1])]);}}let area=0,sx=0,sy=0;for(let i=0;i<res.length;i++){const a=res[i],b=res[(i+1)%res.length],z=a[0]*b[1]-b[0]*a[1];area+=z;sx+=(a[0]+b[0])*z;sy+=(a[1]+b[1])*z;}area/=2;return {area:Math.abs(area),x:area?sx/(6*area):0,y:area?sy/(6*area):0};}
function section(p,bs,theta,c,design=true){let nx=Math.cos(theta),ny=Math.sin(theta),edge=Math.abs(nx)*p.L/2+Math.abs(ny)*p.t/2,beta=Math.max(.65,.85-.05*Math.max(0,p.fc-280)/70),a=beta*c,poly=polygon(p.L,p.t,nx,ny,edge-a),C=.85*p.fc*poly.area,P=C,Mx=C*poly.x,My=C*poly.y,et=0;for(const b of bs){const proj=nx*b.x+ny*b.y,eps=.003*(1-(edge-proj)/c),fs=Math.max(-p.fy,Math.min(p.fy,ES*eps)),subtract=proj>=edge-a?.85*p.fc:0,F=b.a*(fs-subtract);P+=F;Mx+=F*b.x;My+=F*b.y;et=Math.max(et,-eps);}const ey=p.fy/ES,phi=.65+.25*Math.max(0,Math.min(1,(et-ey)/.003));return {P:(design?phi:1)*P/1000,Mi:(design?phi:1)*Mx/100000,Mo:(design?phi:1)*My/100000,c,phi,et,beta,rawP:P/1000,rawMi:Mx/100000,rawMo:My/100000};}
function atP(p,bs,theta,P,design=true){let lo=Math.max(p.L,p.t)*1e-8,hi=Math.max(p.L,p.t)*1e7;if(section(p,bs,theta,lo,design).P>P||section(p,bs,theta,hi,design).P<P)return null;for(let i=0;i<75;i++){let mid=Math.sqrt(lo*hi),r=section(p,bs,theta,mid,design);if(r.P<P)lo=mid;else hi=mid;}return section(p,bs,theta,Math.sqrt(lo*hi),design);}
function biaxial(p,bs){let A=bs.reduce((a,b)=>a+b.a,0),pmax=.65*.8*(.85*p.fc*(p.L*p.t-A)+p.fy*A)/1000,pmin=-.9*p.fy*A/1000;if(p.Pu>pmax||p.Pu<pmin)return {ratio:Infinity,pmax,pmin,cap:null};const mi=Math.abs(p.Mi),mo=Math.abs(p.Mo);if(mi===0&&mo===0)return {ratio:p.Pu>=0?p.Pu/pmax:p.Pu/pmin,pmax,pmin,cap:atP(p,bs,0,p.Pu)};let theta=mi===0?Math.PI/2:mo===0?0:null;if(theta===null){let lo=0,hi=Math.PI/2;for(let i=0;i<36;i++){let mid=(lo+hi)/2,r=atP(p,bs,mid,p.Pu);if(!r)return {ratio:Infinity,pmax,pmin,cap:null};if(r.Mo*mi<r.Mi*mo)lo=mid;else hi=mid;}theta=(lo+hi)/2;}const r=atP(p,bs,theta,p.Pu);return {ratio:r?Math.hypot(mi,mo)/Math.hypot(r.Mi,r.Mo):Infinity,pmax,pmin,cap:r,theta};}
function curve(p,bs,theta){let out=[];for(let i=0;i<=130;i++){let c=Math.max(p.L,p.t)*Math.pow(10,-3+5*i/130),r=section(p,bs,theta,c);out.push(r);}return out;}
function calc(p){let errors=validate(p);if(errors.length)return {errors};const bs=bars(p),Ag=p.L*p.t,As=bs.reduce((a,b)=>a+b.a,0),rhoV=p.layers*DB[p.vbar][1]/(p.sv*p.t),rhoH=p.layers*DB[p.hbar][1]/(p.sh*p.t),r=p.H/p.L,alpha0=r<=1.5?.8:r>=2?.53:.8-.54*(r-1.5),alpha=p.Pu<0?Math.max(0,.53*(1+p.Pu*1000/(35*Ag))):alpha0,fvh=Math.min(p.fyh,p.mode==='special'?5600:4200),Vc=alpha*Math.sqrt(p.fc)*Ag/1000,Vs=rhoH*fvh*Ag/1000,Vn=Math.min(Vc+Vs,2.12*Math.sqrt(p.fc)*Ag/1000),omega=r<=1?1:r>=2?1.5:1+.5*(r-1),dynamic=r<2?1:.8+.0288*Math.cbrt(p.hn),Ve=p.mode==='special'?(p.seismic==='linear'?Math.abs(p.Vuns+omega*dynamic*p.VeH):Math.abs(p.Vi)):Math.abs(p.Vi),phiV=p.mode==='special'&&!(p.seismic==='linear'&&omega>=1.5)?(p.phiRule==='conservative'?.6:.75):.75;
const high=Ve>.5*phiV*Vc,reqH=p.mode==='special'?.0025:high?.0025:(DB[p.hbar][0]<=1.6&&p.fyh>=4200?.002:.0025),reqV=p.mode==='special'?Math.max(.0025,r<=2?rhoH:0):high?Math.min(Math.max(.0025,rhoH),Math.max(.0025,.0025+.5*(2.5-r)*(rhoH-.0025))):(DB[p.vbar][0]<=1.6&&p.fy>=4200?.0012:.0015),needShear=Ve>phiV*Vc,smaxV=Math.min(3*p.t,45,needShear?p.L/3:Infinity),smaxH=Math.min(3*p.t,45,needShear?p.L/5:Infinity),need2=p.t>25||(p.mode==='special'&&(r>=2||Ve>.53*Math.sqrt(p.fc)*Ag/1000)),c=p.cover+DB[p.hbar][0]+DB[p.vbar][0]/2,d=p.layers===1?p.t/2:p.t-c,AsFace=100/p.sv*DB[p.vbar][1]*(p.layers===1?1:1),rw=AsFace/(100*d),ls=Math.min(1,Math.sqrt(2/(1+d/25))),sf=Math.min(Math.sqrt(p.fc),26.5),ax=Math.min(p.Pu*1000/(6*Ag),.05*p.fc),VcOut=Math.max(0,Math.min((2.12*ls*Math.cbrt(rw)*sf+ax)*100*d,1.33*sf*100*d))/1000,outDemand=Math.abs(p.Vo)*100/p.L,pm=biaxial(p,bs),inCap=atP(p,bs,0,p.Pu),outCap=atP(p,bs,Math.PI/2,p.Pu),nom=atP(p,bs,0,p.Pu,false),stress=p.Pu*1000/Ag+6*Math.abs(p.Mi)*100000/(p.t*p.L*p.L)+6*Math.abs(p.Mo)*100000/(p.L*p.t*p.t),be=p.mode==='special'&&stress>.2*p.fc,beLength=nom?Math.max(nom.c-.1*p.L,nom.c/2):null,VuOriginal=p.mode==='special'&&p.seismic==='linear'?Math.abs(p.VeH+p.Vuns):Math.abs(p.Vi),beHeight=Math.max(p.L,VuOriginal>0?Math.abs(p.Mi)*100/(4*VuOriginal):p.Mi?Infinity:0),coverMin=p.env==='ground'?7.5:p.env==='marine'?10:p.env==='outside'?(Math.max(DB[p.vbar][0],DB[p.hbar][0],p.endn?DB[p.endbar][0]:0)>1.6?5:4):2;
const e=p.Pu>0?Math.abs(p.Mo)*100/p.Pu:Infinity,simpleFactor=1-Math.pow(p.k*p.hu/(32*p.t),2),simpleCap=.65*.55*p.fc*Ag*Math.max(0,simpleFactor)/1000,simpleOK=p.Pu>0&&e<=p.t/6&&simpleFactor>0,minT=p.walltype==='basement'?20:Math.max(10,Math.min(p.L,p.hu)/(p.walltype==='nonbearing'?30:25));
let checks=[];const add=(title,actual,limit,pass,ref)=>checks.push({title,actual,limit,state:pass?'pass':'fail',ref});const manual=(title,yes,ref)=>checks.push({title,actual:yes?'已由設計者確認':'尚未確認',limit:'需工程資料或細部圖說',state:yes?'confirmed':'pending',ref});
let minGap=Infinity;for(let i=0;i<bs.length;i++)for(let j=i+1;j<bs.length;j++)minGap=Math.min(minGap,Math.hypot(bs[i].x-bs[j].x,bs[i].y-bs[j].y)-(bs[i].dia+bs[j].dia)/2);add('縱筋分析位置淨距',fmt(minGap)+' cm','至少2.5 cm；另需核對骨材',minGap>=2.5-1e-8,'25.2');add('材料強度 f′c',p.fc+' kgf/cm²','≥ '+(p.mode==='special'?280:210),p.fc>=(p.mode==='special'?280:210),'19.2.1.1');add('軸力＋雙向彎矩',fmt(pm.ratio,3), '需求／容量 ≤ 1',pm.ratio<=1+1e-8,'11.5.2、18.7.5、22.2、22.4');add('面內剪力',fmt(Ve)+' tf',fmt(phiV*Vn)+' tf',Ve<=phiV*Vn+1e-8,p.mode==='special'?'18.7.3、18.7.4':'11.5.4');add('面外剪力（每米寬）',fmt(outDemand)+' tf/m',fmt(.75*VcOut)+' tf/m',outDemand<=.75*VcOut+1e-8,'11.5.5、22.5.5.1(c)');add('垂直分布筋比 ρℓ',fmt(rhoV*100,3)+'%',fmt(reqV*100,3)+'% 以上',rhoV+1e-10>=reqV,'11.6、18.7.2.1、18.7.4.3');add('水平分布筋比 ρt',fmt(rhoH*100,3)+'%',fmt(reqH*100,3)+'% 以上',rhoH+1e-10>=reqH,'11.6、18.7.2.1');add('垂直筋間距',p.sv+' cm',fmt(smaxV)+' cm 以下',p.sv<=smaxV,'11.7.2.1、18.7.2.1');add('水平筋間距',p.sh+' cm',fmt(smaxH)+' cm 以下',p.sh<=smaxH,'11.7.3.1、18.7.2.1');add('鋼筋網層數',p.layers+' 層',need2?'至少 2 層':'至少 1 層',!need2||p.layers===2,'11.7.2.3、18.7.2.2');add('保護層',p.cover+' cm',coverMin+' cm 以上',p.cover>=coverMin,'20.5.1.3.1');
if(p.mode==='general'&&p.axialMethod==='simple'){add('簡易法適用條件',Number.isFinite(e)?'e = '+fmt(e)+' cm':'Pu 必須為壓力','e ≤ t/6 = '+fmt(p.t/6)+' cm',simpleOK,'11.5.3.1');add('簡易法軸力',p.Pu+' tf',fmt(simpleCap)+' tf',simpleOK&&p.Pu<=simpleCap,'11.5.3');add('簡易法最小牆厚',p.t+' cm',fmt(minT)+' cm 以上',p.t>=minT,'11.3.1.1');}
if(p.walltype==='nonbearing')add('非承重牆最小厚度',p.t+' cm',fmt(minT)+' cm 以上',p.t>=minT,'11.3.1.1');
if(p.mode==='special'){if(p.Mo!==0)checks.push({title:'雙向彎曲邊界構材分析',actual:'面外彎矩與面內彎矩共同作用',limit:'本版c與水平延伸為面內參考，須另分析受壓區',state:'pending',ref:'18.7.6'});const ends=[-1,1].map(sign=>bs.filter(b=>sign*b.x>=p.L/2-.15*p.L-1e-8).reduce((a,b)=>a+b.a,0)/(.15*p.L*p.t)),endReq=1.6*Math.sqrt(p.fc)/p.fy;add('兩端 0.15ℓw 縱筋比（單一臨界斷面）',fmt(Math.min(...ends)*100,3)+'%',fmt(endReq*100,3)+'% 以上',Math.min(...ends)>=endReq,'18.7.2.4');if(r>=2&&p.L/p.t<=6)checks.push({title:'牆墩適用條款',actual:'hw/ℓw ≥ 2 且 ℓw/t ≤ 6',limit:'須按18.7.8另行牆墩／柱設計',state:'pending',ref:'18.7.8'});checks.push({title:'特殊邊界構材判定（應力法）',actual:fmt(stress)+' kgf/cm²',limit:'觸發門檻 '+fmt(.2*p.fc)+' kgf/cm²；'+(be?'須設置':'本組合未觸發'),state:'info',ref:'18.7.6.3'});if(be){add('邊界區水平延伸',p.endlen+' cm',beLength===null?'無法求解':fmt(beLength)+' cm 以上',beLength!==null&&p.endlen>=beLength,'18.7.6.4(a)');add('邊界區厚度',p.t+' cm',fmt(Math.max(p.hu/16,r>=2&&nom&&nom.c/p.L>=.375?30:0))+' cm 以上',p.t>=Math.max(p.hu/16,r>=2&&nom&&nom.c/p.L>=.375?30:0),'18.7.6.4(b)(c)');manual('邊界圍束、繫筋與伸展範圍',p.boundary,'18.7.6.4、18.7.6.5');}else manual('牆端橫向筋與水平筋終止細部',p.boundary,'18.7.6.5');manual('耐震鋼筋材質、續接與端部延伸',p.material,'18.2.6、18.7.2.3、18.7.2.4(b)(c)');if(phiV===.75&&omega<1.5)manual('φV = 0.75 的彎剪容量條件',p.phiRule==='verified','21.2.4.1');}
manual('所有載重組合與二階／長細效應',p.second,'5、6、11.4');manual('受壓縱筋側向支撐',p.lateral,'11.7.4、22.4.2.4');manual('鋼筋錨定、搭接及基礎接合',p.anchor,'11.2.4、11.7.1、25.4、25.5');manual('淨距、耐久性與服務性',p.detail,'19.3、24、25.2');const failed=checks.filter(x=>x.state==='fail').length,pending=checks.filter(x=>x.state==='pending').length;return {errors:[],bs,As,Ag,r,rhoV,rhoH,reqV,reqH,Vc,Vs,Vn,alpha,omega,dynamic,Ve,phiV,d,rw,ls,VcOut,outDemand,pm,inCap,outCap,nom,stress,be,beLength,beHeight,coverMin,simpleCap,e,checks,failed,pending,curves:[curve(p,bs,0),curve(p,bs,Math.PI/2)]};}
function fmt(x,n=2){return Number.isFinite(x)?x.toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'—';}
const API={DB,defaults,ES,bars,validate,polygon,section,atP,biaxial,calc,fmt,curve};if(typeof module!=='undefined')module.exports=API;root.RCWall=API;
})(typeof globalThis!=='undefined'?globalThis:this);
