(function(){'use strict';
const VERSION='1.1', CHECKED='2026-10-10', DRAFT='RCWall-TW.draft.v1';
const css=document.createElement('style');css.id='v11-style';css.textContent=`
.workflowbar{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 16px}.workflowbar button{font-size:14px}.paramhelp{min-width:44px;min-height:44px;padding:3px 9px;border:0;background:#edf5fa;color:#155686;float:right;margin:-7px 0 0 5px}.field label{min-height:36px}.field:focus-within{border-radius:8px;outline:2px solid #c7dde9;outline-offset:6px}.filterbar{display:flex;gap:8px;flex-wrap:wrap;padding:12px 16px;border-bottom:1px solid var(--line)}.filterbar button{font-size:13px}.filterbar .active{background:var(--navy);color:white}.draftbar{background:#eff7fb;border:1px solid #c7dde9;padding:12px 16px;border-radius:8px;margin-bottom:16px;display:flex;gap:10px;flex-wrap:wrap;align-items:center}.draftbar span{flex:1}.draft-status{font-size:12px;color:var(--muted)}dialog{border:1px solid var(--line);border-radius:14px;color:var(--ink);padding:0;width:min(640px,calc(100% - 24px));max-height:85dvh;box-shadow:0 20px 80px #112a4333}dialog::backdrop{background:#112a4377}.dialoghead{padding:16px 20px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line)}.dialoghead h2{margin:0;font-size:19px}.dialogbody{padding:20px}.dialogbody dl{display:grid;grid-template-columns:90px minmax(0,1fr);gap:12px;margin:0}.dialogbody dt{color:var(--muted)}.dialogbody dd{margin:0;overflow-wrap:anywhere}.paramsearch{margin:12px 0 16px}.paramcards{display:grid;grid-template-columns:1fr 1fr;gap:12px}.paramcard{padding:16px;border:1px solid var(--line);border-radius:9px;background:#fff}.paramcard h3{margin:0 0 8px}.paramcard p{font-size:14px;margin:5px 0}.paramcard small{color:var(--muted)}.normgrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.normcard{padding:20px;border:1px solid var(--line);border-radius:10px;background:#f8fafc}.normcard h3{margin-top:0}.normcard .badge{margin-bottom:10px}.videobox{background:#112a43;border-radius:10px;overflow:hidden;margin:14px 0}.videobox video{width:100%;display:block;aspect-ratio:16/9}.chapters{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.chapters button{text-align:left;justify-content:flex-start;font-size:14px}.video-status{font-size:14px}.tutorial-transcript p{font-size:15px}.normgrid p{font-size:14px}.view .tablewrap{overscroll-behavior-x:contain}@media(max-width:700px){.paramcards,.normgrid{grid-template-columns:1fr}.chapters{grid-template-columns:1fr 1fr}.dialogbody dl{grid-template-columns:75px minmax(0,1fr)}.nav button{min-height:44px}.workflowbar>*{flex:1}.draftbar{font-size:14px}}@media print{#tutorial,#norms,#parameters,.workflowbar,.draftbar,.filterbar,.paramhelp,dialog{display:none!important}}`;
document.head.appendChild(css);
document.querySelector('.version').textContent='TW-RCW / '+VERSION;
document.querySelector('.sidebottom p').innerHTML='cm · tf · tf·m · kgf/cm²<br>v'+VERSION+' / 2026.10.10<br>離線運算・台灣女聲教學';
document.querySelector('.titleline p').textContent='一般牆與特殊剪力牆・規範查核 2026.10.10・參數說明與影音教學';
const workspace=document.querySelector('.workspace');
document.querySelector('.nav').insertAdjacentHTML('beforeend','<button data-view="parameters"><span>05</span>參數字典</button><button data-view="norms"><span>06</span>規範中心</button><button data-view="tutorial"><span>07</span>影音教學</button>');
const pitfalls={
name:'請標記牆編號、樓層、組合及正／負地震方向，以利追溯。',mode:'不能只因牆有承受地震力就任意指定一般牆；依整體耐震系統分類。',L:'有開孔、翼牆或不規則牆形不在此矩形實心模型範圍。',t:'輸入結構厚度，不能把裝修層算進容量。',H:'本版 hwcs=hw，假設牆底為單一臨界斷面；不是未支撐高度。',hu:'依面外實際支承位置，不一定等於樓高。',hn:'本工具採 cm，例如12 m填1200；不能直接填12。',cover:'量至最外層水平筋外緣，不是至垂直筋中心。',fc:'1 MPa≈10.197162 kgf/cm²；設計指定強度與試體平均值不同。',fy:'需核對耐震鋼筋材質與規範許用強度，不能以拉伸極限強度替代。',fyh:'程式剪力採用上限不代表輸入材料可免除材質／耐震限制。',vbar:'筋號為CNS公稱號數；不要把D16直接當作精確直徑1.6cm。',hbar:'水平筋放在垂直筋外侧；這影響面外有效深度。',sv:'每面分布筋的中心間距，不是兩面交錯後的一半間距。',sh:'沿牆高度之中心間距；不是沿牆長方向。',layers:'雙層是兩面各一層；若選單層，分析位置在厚度中央。',endbar:'此模型左右端及兩面採對稱配筋；非對稱配置須另建模型。',endn:'範例8支代表每端兩面共8支，全牆附加16支；不是全牆8支。',endlen:'只是附加筋分析配置區，不能取代圍束箍筋、繫筋與伸展高度设计。',Pu:'1 tf=1000 kgf=9.80665 kN；從分析軟體取得的壓拉符號需先轉換。',Mi:'對照牆局部軸與截面受壓方向；不能直接假設M2一定是面內。',Mo:'全牆 tf·m；若分析提供每米值，先乘牆長(m)，不可直接貼入。',Vi:'特殊牆線性模式此欄停用；直接模式填已完成放大的Ve。',Vo:'全牆 tf；若來源為每米值，先乘牆長(m)，程式會再換算tf/m。',seismic:'直接Ve模式需另有完整地震剪力放大計算，程式不再重複放大。',VeH:'是該組合已含相應係數的水平E分項剪力，避免重複乘載重係數。',Vuns:'保持與VuEh相同局部方向符號，正、負地震組合各自檢查；不能分別取绝对值相加。',phiRule:'已核對選項須有21.2.4.1彎剪容量比較依據，不能為使結果通過而切換。',axialMethod:'簡易法須在所有高度與所有組合滿足偏心條件；本程式只驗本次斷面。',k:'由實際側移與轉動束制判定；不能任意選較小值增加容量。',walltype:'地下室外牆另有面外土水壓、服務性與接合設計需求。',env:'保護層門檻僅為初步檢核；特殊曝露與耐久性仍需設計者確認。'};
const paramById=new Map(defs.map(d=>[d[0],d]));
function exampleValue(id){const v=R.defaults[id];return options[id]?(options[id].find(([x])=>String(x)===String(v))?.[1]||v):v;}
const dlg=document.createElement('dialog');dlg.id='parameter-dialog';dlg.setAttribute('aria-labelledby','parameter-title');dlg.innerHTML='<div class="dialoghead"><h2 id="parameter-title">參數說明</h2><button id="parameter-close" aria-label="關閉參數說明">關閉</button></div><div class="dialogbody" id="parameter-detail"></div>';document.body.appendChild(dlg);
$('parameter-close').onclick=()=>dlg.close();dlg.addEventListener('click',e=>{if(e.target===dlg&&e.clientX<dlg.getBoundingClientRect().left)dlg.close()});
function explain(id){const d=paramById.get(id);if(!d)return;const [,label,unit,,help,source]=d;$('parameter-title').textContent=label;$('parameter-detail').innerHTML=`<dl><dt>定義</dt><dd>${esc(help)}</dd><dt>單位</dt><dd>${esc(unit||'選項／文字')}</dd><dt>資料來源</dt><dd>${esc(source)}</dd><dt>範例輸入</dt><dd>${esc(exampleValue(id))}${unit?' '+esc(unit):''}</dd><dt>填寫提醒</dt><dd>${esc(pitfalls[id]||'請依實際結構設計資料填寫。')}</dd></dl>`;dlg.showModal();}
for(const [id,label]of defs){const lab=document.querySelector('label[for="f-'+id+'"]');const b=document.createElement('button');b.type='button';b.className='paramhelp';b.textContent='?';b.setAttribute('aria-label',label+' 定義與來源');b.dataset.parameter=id;lab.insertAdjacentElement('beforebegin',b);b.onclick=()=>explain(id);}
workspace.insertAdjacentHTML('beforeend',`<section id="parameters" class="view guide" hidden><div class="panel"><div class="panelhead"><h2>輸入參數字典</h2><span class="badge">定義・來源・範例</span></div><div class="panelbody"><label for="parameter-search">搜尋參數名稱、符號、定義或來源</label><input id="parameter-search" class="paramsearch" type="search" placeholder="例如：面外、Pu、保護層、ETABS"><p class="helptext" id="parameter-count" aria-live="polite"></p><div id="parameter-cards" class="paramcards"></div><h3>設計者確認項目</h3><p>以下是人工完成紀錄，不是程式自動驗算。請先完成相應分析／圖說，再勾選；勾選不改變容量。</p><div id="confirmation-guide"></div><h3>單位換算</h3><div class="formula">1 tf = 1000 kgf = 9.80665 kN<br>1 tf·m = 100000 kgf·cm = 9.80665 kN·m<br>1 MPa ≈ 10.197162 kgf/cm²<br>每米內力 × 牆長(m) = 全牆內力</div></div></div></section>
<section id="norms" class="view guide" hidden><div class="panel"><div class="panelhead"><h2>規範中心</h2><span class="badge">查核 ${CHECKED}</span></div><div class="panelbody"><div class="notice blue">本工具以台灣規範為依據。版本依官方公告查核；線上頁面不會自行修改設計公式。正式工程須指定適用版本並核對設計時的法規。</div><div class="normgrid"><article class="normcard"><span class="badge">斷面與細部檢核</span><h3>建築物混凝土結構設計規範</h3><p>112.8.10修正全文，113.1.1施行；包含113.2.19勘誤。查核當日官方沿革未列更新修正版。</p><p>一般牆：第11章；特殊結構牆：18.7節；材料與保護層：19、20章；φ：21.2；斷面與剪力：22章。</p><a href="https://www.nlma.gov.tw/ch/legislation/regsearch/6874" target="_blank" rel="noopener">官方公告與版本沿革</a> · <a href="https://www.nlma.gov.tw/uploads/files/011d9249cac7d6c5547786aa348e352a.pdf" target="_blank" rel="noopener">官方全文（含勘誤）</a></article><article class="normcard"><span class="badge">整體分析與需求內力</span><h3>建築物耐震設計規範及解說</h3><p>官方沿革列至113.3.1部分規定修正，即日生效。</p><p>用於上游耐震系統分類、地震力、分析方法與結構系統要求。本工具接收分析後因數化內力；不從基地震區或反應譜自行產生地震荷載。</p><a href="https://www.nlma.gov.tw/ch/legislation/regsearch/175" target="_blank" rel="noopener">官方公告與各章全文</a></article></div><h3>與本工具的計算關係</h3><ol><li>依耐震規範建立整體結構模型與正／負地震組合，取得共同發生的Pu、M、V。</li><li>依混凝土規範第5、6章核對載重組合、強度需求及二階效應。</li><li>特殊牆線性分析：18.7.3.1、表18.7.3.2計算Ve = |Vuns + ΩvωvVuEh|；本版hwcs=hw、hn採cm。</li><li>檢核第11章與18.7的適用強度、最少配筋、間距及邊界條件，逐項表保留條文編號。</li><li>邊界圍束、錨定、服務性及全部組合由設計者另完成。預鑄、既有建築補強、開孔與連接梁須用其專用條款。</li></ol><h3>版本與驗證</h3><p>v1.1新增參數字典、草稿恢復、結果篩選、規範中心及台灣女性旁白影片。這次核對官方式11.5.4.3、11.5.4.4與表18.7.3.2，既有計算式維持適用版本。完整測試紀錄見<a href="https://github.com/jerry597640-droid/engineering-calculator-hub/blob/main/rc-wall/VALIDATION.md" target="_blank" rel="noopener">驗證紀錄</a>。</p></div></div></section>
<section id="tutorial" class="view guide" hidden><div class="panel"><div class="panelhead"><h2>操作影片・台灣女性旁白</h2><span class="badge">可離線播放</span></div><div class="panelbody"><p>由特殊剪力牆範例帶你完成尺寸、配筋、內力、結果判讀與匯出。旁白採Microsoft HsiaoChen（zh-TW，台灣華語女性合成語音）。影片不自動播放。</p><button id="load-tutorial" class="primary">載入教學影片</button> <span class="video-status" id="video-status" role="status">按下後才載入影片。</span><div class="videobox"><video id="tutorial-video" controls playsinline preload="none" aria-label="RC牆操作教學影片"></video></div><div class="chapters" id="tutorial-chapters"></div><p class="helptext">可全螢幕播放，使用播放器調整音量與速度；手機橫向觀看文字更清楚。下載離線版會連同影片保存。</p><details class="tutorial-transcript"><summary>查看完整文字逐字稿</summary><div class="inner" id="tutorial-transcript"></div></details><div class="examplebar"><button data-demo-load="special">載入影片中的範例</button><button data-view="parameters">查看所有參數</button></div></div></div></section>`);
const confirmExplain=[['所有組合與二階效應','整體分析報告、柱牆長細比／彎矩放大或二階分析；本次輸入只代表一組合。'],['受壓縱筋側向支撐','牆配筋詳圖與箍筋／繫筋配置，核對受壓筋是否有有效側向支撐。'],['錨定、搭接與基礎接合','依錨定與搭接計算書、基礎圖及施工接縫詳圖。'],['淨距、耐久性、裂縫與撓度','骨材最大粒徑、配筋淨距、曝露環境及服務性分析。'],['牆端／邊界圍束細部','完整邊界尺寸、箍筋量與間距、繫筋及延伸範圍。'],['耐震鋼筋材質、續接與端部延伸','材質證明、機械續接資格與鋼筋延伸詳圖；特殊牆另核對。']];
$('confirmation-guide').innerHTML=confirmExplain.map(([a,b])=>`<p><strong>${a}</strong><br>${b}</p>`).join('');
function dictionary(){const q=$('parameter-search').value.trim().toLowerCase(),items=defs.filter(d=>d.join(' ').toLowerCase().includes(q)||pitfalls[d[0]].toLowerCase().includes(q));$('parameter-count').textContent='顯示 '+items.length+' / '+defs.length+' 個輸入參數';$('parameter-cards').innerHTML=items.map(([id,l,u,g,h,src])=>`<article class="paramcard"><h3>${esc(l)} <small>${esc(u)}</small></h3><p>${esc(h)}</p><p><strong>來源：</strong>${esc(src)}</p><p><strong>範例：</strong>${esc(exampleValue(id))}${u?' '+esc(u):''}</p><p><strong>提醒：</strong>${esc(pitfalls[id])}</p><button data-explain="${id}">詳細說明</button></article>`).join('');}
$('parameter-search').oninput=dictionary;$('parameter-cards').onclick=e=>{const b=e.target.closest('[data-explain]');if(b)explain(b.dataset.explain)};dictionary();
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
document.querySelector('[data-demo-load]').onclick=()=>example('special');
document.querySelector('#design .layout').insertAdjacentHTML('beforebegin','<div class="draftbar" id="draft-restore" hidden><span id="draft-message"></span><button id="restore-draft">恢復草稿</button><button id="dismiss-draft">略過</button></div><div class="workflowbar"><button id="go-parameters">參數說明</button><button id="go-tutorial">觀看教學</button><button id="expand-input">展開所有輸入</button><button id="collapse-input">收合輸入群組</button><span id="draft-status" class="draft-status" role="status"></span></div>');
$('go-parameters').onclick=()=>view('parameters');$('go-tutorial').onclick=()=>view('tutorial');$('expand-input').onclick=()=>document.querySelectorAll('.inputpanel details').forEach(d=>d.open=true);$('collapse-input').onclick=()=>document.querySelectorAll('.inputpanel details').forEach(d=>d.open=false);
let saved=null, draftTimer, filter='all',restoring=false;
try{saved=JSON.parse(localStorage.getItem(DRAFT)||'null');if(saved?.inputs&&!R.validate({...R.defaults,...saved.inputs}).length){$('draft-restore').hidden=false;$('draft-message').textContent='找到本機草稿：'+saved.inputs.name+'（'+new Date(saved.at).toLocaleString('zh-TW')+'）';}}catch{}
$('restore-draft').onclick=()=>{if(!saved)return;p={...R.defaults,...saved.inputs};restoring=true;sync();restoring=false;$('draft-restore').hidden=true;toast('已恢復本機草稿。');};$('dismiss-draft').onclick=()=>{$('draft-restore').hidden=true;};
function applyFilter(){const table=$('results').querySelector('table');if(!table)return;for(const row of table.tBodies[0].rows){const badge=row.querySelector('.badge');row.hidden=filter!=='all'&&!badge?.classList.contains(filter);}document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));}
const prevRender=render;render=function(){prevRender();if(result.errors.length){$('draft-status').textContent='輸入有誤，草稿暫停更新';return;}const head=Array.from($('results').querySelectorAll('.panelhead')).find(e=>e.textContent.includes('檢核'));if(head)head.insertAdjacentHTML('afterend','<div class="filterbar" role="group" aria-label="篩選檢核狀態"><button data-filter="all">全部</button><button data-filter="fail">未通過</button><button data-filter="pending">待確認</button><button data-filter="pass">數值通過</button></div>');applyFilter();clearTimeout(draftTimer);if(!saved||$('draft-restore').hidden||restoring){const draft=structuredClone(p);draftTimer=setTimeout(()=>{try{localStorage.setItem(DRAFT,JSON.stringify({version:1,at:new Date().toISOString(),inputs:draft}));$('draft-status').textContent='草稿已存於此裝置';}catch{$('draft-status').textContent='此瀏覽器無法保存草稿，請儲存案例';}},650);}};
$('results').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;applyFilter();}});
// Tutorial bytes are published as a text asset because the connected repository API accepts UTF-8 files.
// Offline export includes this exact payload; runtime creates a local MP4 Blob URL.
let mediaLoading=null,videoUrl=null;
async function loadMedia(){if(window.RCWallTutorial)return window.RCWallTutorial;if(!mediaLoading)mediaLoading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.id='tutorial-payload';s.src='tutorial-media.js';s.onload=()=>window.RCWallTutorial?resolve(window.RCWallTutorial):reject(Error('影片資料不完整'));s.onerror=()=>{s.remove();mediaLoading=null;reject(Error('影片載入失敗，請連網重試或使用完整離線版。'));};document.body.appendChild(s);});return mediaLoading;}
async function prepareVideo(){try{$('video-status').textContent='正在載入影片…';const media=await loadMedia();if(!videoUrl){const bin=atob(media.video),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);videoUrl=URL.createObjectURL(new Blob([bytes],{type:'video/mp4'}));$('tutorial-video').src=videoUrl;}$('video-status').textContent='已載入・'+Math.round(media.duration)+'秒・台灣女性旁白';$('load-tutorial').textContent='影片已載入';$('tutorial-chapters').innerHTML=media.chapters.map((c,i)=>`<button data-seek="${c.start}">${String(i+1).padStart(2,'0')} ${esc(c.title)}</button>`).join('');$('tutorial-transcript').innerHTML=media.chapters.map(c=>`<h3>${esc(c.title)}</h3><p>${esc(c.text)}</p>`).join('');return true;}catch(e){$('video-status').textContent=e.message;return false;}}
$('load-tutorial').onclick=prepareVideo;$('tutorial-chapters').onclick=async e=>{const b=e.target.closest('[data-seek]');if(b&&await prepareVideo()){$('tutorial-video').currentTime=Number(b.dataset.seek);try{await $('tutorial-video').play();}catch{}}};
$('offline').onclick=async()=>{if(R.validate(p).length)return toast('請先修正輸入。');const button=$('offline');button.disabled=true;try{const media=await loadMedia();const doc=document.documentElement.cloneNode(true);const payload=doc.querySelector('#tutorial-payload')||document.createElement('script');payload.id='tutorial-payload';payload.removeAttribute('src');payload.textContent='window.RCWallTutorial='+JSON.stringify(media)+';';if(!payload.parentNode)doc.querySelector('body').appendChild(payload);const seed=doc.querySelector('#word-seed');seed.textContent=JSON.stringify({state:structuredClone(p)}).replace(/</g,'\\u003c');doc.querySelector('body').insertBefore(seed,doc.querySelector('script'));for(const id of ['results','calcprocess','mainfields','geometry','rebar','loads','seismic','other','confirm','inputguide'])doc.querySelector('#'+id).innerHTML='';doc.querySelector('#toast').hidden=true;doc.querySelectorAll('.view').forEach(e=>e.hidden=e.id!=='design');doc.querySelectorAll('.nav [data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view==='design'));doc.querySelectorAll('#parameter-dialog,#parameters,#norms,#tutorial,.workflowbar,.draftbar,#v11-style').forEach(e=>e.remove());doc.querySelectorAll('.nav [data-view="parameters"],.nav [data-view="norms"],.nav [data-view="tutorial"]').forEach(e=>e.remove());download('<!doctype html>\n'+doc.outerHTML,'RC牆設計檢核_離線版_v1.1.html','text/html;charset=utf-8');toast('已下載包含影片的離線版。');}catch(e){toast(e.message);}finally{button.disabled=false;}};
// Rebuilt input components will receive their help buttons when the exported file opens.
render();
})();
