(function(){'use strict';
const source='臺灣112年混凝土結構設計規範／113年勘誤；https://www.nlma.gov.tw/filesys/file/EMMA/c1130219-1.pdf',n=x=>typeof x==='number'?(Number.isFinite(x)?String(x):x===Infinity?'∞':x===-Infinity?'−∞':'無效'):String(x),cell=x=>esc(n(x));
function traceReport(s,r){const v=r.traceScalars,step=(title,formula,values,condition='')=>({title,formula,substitution:values.map(([k,x])=>k+' = '+n(x)).join('\n'),condition,source});
const steps=[
step('實際配筋數與截面','web count = ceil((L−2c)/sv)+1；每層等距；端部以0.1cm候選最大化最小淨距',[['L',s.L],['t',s.t],['c',v.c],['layers',s.layers],['web ceil前區間數',r.trace.barLayout.rawIntervals],['web 每層筋數',r.trace.barLayout.num],['端部偏移ce',r.trace.barLayout.ce],['bars',r.bs.length],['Ag=L×t',r.Ag],['Ast=ΣAb',r.As],['minGap',v.minGap]]),
step('縱橫筋比','ρv=layers Abv/(sv t)；ρh=layers Abh/(sh t)',[['Abv',R.DB[s.vbar][1]],['Abh',R.DB[s.hbar][1]],['sv',s.sv],['sh',s.sh],['t',s.t],['ρv',r.rhoV],['ρh',r.rhoH]]),
step('剪力係數及材料上限','r=H/L；α0: r≤1.5→0.8，r≥2→0.53，其他0.8−0.54(r−1.5)；Pu<0另採max(0,0.53(1+Pu×1000/(35Ag)))；fyh使用min(fyh,模式上限)',[['H',s.H],['L',s.L],['r',r.r],['Pu',s.Pu],['α0',v.alpha0],['α',r.alpha],['fyh',s.fyh],['fyh採用',v.fvh]]),
step('面內剪力容量與控制','Vc=α√fc Ag/1000；Vs=ρh fyh採用 Ag/1000；Vn=min(Vc+Vs,2.12√fc Ag/1000)',[['α',r.alpha],['fc',s.fc],['Ag',r.Ag],['ρh',r.rhoH],['fyh採用',v.fvh],['Vc',r.Vc],['Vs',r.Vs],['Vn',r.Vn],['φV',r.phiV],['φVn',r.phiV*r.Vn]]),
step('地震放大與需求','ω: r≤1→1，r≥2→1.5，其他1+0.5(r−1)；dynamic: r<2→1，其他0.8+0.0288 cbrt(hn)；linear: Ve=|Vuns+ω dynamic VeH|；direct/general: |Vi|',[['mode',s.mode],['seismic',s.seismic],['r',r.r],['hn cm',s.hn],['ω',r.omega],['dynamic',r.dynamic],['Vuns',s.Vuns],['VeH',s.VeH],['Vi',s.Vi],['Ve',r.Ve],['φV',r.phiV]],'φV分支保持原引擎；conservative/verified與ω≥1.5條件按當次輸入執行。'),
step('最小筋比、間距與層數','reqH=special?0.0025:high?0.0025:(dbh≤1.6且fyh≥4200?0.002:0.0025)；reqV=special?max(0.0025,r≤2?ρh:0):high?min(max(0.0025,ρh),max(0.0025,0.0025+0.5(2.5−r)(ρh−0.0025))):(dbv≤1.6且fy≥4200?0.0012:0.0015)；need2=t>25或special且(r≥2或Ve>0.53√fcAg/1000)；high = Ve>0.5 φV Vc；needShear=Ve>φV Vc；sv,max=min(3t,45,需要剪力筋時L/3)；sh,max=min(3t,45,需要剪力筋時L/5)',[['high',v.high],['needShear',v.needShear],['reqV',r.reqV],['reqH',r.reqH],['smaxV',v.smaxV],['smaxH',v.smaxH],['need2',v.need2]],'一般／特殊、徑≤1.6cm、fy≥4200及r≤2等分支採實際結果；逐項判定表完整列出。'),
step('面外剪力有效深度與材料','d: 單層t/2；雙層t−c；AsFace=100/sv Abv；ρw=AsFace/(100d)；λs=min(1,√(2/(1+d/25)))；sf=min(√fc,26.5)；ax=min(Pu×1000/(6Ag),0.05fc)',[['c',v.c],['d',r.d],['AsFace',v.AsFace],['ρw',r.rw],['λs',r.ls],['sf',v.sf],['ax',v.ax]]),
step('面外容量上下限與需求','VcOut=max(0,min((2.12 λs cbrt(ρw) sf+ax)100d,1.33 sf 100d))/1000；需求=|Vo|100/L',[['VcOut tf/m',r.VcOut],['φVcOut',.75*r.VcOut],['Vo',s.Vo],['L',s.L],['需求',r.outDemand]]),
step('軸力上下限與雙向容量','Pmax=0.65×0.8×(0.85fc(Ag−Ast)+fyAst)/1000；Pmin=−0.9fyAst/1000；容量角及c採實際求解', [['Ag',r.Ag],['Ast',r.As],['fc',s.fc],['fy',s.fy],['Pu',s.Pu],['Pmax',r.pm.pmax],['Pmin',r.pm.pmin],['θ',r.pm.theta],['D/C',r.pm.ratio]],'軸力超出限值時保持Infinity與失敗；不虛構容量。'),
step('壓力區多邊形與逐筋積分','β1=max(0.65,0.85−0.05 max(0,fc−280)/70)；a=β1c；C=0.85fc×polygon.area；εs=0.003(1−(edge−projection)/c)；fs=clamp(Esεs,−fy,+fy)；受壓塊內扣0.85fc；F=Ab(fs−扣除)；ΣF、ΣFx、ΣFy；φ=0.65+0.25clamp((εt−fy/Es)/0.003,0,1)', [['Es',R.ES],['求解組數',r.trace.solvers.length],['角迭代數',r.trace.angles.length]],'各實際75次二分表、最終逐筋表、36次角度二分及262個曲線樣本隨附；非另一次模型。'),
step('邊界應力及範圍','σmax=Pu1000/Ag+6|Mi|100000/(tL²)+6|Mo|100000/(Lt²)；觸發σmax>0.2fc；length=max(c−0.1L,c/2)；height=max(L,|Mi|100/(4VuOriginal))',[['σmax',r.stress],['0.2fc',.2*s.fc],['觸發',r.be],['nominal c',r.nom?.c],['邊界長度',r.beLength],['VuOriginal',v.VuOriginal],['邊界高度',r.beHeight],['保護層最小值',r.coverMin]],'特殊牆按原適用條件執行；人工確認與雙向邊界限制仍為待確認。'),
step('簡化軸力與厚度','e=|Mo|100/Pu；factor=1−(k hu/(32t))²；capacity=0.65×0.55fc Ag×max(0,factor)/1000',[['e cm',r.e],['k',s.k],['hu',s.hu],['t',s.t],['factor',v.simpleFactor],['capacity',r.simpleCap],['simpleOK',v.simpleOK],['minT',v.minT]],'僅一般牆選簡化法才用該判定；未選用時僅列原引擎參考值。'),
step('取整與最後判定','計算使用原完整精度；顯示採既有小數格式。幾何筋數採ceil，實際筋座標均見附表。',[['數值失敗項數',r.failed],['人工待確認項數',r.pending]],'D/C≤1+1e−8、剪力≤容量+1e−8、筋比容許1e−10與淨距1e−8等既有容差不變。人工確認不是本程式計算通過。')];
const tables=[{title:'實際筋徑來源列欄',headers:['列','db cm','Ab cm²'],rows:[...new Set([s.vbar,s.hbar,s.endbar])].map(k=>[k,...R.DB[k]]),source:'本工具DB；欄0=db、欄1=Ab；未內插或修正。'}, {title:'逐項結果與條件',headers:['檢核','實際','限制','狀態','來源'],rows:r.checks.map(c=>[c.title,c.actual,c.limit,c.state,c.ref]),source}, {title:'實際配筋座標',headers:['編號','種類','x cm','y cm','Ab cm²','db cm'],rows:r.bs.map((b,i)=>[i+1,b.kind,b.x,b.y,b.a,b.dia]),source:'bars(p)實際返回座標；壁中央為原點。'}];
if(r.trace.endRatios)tables.push({title:'兩端0.15L區域實際筋比',headers:['項目','值'],rows:[['左端筋比',r.trace.endRatios.ends[0]],['右端筋比',r.trace.endRatios.ends[1]],['需求1.6√fc/fy',r.trace.endRatios.endReq]],source:'原18.7.2.4檢核；逐筋座標篩選±x≥L/2−0.15L−1e−8。'});
if(r.trace.barSearch.length)tables.push({title:'端部實際0.1cm位置搜尋',headers:['次','起點','終點','間隔','候選數','選用位置','最小淨距'],rows:r.trace.barSearch.map(x=>Object.values(x)),source:'bars函數選用最大最小淨距；左右端與兩面鏡射，未更改搜尋。'});
if(r.trace.angles.length)tables.push({title:'實際雙向角度二分',headers:['次','lo','hi','mid','Mi','Mo','Mo×需求Mi','Mi×需求Mo','分支'],rows:r.trace.angles.map(x=>Object.values(x))});
r.trace.solvers.forEach((q,i)=>{tables.push({title:'容量求解 '+(i+1)+'：θ='+n(q.theta)+'，Pu='+n(q.targetP)+'，design='+q.design,headers:['參數','值'],rows:[['初始lo',q.initialLo],['初始hi',q.initialHi],['lo端P',q.lowP],['hi端P',q.highP??'未執行'],['停止',q.reason]],source});if(q.iterations.length)tables.push({title:'求解 '+(i+1)+' 實際75次迭代',headers:['次','lo','hi','mid','P','φ','Mi','Mo','分支'],rows:q.iterations.map(x=>Object.values(x))});if(q.final){const a=q.final.integration;tables.push({title:'求解 '+(i+1)+' 最終混凝土與強度',headers:['項目','值'],rows:Object.entries({...q.final,integration:undefined,...a,steel:undefined,poly:undefined,'polygon.area':a.poly.area,'polygon.x':a.poly.x,'polygon.y':a.poly.y}).filter(([k,v])=>v!==undefined),source});tables.push({title:'求解 '+(i+1)+' 逐筋實際積分',headers:['種類','x','y','Ab','projection','εs','fs','扣除','F','ΣP kgf','ΣMx kgfcm','ΣMy kgfcm'],rows:a.steel.map(b=>[b.kind,b.x,b.y,b.a,b.proj,b.eps,b.fs,b.subtract,b.F,b.P,b.Mx,b.My]),source})}});
r.curves.forEach((rows,i)=>tables.push({title:'實際P-M曲線樣本 '+(i?'面外':'面內'),headers:['序','c','φP','φMi','φMo','φ','εt','β1'],rows:rows.map((x,j)=>[j,x.c,x.P,x.Mi,x.Mo,x.phi,x.et,x.beta]),source:'curve：i=0…130；c=max(L,t)×10^(−3+5i/130)，同section引擎。'}));
return {steps,tables};}
function traceHTML(r){if(r.errors.length)return '';const data=traceReport(p,r);return '<h2>本次完整實算與中間值</h2>'+data.steps.map(s=>'<h3>'+esc(s.title)+'</h3><pre class="trace-pre">'+esc(s.formula+'\n'+s.substitution+'\n'+s.condition)+'</pre>').join('')+data.tables.map(t=>'<details><summary>'+esc(t.title)+'</summary><p>'+esc(t.source||source)+'</p><div class="tablewrap"><table><thead><tr>'+t.headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+t.rows.map(row=>'<tr>'+row.map(x=>'<td>'+cell(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div></details>').join('');}
const oldProcess=processHTML;processHTML=r=>oldProcess(r)+traceHTML(r);
function capture(){for(const [id]of defs){const e=$('f-'+id),raw=typeof R.defaults[id]==='number'?(e.value.trim()===''?NaN:Number(e.value)):e.value;if(!Object.is(raw,p[id]))throw Error('輸入已變更，請重新計算。')}for(const [id]of bools)if($('f-'+id).checked!==p[id])throw Error('確認條件已變更。');const s=structuredClone(p),r=R.calc(s);if(r.errors.length)throw Error('輸入無效，無法匯出。');const data=traceReport(s,r),svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1120 600"><svg x="0" y="0" width="560" height="600">'+schematic(r).replace('<svg ','<svg x="0" y="0" width="560" height="600" ')+'</svg><svg x="560" y="0" width="560" height="600">'+pmplot(r).replace('<svg ','<svg x="0" y="0" width="560" height="600" ')+'</svg></svg>';return {title:(s.name||'RC牆')+' 詳細計算書',summary:'數值失敗 '+r.failed+' 項；人工待確認 '+r.pending+' 項。',inputs:defs.map(([id,label,unit])=>({label,value:s[id],unit})).concat(bools.map(([id,label])=>({label,value:s[id]?'設計者已確認':'尚未確認',unit:''}))),...data,conclusions:[r.failed?'數值檢核未通過':r.pending?'數值通過，仍需設計者確認':'本次檢核完成','數值失敗 '+r.failed+' 項；人工待確認 '+r.pending+' 項。','本工具原適用範圍、第二階、錨定、邊界細節及所有載重組合仍需原設計核對。'],diagram:{svg,width:560,height:300,caption:'當次實際配筋及容量曲線；壁中央座標；示意不按比例。'},valid:true};}
let busy=false;async function word(){try{if(busy)return;const report=capture();busy=true;refresh();await CalculationDocx.download(report,'RC牆_詳細計算.docx');toast('已匯出可編輯Word。')}catch(e){toast(e.message)}finally{busy=false;refresh()}}
let b=$('word');if(!b){b=document.createElement('button');b.id='word';b.textContent='匯出可編輯 Word';document.querySelector('header .actions').appendChild(b)}b.onclick=word;
function refresh(){b.disabled=busy||!!R.validate(p).length}const oldRender=render;render=function(){oldRender();refresh()};
let seed=$('word-seed');if(!seed){seed=document.createElement('script');seed.type='application/json';seed.id='word-seed';seed.textContent='{}';document.body.appendChild(seed)}try{const saved=JSON.parse(seed.textContent);if(saved.state){p={...R.defaults,...saved.state};sync()}}catch{}
$('offline').onclick=()=>{if(R.validate(p).length)return toast('請先修正輸入。');const doc=document.documentElement.cloneNode(true);doc.querySelector('#word-seed').textContent=JSON.stringify({state:structuredClone(p)}).replace(/</g,'\\u003c');doc.querySelector('body').insertBefore(doc.querySelector('#word-seed'),doc.querySelector('script'));for(const id of ['results','calcprocess','mainfields','geometry','rebar','loads','seismic','other','confirm','inputguide'])doc.querySelector('#'+id).innerHTML='';doc.querySelector('#toast').hidden=true;download('<!doctype html>\n'+doc.outerHTML,'RC牆_離線版.html','text/html;charset=utf-8')};
const style=document.createElement('style');style.textContent='.trace-pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 system-ui;margin:12px 0;background:#f3f6fa;padding:12px}.tablewrap{max-width:100%}details{margin:10px 0}summary{cursor:pointer;min-height:44px;padding:8px;overflow-wrap:anywhere}.workspace,.panel,.view{min-width:0}header .actions{flex-wrap:wrap}@media print{details{display:block}}';document.head.appendChild(style);window.WallWord={capture,traceReport};render();
})();
