(function(){'use strict';
const E=CorbelEngine,$=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),f=(v,n=3)=>Number.isFinite(v)?Number(v).toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'無有效解';
const defs=[
 ['project','案件名稱','','material','text','填入工程名稱，供報告識別。','專案基本資料'],['member','構件／組合名稱','','material','text','例如 C1 托架／1.2D＋1.6L；每個控制組合分別檢核。','結構分析構件編號與載重組合'],
 ['kind','構件型式','','material',{corbel:'RC 托架',bracket:'RC 梁托'},'兩型式均採16.5；梁托指外伸短懸臂，不含梁端凹槽。','結構平立面與接合詳圖'],
 ['concrete','混凝土種類','','material',{normal:'常重混凝土',sand:'常重砂輕質（λ＝0.85）',all:'全輕質（λ＝0.75）'},'按骨材及混凝土種類選擇，輕質上限使用16.5.2.5。','混凝土配比與材料證明'],
 ['fc','混凝土強度 f′c','kgf/cm²','material','number','175～700；施工縫兩側不同強度時取較低值。','結構設計圖、試驗報告'],['fy','鋼筋強度 fy','kgf/cm²','material','number','主筋及箍筋同級，2800～4200；剪力摩擦不得超過4200。','結構配筋圖、鋼筋材料證明'],
 ['interface','支承面／施工縫','','material',{mono:'一體澆置（μ＝1.4λ）',rough:'粗糙施工縫（μ＝1.0λ）',smooth:'未粗糙施工縫（μ＝0.6λ）'},'粗糙施工縫須清潔無浮漿，粗糙度約0.6 cm；與支承墊摩擦不同。','施工縫詳圖與現場處理記錄'],
 ['bw','托架寬度 bw','cm','geometry','number','垂直於立面的有效寬度，不是伸出長度。','結構平面／剖面圖'],['h','支承面全深 h','cm','geometry','number','柱／牆交界處的全深，由頂面量至底面。','結構立面剖面圖'],['htip','外端全深','cm','geometry','number','托架最外端全深；本版底面為線性斜面。','托架剖面詳圖'],['L','伸出總長 L','cm','geometry','number','從支承交界面至托架外端。','接合部平面與立面圖'],['av','剪跨 aᵥ','cm','geometry','number','支承交界面至承壓面合力中心；本版承壓面均勻受壓。','梁端反力位置、支承板配置'],['cover','混凝土保護層','cm','geometry','number','量至最外層鋼筋外表面；d＝h－cover－箍筋直徑－主筋直徑/2。','結構詳圖；依20.5及暴露條件確認'],['agg','粗骨材最大粒徑','cm','geometry','number','用於鋼筋淨距檢查：至少4/3骨材粒徑。','混凝土配比單'],['bl','承壓面長度','cm','geometry','number','沿托架伸出方向的實際有效接觸長度。','梁端支承板／墊材有效接觸尺寸'],['bb','承壓面寬度','cm','geometry','number','垂直立面方向的實際有效接觸寬度，須≤bw。','支承板及墊材配置詳圖'],['xAnchor','端部錨定內側位置 x','cm','geometry','number','由支承面量至主筋直線端／橫向錨定筋內側；承壓外緣不得超過此位置。','水平環或橫向錨定筋施工詳圖'],
 ['Vu','因數化豎向反力 Vu','tf','loads','number','向下為正，須含自重；輸入同一控制組合的總反力。','結構分析模型、支承反力報表'],['Nu','因數化向外拉力 N','tf','loads','number','不得填服務載重；支承墊模式取此值與束制力估值較大者。','同一控制組合的水平反力、束制分析'],['nMode','束制力計算方式','','loads',{direct:'直接輸入 Nuc',pad:'支承墊：0.2 × 1.6 × Rs',tested:'試驗低摩擦支承墊'},'無支承墊須直接輸入結構束制分析所得的因數化Nuc。','16.2.2.3與16.2.2.4、支承構造'],['Rs','持續未因數化反力 Rs','tf','loads','number','靜載重與其他永久載重的反力；不等於Vu。','服務載重持續反力分析、設備永久載重'],['muPad','墊材試驗摩擦係數','','loads','number','僅適用可靠試驗低摩擦墊材，考慮溫度、齡期、暴露；本版上限min(0.2,μpad)。','墊材性能試驗與製造商資料'],
 ['mainBar','主筋號數','','rebar',Object.fromEntries(Object.keys(E.BARS).map(k=>[k,k])),'採台灣常用標稱鋼筋尺寸與面積。','CNS鋼筋規格、結構配筋圖'],['mainN','單排主筋數量','支','rebar','number','同一排且穿越剪力面，2～100整數；需有完整錨定。','托架頂部主拉力筋施工圖'],['hoopBar','水平閉合箍號數','','rebar',Object.fromEntries(Object.keys(E.BARS).map(k=>[k,k])),'與主筋平行的閉合水平箍；非一般梁垂直箍。','托架水平箍配置詳圖'],['hoopN','水平閉合箍數量','道','rebar','number','每道計2肢，均勻分布於主筋下方2d/3；1～100整數。','水平閉合箍配置剖面圖']
];
const detailDefs=[['front','前端主筋錨定已確認','水平環、合格焊接橫筋或其他可發展 fy 的錨定；§16.5.6.3。'],['support','柱／牆內鋼筋發展與母構材已確認','主筋及水平箍須在剪力面兩側充分錨定，並另核母構材；§16.5.6.4、22.9.5。'],['bearing','被支承構材、墊材、鋼板及連接已確認','本工具僅計算托架混凝土承壓；支承附件與水平力傳遞須另核。'],['durability','保護層、暴露條件與箍筋構造已確認','核對§20.5、25.2及16.5.6；圖示等間距箍須落實於施工圖。']];
let p={...E.DEFAULT},result,currentView='overview',toastTimer;
const KEY='rc-corbel.tw112.v1';try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&saved.version===1&&saved.inputs&&typeof saved.inputs==='object')p={...p,...saved.inputs};}catch{}
for(const [k,label,unit,group,type,help,source]of defs){const wide=typeof type==='object'&&['interface','nMode'].includes(k)||type==='text';$('fields-'+group).insertAdjacentHTML('beforeend',`<div class="field ${wide?'wide':''}" id="field-${k}"><label for="${k}">${esc(label)}</label>${typeof type==='object'?`<select id="${k}" title="${esc(help+' 來源：'+source)}">${Object.entries(type).map(([v,t])=>`<option value="${v}">${esc(t)}</option>`).join('')}</select>`:`<div class="input-unit"><input id="${k}" type="${type}" ${type==='number'?'step="any" inputmode="decimal"':'maxlength="160"'} title="${esc(help+' 來源：'+source)}" aria-describedby="help-${k}">${unit?`<span>${esc(unit)}</span>`:''}</div>`}<small id="help-${k}">${esc(help)}</small></div>`);}
$('detail-checks').innerHTML=detailDefs.map(([k,t,s])=>`<label class="detail-item"><input id="${k}" type="checkbox"><span>${esc(t)}<small>${esc(s)}</small></span></label>`).join('');
$('manual-fields').innerHTML=defs.map(([k,t,u,g,ty,h,s])=>`<tr><td><b>${esc(t)}</b>${u?`<br>${esc(u)}`:''}</td><td>${esc(h)}</td><td>${esc(s)}</td></tr>`).join('');
function fill(){for(const [k]of defs)$(k).value=p[k];for(const [k]of detailDefs)$(k).checked=p[k]===true;}
function read(){for(const [k,t,u,g,ty]of defs)p[k]=ty==='number'?($(k).value.trim()===''?NaN:Number($(k).value)):$(k).value;for(const [k]of detailDefs)p[k]=$(k).checked;}
function notify(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function download(text,name,type='text/html;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function resetDetails(){for(const [k]of detailDefs){p[k]=false;$(k).checked=false;}}
function switchView(v){currentView=v;for(const el of document.querySelectorAll('.view'))el.hidden=el.id!=='view-'+v;for(const b of document.querySelectorAll('nav button'))b.classList.toggle('active',b.dataset.view===v);window.scrollTo({top:0,behavior:'auto'});}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function diagram(r){const q=r.p,main=E.BARS[q.mainBar],hoop=E.BARS[q.hoopBar],s=Math.min(260/q.h,295/q.L),x=135,y=112,w=q.L*s,h=q.h*s,ht=q.htip*s,ybar=y+(q.h-r.d)*s,px=x+q.av*s,plen=q.bl*s,hoopEnd=Math.min(w-17,q.xAnchor*s),bcount=Math.min(q.hoopN,24);const dims=(x1,y1,x2,y2,label,tx,ty)=>`<path d="M${x1} ${y1}L${x2} ${y2}" stroke="#728da2" stroke-width="1" marker-start="url(#dim)" marker-end="url(#dim)"/><text x="${tx}" y="${ty}" fill="#5b7287" font-size="11" text-anchor="middle">${esc(label)}</text>`;
const sx=528,sy=142,cs=Math.min(145/q.bw,200/q.h),sw=q.bw*cs,sh=q.h*cs;let bars='';for(let i=0;i<Math.min(q.mainN,32);i++){const bx=sx+(q.cover+hoop.d+main.d/2+(q.bw-2*(q.cover+hoop.d)-main.d)*i/(q.mainN-1))*cs;bars+=`<circle cx="${bx}" cy="${sy+(q.h-r.d)*cs}" r="${Math.max(2,main.d*cs/2)}" fill="#b8792f"/>`;}
const fullSvg=`<svg viewBox="0 0 720 500" role="img" aria-label="托架立面與支承面斷面：豎向及向外水平作用力、主筋、水平閉合箍、剪跨、有效深度"><defs><pattern id="grid" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M22 0H0V22" fill="none" stroke="#e5edf5" stroke-width=".5"/></pattern><marker id="arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0L8 4L0 8z" fill="#b74644"/></marker><marker id="dim" viewBox="0 0 6 6" refX="3" refY="3" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M6 0L0 3L6 6" fill="none" stroke="#728da2"/></marker></defs><rect width="720" height="500" fill="url(#grid)"/><text x="25" y="28" font-size="12" fill="#405b71">01 / 托架立面</text><text x="511" y="28" font-size="12" fill="#405b71">02 / 支承面斷面</text><path d="M52 67H${x}V${y}H${x+w}V${y+ht}L${x} ${y+h}V${y+h+43}H52Z" fill="#e5eff5" stroke="#5286a1" stroke-width="1.6"/><path d="M${x} ${y-20}V${y+h+25}" stroke="#789bad" stroke-dasharray="4 5"/><path d="M77 ${ybar}H${x+q.xAnchor*s}" fill="none" stroke="#c58435" stroke-width="4"/><path d="M${x+q.xAnchor*s} ${ybar-7}v15" stroke="#c58435" stroke-width="3"/>${Array.from({length:bcount},(_,i)=>{const depth=q.h-r.d+(i+1)/bcount*2*r.d/3,hy=y+depth*s,maxEnd=q.h===q.htip?q.L-q.cover:Math.max(0,q.L*(q.h-depth-q.cover)/(q.h-q.htip));return `<path d="M83 ${hy}H${x+Math.min(hoopEnd,maxEnd*s)}" stroke="#c58435" stroke-width="1.7"/>`;}).join('')}<rect x="${px-plen/2}" y="${y-8}" width="${plen}" height="8" fill="#536e83"/><path d="M${px} 47V${y-14}" stroke="#b74644" stroke-width="2" marker-end="url(#arrow)"/><text x="${px+12}" y="54" font-size="12" fill="#b74644">Vu ${f(r.Vu/1000,1)} tf</text><path d="M${px} 88H${Math.min(470,px+75)}" stroke="#b74644" stroke-width="2" marker-end="url(#arrow)"/><text x="${Math.min(444,px+48)}" y="78" font-size="11" fill="#b74644" text-anchor="middle">Nuc ${f(r.Nuc/1000,1)}</text>${dims(x,y-15,px,y-15,'av '+f(q.av,1),x+q.av*s/2,y-22)}${dims(x+w+20,ybar,x+w+20,y+h,'d '+f(r.d,2),x+w+30,y+h/2)}${dims(x,y+h+53,x+w,y+h+53,'L '+f(q.L,1),x+w/2,y+h+72)}<text x="69" y="${ybar+16}" font-size="10" fill="#976126">${q.mainN}-${esc(q.mainBar)}</text><text x="165" y="${ybar+2*r.d/3*s+17}" font-size="10" fill="#976126">Ah：${q.hoopN} 道 ${esc(q.hoopBar)} / 2d/3</text><rect x="${sx}" y="${sy}" width="${sw}" height="${sh}" fill="#e5eff5" stroke="#5286a1" stroke-width="1.5"/>${bars}${Array.from({length:Math.min(q.hoopN,24)},(_,i)=>{const hy=sy+(q.h-r.d+(i+1)/Math.min(q.hoopN,24)*2*r.d/3)*cs;return `<circle cx="${sx+(q.cover+hoop.d/2)*cs}" cy="${hy}" r="2.5" fill="#c58435"/><circle cx="${sx+sw-(q.cover+hoop.d/2)*cs}" cy="${hy}" r="2.5" fill="#c58435"/>`;}).join('')}${dims(sx,sy+sh+19,sx+sw,sy+sh+19,'bw '+f(q.bw,1),sx+sw/2,sy+sh+39)}<text x="510" y="${sy+sh+68}" font-size="10" fill="#647a8c">主筋淨距 ${f(r.clear,2)} cm</text><text x="25" y="485" font-size="10" fill="#798ea0">單位 cm · 示意配置，端部及支承內錨定依施工詳圖確認</text></svg>`;
return `<div class="diagram-wide">${fullSvg}</div><div class="diagram-mobile">${fullSvg.replace('viewBox="0 0 720 500"','viewBox="15 12 470 470"')}<div class="mobile-diagram-label">02 / 支承面斷面</div>${fullSvg.replace('viewBox="0 0 720 500"','viewBox="500 123 190 310"')}</div>`;
}
function trace(r){const q=r.p;const blocks=[
 ['01　幾何、有效深度與適用範圍',`d = h − cover − d箍 − d主/2\n  = ${f(q.h)} − ${f(q.cover)} − ${f(E.BARS[q.hoopBar].d)} − ${f(E.BARS[q.mainBar].d)}/2 = ${f(r.d)} cm\naᵥ/d = ${f(q.av)} / ${f(r.d)} = ${f(q.av/r.d)}（上限 1）\nNuc/Vu = ${f(r.Nuc/1000)} / ${f(q.Vu)} = ${f(r.Nuc/r.Vu)}（上限 1）\n承壓外緣 x = aᵥ + l承壓/2 = ${f(q.av+q.bl/2)} cm\nh外緣 = h + (h端 − h) × x/L = ${f(r.hOuter)} cm ≥ 0.5d = ${f(r.d/2)} cm\n端部錨定內側 x = ${f(q.xAnchor)} cm ≥ 承壓外緣 ${f(q.av+q.bl/2)} cm`,'16.5.1.1、16.5.2.1～3。超出範圍時結果不作合格依據。'],
 ['02　設計作用力與束制拉力',`Vu = ${f(q.Vu)} × 1000 = ${f(r.Vu,1)} kgf\n${q.nMode==='direct'?`Nuc = N直接 = ${f(q.Nu)} tf`:q.nMode==='pad'?`N束制 = 0.2 × 1.6 × Rs = 0.32 × ${f(q.Rs)} = ${f(.32*q.Rs)} tf\nNuc = max(N直接, N束制) = ${f(r.Nuc/1000)} tf`:`N束制 = min(0.2, μpad) × 1.6 × Rs\n      = min(0.2, ${f(q.muPad)}) × 1.6 × ${f(q.Rs)} tf\nNuc = max(N直接, N束制) = ${f(r.Nuc/1000)} tf`}\nMu = Vu × aᵥ + Nuc × (h − d)\n   = ${f(r.Vu,1)} × ${f(q.av)} + ${f(r.Nuc,1)} × ${f(q.h-r.d)}\n   = ${f(r.Mu,1)} kgf·cm = ${f(r.Mu/100000)} tf·m`,'16.2.2.3～4、R16.5.3.3。Rs為持續未因數化反力；若外部另有水平拉力，此處保守取較大值，須用控制組合核對。'],
 ['03　混凝土剪力尺寸限制',`φ = 0.75；Ac（本版）= bw × d = ${f(q.bw)} × ${f(r.d)} = ${f(q.bw*r.d)} cm²\n${q.concrete==='normal'?'常重：Vn,dim = min[0.2f′c, (33.6+0.08f′c), 112] × bw × d':'輕質：Vn,dim = min[(0.2−0.07aᵥ/d)f′c, (56−20aᵥ/d)] × bw × d'}\n各剪應力上限 = [${r.capTerms.map(v=>f(v)).join(', ')}] kgf/cm²\nφVn,dim = ${f(E.PHI*r.vDim/1000)} tf ≥ Vu = ${f(q.Vu)} tf\n施工縫另依22.9.4.4限制：φVn,interface = ${f(.75*r.vInterface/1000)} tf`,'16.5.2.4～5、22.9.4.4。採臺灣kgf/cm²公式常數，不混用SI單位。'],
 ['04　Af、An 與 Avf 分別計算',`φ = 0.75（托架撓曲、拉力與剪力）；fy = ${f(q.fy,0)} kgf/cm²\nAn = Nuc/(φfy) = ${f(r.Nuc,1)}/(0.75 × ${f(q.fy,0)}) = ${f(r.An)} cm²\nλ = ${f(r.lambda,2)}；μ = ${f(r.mu)}（施工縫與混凝土種類決定）\nAvf = Vu/(φμfy) = ${f(r.Vu,1)}/(0.75 × ${f(r.mu)} × ${f(q.fy,0)}) = ${f(r.Avf)} cm²\nMn = Af fy(d − a/2)，a = Af fy/(0.85f′c bw)\n由 φMn = Mu 反算：\nAf = 2Mu / {φfy[d + √(d² − 2Mu/(φ × 0.85f′c bw))]}\n   = 2×${f(r.Mu,1)} / {0.75×${f(q.fy,0)}[${f(r.d)} + √(${f(r.d)}² − 2×${f(r.Mu,1)}/(0.75×0.85×${f(q.fc,0)}×${f(q.bw)}))]}\nAf = ${f(r.Af)} cm²；降伏假設：${r.reqYield?'成立':'不成立／無有效降伏解，需調整斷面'}\nβ₁ = ${f(r.beta)}；降伏界線 As,bal = ${f(r.AsBal)} cm²`,'16.5.4.3～5、22.2。直接拉力鋼筋先保留，再作撓曲強度檢核。'],
 ['05　主拉力筋 Asc 的控制值',`撓曲＋拉力：Af + An = ${f(r.Af)} + ${f(r.An)} = ${f(r.Af+r.An)} cm²\n剪力摩擦＋拉力：(2/3)Avf + An = ${f(2*r.Avf/3+r.An)} cm²\n最少筋量：0.04(f′c/fy)bw d = ${f(r.Amin)} cm²\nAsc,req = max(以上三者) = ${f(r.AscReq)} cm²\nAsc,實配 = n主 × A主 = ${q.mainN} × ${f(E.BARS[q.mainBar].a,4)} = ${f(r.Asc)} cm²`,'16.5.5.1。需求超出單筋降伏反算適用範圍時，本版列NG。'],
 ['06　閉合水平箍 Ah 與合計剪力摩擦',`Ah,req = 0.5(Asc,實配 − An)\n       = 0.5(${f(r.Asc)} − ${f(r.An)}) = ${f(r.AhReq)} cm²\nAh,實配 = n箍 × 2 × A箍 = ${q.hoopN} × 2 × ${f(E.BARS[q.hoopBar].a,4)} = ${f(r.Ah)} cm²\nAvf,有效 = max(0, Asc + Ah − An) = ${f(Math.max(0,r.Asc+r.Ah-r.An))} cm²\nVn,steel = μfyAvf,有效 = ${f(r.mu)} × ${f(q.fy,0)} × ${f(Math.max(0,r.Asc+r.Ah-r.An))} / 1000 = ${f(r.vSteel/1000)} tf\nφVn = 0.75 × min(Vn,steel, Vn,dim, Vn,interface)\n     = ${f(r.vCap/1000)} tf\n箍筋分布深度 = 2d/3 = ${f(2*r.d/3)} cm\n本版各道位置 = 主筋中心 + i × (2d/3)/n箍，i=1～n箍\n層間中心距 = ${f(r.pitch)} cm；最小層間淨距 = min(箍間距,主筋到首道箍淨距) = ${f(r.layerClear)} cm\n需求層間淨距 = max(2.5, 4骨材粒徑/3) = ${f(r.layerMin)} cm`,'16.5.5.2、16.5.6.6、22.9。Ah依實配Asc計算；增加主筋後須重新檢核Ah。'],
 ['07　實配撓曲強度：應變相容',`As,flex = max(0, Asc − An) = ${f(Math.max(0,r.Asc-r.An))} cm²\nεcu = 0.003；Es = 2.04×10⁶ kgf/cm²；β₁ = ${f(r.beta)}\nC = 0.85f′c bw β₁c；T = As,flex fs\nεs = 0.003(d − c)/c；fs = min(fy, Es εs)\n求 C = T：c = ${f(r.flex.c)} cm，a = β₁c = ${f(r.flex.a)} cm\nεs = ${f(r.flex.eps,6)}；fs = ${f(r.flex.fs,1)} kgf/cm²\nMn = As,flex fs(d − a/2)\n    = ${f(Math.max(0,r.Asc-r.An))} × ${f(r.flex.fs,1)} × (${f(r.d)} − ${f(r.flex.a)}/2) = ${f(r.flex.Mn,1)} kgf·cm\nφMn = 0.75 × ${f(r.flex.Mn,1)} / 100000 = ${f(.75*r.flex.Mn/100000)} tf·m ≥ Mu = ${f(r.Mu/100000)} tf·m`,'22.2、16.5.4.5。本版以支承面矩形單筋斷面計算，鋼筋未降伏時不直接代入fy。'],
 ['08　局部承壓與鋼筋淨距',`A₁ = l承壓 × b承壓 = ${f(q.bl)} × ${f(q.bb)} = ${f(q.bl*q.bb)} cm²\n承壓增益 k = 1（未採A₂/A₁增益）；φb = 0.65\nBn = 0.85f′c A₁\nφbBn = 0.65 × 0.85 × ${f(q.fc,0)} × ${f(q.bl*q.bb)} /1000 = ${f(r.bCap/1000)} tf\n主筋單排淨距 = [bw − 2(cover + d箍) − n主d主]/(n主 − 1)\n             = ${f(r.clear)} cm\n需求淨距 = max(2.5 cm, d主, 4d骨材/3) = ${f(r.clearMin)} cm`,'22.8、表21.2.1(d)、25.2.1。另核被支承構材、墊材與鋼板之較小承壓能力。']];
const grouped=[[0,1,2,3],[],[4],[8],[5],[6,7,11],[8],[9,10]];return blocks.map(([t,e,n],i)=>`<section class="card calc-section"><h3>${esc(t)}</h3><pre class="equation">${esc(e)}</pre><p>${esc(n)}</p>${grouped[i].length?`<p><b>本步檢核：${grouped[i].map(j=>esc(r.checks[j].name)+' '+(r.checks[j].ok?'OK':'NG')).join('；')}</b></p>`:''}</section>`).join('');}
function checkHTML(r){return r.checks.map(c=>`<div class="check"><div><b>${esc(c.name)}</b><small>§${esc(c.ref)}${c.note?' · '+esc(c.note):''}</small></div><div class="values">${f(c.demand)} / ${f(c.capacity)} ${esc(c.unit)}<small>需求／${c.name.startsWith('剪跨')||c.name.startsWith('水平拉力')?'上限':'提供或能力'}</small></div><span class="badge ${c.ok?'':'ng'}">${c.ok?'OK':'NG'}</span></div>`).join('');}
function update(){read();result=E.calculate(p);$('field-Rs').hidden=p.nMode==='direct';$('field-muPad').hidden=p.nMode!=='tested';for(const [k]of defs)$(k).removeAttribute('aria-invalid');const status=document.querySelector('.status-bar');status.classList.remove('ok','fail');
if(!result.valid){$('message').hidden=false;$('message').textContent='請修正輸入：\n'+result.errors.join('\n');$('overall').textContent='輸入資料待修正';status.classList.add('fail');for(const [k]of defs)if(result.errors.some(t=>t.startsWith(k+' ')))$(k).setAttribute('aria-invalid','true');for(const k of ['stat-d','stat-m','stat-as','stat-ah'])$(k).textContent='—';$('checks').innerHTML='';$('diagram').innerHTML='';$('calculation').innerHTML='<div class="card calc-section">輸入資料待修正，未產生計算結果。</div>';$('geometry-summary').textContent='';$('check-count').textContent='';$('restraint-note').textContent='輸入資料待修正。';}
else{const r=result;status.classList.add(r.passed?'ok':'fail');$('overall').textContent=r.status;$('status-note').textContent=`${p.member} · φ＝0.75 · cm / tf`;$('message').hidden=r.applicable;$('message').textContent=r.applicable?'':'本組參數超出 §16.5 適用範圍，以下為試算值，不作合格依據。請採第二十三章壓拉桿法等適用分析。';$('stat-d').innerHTML=f(r.d,2)+'<em>cm</em>';$('stat-m').innerHTML=f(r.Mu/100000,2)+'<em>tf·m</em>';$('stat-as').innerHTML=f(r.AscReq,2)+'<em>cm²</em>';$('stat-ah').innerHTML=f(r.AhReq,2)+'<em>cm²</em>';$('stat-as-note').textContent='實配 '+f(r.Asc,2)+' cm²';$('diagram').innerHTML=diagram(r);$('checks').innerHTML=checkHTML(r);$('check-count').textContent=r.checks.filter(c=>c.ok).length+' / '+r.checks.length+' 項通過';$('geometry-summary').innerHTML=`<span>aᵥ/d <b>${f(p.av/r.d)}</b></span><span>μ <b>${f(r.mu,2)}</b></span><span>外緣深度 <b>${f(r.hOuter,2)} cm</b></span><span>2d/3 <b>${f(2*r.d/3,2)} cm</b></span>`;$('calculation').innerHTML=trace(r);$('restraint-note').textContent=`採用 Nuc＝${f(r.Nuc/1000)} tf；${p.nMode==='direct'?'由使用者輸入的因數化拉力。':p.nMode==='pad'?'依持續未因數化反力估計束制力，與直接輸入力取大值。':'試驗低摩擦支承墊取 min(0.2, μpad)；試驗須涵蓋實際使用條件。'}`;try{localStorage.setItem(KEY,JSON.stringify({version:1,inputs:p}));}catch{if(!update.warned){notify('本機儲存受限，請使用「儲存案件」備份。');update.warned=true;}}}
for(const b of [$('export-report'),$('print-report'),$('save-project')])b.disabled=!result.valid;}
function example(){p={...E.DEFAULT};fill();update();switchView('overview');notify('已載入示範參數；細部確認需依實際圖說完成。');}
$('input-form').addEventListener('input',()=>{resetDetails();update();});$('input-form').addEventListener('change',()=>{resetDetails();update();});$('input-form').addEventListener('submit',e=>e.preventDefault());for(const [k]of detailDefs)$(k).onchange=update;
$('load-example').onclick=example;$('example-manual').onclick=example;
$('save-project').onclick=()=>{if(!result.valid)return;download(JSON.stringify({tool:'RC-Corbel-TW112',version:1,exportedAt:new Date().toISOString(),inputs:p},null,2),'RC托架_案件.json','application/json');notify('案件已下載，包含目前輸入與確認狀態。');};
$('open-project').onclick=()=>$('file-input').click();$('file-input').onchange=async ev=>{try{const file=ev.target.files[0];if(!file)return;if(file.size>1024*1024)throw Error('案件檔須小於1MB');const data=JSON.parse(await file.text());if(data.tool!=='RC-Corbel-TW112'||data.version!==1||!data.inputs||typeof data.inputs!=='object')throw Error('不支援的案件格式');const allowed=new Set([...defs.map(x=>x[0]),...detailDefs.map(x=>x[0])]);const next={...E.DEFAULT};for(const [k,v]of Object.entries(data.inputs)){if(!allowed.has(k))continue;if(typeof v!==typeof E.DEFAULT[k])throw Error('欄位型態錯誤：'+k);next[k]=v;}const check=E.calculate(next);if(!check.valid)throw Error(check.errors.join('；'));p=next;fill();update();notify('案件已開啟');}catch(e){notify('開啟失敗：'+e.message);}ev.target.value='';};
function report(){if(!result.valid)return '';const r=result;const inputRows=defs.filter(([k])=>!(k==='Rs'&&p.nMode==='direct')&&!(k==='muPad'&&p.nMode!=='tested')).map(([k,t,u,g,ty])=>`<tr><td>${esc(t)}</td><td>${esc(typeof ty==='object'?ty[p[k]]:p[k])} ${esc(u)}</td></tr>`).join('');return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><title>RC托架計算書</title><style>body{font:14px/1.8 system-ui,sans-serif;color:#24384b;max-width:920px;margin:35px auto;padding:0 20px}h1{font-size:25px}h2{font-size:20px;margin-top:30px}h3{font-size:16px}.card{border:1px solid #d5dfe8;border-radius:8px;padding:18px;margin:18px 0;break-inside:avoid}.equation{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.9 system-ui,sans-serif;background:#f3f7fa;padding:14px}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #dde5ec;padding:10px;text-align:left}.check{display:grid;grid-template-columns:1fr 190px 40px;gap:10px;align-items:center;border-bottom:1px solid #dde5ec;padding:10px 0}.check small{display:block;color:#6d7d89;font-size:10px}.values{text-align:right}.badge{color:#18745e;font-size:12px}.ng{color:#b6433c}svg{width:100%;height:auto}.diagram-mobile{display:none}.note{background:#fff7e8;padding:14px}@media print{body{margin:0;max-width:none}.card{break-inside:avoid}button{display:none}}</style></head><body><h1>RC 托架及梁托設計檢核計算書</h1><p>案件：${esc(p.project)}<br>構件／組合：${esc(p.member)}<br>產生時間：${esc(new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}))}（台灣）<br>版本：v1.0.0 ／ TW112 §16.5 ／ 113勘誤查核</p><p class="note"><b>${esc(r.status)}</b><br>本版未涵蓋母構材整體強度、耐震容量設計、完整錨定及支承附件設計。${r.applicable?'':'參數超出§16.5適用範圍，以下試算不作合格依據。'}</p><h2>輸入資料</h2><table><tbody>${inputRows}</tbody></table><h2>受力與配置圖</h2>${diagram(r)}<h2>檢核結果</h2>${checkHTML(r)}<h2>細部確認</h2><ul>${detailDefs.map(([k,t,s])=>`<li>${p[k]?'已由使用者確認':'待確認'}：${esc(t)} — ${esc(s)}</li>`).join('')}</ul><h2>計算過程</h2>${trace(r)}<h2>規範來源與假設</h2><p>內政部112年《建築物混凝土結構設計規範》16.5、16.2.2.3～4、21.2、22.2、22.8、22.9、25.2，含113年勘誤查核。採單排主筋、主筋／水平箍同級，承壓面中心為載重點，底面線性變化，承壓不採圍束增益。</p><p><a href="https://www.nlma.gov.tw/ch/legislation/regsearch/6874">國土管理署現行規範公告</a></p></body></html>`;}
$('export-report').onclick=()=>{const t=report();if(t)download(t,'RC托架_詳細計算書.html');};$('print-report').onclick=()=>{if(!result.valid)return;const w=window.open('','_blank');if(!w){notify('請允許開啟列印視窗，或使用匯出計算書。');return;}w.document.write(report());w.document.close();setTimeout(()=>w.print(),300);};
$('download-offline').onclick=async()=>{try{if(location.protocol==='file:'){const copy=document.documentElement.cloneNode(true);for(const id of ['fields-material','fields-geometry','fields-loads','fields-rebar','detail-checks','manual-fields'])copy.querySelector('#'+id).innerHTML='';download('<!doctype html>\n'+copy.outerHTML,'RC托架及梁托_離線版.html');notify('已下載單檔離線版本');return;}const files=await Promise.all(['style.css','engine.js','verification.js','app.js'].map(async name=>{const response=await fetch(name,{cache:'no-cache'});if(!response.ok)throw Error('無法讀取 '+name);return response.text();}));const doc=document.documentElement.cloneNode(true);doc.querySelector('link[rel=stylesheet]').outerHTML='<style>'+files[0]+'</style>';doc.querySelector('script[src="engine.js"]').outerHTML='<script>'+files[1].replace(/<\/script/gi,'<\\/script')+'</script>';doc.querySelector('script[src="verification.js"]').outerHTML='<script>'+files[2].replace(/<\/script/gi,'<\\/script')+'</script>';doc.querySelector('script[src="app.js"]').outerHTML='<script>'+files[3].replace(/<\/script/gi,'<\\/script')+'</script>';for(const id of ['fields-material','fields-geometry','fields-loads','fields-rebar','detail-checks','manual-fields'])doc.querySelector('#'+id).innerHTML='';doc.querySelector('#toast').hidden=true;download('<!doctype html>\n'+doc.outerHTML,'RC托架及梁托_離線版.html');notify('已下載單檔離線版，可直接雙擊開啟');}catch(e){notify('下載失敗：'+e.message);}};
function tests(){const list=CorbelVerification.run();$('validation-result').textContent=`${list.filter(t=>t.ok).length} / ${list.length} 項驗證通過。`;$('validation-tests').innerHTML=list.map(t=>`<div class="test-row"><span>${esc(t.name)}</span><span class="badge ${t.ok?'':'ng'}">${t.ok?'PASS':'FAIL'}</span></div>`).join('');return list;}$('run-tests').onclick=tests;
const ex=E.calculate(E.DEFAULT);$('example-results').textContent=`範例基準：d＝${f(ex.d)} cm；Mu＝${f(ex.Mu/100000)} tf·m；Asc需求＝${f(ex.AscReq)} cm²；Ah需求＝${f(ex.AhReq)} cm²。實配主筋20.268 cm²、閉合箍8.5596 cm²；數值通過，錨定等細部待確認。`;
fill();update();tests();const initialView=new URLSearchParams(location.search).get('view');if(['overview','process','manual','verify'].includes(initialView))switchView(initialView);window.CorbelApp={getInputs:()=>({...p}),getResult:()=>result,report,trace,diagram};
})();
