const $=id=>document.getElementById(id),fmt=(v,n=3)=>Number.isFinite(v)?v.toLocaleString('zh-TW',{maximumFractionDigits:n,minimumFractionDigits:n}):'—';
const keys=Object.keys(DEFAULT).filter(k=>typeof DEFAULT[k]==='number');let current=null;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,3500)}
function download(s,name,type){const u=URL.createObjectURL(new Blob([s],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function read(){let x={};for(let k of keys){let v=$(k).value;x[k]=v.trim()===''?NaN:Number(v)}x.title=$('project').value.trim()||'鋼板樁案例';x.section=$('section').value;return x}
function fill(x){for(let k of keys)$(k).value=x[k];$('project').value=x.title;$('section').value=x.section;update()}
$('case').innerHTML=CASES.slice(1).map((c,i)=>`<option value="${i+1}">${i+1}. ${c[0]}</option>`).join('');
$('section').innerHTML=SECTIONS.map(s=>`<option value="${s.name}">${s.name}｜Sx ${s.S} cm³/m</option>`).join('')+'<option value="custom">自行輸入</option>';
const EXAMPLES=CASES.slice(1).map((c,i)=>({...DEFAULT,case:i+1,title:'範例 '+(i+1)+'：'+c[0],...(i===2?{H:5,length:12,water:2.5}:{}),...([1,6].includes(i)?{length:10}:{} )}));
function example(i){let x=EXAMPLES[i-1],r=analyze(x);fill(x);$('example-detail').innerHTML=`<h3 style="margin-top:20px">${esc(x.title)}</h3><p>① 選工況 ${i}；② 依下表輸入；③ 比較即時結果；④ 將 q 增加至 1.5，觀察需求變化，再儲存案例。</p><div class="table-wrap"><table><tr><th>輸入</th><th>指定值</th><th>結果</th><th>參考值</th></tr><tr><td>H / q / 總樁長</td><td>${x.H} m / ${x.q} tf/m² / ${x.length} m</td><td>理論入土 D</td><td>${fmt(r.D,6)} m</td></tr><tr><td>γ / γsat / φ′</td><td>${x.gamma} / ${x.gammaSat} tf/m³ / ${x.phi}°</td><td>最大彎矩</td><td>${fmt(r.Mmax,6)} tf·m/m</td></tr><tr><td>γc / Su</td><td>${x.gammaClay} tf/m³ / ${x.su} tf/m²</td><td>彎曲應力</td><td>${fmt(r.sigma,3)} kgf/cm²</td></tr><tr><td>h₁ / a / s / θ</td><td>${x.water} m / ${x.anchor} m / ${x.spacing} m / ${x.angle}°</td><td>每米牆地錨水平反力</td><td>${r.anchored?fmt(r.Ta,6)+' tf/m':'無地錨'}</td></tr><tr><td>Sx / η / fb</td><td>${x.S} cm³/m / ${x.eta} / ${x.fb} kgf/cm²</td><td>控制需求入土</td><td>${fmt(r.Ddesign,6)} m</td></tr><tr><td>α / 原式 FS</td><td>${x.mult} / ${x.fs}</td><td>入土及應力檢核</td><td>${r.depthPass?'入土通過':'入土不足'}；${r.stressPass?'應力通過':'應力超限'}</td></tr></table></div><p class="muted">本表值由獨立驗算資料核對；欄位不適用時會停用。每個範例使用 SP-Ⅳ 原檔 Sx＝2270 cm³/m，η＝1，fb＝1500。</p>`;toast('已載入範例 '+i)}
$('example-buttons').innerHTML=EXAMPLES.map((x,i)=>`<button data-example="${i+1}">${i+1}. ${esc(CASES[i+1][0])}</button>`).join('');for(const b of document.querySelectorAll('[data-example]'))b.onclick=()=>example(+b.dataset.example);
function svgFrame(inner,title){return `<svg viewBox="0 0 420 420" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><rect width="420" height="420" fill="#fafcfe" rx="8"/><text x="20" y="27" fill="#2d4661" font-size="15" font-weight="650">${title}</text>${inner}</svg>`}
function geometry(r){let scale=310/Math.max(r.L,r.x.length),y=z=>60+z*scale,H=y(r.x.H),tip=y(r.L),actual=y(r.x.length),water=y(r.x.water);let inner=`<rect x="40" y="60" width="140" height="${H-60}" fill="#e7d8bb"/><rect x="40" y="${H}" width="310" height="${actual-H}" fill="#ede4cf"/><path d="M40 60H180M180 ${H}H350" stroke="#927953" stroke-width="2"/><path d="M180 53V${actual}" stroke="#aac1d7" stroke-width="11"/><path d="M180 53V${tip}" stroke="#315d88" stroke-width="7"/><path d="M190 ${tip}H335" stroke="#9aaec3" stroke-dasharray="4 4"/><text x="45" y="49" font-size="12">原地面 / q=${fmt(r.x.q,2)}</text><text x="205" y="${H-8}" font-size="12">開挖面 H=${fmt(r.x.H)}</text><text x="204" y="${tip-7}" font-size="12">理論樁尖</text><text x="204" y="${actual+17}" font-size="12">實際總長 ${fmt(r.x.length)} m</text><text x="50" y="${H+25}" font-size="12">${r.soil==='sand'?'砂土':'黏土'}</text><path d="M370 60V${H}M365 60H375M365 ${H}H375" stroke="#426b92"/><text x="375" y="${(60+H)/2}" font-size="12">H</text>`;
if(r.wet)inner+=`<path d="M40 ${water}H350" stroke="#338ec5" stroke-dasharray="7 4"/><text x="45" y="${water-6}" fill="#267eb8" font-size="12">兩側等水位 h₁=${fmt(r.x.water,2)}</text>`;
if(r.anchored){let a=y(r.x.anchor);inner+=`<path d="M180 ${a}L55 ${a+35}" stroke="#cd8b32" stroke-width="4"/><circle cx="180" cy="${a}" r="6" fill="#cd8b32"/><text x="205" y="${a+4}" font-size="12">a=${fmt(r.x.anchor,2)} m</text>`}return svgFrame(inner,'施工剖面與理論樁尖')}
function plot(r,kind){let unit=kind==='P'?'tf/m²':kind==='V'?'tf/m':'tf·m/m',title=kind==='P'?'淨土壓 p':kind==='V'?'剪力 V':'彎矩 M';let points=[];if(kind==='P'){for(let s of r.segs)points.push([s[0],s[2]],[s[1],s[3]])}else{let zlist=[...Array.from({length:301},(_,i)=>r.L*i/300),r.zM,...r.segs.flatMap(s=>[s[0],s[1]])];if(r.anchored)zlist.push(r.x.anchor-1e-9,r.x.anchor+1e-9);zlist.sort((a,b)=>a-b);points=zlist.map(z=>[z,r.vm(z)[kind]])}
let bound=Math.max(.01,...points.map(p=>Math.abs(p[1]))),xx=v=>210+v/bound*145,yy=z=>60+z/r.L*310,poly=points.map(([z,v])=>`${xx(v)},${yy(z)}`).join(' '),color=kind==='M'?'#7655ae':kind==='V'?'#267b78':'#277ab4';let inner='';for(let i=0;i<=4;i++){let z=r.L*i/4;inner+=`<path d="M55 ${yy(z)}H380" stroke="#e1e9f1"/><text x="13" y="${yy(z)+4}" font-size="11" fill="#718398">${fmt(z,2)}</text>`}inner+=`<path d="M210 50V380" stroke="#92a9c0"/><polygon points="210,${yy(points[0][0])} ${poly} 210,${yy(points.at(-1)[0])}" fill="${color}" opacity=".09"/><polyline points="${poly}" fill="none" stroke="${color}" stroke-width="2.5"/><text x="50" y="400" font-size="11">深度 m</text><text x="190" y="47" font-size="11">0</text><text x="325" y="47" font-size="11">${fmt(bound,2)}</text><text x="55" y="47" font-size="11">−${fmt(bound,2)}</text><text x="293" y="400" font-size="11">${unit}</text>`;if(kind==='M')inner+=`<circle cx="${xx(r.vm(r.zM).M)}" cy="${yy(r.zM)}" r="5" fill="${color}"/><text x="60" y="385" font-size="11">|M|max=${fmt(r.Mmax)}；z=${fmt(r.zM)} m</text>`;return svgFrame(inner,title+' / '+unit)}
function update(){let x=read(),c=CASES[x.case];if(c){let [n,a,s,w]=c;const used={gamma:s!=='clay',gammaSat:w,phi:s!=='clay',gammaClay:s!=='sand',su:s!=='sand',water:w,anchor:a,spacing:a,angle:a,fs:a||s!=='sand'};for(let [key,v]of Object.entries(used))$(key).disabled=!v;}
try{let r=analyze(x);current=r;$('error').hidden=true;$('output').hidden=false;let kpis=[['理論入土深度 D',fmt(r.D),'m · 極限平衡'],['控制需求入土',fmt(r.Ddesign),'m · 加長／規範較大值'],['最大彎矩 |M|max',fmt(r.Mmax),'tf·m/m'],['彎曲應力 σ',fmt(r.sigma,1),'kgf/cm²'],['應力使用率',fmt(r.ratio*100,1)+'%','σ / fb'],['每米牆水平錨力',r.anchored?fmt(r.Ta):'—','tf/m']];$('kpis').innerHTML=kpis.map(([l,v,u])=>`<div class="kpi"><span>${l}</span><strong>${v}</strong><em>${u}</em></div>`).join('');
$('checks').innerHTML=`<div class="status ${r.depthPass?'':'fail'}"><strong>入土長度 ${r.depthPass?'通過':'不足'}</strong>｜可用 ${fmt(r.Dprovided)} m ${r.depthPass?'≥':'＜'} 需求 ${fmt(r.Ddesign)} m</div><div class="status ${r.stressPass?'':'fail'}"><strong>彎曲應力 ${r.stressPass?'通過':'超限'}</strong>｜${fmt(r.sigma,1)} ${r.stressPass?'≤':'＞'} ${fmt(x.fb,1)} kgf/cm²</div><p>模型平衡殘差：ΣF＝${r.resF.toExponential(2)} tf/m；ΣM＝${r.resM.toExponential(2)} tf·m/m。</p><p class="muted">目前僅檢核上列兩項。原檔斷面庫及 fb 預設值仍需對照現行材質與核定設計條件。</p>`;
if(r.norm)$('checks').innerHTML+=`<div class="status ${r.norm.pass?'':'fail'}"><strong>112 年版 8.8.1 側壓平衡 ${r.norm.pass?'通過':'不符'}</strong>｜FS=${fmt(x.fs,2)}；折減後淨傾覆力矩 ${fmt(r.norm.netMoment)} tf·m/m（應≤0）<br>需求入土 ${r.norm.Drequired===null?'無有限解':fmt(r.norm.Drequired)+' m'}；忽略結構抵抗 Ms，僅計最下層錨點以下力矩。</div>`;
$('geometry').innerHTML=geometry(r);$('pressure-chart').innerHTML=plot(r,'P');$('shear-chart').innerHTML=plot(r,'V');$('moment-chart').innerHTML=plot(r,'M');
let rows=[['工況',r.name],['Ka / Kp',fmt(r.Ka,6)+' / '+fmt(r.Kp,6)],['上覆垂直壓力 Q',fmt(r.Q)+' tf/m²'],['水位以下有效 γ′',r.wet?fmt(r.ge)+' tf/m³':'未使用浮重'],['主動正壓合力 Pa',fmt(r.Pa)+' tf/m'],['正壓合力距基準 ȳ',fmt(r.ybar)+' m（懸臂砂土基準為壓力零點，其餘為開挖面）'],['壓力零點距開挖面 y₀',fmt(r.y0)+' m'],['樁底反向區長度',fmt(r.transition)+' m'],['理論平衡樁長 H+D',fmt(r.L)+' m'],['最大彎矩位置',fmt(r.zM)+' m，自原地面向下'],['需求名義 Sx',fmt(r.Srequired,1)+' cm³/m'],['有效 Sx＝ηSx',fmt(x.S*x.eta,1)+' cm³/m'],['σ＝M×100000/(ηSx)',fmt(r.sigma,1)+' kgf/cm²']];if(r.anchored)rows.push(['每支地錨水平力',fmt(r.anchorHorizontal)+' tf＝'+fmt(r.anchorHorizontal*1000,1)+' kgf'],['每支地錨軸力',fmt(r.anchorAxial)+' tf＝'+fmt(r.anchorAxial*1000,1)+' kgf']);if(r.norm)rows.push(['規範 8.8.1 折減 φ／Su',fmt(r.norm.phiReduced)+'° / '+fmt(r.norm.suReduced)+' tf/m²'],['規範側壓平衡需求入土',r.norm.Drequired===null?'無有限解':fmt(r.norm.Drequired)+' m']);if(r.soil!=='sand')rows.push(['淨抵抗 B＝4Su−Q',fmt(r.B)+' tf/m²'],['原檔 Hlim 參考',fmt(r.legacyHlim)+' m；非完整規範檢核']);
$('calculation').innerHTML=`<p class="formula">${r.formula}</p>${r.coeff.length?'<p class="mono">由最高次至常數項之方程係數：'+r.coeff.map(v=>v.toPrecision(8)).join(', ')+'</p>':''}<div class="table-wrap"><table><tr><th>計算項目</th><th>結果</th></tr>${rows.map(([a,b])=>`<tr><td>${esc(a)}</td><td>${esc(b)}</td></tr>`).join('')}</table></div>`;
$('data-table').innerHTML=`<h3 style="margin-top:20px">土壓分段資料</h3><table><tr><th>深度起點 m</th><th>深度終點 m</th><th>起點 p tf/m²</th><th>終點 p tf/m²</th></tr>${r.segs.map(s=>'<tr>'+s.map(v=>`<td class="num">${fmt(v,5)}</td>`).join('')+'</tr>').join('')}</table>`;
}catch(e){current=null;$('error').textContent=e.message;$('error').hidden=false;$('output').hidden=true}}
for(let k of keys)$(k).addEventListener(k==='case'?'change':'input',update);$('project').oninput=update;$('section').onchange=()=>{let s=SECTIONS.find(s=>s.name===$('section').value);if(s)$('S').value=s.S;update()};$('S').addEventListener('input',()=>{$('section').value='custom'});
$('save').onclick=()=>{if(!current)return toast('先修正輸入，才能儲存有效案例。');download(JSON.stringify({format:'sheet-pile-case',version:1,inputs:read()},null,2),'鋼板樁_案例.json','application/json')};$('load').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{try{let f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error('案例檔過大。');let d=JSON.parse(await f.text());if(d.format!=='sheet-pile-case'||d.version!==1||!d.inputs)throw Error('不是支援的鋼板樁案例檔。');for(let k of keys)if(typeof d.inputs[k]!=='number'||!Number.isFinite(d.inputs[k]))throw Error('案例缺少有效欄位：'+k);if(typeof d.inputs.title!=='string'||d.inputs.title.length>80)throw Error('案例名稱不合法。');let x={...DEFAULT,...d.inputs};if(!SECTIONS.some(s=>s.name===x.section)&&x.section!=='custom')x.section='custom';analyze(x);fill(x);toast('案例已匯入')}catch(e){toast('匯入失敗：'+e.message)}finally{e.target.value=''}};
$('print').onclick=()=>{if(!current)return toast('先修正輸入再列印。');window.print()};
$('report').onclick=()=>{if(!current)return toast('先修正輸入再匯出。');let css=document.querySelector('style').textContent,inputs=Object.entries(read()).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join(''),body=`<h1>${esc(read().title)}</h1><p>鋼板樁分析設計報告｜${new Date().toLocaleString('zh-TW')}｜v1.0</p><p class="notice">簡化極限平衡分析；檢核與尚待評估項目如下。不得視為完整開挖設計簽證。</p><section class="panel"><h2>全部輸入（鍵值定義參見操作說明）</h2><table>${inputs}</table></section>`+$('output').innerHTML+$('help').outerHTML+$('basis').outerHTML;download(`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(read().title)}</title><style>${css}body{max-width:1100px;margin:auto;padding:24px}</style>${body}</html>`,'鋼板樁_計算報告.html','text/html;charset=utf-8')};
$('offline').onclick=()=>{let doc=document.documentElement.cloneNode(true);doc.querySelector('#toast').hidden=true;download('<!doctype html>\n'+doc.outerHTML,'鋼板樁分析設計_離線版.html','text/html;charset=utf-8');toast('離線網頁已下載；個別案例請另存 JSON')};
fill(DEFAULT);example(1);
