// v1.1: accessible field explanations, recoverable drafts and comparison.
const FIELD_META=JSON.parse(document.getElementById('field-meta').textContent);
const constraints={H:['0 < H ≤ 30','開挖深度以本次施工階段為準，並非地下室總深。'],q:['q ≥ 0','1 tf/m² = 0.1 kgf/cm²；集中載重須先依合理分布換算。'],length:['總長 > H','可用入土＝總樁長−H；不是直接輸入入土深度。'],gamma:['γ > 0','採天然／濕單位重，不要填浮重。'],gammaSat:['γsat > 1','填飽和重；程式自行扣水重 1.0 tf/m³。'],phi:['0 < φ′ < 50°','有效應力排水參數；不可混用不排水摩擦角。'],gammaClay:['γc > 0','黏土總應力採總單位重。'],su:['Su > 0','若報告只有 qu，先確認試驗條件，再換算 Su=qu/2。'],water:['0 ≤ h₁ ≤ H','只支援兩側相同水位；抽降水不得套用。'],anchor:['0 ≤ a < H','只有單層地錨；a 從原地面量起。'],spacing:['s > 0','每支水平力＝每米牆錨力×s。'],angle:['0 ≤ θ < 80°','每支軸力＝每支水平力/cosθ；角度相對水平線。'],S:['Sx > 0','必須是每米牆寬 cm³/m，不能直接填單支值。'],eta:['0 < η ≤ 1','有效模數 ηSx；接頭滑移、腐蝕與重用需有依據。'],fb:['fb > 0','1500 是原檔對照值，並非任意鋼材的規範容許應力。'],mult:['1 ≤ α ≤ 2','原方法常列1.2～1.4；不是土壤強度安全係數。'],fs:['FS ≥ 1；地錨規範 ≥ 1.2','以 Su/FS 與 tanφ/FS 折減；懸臂不得視為已完成規範側向穩定檢核。']};
const dlg=$('field-dialog');let opener;
function explain(k){const f=FIELD_META.find(f=>f[1]===k);if(!f)return;opener=document.activeElement;const [range,mistake]=constraints[k];$('field-dialog-title').textContent=f[2];$('field-dialog-body').innerHTML=`<dl class="field-detail"><dt>定義與單位</dt><dd>${esc(f[5])} 單位：${esc(f[3])}。</dd><dt>資料來源</dt><dd>${esc(f[6])}</dd><dt>程式接受範圍</dt><dd>${esc(range)}；仍須符合本模型的地工條件。</dd><dt>教學範例值</dt><dd>${esc(f[4])} ${esc(f[3])}，僅供練習。</dd><dt>常見輸入錯誤</dt><dd>${esc(mistake)}</dd><dt>目前工況</dt><dd>${$(k).disabled?'此欄目前不參與計算。':'此欄參與本工況計算。'}</dd></dl>`;dlg.showModal();}
for(const f of FIELD_META){const k=f[1],wrap=document.querySelector(`[data-field="${k}"]`),b=document.createElement('button');b.type='button';b.className='field-help';b.textContent='欄位說明';b.setAttribute('aria-label',f[2]+'的定義與資料來源');b.onclick=()=>explain(k);wrap.append(b);}
$('field-dialog-close').onclick=()=>dlg.close();dlg.addEventListener('close',()=>opener?.focus());
$('parameter-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();for(const row of document.querySelectorAll('#parameter-table tbody tr'))row.hidden=!row.textContent.toLowerCase().includes(q)};
const draftKey='sheet-pile-draft-v1',baseKey='sheet-pile-baseline-v1';
function stash(){if(!current)return;try{localStorage.setItem(draftKey,JSON.stringify({savedAt:new Date().toISOString(),inputs:read()}));$('draft-state').textContent='有效輸入已暫存於本機';}catch(e){$('draft-state').textContent='瀏覽器不允許本機暫存；請儲存 JSON 案例';}}
function syncExtras(persist=true){if(!current){$('case-state').textContent='輸入待修正';$('comparison').textContent='修正輸入後才可比較。';return;}const r=current;$('case-state').textContent=`${r.name}｜有效輸入 · ${r.depthPass&&r.stressPass&&(!r.norm||r.norm.pass)?'列出檢核通過':'有檢核未通過'}（非完整設計結論）`;if(persist)stash();try{const d=JSON.parse(localStorage.getItem(baseKey));if(d){const b=analyze(d.inputs);$('comparison').innerHTML=`<strong>比較基準：${esc(d.inputs.title)}</strong><div class="comparison-grid"><span>需求入土差 ${fmt(r.Ddesign-b.Ddesign)} m</span><span>最大彎矩差 ${fmt(r.Mmax-b.Mmax)} tf·m/m</span><span>應力差 ${fmt(r.sigma-b.sigma,1)} kgf/cm²</span></div><small>差值＝目前−基準；比較不代表兩者具有相同適用條件。</small>`;}else $('comparison').textContent='先將目前案例設為基準，再調整 q、樁長或斷面，查看結果差值。';}catch(e){$('comparison').textContent='目前沒有可用的比較基準。';}}
const beforeEnhanceUpdate=update;update=function(){beforeEnhanceUpdate();syncExtras();};
document.addEventListener('input',e=>{if(e.target.matches('.inputs input'))syncExtras();});document.addEventListener('change',e=>{if(e.target.matches('.inputs select'))syncExtras();});
let initialDraft=null;try{initialDraft=JSON.parse(localStorage.getItem(draftKey));if(initialDraft)analyze(initialDraft.inputs);}catch(e){initialDraft=null;}
$('restore-draft').disabled=!initialDraft;$('restore-draft').onclick=()=>{if(!initialDraft)return;fill(initialDraft.inputs);toast('已恢復先前有效草稿。');};
$('baseline-save').onclick=()=>{if(!current)return toast('請先修正輸入。');try{localStorage.setItem(baseKey,JSON.stringify({inputs:read()}));syncExtras();toast('已設為比較基準。');}catch(e){toast('本機儲存不可用。');}};
$('baseline-clear').onclick=()=>{try{localStorage.removeItem(baseKey);syncExtras();}catch(e){toast('本機儲存不可用。');}};
$('jump-result').onclick=()=>$('results').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
for(const b of document.querySelectorAll('[data-video-time]'))b.onclick=()=>{const v=$('tutorial-video'),target=Number(b.dataset.videoTime);const seek=()=>{v.currentTime=target;v.play().catch(()=>{$('video-status').textContent='已跳至章節，請按影片播放鍵。';});};if(v.readyState===0){v.addEventListener('loadedmetadata',seek,{once:true});v.load();}else seek();};
$('tutorial-video').addEventListener('error',()=>{$('video-status').textContent='影片未能載入。離線使用請解壓完整套件，並保留 media 資料夾。'});
// Reading the saved draft precedes the first new stash, so opening this page does not erase recoverability.
syncExtras(false);
