/* Isolated footing, Taiwan kgf/cm units. No external dependencies. */
(function(root){'use strict';
const bars={4:{db:1.27,area:1.267},5:{db:1.59,area:1.986},6:{db:1.91,area:2.865},7:{db:2.22,area:3.871},8:{db:2.54,area:5.067},9:{db:2.87,area:6.469},10:{db:3.22,area:8.143},11:{db:3.58,area:10.07}};
const defaults={L:4.1,B:4.1,h:85,Df:1.5,cx:.75,cy:.3,ex:0,ey:0,cover:7.5,fc:210,fy:4200,barX:8,barY:8,sx:20,sy:20,lower:'x',gammaC:2.4,gammaS:.91,qa:22.5,qaType:'gross',phiS:30,mu:.5,cohesion:0,passive:0,active:0,qs:.5,fsSlide:1.5,fsOT:2,zw:100,gammaSat:2,lambdaMode:'auto',pedestal:true,cases:[{name:'S1｜D + L',type:'S',N:315,Mx:0,My:0,Hx:0,Hy:0,wf:1,qaFactor:1},{name:'U1｜1.2D + 1.6L',type:'U',N:434,Mx:0,My:0,Hx:0,Hy:0,wf:1.2,qaFactor:1},{name:'U2｜1.4D',type:'U',N:245,Mx:0,My:0,Hx:0,Hy:0,wf:1.4,qaFactor:1}]};
function rect(x0,x1,y0,y1){return [[x0,y0],[x1,y0],[x1,y1],[x0,y1]]}
function clip(poly,a,b,c){const out=[];if(!poly.length)return out;let p=poly.at(-1),vp=a*p[0]+b*p[1]+c;for(const q of poly){let vq=a*q[0]+b*q[1]+c;if((vq>=0)!==(vp>=0)){let t=vp/(vp-vq);out.push([p[0]+t*(q[0]-p[0]),p[1]+t*(q[1]-p[1])])}if(vq>=0)out.push(q);p=q;vp=vq}return out}
// Integrals [1,x,y,x²,xy,y²] by degree-two exact triangle quadrature.
function moments(p){let r=[0,0,0,0,0,0];if(p.length<3)return r;for(let i=1;i<p.length-1;i++){let t=[p[0],p[i],p[i+1]],A=Math.abs((t[1][0]-t[0][0])*(t[2][1]-t[0][1])-(t[2][0]-t[0][0])*(t[1][1]-t[0][1]))/2;for(let j=0;j<3;j++){let x=(4*t[j][0]+t[(j+1)%3][0]+t[(j+2)%3][0])/6,y=(4*t[j][1]+t[(j+1)%3][1]+t[(j+2)%3][1])/6;r[0]+=A/3;r[1]+=A*x/3;r[2]+=A*y/3;r[3]+=A*x*x/3;r[4]+=A*x*y/3;r[5]+=A*y*y/3}}return r}
function solve3(A,b){let m=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<3;i++){let k=i;for(let j=i+1;j<3;j++)if(Math.abs(m[j][i])>Math.abs(m[k][i]))k=j;[m[i],m[k]]=[m[k],m[i]];if(Math.abs(m[i][i])<1e-18)throw Error('接觸解奇異');let d=m[i][i];for(let j=i;j<4;j++)m[i][j]/=d;for(let k2=0;k2<3;k2++)if(k2!==i){let v=m[k2][i];for(let j=i;j<4;j++)m[k2][j]-=v*m[i][j]}}return m.map(r=>r[3])}
function pressure(L,B,N,Sx,Sy){if(N<=0)throw Error('有效垂直力 ≤ 0，無壓力接觸平衡。');if(Math.abs(Sx/N)>=L/2||Math.abs(Sy/N)>=B/2)throw Error('合力位於基底範圍外，無有限壓力接觸解。');let box=rect(-L/2,L/2,-B/2,B/2),target=[N,Sx,Sy],v=[N/(L*B),12*Sx/(B*L**3),12*Sy/(L*B**3)];function state(w){let poly=clip(box,w[1],w[2],w[0]),m=moments(poly),J=[[m[0],m[1],m[2]],[m[1],m[3],m[4]],[m[2],m[4],m[5]]],F=J.map(r=>r.reduce((s,x,i)=>s+x*w[i],0)),err=F.map((x,i)=>x-target[i]),norm=Math.hypot(err[0]/N,err[1]/(N*L),err[2]/(N*B));return{poly,m,J,F,err,norm}}let st=state(v),iterations=0;for(;iterations<80&&st.norm>1e-10;iterations++){let dv=solve3(st.J,st.err),step=1,ok=false;for(let k=0;k<30;k++){let nv=v.map((x,i)=>x-step*dv[i]),ns=state(nv);if(ns.norm<st.norm){v=nv;st=ns;ok=true;break}step/=2}if(!ok)break}if(st.norm>1e-7)throw Error('壓力接觸未收斂，請調整幾何或偏心。');let q=box.map(([x,y])=>Math.max(0,v[0]+v[1]*x+v[2]*y));return{v,poly:st.poly,area:st.m[0],qmax:Math.max(...q),qmin:Math.min(...q),full:st.m[0]>L*B*(1-1e-9),residual:st.norm,iterations,F:st.F,box}}
function pIntegral(p,poly){let m=moments(clip(poly,p.v[1],p.v[2],p.v[0])),v=p.v;return[v[0]*m[0]+v[1]*m[1]+v[2]*m[2],v[0]*m[1]+v[1]*m[3]+v[2]*m[4],v[0]*m[2]+v[1]*m[4]+v[2]*m[5]]}
function intersectRect(poly,b){return clip(clip(clip(clip(poly,1,0,-b[0]),-1,0,b[1]),0,1,-b[2]),0,-1,b[3])}
function flex(As,b,d,fc,fy){let a=As*fy/(.85*fc*b),beta=Math.max(.65,.85-.05*Math.max(0,fc-280)/70),c=a/beta,et=c>0?.003*(d-c)/c:Infinity,ey=fy/2040000,phi=et>=ey+.003?.9:et<=ey?.65:.65+.25*(et-ey)/.003;return{As,a,c,et,phi,capacity:Math.max(0,phi*As*fy*(d-a/2)/100000),ductile:et>=ey+.003}}
function asReq(M,b,d,fc,fy){let lo=0,hi=.85*fc*b*d/fy;for(let i=0;i<65;i++){let mid=(lo+hi)/2;if(flex(mid,b,d,fc,fy).capacity>=Math.abs(M))hi=mid;else lo=mid}return hi}
function validate(i){let errs=[];for(const k of ['L','B','h','Df','cx','cy','cover','fc','fy','sx','sy','gammaC','gammaS','qa','gammaSat','fsSlide','fsOT'])if(!Number.isFinite(i[k])||i[k]<=0)errs.push(k+' 必須為正數');for(const k of ['ex','ey','qs','cohesion','zw','phiS','passive','active','mu'])if(!Number.isFinite(i[k]))errs.push(k+' 必須為有限數值');if(i.Df<i.h/100)errs.push('埋深 Df 不可小於基礎厚度');if(Math.abs(i.ex)+i.cx/2>i.L/2+1e-9||Math.abs(i.ey)+i.cy/2>i.B/2+1e-9)errs.push('柱斷面超出基礎邊界');if(i.fc<175||i.fc>700||i.fy<2800||i.fy>4200)errs.push('本版材料範圍：fc′ 175–700、fy 2800–4200 kgf/cm²');if(i.cover<7.5)errs.push('本版按接觸土壤澆置，淨保護層須 ≥ 7.5 cm');if(i.mu<0||i.mu>Math.min(.6,Math.tan(i.phiS*Math.PI/180))+1e-9)errs.push('底面摩擦係數不得超過 min(0.6, tanφ)');if(i.phiS<0||i.phiS>=45||i.passive<0||i.passive>1||i.active<0||i.active>1||i.qs<0||i.cohesion<0||i.zw<0||i.gammaSat<=1)errs.push('地盤參數超出允許範圍');if(!bars[i.barX]||!bars[i.barY])errs.push('鋼筋號數不支援');if(!Array.isArray(i.cases)||!i.cases.some(c=>c.type==='S')||!i.cases.some(c=>c.type==='U'))errs.push('至少需要一組使用與一組強度荷載');for(const c of i.cases||[]){if(!['S','U'].includes(c.type)||!['N','Mx','My','Hx','Hy','wf','qaFactor'].every(k=>Number.isFinite(c[k]))||c.wf<0||c.qaFactor<=0)errs.push('荷載組合數值或類型無效')}return errs}
function calculate(input){let i=JSON.parse(JSON.stringify(input)),errors=validate(i);if(errors.length)return{errors};let bx=bars[i.barX],by=bars[i.barY],dx=i.h-i.cover-bx.db/2-(i.lower==='y'?by.db:0),dy=i.h-i.cover-by.db/2-(i.lower==='x'?bx.db:0),d=(dx+dy)/200;if(Math.min(dx,dy)<15)return{errors:['兩向有效深度須至少 15 cm']};let A=i.L*i.B,Ac=i.cx*i.cy,depth=i.Df-i.h/100,wet=Math.max(0,depth-i.zw),dry=depth-wet,soilPSF=i.gammaS*dry+i.gammaSat*wet+i.qs,ws=soilPSF*(A-Ac),wc=i.gammaC*A*i.h/100,wp=i.pedestal?i.gammaC*Ac*depth:0,U=Math.max(0,i.Df-i.zw)*A,cb=[i.ex-i.cx/2,i.ex+i.cx/2,i.ey-i.cy/2,i.ey+i.cy/2],box=rect(-i.L/2,i.L/2,-i.B/2,i.B/2),nx=Math.floor((i.B*100-2*i.cover-bx.db)/i.sx)+1,ny=Math.floor((i.L*100-2*i.cover-by.db)/i.sy)+1,Asx=nx*bx.area,Asy=ny*by.area,fx=flex(Asx,i.B*100,dx,i.fc,i.fy),fy=flex(Asy,i.L*100,dy,i.fc,i.fy),minx=.0018*i.B*100*i.h,miny=.0018*i.L*100*i.h,Ka=Math.tan((45-i.phiS/2)*Math.PI/180)**2,Kp=1/Ka,earthInt=i.gammaS*Math.min(i.Df,i.zw)**2/2+(i.gammaSat-1)*Math.max(0,i.Df-i.zw)**2/2+i.gammaS*Math.min(i.Df,i.zw)*Math.max(0,i.Df-i.zw),Ppx=i.passive*Kp*earthInt*i.B,Ppy=i.passive*Kp*earthInt*i.L,Pax=i.active*Ka*(earthInt+i.qs*i.Df)*i.B,Pay=i.active*Ka*(earthInt+i.qs*i.Df)*i.L;
let results=[];for(const c of i.cases){let w=c.wf,N=c.N+w*(wc+ws+wp)-w*U,Sx=c.My+(c.N+w*wp-w*soilPSF*Ac)*i.ex,Sy=-c.Mx+(c.N+w*wp-w*soilPSF*Ac)*i.ey,entry={...c,Ntotal:N,Sx,Sy};try{let p=pressure(i.L,i.B,N,Sx,Sy);entry.p=p;let qallow=i.qaType==='gross'?i.qa:i.qa+(i.gammaS*Math.min(i.Df,i.zw)+(i.gammaSat-1)*Math.max(0,i.Df-i.zw));entry.bearing=p.qmax/(qallow*c.qaFactor);let H=Math.hypot(Math.abs(c.Hx)+Pax,Math.abs(c.Hy)+Pay),res=i.mu*N+i.cohesion*p.area+(H>0?(Ppx*(Math.abs(c.Hx)+Pax)+Ppy*(Math.abs(c.Hy)+Pay))/H:0);entry.fsSliding=H>0?res/H:Infinity;function overturn(size,offset,moment){return Math.min(...[-1,1].map(sign=>{let R=(Math.max(0,c.N)+w*wp)*(size/2-sign*offset)+w*(wc+ws)*size/2+sign*w*soilPSF*Ac*offset+Math.max(0,-sign*moment),O=Math.max(0,-c.N)*(size/2-sign*offset)+w*U*size/2+Math.max(0,sign*moment);return O>0?R/O:Infinity}))}entry.fsOTx=overturn(i.L,i.ex,c.My);entry.fsOTy=overturn(i.B,i.ey,-c.Mx);entry.fsOT=Math.min(entry.fsOTx,entry.fsOTy);entry.exr=Sx/N;entry.eyr=Sy/N;
// Exact distributed net upward integrals, excluding downward overburden over column.
function net(poly){let pr=pIntegral(p,poly),m=moments(poly),mc=moments(intersectRect(poly,cb)),uniform=w*(U/A-wc/A-soilPSF);return pr.map((x,j)=>x+uniform*m[j]+w*soilPSF*mc[j])}
let all=net(box),sides=[];for(const [axis,sign,pos,dd,b] of [['x',-1,cb[0],dx/100,i.B],['x',1,cb[1],dx/100,i.B],['y',-1,cb[2],dy/100,i.L],['y',1,cb[3],dy/100,i.L]]){let poly=clip(box,axis==='x'?sign:0,axis==='y'?sign:0,-sign*pos),r=net(poly),M=sign*(r[axis==='x'?1:2]-pos*r[0]),sv=net(clip(box,axis==='x'?sign:0,axis==='y'?sign:0,-sign*(pos+sign*dd)))[0],as=axis==='x'?Asx:Asy,dcm=dd*100,rho=as/(b*100*dcm),ls=i.lambdaMode==='on'||!p.full?Math.min(1,Math.sqrt(2/(1+dcm/25))):1,Vc=Math.min(1.33,2.12*ls*Math.cbrt(rho))*Math.sqrt(i.fc)*b*100*dcm/1000,cap=axis==='x'?fx.capacity:fy.capacity;sides.push({axis,sign,pos,M,Vu:Math.abs(sv),capacity:cap,shearCap:.75*Vc,shearRatio:Math.abs(sv)/(.75*Vc),ratio:Math.abs(M)/cap,top:M<0,AsReq:asReq(M,b*100,dcm,i.fc,i.fy),lambda:ls})}entry.sides=sides;
let bounds=[cb[0]-d/2,cb[1]+d/2,cb[2]-d/2,cb[3]+d/2],interior=bounds[0]>-i.L/2&&bounds[1]<i.L/2&&bounds[2]>-i.B/2&&bounds[3]<i.B/2;entry.punch={interior};if(interior){let a=i.cx+d,b=i.cy+d,bo=2*(a+b),inside=net(rect(...[bounds[0],bounds[1],bounds[2],bounds[3]])),V=all[0]-inside[0],Tx=all[1]-inside[1]-i.ex*V,Ty=all[2]-inside[2]-i.ey*V,Jy=d*a**3/6+a*d**3/6+d*b*a*a/2,Jx=d*b**3/6+b*d**3/6+d*a*b*b/2,gx=1-1/(1+2/3*Math.sqrt(a/b)),gy=1-1/(1+2/3*Math.sqrt(b/a)),vmax=Math.max(...[-1,1].flatMap(s=>[-1,1].map(t=>Math.abs(V/(bo*d)+gx*Tx*(s*a/2)/Jy+gy*Ty*(t*b/2)/Jx))))/10,ls=i.lambdaMode==='on'||!p.full?Math.min(1,Math.sqrt(2/(1+d*100/25))):1,beta=Math.max(i.cx,i.cy)/Math.min(i.cx,i.cy),vc=ls*Math.min(1.06,.53*(1+2/beta),.265*(2+40*d/bo))*Math.sqrt(i.fc),bandx=Math.min(i.B,i.cy+3*i.h/100),bandy=Math.min(i.L,i.cx+3*i.h/100),vdirect=Math.abs(V)/(bo*d)/10,high=vdirect>.75*.53*ls*Math.sqrt(i.fc),localX=high?5*vmax*bandx*100*bo*100/(.75*40*i.fy):.0018*bandx*100*i.h,localY=high?5*vmax*bandy*100*bo*100/(.75*40*i.fy):.0018*bandy*100*i.h,mBandX=(1-gx)*Math.abs(Tx),mBandY=(1-gy)*Math.abs(Ty),asBandX=Asx*bandx/i.B,asBandY=Asy*bandy/i.L;entry.punch={interior,V,Tx,Ty,bo,d,Jx,Jy,gx,gy,vmax,vc,capacity:.75*vc,ratio:vmax/(.75*vc),lambda:ls,bandx,bandy,localX,localY,asBandX,asBandY,bandCapX:flex(asBandX,bandx*100,dx,i.fc,i.fy).capacity,bandCapY:flex(asBandY,bandy*100,dy,i.fc,i.fy).capacity,mBandX,mBandY,high};}
entry.netBalance=Math.abs(all[0]-(c.N+w*wp))/Math.max(1,Math.abs(c.N+w*wp));entry.flexRatio=Math.max(...sides.map(s=>s.ratio));entry.shearRatio=Math.max(...sides.map(s=>s.shearRatio));entry.needsTop=sides.some(s=>s.top&&Math.abs(s.M)>1e-6);entry.fail=c.type==='S'?(entry.bearing>1||entry.fsSliding<i.fsSlide||entry.fsOT<i.fsOT):(entry.flexRatio>1||entry.shearRatio>1||(interior&&entry.punch.ratio>1));}catch(e){entry.error=e.message;entry.fail=true}results.push(entry)}
let maxM={x:0,y:0},maxAs={x:minx,y:miny},short=i.L>=i.B?'y':'x',betaFoot=Math.max(i.L,i.B)/Math.min(i.L,i.B),distFactor=2*betaFoot/(betaFoot+1);for(const r of results.filter(r=>r.type==='U'&&!r.error)){for(const s of r.sides){maxM[s.axis]=Math.max(maxM[s.axis],Math.abs(s.M));maxAs[s.axis]=Math.max(maxAs[s.axis],s.AsReq)}if(r.punch.interior){maxAs.x=Math.max(maxAs.x,r.punch.localX*i.B/r.punch.bandx,asReq(r.punch.mBandX,r.punch.bandx*100,dx,i.fc,i.fy)*i.B/r.punch.bandx);maxAs.y=Math.max(maxAs.y,r.punch.localY*i.L/r.punch.bandy,asReq(r.punch.mBandY,r.punch.bandy*100,dy,i.fc,i.fy)*i.L/r.punch.bandy)}}maxAs[short]*=distFactor;
let spacingLimit=Math.min(2*i.h,45),spacingOK=i.sx<=spacingLimit&&i.sy<=spacingLimit&&i.sx-bx.db>=Math.max(2.5,bx.db)&&i.sy-by.db>=Math.max(2.5,by.db),reinforceOK=Asx>=maxAs.x&&Asy>=maxAs.y&&spacingOK&&fx.ductile&&fy.ductile;
let review=results.some(r=>r.type==='U'&&!r.error&&(!r.punch.interior||r.needsTop))||i.active>0||i.passive>0||i.cohesion>0,fail=results.some(r=>r.fail)||!reinforceOK;return{errors:[],i,A,Ac,dx,dy,d,ws,wc,wp,U,soilPSF,Asx,Asy,nx,ny,fx,fy,minx,miny,maxM,maxAs,short,distFactor,spacingLimit,spacingOK,reinforceOK,Ka,Kp,Ppx,Ppy,Pax,Pay,results,review,fail,status:fail?'NG':review?'REVIEW':'PASS'};}
const API={bars,defaults,rect,clip,moments,pressure,pIntegral,flex,asReq,validate,calculate};root.Footing=API;if(typeof module!=='undefined')module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
