/* v1.1: searchable engineering definitions and prerecorded Taiwan narration. */
const parameterNotes={
L:['基礎沿 X 軸的總尺寸，不是柱寬。','結構基礎平面圖','影響底面積、X 向懸臂長度與偏心界限。'],B:['基礎沿 Y 軸的總尺寸，不是有效受壓寬度。','結構基礎平面圖','部分接觸面積由力平衡另求，不可把 B 改成接觸寬。'],h:['由基礎頂面到基底的總厚度。','基礎剖面圖','以 cm 輸入；算自重時自動除以100。'],Df:['地表到基底的垂直距離。','開挖圖、地質剖面','Df ≥ h/100；覆土厚度為 Df−h/100。'],cx:['RC 柱或柱墩沿 X 軸尺寸。','柱表、柱墩詳圖','控制柱面彎矩與沖切臨界周界。'],cy:['RC 柱或柱墩沿 Y 軸尺寸。','柱表、柱墩詳圖','長寬比影響沖切三式中的 β。'],ex:['由基礎中心量至柱心的 X 向偏位，向右為正。','基礎平面尺寸、柱定位圖','程式另計 N×ex；荷載輸入勿再次包含此平面偏位矩。'],ey:['由基礎中心量至柱心的 Y 向偏位，向上為正。','基礎平面尺寸、柱定位圖','正 Mx 的反力梯度指向 −Y，注意右手座標。'],cover:['基底混凝土表面至最外層鋼筋表面的淨距。','基礎剖面與耐久性設計','本版按現澆接觸土壤，至少7.5 cm；不是到鋼筋中心距。'],fc:['混凝土指定抗壓強度 fc′。','材料規格、圓柱試體試驗報告','本版175–700 kgf/cm²；1 MPa約10.1972 kgf/cm²。'],fy:['鋼筋指定降伏強度，不是容許拉應力。','鋼筋級別、材質證明','本版2800–4200 kgf/cm²；不是以 MPa 直接填420。'],gammaC:['RC 混凝土每立方公尺的重力。','材料單位重、專案設計準則','常重RC示例2.4 tf/m³；Wc=γc×L×B×h/100。'],gammaS:['地下水以上土的天然單位重。','地質鑽探、室內試驗','原重建例0.91為舊測試資料；新例1.8不能取代實案報告。'],gammaSat:['水位以下土的飽和單位重，不是浮單位重。','地質試驗報告','程式以γsat−1.0算有效上覆壓力；γsat須>1。'],zw:['地表往下量的設計地下水深度。','地質報告、監測與設計最高水位','zw=0表示水位在地表；100為示例的深水位。水位高於基底時自動算浮力。'],qs:['柱斷面範圍以外的地表均佈附加載重。','地坪、堆載與使用條件','不重複填柱反力中已傳入的上部載重。'],qa:['工程師核定的容許地盤承載力。','地質報告及基礎設計準則','確認適用尺寸、埋深、沉陷控制，以及總／淨定義。'],phiS:['有效應力條件下土的內摩擦角。','直剪、三軸試驗或地質報告','本版0≤φ<45°；不以φ自動推估qa。'],mu:['基底混凝土與土之間的有效摩擦係數。','界面試驗或專案地工準則','本版不得超過min(0.6,tanφ)；不是一律照填0.5。'],cohesion:['基底界面的可採用黏著力 ca。','地工工程師核定的界面參數','與土壤凝聚力 c 不同；無依據填0，採用時標示REVIEW。'],passive:['永久有效側向土體被動反力的可採比例。','地工準則與施工階段分析','0–1；預設0。考慮開挖、沖刷、位移需求；作用點與傾覆另核。'],active:['最不利單側主動土壓的可採比例。','擋土與非對稱地形分析','0–1；預設0表示不啟用單側土壓；啟用會要求專案複核。'],fsSlide:['滑動抵抗與水平需求之比的最低要求。','適用載重狀態與專案設計準則','示例1.5；零水平需求時FS顯示∞。震時不得未經依據降低。'],fsOT:['兩側趾點抵抗矩／傾覆矩的最低要求。','專案地工與穩定準則','示例2.0；含浮力，取X、Y及兩側最小值。'],sx:['平行 X 的鋼筋在 Y 方向的中心到中心間距。','基礎底筋詳圖','s−db為淨距；本版最大中心距min(2h,45 cm)。'],sy:['平行 Y 的鋼筋在 X 方向的中心到中心間距。','基礎底筋詳圖','不是鋼筋根數，也不是淨距。']};
const parameterExtra=[
['qaType','承載力定義','—','總值可直接與有效總土壓比較；淨值加上原地層有效上覆壓力換算。','地質報告對qa的明確定義','不同水位、地質假設的qa不能混用。','soil'],
['barX','X 向鋼筋號數','#','平行X軸的底筋號數，名義直徑及面積由程式鋼筋表取得。','結構配筋圖及鋼筋規格','支援#4–#11；號數不等於直徑cm。','steel'],
['barY','Y 向鋼筋號數','#','平行Y軸的底筋號數。','結構配筋圖及鋼筋規格','兩向鋼筋可不同號數。','steel'],
['lower','較下層鋼筋','X / Y','較靠近基底表面的方向；另一方向多扣下層筋直徑。','配筋剖面圖','X在下時dx=h−cover−dbx/2；dy另扣dbx。','steel'],
['lambdaMode','剪力尺寸效應','—','全接觸、連續土壤承壓淺基礎可採λs=1；部分接觸採保守尺寸效應。','混凝土規範13.2.6.2、22.5、22.6','全部納入選項：λs=min(1,√(2/(1+d/25)))，d用cm。','steel'],
['pedestal','另加埋置柱自重','勾選','柱尺寸×覆土深度×混凝土重；依wf納入各組合。','結構分析模型的自重計入範圍','若反力已含這段柱重，取消勾選。','geometry'],
['type','組合用途','S / U','S為使用載重，檢查地盤與穩定；U為因數化强度載重，檢查RC。','結構分析的使用與強度組合清單','至少各1組；完整風震與低軸力組合需自行新增。','loads'],
['N','柱垂直力','tf','本組合柱反力，向下壓為正，向上拔為負。','SAP2000／MIDAS等結構分析反力','1 tf=1000 kgf≈9.80665 kN；不含程式另加的基礎、覆土及可選柱重。','loads'],
['Mx','柱彎矩 Mx','tf·m','依右手座標繞X軸的基底力矩；正值令+Y土壓降低。','已完成到基底水平面力矩轉移的分析內力','不得重複加H×高度或柱平面偏位矩。','loads'],
['My','柱彎矩 My','tf·m','依右手座標繞Y軸的基底力矩；正值令+X土壓增加。','已完成到基底水平面力矩轉移的分析內力','1 tf·m=100000 kgf·cm。','loads'],
['Hx','水平力 Hx','tf','與同列N、Mx、My同時發生的X水平力；用於滑動。','同一荷載組合分析反力','力矩轉移應先在外部完成，不由此欄自動重加。','loads'],
['Hy','水平力 Hy','tf','與同列內力同時發生的Y水平力；以雙向合力檢查滑動。','同一荷載組合分析反力','保留正負號；不得拼接各組合包絡最大值。','loads'],
['wf','自重／覆土係數','—','乘基礎重、覆土及附載、可選柱重，也乘水浮力。','該組合的載重係數與水力設計準則','S示例1；1.2D+1.6L示例1.2；1.4D示例1.4。水力係數不同時須另核。','loads'],
['qaFactor','qa 倍率','—','仅提高或降低S組合的qa；不乘U的RC容量。','地質或適用規範核准的短期容許值','無核准提高填1。不能把1.33當成一律可用值。','loads']
];
const tabFor=k=>['qa','gammaS','gammaSat','zw','qs','phiS','mu','cohesion','passive','active','fsSlide','fsOT'].includes(k)?'soil':['sx','sy'].includes(k)?'steel':'geometry';
function parameterRows(){return [...Object.entries(defs).map(([k,d])=>[k,d[0],d[1],parameterNotes[k]?.[0]||d[2],parameterNotes[k]?.[1]||'專案設計文件',parameterNotes[k]?.[2]||d[2],tabFor(k)]),...parameterExtra].map(a=>({key:a[0],label:a[1],unit:a[2],definition:a[3].replace('强','強').replace('仅','僅'),source:a[4],hint:a[5],tab:a[6]}));}
function glossaryRender(key){$('paramview').innerHTML=panel('輸入參數字典',`<p class="note">由定義 → 單位 → 資料來源 → 檢核影響，逐項確認。圖面、分析反力與地質報告應使用同一工程版本。</p><div class="parameter-tools"><input id="parameterSearch" type="search" placeholder="搜尋：承載力、N、保護層、水位…" aria-label="搜尋參數定義"><span id="parameterCount" role="status"></span></div><div id="parameterList" class="parameter-grid"></div>`,parameterRows().length+' 項參數');let q=$('parameterSearch');q.value=key||'';q.oninput=renderParameterList;renderParameterList();}
function renderParameterList(){let q=$('parameterSearch').value.trim().toLowerCase(),rows=parameterRows().filter(p=>[p.key,p.label,p.unit,p.definition,p.source,p.hint].join(' ').toLowerCase().includes(q));$('parameterCount').textContent=rows.length+' 項參數';$('parameterList').innerHTML=rows.length?rows.map(p=>`<article class="parameter-card"><h3><code>${esc(p.key)}</code> ${esc(p.label)} <small>${esc(p.unit)}</small></h3><p>${esc(p.definition)}</p><p class="source"><b>資料來源：</b>${esc(p.source)}</p><p><b>填寫與檢核：</b>${esc(p.hint)}</p><button data-locate="${p.tab}" data-key="${p.key}">前往輸入位置</button></article>`).join(''):'<p>沒有符合的參數，請改用中文名稱或符號搜尋。</p>';for(const b of document.querySelectorAll('[data-locate]'))b.onclick=()=>{setTab(b.dataset.locate);let e=$(b.dataset.key)||document.querySelector(`[data-case="0"][data-key="${b.dataset.key}"]`);if(e){e.focus();e.scrollIntoView({block:'center',behavior:'smooth'})}};}
const limits={L:[.01,null],B:[.01,null],h:[1,null],Df:[0,null],cx:[.01,null],cy:[.01,null],cover:[7.5,null],fc:[175,700],fy:[2800,4200],gammaC:[.01,null],gammaS:[.01,null],gammaSat:[1.001,null],zw:[0,null],qa:[.01,null],qs:[0,null],phiS:[0,44.999],mu:[0,.6],cohesion:[0,null],passive:[0,1],active:[0,1],fsSlide:[.01,null],fsOT:[.01,null],sx:[.01,null],sy:[.01,null]};
function updateInputHints(){for(const e of document.querySelectorAll('input[data-field]')){let k=e.dataset.field;if(limits[k]){let [min,max]=limits[k];e.min=min;if(max!==null)e.max=max;let n=Number(e.value),bad=e.value===''||!Number.isFinite(n)||n<min||(max!==null&&n>max);if(k==='Df')bad||=n<data.h/100;if(k==='mu')bad||=n>Math.min(.6,Math.tan(data.phiS*Math.PI/180))+1e-9;e.setAttribute('aria-invalid',String(bad));}}}
let tutorialPromise,tutorialURL,tutorialVttURL;
function ensureTutorialData(){if(window.FootingTutorial)return Promise.resolve(window.FootingTutorial);if(tutorialPromise)return tutorialPromise;tutorialPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='media/tutorial-data.js';s.dataset.mediaLoader='true';s.onload=()=>window.FootingTutorial?resolve(window.FootingTutorial):reject(Error('影片資料格式錯誤'));s.onerror=()=>{s.remove();tutorialPromise=null;reject(Error('影片尚未載入。請確認連線或使用完整离線版。'.replace('离','離')))};document.body.append(s);});return tutorialPromise;}
function base64Blob(s,type){let chunks=[];for(let start=0;start<s.length;start+=65536){let b=atob(s.slice(start,start+65536)),a=new Uint8Array(b.length);for(let j=0;j<b.length;j++)a[j]=b.charCodeAt(j);chunks.push(a)}return new Blob(chunks,{type});}
async function tutorialRender(){if($('tutorialPlayer'))return;$('tutorialview').innerHTML=panel('操作影片｜台灣女性旁白',`<p class="note">用「厚度調整範例」完成一輪輸入與檢核。可暫停跟著操作，也可點章節跳轉；影片不會自動播放。</p><p id="tutorialLoading" class="tutorial-note" role="status">正在載入影片…</p><video id="tutorialPlayer" class="tutorial-video" controls playsinline preload="metadata" aria-label="獨立基礎操作教學影片"></video><div id="tutorialChapters" class="chapter-list"></div><div class="tutorial-toolbar"><button id="tutorialSample">載入影片同款範例</button><button id="tutorialSpeed">播放速度 1×</button></div><div id="tutorialTranscript" class="tutorial-script"></div>`,'zh-TW · 曉臻');$('tutorialSample').onclick=()=>loadExample('safe');const v=$('tutorialPlayer');$('tutorialSpeed').onclick=()=>{v.playbackRate=v.playbackRate===1?.85:v.playbackRate===.85?1.25:1;$('tutorialSpeed').textContent='播放速度 '+v.playbackRate+'×'};try{let meta=await ensureTutorialData();if(!tutorialURL)tutorialURL=URL.createObjectURL(base64Blob(meta.video,'video/mp4'));v.src=tutorialURL;v.onloadedmetadata=()=>{$('tutorialLoading').textContent='台灣國語女性：'+meta.voice+'｜'+fmt(v.duration/60,1)+' 分鐘｜製作與規範核對：'+meta.checkedOn};if(meta.vtt){tutorialVttURL||=URL.createObjectURL(new Blob([meta.vtt],{type:'text/vtt'}));let track=document.createElement('track');track.kind='captions';track.label='繁體中文字幕';track.srclang='zh-TW';track.src=tutorialVttURL;v.append(track);} $('tutorialChapters').innerHTML=meta.chapters.map(c=>`<button data-seek="${c.start}">${c.id}｜${esc(c.title)}<small>${Math.floor(c.start/60)}:${String(Math.floor(c.start%60)).padStart(2,'0')}</small></button>`).join('');for(const b of document.querySelectorAll('[data-seek]'))b.onclick=()=>{v.currentTime=Number(b.dataset.seek);v.play().catch(()=>{})};$('tutorialTranscript').innerHTML='<h3>旁白逐字稿</h3>'+meta.chapters.map(c=>`<details><summary>${c.id}｜${esc(c.title)}</summary><p>${esc(c.text)}</p></details>`).join('');}catch(e){$('tutorialLoading').textContent=e.message;tutorialPromise=null;let b=document.createElement('button');b.textContent='重新載入';b.onclick=()=>{$('tutorialview').innerHTML='';tutorialRender()};$('tutorialLoading').append(b)}}
// Stable deep links for help, definition lookup and tutorial chapters.
const validTabs=['geometry','loads','soil','steel','report','help','parameters','tutorial'];const requestedTab=location.hash.slice(1);if(validTabs.includes(requestedTab))setTab(requestedTab);updateInputHints();
