/* Shared presentation and guidance layer; no catalog strength or certification claims. */
(()=>{'use strict';const E=id=>document.getElementById(id),HOME='https://jerry597640-droid.github.io/engineering-calculator-hub/',M=window.STEEL_MEDIA||{},CH=window.STEEL_CHAPTERS||[];
const P=[['q','規格關鍵字','尺寸字串','輸入完整或部分規格，x、×、* 可混用。','施工圖、材料表或鋼廠型錄，例如 300x150。'],['family','斷面種類','選项','限定截面形狀，不代表已符合材料或設計規範。','依實際加工或型錄形狀選擇。'],['sourceFilter','資料性質','型錄／理論','型錄為原廠表列值；理論為板件幾何推算。','31 筆理論示例不是已確認的供货清單。'],['sort','排列方式','選項','只調整排序，不更動型錄參數。','可按高度、單位重量及截面性質排列。'],['minIx','Ix 下限','cm⁴','x 軸二次面積矩篩選門檻；留白不限制。','使用者的選型需求，不是規範合格值。'],['maxW','單位重量上限','kg/m','每公尺名目質量上限；留白不限制。','由搬運或初步選型需求決定。'],['dimUnit','尺寸顯示單位','mm／cm','僅切換檢視區尺寸；名稱及圖面仍採 mm。','A 維持 cm²、I 維持 cm⁴，不會全部一起換單位。'],['length','單支長度 L','m','一支相同規格型鋼的長度，必須大於零。','施工圖或採購清單，範例 6 m。'],['quantity','支數 n','支','相同規格及長度的型鋼支數，必須為正整數。','範例 4 支，不同長度請分批計算。'],['customType','自訂斷面種類','選項','選擇理想化幾何模型，依圖說及定義輸入。','不包含軋延圓角、冷彎有效寬度與強度設計。'],['cust-H','截面高度 H','mm','外框總高，H 型包括上下翼板。','依原廠型錄或加工圖。'],['cust-B','總寬度 B','mm','斷面外框寬度；角鋼為水平肢外尺寸。','方形鋼管要求 H＝B。'],['cust-tw','腹板厚 tw','mm','腹板板厚，不是腹板淨高。','加工圖或型錄。'],['cust-tf','翼板厚 tf','mm','簡化模型採等厚翼板。','H 型須 H>2tf，T 型須 H>tf；不模擬漸變翼板。'],['cust-t','均勻板厚 t','mm','角鋼、C 型及鋼管的均勻板厚。','真實壁厚及公差由供應商資料確認。'],['cust-lip','折邊淨長 lip','mm','翼板內面至折邊端的直線淨長，不含翼板厚。','与原廠含彎角外尺寸的基準不同，需先換算。'],['cust-D','圓管外徑 D','mm','圓形管外直徑，不是公稱管徑或內徑。','須 D>2t。'],['A','斷面積 A','cm²','材料毛斷面的幾何面積。','型錄值為原廠表列；理論值為帶正負號面積總和。'],['W','單位重量 W','kg/m','每公尺名目質量；理論 W=0.785A。','密度假設 7850 kg/m³；kg 是質量，不是 kgf。'],['IxIy','慣性矩 Ix／Iy','cm⁴','通過重心、平行外框的二次面積矩。','非對稱斷面不一定是主軸；未處理 Ixy 耦合彎曲。'],['SxSy','彈性模數 Sx／Sy','cm³','S=I/c；本工具 c 採較遠側極纖維距。','不等同塑性模數，也不取代非對稱彎曲分析。'],['ZxZy','塑性模數 Zx／Zy','cm³','只顯示原廠 H 型鋼已提供的數值。','能否達塑性強度仍須局部挫屈及穩定檢核。'],['rxry','迴轉半徑 rx／ry','cm','r=√(I/A)，不是軋延圓角半徑。','供後續細長比評估；本工具不執行構件耐力設計。'],['R','根部圓角 R／翼端 R₂','mm','熱軋型鋼根部及翼端半徑。','取自型錄；自訂模型未納入圓角。'],['Cy','槽鋼重心 Cy','cm','依原廠型錄定义的水平重心距。','原點依型錄示意核對，不可直接以 B/2 代替。'],['mass','總重量 M','kg／t','M=W×L×n；1000 kg＝1 t。','W=36.7、L=6、n=4 時為 880.8 kg；未含接合件與耗損。']];
for(const p of P)for(let i=0;i<p.length;i++)p[i]=p[i].replaceAll('选项','選項').replaceAll('供货','供貨').replaceAll('与','與').replaceAll('定义','定義');
window.STEEL_V11={version:'1.2.0',params:P,chapters:CH,home:HOME};
if(!E('steel-ux-style')){const s=document.createElement('style');s.id='steel-ux-style';s.textContent=`html{scroll-padding-top:170px}.side{overflow:auto}.side nav{flex-shrink:0}.topbar{z-index:20}.v11-home{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:9px 16px;border:1px solid #c08b32;border-radius:10px;text-decoration:none!important;background:#ffe0a3;color:#13263c!important;font-weight:750;white-space:nowrap}.v11-dock{display:none}.v11-help{display:inline-grid;place-items:center;min-height:28px;width:28px;padding:0;border-radius:50%;background:#eaf2fa;color:#1f517d;margin-left:5px}.v11-hint{padding:10px 12px;background:#f1f6fc;border-left:3px solid #2774af;color:#344e68;font-size:13px}.v11-hint[hidden]{display:none}.v11-search{width:100%;min-height:46px;padding:10px;border:1px solid #bacdde;border-radius:8px;font-size:16px}.v11-para-card{padding:14px;border:1px solid #dce5ef;background:#f4f7fb;margin:10px 0;border-radius:9px}.v11-para-card h3{margin:0 0 5px}.v11-para-card p{margin:4px 0}.v11-context{padding:16px;background:#fff8ec;border:1px solid #ead4b0;border-radius:10px;margin:16px 0}.v11-pill{display:inline-block;padding:4px 10px;border-radius:20px;background:#eaf5ee;color:#136b57;font-size:12px}.v11-video{display:block;width:100%;max-height:72vh;aspect-ratio:3/2;background:#13263c;border-radius:12px;margin:14px 0}.v11-chapters{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:16px 0}.v11-chapters button{min-height:48px;text-align:left}.v11-toolbar{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.toast{z-index:50}.v11-status{font-size:13px;color:#53687b}@media(max-width:790px){body{padding-bottom:calc(84px + env(safe-area-inset-bottom))}.topbar{position:sticky;top:0;padding:8px 12px}.topactions{display:grid;grid-template-columns:1fr 1fr;width:100%;gap:7px}.v11-home{grid-column:1/-1;min-height:44px}.topactions button{min-height:44px}input,select{font-size:16px!important}.v11-dock{position:fixed;left:0;right:0;bottom:0;display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,1fr) 46px;gap:7px;padding:9px 12px calc(9px + env(safe-area-inset-bottom));background:#fff;border-top:1px solid #cad8e5;z-index:25}.v11-dock .v11-home{grid-column:auto;font-size:14px;padding:7px 10px}.v11-dock button{min-height:44px;padding:7px;font-size:13px}.v11-chapters{grid-template-columns:1fr}.toast{bottom:calc(88px + env(safe-area-inset-bottom))}.v11-help{width:32px;min-height:32px}.v11-video{max-height:none}}@media print{.v11-dock,.v11-help,.v11-video,.v11-chapters{display:none!important}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}`;document.head.appendChild(s)}
for(const a of document.querySelectorAll('[data-home],#goHome')){a.href=HOME;a.target='_blank';a.rel='noopener noreferrer';a.className='v11-home';a.removeAttribute('style');a.textContent='← 回到工程工具';a.title='另開入口，保留目前查詢分頁'}
const anchor=document.querySelector('.footer');if(!document.querySelector('[data-view="dictionary"]'))anchor.insertAdjacentHTML('beforebegin','<section data-view="dictionary" class="hidden"><div class="panel other"><h2>參數辭典｜定義、單位與來源</h2><label for="v11-param-search">搜尋參數</label><input id="v11-param-search" class="v11-search" placeholder="例如：腹板、Ix、圓角"><p id="v11-param-count" role="status"></p><div id="v11-params"></div></div></section>');
if(!E('v11-video'))anchor.insertAdjacentHTML('beforebegin','<section data-view="tutorial" class="hidden"><div class="panel other"><h2>操作影片｜台灣女性旁白</h2><span class="v11-pill">繁體中文字幕・章節定位・離線內嵌</span><p id="v11-media-status" class="v11-status"></p><video id="v11-video" class="v11-video" controls playsinline preload="metadata" aria-label="型鋼資料庫操作教學影片"></video><div class="v11-toolbar"><label for="v11-speed">播放速度</label><select id="v11-speed"><option value="0.8">0.8 倍</option><option selected value="1">1 倍</option><option value="1.25">1.25 倍</option><option value="1.5">1.5 倍</option></select><button id="v11-download-video">下載 MP4</button><button id="v11-transcript-download">下載旁白文字</button></div><div id="v11-chapters" class="v11-chapters"></div><details><summary>完整旁白文字</summary><div id="v11-transcript"></div></details></div></section>');
if(!E('v11-codes'))document.querySelector('[data-view="source"] .panel').insertAdjacentHTML('afterbegin',`<div class="v11-context" id="v11-codes"><h2>結構規範對照｜公開來源核對日 2026-10-10</h2><p><b>整合範圍為規範來源、適用性及設計前檢核清單，不是新增構件耐力設計引擎。</b></p><div class="sourcebox"><b>熱軋型鋼尺寸與公差：CNS 1490</b><p>標準檢驗局 2026 年標準確認徵詢列前次公布日為 2020-10-19。這不是 2026 年新版結構設計規範；後續確認結果及正文仍應查 CNS 官方系統。</p><a href="https://www.bsmi.gov.tw/wSite/public/Data/f1774507899654.pdf#page=44" target="_blank" rel="noopener noreferrer">官方標準確認公告，第 44 頁</a></div><div class="sourcebox"><b>鋼構造建築物鋼結構設計技術規範</b><p>國土管理署列示 96.6.11 修正發布，99.9.16 修正 ASD／極限設計法第十三．二點。依專案適用法規及設計方法另檢核軸力、抗彎、剪力、局部與整體穩定、耐震及接合。</p><a href="https://www.nlma.gov.tw/ch/legislation/regsearch/7176" target="_blank" rel="noopener noreferrer">國土管理署官方規範</a></div><div class="sourcebox"><b>冷軋型鋼构造建築物結構設計規範及解說</b><p>官方列示 104.10.29 修正、105.1.1 生效。有效斷面、局部與扭曲挫屈等設計不能由本工具的毛斷面幾何值取代。</p><a href="https://www.nlma.gov.tw/ch/legislation/regsearch/968" target="_blank" rel="noopener noreferrer">國土管理署冷軋型鋼規範</a></div><p>未實作 Fy／Fu、設計載重、支承條件、寬厚比分類、KL/r、側向扭轉挫屈、有效斷面、J／Cw、接合及耐震設計。本工具不出具「結構安全合格」結論或 CNS 認證。</p></div>`);
E('v11-codes').innerHTML=E('v11-codes').innerHTML.replaceAll('构造','構造');
for(const [tab,label]of [['dictionary','? 參數辭典'],['tutorial','▶ 操作影片']])if(!document.querySelector('[data-tab="'+tab+'"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.tab=tab;b.textContent=label;document.querySelector('.side nav').appendChild(b)}
if(!E('v11-open-video'))document.body.insertAdjacentHTML('beforeend',`<nav class="v11-dock" aria-label="手機固定導覽"><a data-home class="v11-home" href="${HOME}" target="_blank" rel="noopener noreferrer">← 回到工程工具</a><button id="v11-open-video">▶ 操作影片</button><button id="v11-go-top" aria-label="回到頁首">↑</button></nav>`);
const tab0=setTab;setTab=function(tab){if(tab!=='tutorial')E('v11-video').pause();tab0(tab);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'))};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));E('v11-open-video').onclick=()=>setTab('tutorial');E('v11-go-top').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
function help(){for(const p of P){const x=E(p[0]),f=x?.closest('.field'),l=f?.querySelector('label');if(!x||!f||!l||f.querySelector('.v11-help'))continue;const b=document.createElement('button');b.type='button';b.className='v11-help';b.textContent='?';b.setAttribute('aria-label',p[1]+'的定義與來源');b.setAttribute('aria-expanded','false');const h=document.createElement('div');h.id='hint-'+p[0];h.className='v11-hint';h.hidden=true;h.textContent=p[2]+'｜'+p[3]+' '+p[4];b.setAttribute('aria-controls',h.id);x.setAttribute('aria-describedby',h.id);l.appendChild(b);f.appendChild(h);b.onclick=e=>{e.preventDefault();h.hidden=!h.hidden;b.setAttribute('aria-expanded',String(!h.hidden))}}}
function dictionary(){const q=E('v11-param-search').value.trim().toLowerCase(),found=P.filter(p=>p.join(' ').toLowerCase().includes(q));E('v11-param-count').textContent='顯示 '+found.length+' / '+P.length+' 項';E('v11-params').innerHTML=found.map(p=>'<article class="v11-para-card"><h3>'+esc(p[1])+'（'+esc(p[2])+'）</h3><p>'+esc(p[3])+'</p><p>來源／注意：'+esc(p[4])+'</p></article>').join('')||'<p>沒有符合的參數。</p>'}E('v11-param-search').oninput=dictionary;dictionary();
state.lengthValue=state.lengthValue||'6';state.quantityValue=state.quantityValue||'4';weightUpdate=function(){const L=Number(E('length').value),n=Number(E('quantity').value),r=get(state.selected);state.lengthValue=E('length').value;state.quantityValue=E('quantity').value;const kg=r?.W*L*n,ok=Number.isFinite(L)&&L>0&&Number.isSafeInteger(n)&&n>0&&Number.isFinite(kg);E('length').setAttribute('aria-invalid',String(!(Number.isFinite(L)&&L>0)));E('quantity').setAttribute('aria-invalid',String(!(Number.isSafeInteger(n)&&n>0)));E('totalWeight').textContent=ok?'重量 '+fmt(kg,1)+' kg ≈ '+fmt(kg/1000,4)+' t':'請輸入大於 0 的長度及正整數支數。'};
const rd=renderDetail;renderDetail=function(){rd();if(E('length')){E('length').value=state.lengthValue;E('quantity').value=state.quantityValue;E('length').oninput=weightUpdate;E('quantity').oninput=weightUpdate;weightUpdate()}help()};
const c0=calculate;calculate=function(p){if(p.type==='SHS'&&Math.abs(Number(p.H)-Number(p.B))>1e-8)throw Error('方形鋼管必須 H＝B。');return c0(p)};
const ae=addExample;addExample=function(){state.minIx=0;state.maxW=0;E('minIx').value='';E('maxW').value='';state.lengthValue='6';state.quantityValue='4';ae();renderDetail()};E('example').onclick=addExample;
const rr=renderRows;renderRows=function(){rr();E('tbody').querySelectorAll('tr[data-id]').forEach(tr=>{tr.tabIndex=0;tr.setAttribute('aria-selected',String(tr.dataset.id===state.selected))})};E('tbody').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const tr=e.target.closest('tr[data-id]');if(tr){e.preventDefault();select(tr.dataset.id)}}});
for(const id of ['minIx','maxW'])E(id).addEventListener('input',()=>{const bad=E(id).value!==''&&(!Number.isFinite(Number(E(id).value))||Number(E(id).value)<0);E(id).setAttribute('aria-invalid',String(bad));if(bad)toast('篩選值不能為負數；目前按不限制處理。')});
E('v11-transcript').innerHTML=CH.map((c,i)=>'<h3>'+String(i+1).padStart(2,'0')+' '+esc(c[0])+'</h3><p>'+esc(c[1])+'</p>').join('');E('v11-chapters').innerHTML=CH.map((c,i)=>'<button data-chapter="'+i+'">'+String(i+1).padStart(2,'0')+'　'+esc(c[0])+'</button>').join('');
if(M.src){E('v11-video').src=M.src;E('v11-media-status').textContent='已內嵌 MP4｜Microsoft HsiaoChen（zh-TW，女性合成語音），不依賴裝置語音。'}else E('v11-media-status').textContent='此開發版尚未封裝語音影片；以完成封裝的版本為準。';
E('v11-chapters').onclick=e=>{const b=e.target.closest('[data-chapter]');if(!b)return;if(!M.src)return toast('本版本尚未封裝影片。');E('v11-video').currentTime=M.times[Number(b.dataset.chapter)]||0;E('v11-video').play().catch(()=>toast('請按影片播放鍵開始。'))};E('v11-speed').onchange=e=>E('v11-video').playbackRate=Number(e.target.value);E('v11-download-video').onclick=()=>{if(!M.src)return toast('本版本尚未封裝影片。');const a=document.createElement('a');a.href=M.src;a.download='型鋼操作教學_台灣女性旁白.mp4';a.click()};E('v11-transcript-download').onclick=()=>saveFile(CH.map((c,i)=>(i+1)+' '+c[0]+'\n'+c[1]).join('\n\n'),'型鋼操作教學_旁白.txt','text/plain;charset=utf-8');
renderRows();renderDetail();setTab('lookup');
})();