(function(){'use strict';let stale=false,busy=false;
 const css='#report{overflow-wrap:anywhere;min-width:0;max-width:100%}#report .scroll{max-width:100%;overflow-x:auto}#report-content{min-width:0}#report table{max-width:none}#report .actions{flex-wrap:wrap}#report .actions button{white-space:normal;flex:0 1 auto;max-width:100%}#word-status{overflow-wrap:anywhere;max-width:100%}.cf-trace{overflow-wrap:anywhere}.cf-trace pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.8 system-ui}.cf-trace details{border:1px solid #d7e1eb;border-radius:8px;margin:12px 0}.cf-trace summary{padding:12px;cursor:pointer;font-weight:bold}.cf-trace article{padding:14px;border-bottom:1px solid #d7e1eb}@media print{.cf-trace details>div{display:block!important}.cf-trace article{break-inside:avoid}}';const style=document.querySelector('style');if(!style.textContent.includes('.cf-trace'))style.textContent+=css;
 const btn=$('word-report')||document.createElement('button');btn.id='word-report';btn.textContent='匯出 Word 計算書';if(!btn.isConnected)$('html-report').insertAdjacentElement('afterend',btn);const note=$('word-status')||document.createElement('span');note.id='word-status';note.setAttribute('role','status');note.textContent='';if(!note.isConnected)btn.insertAdjacentElement('afterend',note);
 function state(){btn.disabled=busy||stale||!result?.valid;}
 function traceHTML(r){return '<div class="cf-trace"><h3>10. 本次實際引擎計算紀錄</h3><p>'+r.trace.length+' 筆實際運算。多項式係數從常數項排列，解析積分與平衡残差來自原引擎。詳細值顯示12位有效數字，計算使用完整浮點數；只有連梁支數明示floor取整。</p>'+r.trace.map(s=>'<details><summary>'+esc(s.title)+'</summary><div><article><pre>公式：'+esc(s.formula)+'\n數值代入：'+esc(s.substitution)+'</pre><p><b>結果：'+esc(s.result)+(s.unit?' '+esc(s.unit):'')+'</b></p><p>條件及限制：'+esc(s.condition)+'</p><p class="meta">來源：'+esc(s.source)+'</p></article></div></details>').join('')+'</div>';}
 const oldDrawReport=drawReport;drawReport=function(r){oldDrawReport(r);$('report-content').insertAdjacentHTML('beforeend',traceHTML(r));stale=false;state();};
 document.addEventListener('input',e=>{if(e.target.closest('#input-groups')){stale=true;state();}},true);$('mode').addEventListener('change',()=>{stale=true;state();},true);
 const oldRun=run;run=function(){try{return oldRun();}finally{stale=!result?.valid;state();}};
 function snapshot(){if(stale||!result?.valid)throw Error('請先完成本次有效輸入計算後匯出。');const r=result,selected=$('plot-combo').selectedOptions[0]?.textContent||'';
 const inputs=[{label:'基礎型式',value:p.mode==='rect'?'長方形':p.mode==='trap'?'梯形':'懸臂聯合基礎',unit:'選項'},{label:'自訂Pu',value:p.manual?'是（僅本組合）':'否（兩規範組合）',unit:'選項'},...fields.map(f=>({label:f[1]+' ['+f[0]+']',value:r.p[f[0]],unit:f[2]}))];
 const plan=$('plan').querySelector('svg')?.outerHTML,plots=[...$('plots').querySelectorAll('svg')].map(s=>s.outerHTML);let y=0;const diagram='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 780" width="700" height="780">'+[plan,...plots].filter(Boolean).map((s,i)=>{const h=i?165:285;const out=s.replace('<svg ','<svg x="0" y="'+y+'" width="700" height="'+h+'" ');y+=h;return out;}).join('')+'</svg>';
 return structuredClone({valid:true,stale:false,title:'聯合基礎詳細計算書',summary:'本次輸入與計算快照；'+r.overall+'。幾何、土壓多項式、分段荷重與平衡殘差、各組合需求、剪力、沖切和配筋均由同一引擎保存；圖中內力曲線為 '+selected+'。',inputs,steps:r.trace,diagram:{svg:diagram,width:500,height:557,caption:'本次基礎與兩柱配置、沖切周界、使用總土壓及 '+selected+' 的剪力/彎矩曲線。示意圖非施工圖。'},conclusions:[...r.checks.map(c=>c.name+'：'+(c.pass===true?'通過':c.pass===false?'未通過':'需專案分析')+'；需求='+n(c.demand,6)+' '+c.unit+'；容量='+n(c.capacity,6)+' '+c.unit+'；組合='+c.combo),...r.warnings,'僅完成本頁明列範圍；沉陷、柱底彎矩、自由邊偏心沖切、水平力、浮力、液化、風震完整組合、錨定及施工細部另核。']});
 }
 btn.onclick=async()=>{if(busy)return;try{const r=snapshot();busy=true;state();note.textContent='正在建立本次 Word 計算書…';await CalculationDocx.download(r,'聯合基礎_詳細計算書.docx');note.textContent='Word 已建立，保留匯出開始時的輸入與圖示。';}catch(e){note.textContent=e.message;notify(e.message);}finally{busy=false;state();}};
 const oldOffline=$('offline').onclick;$('offline').onclick=()=>{if(stale||!result?.valid)return notify('請先修正本次輸入。');const prev=btn.disabled,text=note.textContent;btn.disabled=false;note.textContent='';try{oldOffline();}finally{btn.disabled=prev;note.textContent=text;}};
 window.CombinedFootingReport={snapshot,traceHTML,getResult:()=>result,getStale:()=>stale};if(result?.valid)drawReport(result);state();
})();
