/* SRC Beam 1.1 — units cm, kgf, kgf/cm². Pure section engine. */
(function(root){
'use strict';
const BARS={D10:[0.953,0.7133],D13:[1.27,1.267],D16:[1.59,1.986],D19:[1.91,2.865],D22:[2.22,3.871],D25:[2.54,5.067],D29:[2.87,6.469],D32:[3.22,8.143],D36:[3.58,10.07]};
const clone=x=>JSON.parse(JSON.stringify(x));
const defaults=()=>({b:50,h:80,hs:50,bf:20,tw:1,tf:1.6,xs:25,ys:40,fc:280,fy:4200,Fy:3500,Fyw:3500,Es:2100000,grade:'490',cover:4,agg:2,stirrup:'D13',legs:2,s:15,fyh:2800,Avf:2.534,mu:0.8,stud:0,mp:100,mn:100,vp:35,vn:35,shored:true,seismic:false,anchored:true,mode:'layers',layers:[{n:2,bar:'D32',y:8,x1:7,x2:43},{n:2,bar:'D32',y:14,x1:7,x2:43},{n:2,bar:'D32',y:66,x1:7,x2:43},{n:2,bar:'D32',y:72,x1:7,x2:43}],bars:[]});
function bars(p){if(p.mode==='manual')return p.bars.map(b=>({...b}));return p.layers.flatMap(l=>Array.from({length:l.n},(_,i)=>({x:l.n===1?l.x1:l.x1+(l.x2-l.x1)*i/(l.n-1),y:l.y,bar:l.bar,A:BARS[l.bar][1],db:BARS[l.bar][0]})));}
function rectangles(p,negative=false){const top=p.ys-p.hs/2,left=p.xs-p.bf/2;let rs=[{x:left,y:top,w:p.bf,h:p.tf},{x:p.xs-p.tw/2,y:top+p.tf,w:p.tw,h:p.hs-2*p.tf},{x:left,y:top+p.hs-p.tf,w:p.bf,h:p.tf}];return negative?rs.map(r=>({...r,y:p.h-r.y-r.h})):rs;}
function block(p,a,bs,negative){const stress=.85*p.fc;const grossA=p.b*a,grossQ=p.b*a*a/2;let A=grossA,Q=grossQ;const deductions=[];for(const [i,r] of rectangles(p,negative).entries()){const u=Math.max(0,Math.min(a,r.y+r.h)-r.y),area=r.w*u,q=area*(r.y+u/2);A-=area;Q-=q;deductions.push({kind:'steel',index:i+1,y:r.y,w:r.w,h:r.h,u,A:area,Q:q});}for(const [i,r] of bs.entries()){const rad=Math.sqrt(r.A/Math.PI),u=Math.max(-1,Math.min(1,(a-r.y)/rad));const ar=rad*rad*(Math.asin(u)+Math.PI/2+u*Math.sqrt(Math.max(0,1-u*u)));const q=r.y*ar-2/3*Math.pow(Math.max(0,rad*rad*(1-u*u)),1.5);A-=ar;Q-=q;deductions.push({kind:'bar',index:i+1,y:r.y,r:rad,u,A:ar,Q:q});}return {A,Q,F:stress*A,M:stress*Q,grossA,grossQ,deductions};}
function flex(p,negative=false){const bs=bars(p).map(b=>({...b,y:negative?p.h-b.y:b.y}));const beta=Math.max(.65,Math.min(.85,.85-.05*(p.fc-280)/70));function state(c){const a=Math.min(p.h,beta*c),con=block(p,a,bs,negative);const rs=bs.map(b=>{const eps=.003*(c-b.y)/c,stress=Math.max(-p.fy,Math.min(p.fy,p.Es*eps));return {...b,eps,stress,F:stress*b.A};});return {c,a,con,rs,N:con.F+rs.reduce((s,b)=>s+b.F,0)};}let lo=.000001,hi=p.h*2;const boundaryLo=state(lo),boundaryHi=boundaryLo.N>=0?null:state(hi);if(boundaryLo.N>=0||boundaryHi.N<=0)throw Error('RC 子斷面找不到軸力平衡，請檢查主筋。');const trace=[];for(let k=0;k<90;k++){const c=(lo+hi)/2,actual=state(c),N=actual.N;trace.push({k:k+1,lo,hi,c,N,state:actual,branch:N>0?'hi=c':'lo=c'});if(N>0)hi=c;else lo=c;}const z=state((lo+hi)/2);const tension=z.rs.filter(b=>b.y>p.h/2),At=tension.reduce((s,b)=>s+b.A,0),d=tension.reduce((s,b)=>s+b.A*b.y,0)/At;const et=Math.max(0,...z.rs.map(b=>-b.eps)),limit=p.fy/p.Es+.003;const Mr=Math.abs(z.con.M+z.rs.reduce((s,b)=>s+b.F*b.y,0))/1e5;const Z=p.bf*p.tf*(p.hs-p.tf)+p.tw*Math.pow(p.hs-2*p.tf,2)/4,Ms=Z*p.Fy/1e5;const phiRC=Math.max(.65,Math.min(.9,.65+.25*(et-p.fy/p.Es)/.003));return {...z,trace,bounds:{lo:boundaryLo,hi:boundaryHi,finalLo:lo,finalHi:hi},beta,d,et,limit,At,Z,rawMr:Mr,Mr:p.anchored?Mr:0,Ms,M:Ms+(p.anchored?Mr:0),phiRC,capacity:.9*Ms+(p.anchored?phiRC*Mr:0),tensionControlled:et>=limit-1e-9};}
function shear(p,f,V){const Av=BARS[p.stirrup][1]*p.legs,Aw=p.tw*p.hs,Vsteel=.6*p.Fyw*Aw/1000;const capR=2.12*Math.sqrt(p.fc)*p.b*f.d/1000;const Vr=Math.min(Av*p.fyh*f.d/p.s/1000,capR),Vc=.53*Math.sqrt(p.fc)*p.b*f.d/1000;const Vfr=Math.min(p.mu*p.Avf*p.fyh*f.d/p.s/1000,p.mu*capR),Vfc=28*(p.b-p.bf)*f.d/1000;const normal=Vr+Vc,friction=Vfr+Vfc+p.stud,Vrc=Math.min(normal,friction),alpha=f.Ms/f.M;const ds=V*alpha,dr=V*(1-alpha);const cs=.9*Vsteel,cr=.75*Vrc;return {capR,V,stirrupArea:BARS[p.stirrup][1],stirrupDiameter:BARS[p.stirrup][0],vrRaw:Av*p.fyh*f.d/p.s/1000,vfrRaw:p.mu*p.Avf*p.fyh*f.d/p.s/1000,vfrLimit:p.mu*capR,steelEquivalent:cs/alpha,rcEquivalent:cr/(1-alpha),Av,Aw,Vsteel,Vr,Vc,Vfr,Vfc,normal,friction,Vrc,alpha,ds,dr,cs,cr,rs:ds/cs,rr:dr/cr,capacity:Math.min(cs/alpha,cr/(1-alpha))};}
function geometry(p){const errors=[];const warnings=[];const checks=[];const barSteelCandidates=[],barPairCandidates=[];const add=(name,ok,detail)=>checks.push({name,ok,detail});const bs=bars(p),sd=BARS[p.stirrup][0];const steelCover=Math.min(p.xs-p.bf/2,p.b-p.xs-p.bf/2,p.ys-p.hs/2,p.h-p.ys-p.hs/2),reqSteel=bs.some(b=>b.db>=2.22)?12.5:10;
add('鋼骨保護層',steelCover>=reqSteel,`${steelCover.toFixed(2)} ≥ ${reqSteel} cm · SRC 4.5`);
const fl=p.bf/p.tf,wl=(p.hs-2*p.tf)/p.tw,lf=p.grade==='490'?20:23,lw=p.grade==='490'?91:107;
add('翼板寬厚比',fl<=lf,`bf/tf = ${fl.toFixed(2)} ≤ ${lf} · 表 3.4-1`);add('腹板寬厚比',wl<=lw,`hc/tw = ${wl.toFixed(2)} ≤ ${lw} · 表 3.4-1`);
add('材料適用範圍',p.fc>=210&&p.fc<=420&&p.Fy<=3520&&p.Fyw<=3520&&p.fy<=5600,`fc′ 210–420；Fys / Fyw ≤ 3520；Fyr ≤ 5600 kgf/cm² · SRC 5.3`);
const rbCover=Math.min(...bs.map(b=>Math.min(b.x,p.b-b.x,b.y,p.h-b.y)-b.db/2-sd));add('主筋位於箍筋內側',rbCover>=p.cover-1e-8,`換算箍筋外側保護層 ${rbCover.toFixed(2)} ≥ 輸入 ${p.cover} cm`);add('箍筋保護層（一般室內梁）',p.cover>=4,`${p.cover} ≥ 4 cm；特殊曝露、耐火另核`);
let sg=Infinity;for(const b of bs)for(const r of rectangles(p)){const dx=Math.max(r.x-b.x,0,b.x-r.x-r.w),dy=Math.max(r.y-b.y,0,b.y-r.y-r.h);const gap=Math.hypot(dx,dy)-b.db/2;barSteelCandidates.push({bar:b,rectangle:r,dx,dy,gap});sg=Math.min(sg,gap);}
const minSG=Math.max(2.5,1.25*p.agg);add('主筋至鋼骨淨距',sg>=minSG-1e-8,`${sg.toFixed(2)} ≥ ${minSG.toFixed(2)} cm · SRC 4.4`);
const stGap=steelCover-p.cover-sd;add('箍筋至鋼骨淨距',stGap>=2.5,`${stGap.toFixed(2)} ≥ 2.5 cm · SRC 4.4`);
let minBar=Infinity,spacingOK=true;for(let i=0;i<bs.length;i++)for(let j=i+1;j<bs.length;j++){const u=bs[i],v=bs[j],gap=Math.hypot(u.x-v.x,u.y-v.y)-(u.db+v.db)/2;const same=Math.abs(u.y-v.y)<.01,req=same?Math.max(2.5,u.db,v.db,4/3*p.agg):Math.max(2.5,1.25*p.agg);barPairCandidates.push({i:i+1,j:j+1,u,v,gap,same,req,ok:gap>=req-1e-8});minBar=Math.min(minBar,gap);if(gap<req-1e-8)spacingOK=false;}
add('主筋淨距',spacingOK,`最小 ${minBar.toFixed(2)} cm；同層 max(2.5, db, 4dagg/3)，層間 2.5 且骨材需求`);
const smax=Math.min(p.h/2,p.stirrup==='D10'?25:45);add('箍筋直徑與間距',sd>=.953&&p.s>=7.5&&p.s<=smax,`${p.stirrup} @ ${p.s} cm；7.5 ≤ s ≤ ${smax} · SRC 4.3.4`);
add('最小箍筋比',BARS[p.stirrup][1]*p.legs/(p.b*p.s)>=.001,`ρw = ${(100*BARS[p.stirrup][1]*p.legs/(p.b*p.s)).toFixed(3)}% ≥ 0.1%`);
add('四角配置主筋',[true,false].every(bottom=>[true,false].every(right=>bs.some(b=>(b.y>p.h/2)===bottom&&(b.x>p.b/2)===right))),'矩形梁四角各配置有效主筋 · SRC 4.3.2');
add('主筋連續或適當錨定',p.anchored,'SRC 5.4：未連續且未適當錨定之主筋不得計入抗彎');
if(bs.some(b=>b.x>=p.xs-p.bf/2&&b.x<=p.xs+p.bf/2))warnings.push('有主筋位於鋼骨翼板投影範圍；須以梁柱接頭詳圖確認可連續通過或適當錨定。');
if(!p.shored)warnings.push('施工階段未設充分臨時支撐：須另完成裸鋼梁強度、側扭挫屈與撓度檢核（SRC 3.3 / 5.3）。');
if(p.seismic)warnings.push('已指定耐震用途：本頁第五章檢核不能取代第九章塑鉸剪力、梁柱接頭及耐震細部設計。');
checks.filter(c=>!c.ok).forEach(c=>errors.push(c.name+'未符合'));return {checks,errors,warnings,steelCover,minBar,sg,barSteelCandidates,barPairCandidates,raw:{reqSteel,fl,wl,lf,lw,rbCover,minSG,stGap,smax,spacingOK,stirrupDiameter:sd,stirrupRatio:BARS[p.stirrup][1]*p.legs/(p.b*p.s),steelCoverCandidates:[p.xs-p.bf/2,p.b-p.xs-p.bf/2,p.ys-p.hs/2,p.h-p.ys-p.hs/2],barCoverCandidates:bs.map(b=>({bar:b,cover:Math.min(b.x,p.b-b.x,b.y,p.h-b.y)-b.db/2-sd}))}};}
function validate(p){const positive=['b','h','hs','bf','tw','tf','fc','fy','Fy','Fyw','Es','cover','agg','s','fyh'];for(const k of positive)if(!Number.isFinite(p[k])||p[k]<=0)throw Error(`${k} 必須為大於零的有限數值。`);if(!['400','490'].includes(p.grade)||!BARS[p.stirrup])throw Error('材料級別或箍筋號數無效。');for(const k of ['xs','ys','Avf','mu','stud','mp','mn','vp','vn'])if(!Number.isFinite(p[k])||p[k]<0)throw Error(`${k} 不得為負或空白。`);if(p.mu>0.8)throw Error('常重混凝土 μ 不得大於 0.8。');if(p.hs<=2*p.tf||p.bf<=p.tw)throw Error('H 型鋼尺寸不成立：hs > 2tf 且 bf > tw。');if(!Number.isInteger(p.legs)||p.legs<2||p.legs>12)throw Error('有效箍筋肢數须為 2–12 整數。');if(p.Avf>BARS[p.stirrup][1]*p.legs+1e-8)throw Error('剪力摩擦有效面積 Avf 不得大於總箍筋面積 Av。');if(p.xs-p.bf/2<=0||p.xs+p.bf/2>=p.b||p.ys-p.hs/2<=0||p.ys+p.hs/2>=p.h)throw Error('鋼骨必須完全包覆於混凝土內。');if(p.mode==='layers'){if(!p.layers.length||p.layers.length>30)throw Error('主筋層數須為 1–30。');for(const l of p.layers)if(!BARS[l.bar]||!Number.isInteger(l.n)||l.n<1||l.n>30||![l.y,l.x1,l.x2].every(Number.isFinite)||l.x2<l.x1)throw Error('配筋層的數量、位置或號數無效。');}else if(p.mode!=='manual')throw Error('主筋輸入方式無效。');const bs=bars(p);if(bs.length<2||bs.length>200)throw Error('須有 2–200 支主筋。');for(const b of bs)if(![b.A,b.db,b.x,b.y].every(Number.isFinite)||b.A<=0||b.db<=0||Math.min(b.x,p.b-b.x,b.y,p.h-b.y)<=b.db/2)throw Error('主筋面積、直徑及座標須有效且位於斷面內。');if(!bs.some(b=>b.y<p.h/2)||!bs.some(b=>b.y>p.h/2))throw Error('頂部與底部均須配置有效主筋。');}
function calculate(p){validate(p);const pos=flex(p),neg=flex(p,true);const sp=shear(p,pos,p.vp),sn=shear(p,neg,p.vn),g=geometry(p);g.checks.push({name:'正彎矩 RC 拉力控制',ok:pos.tensionControlled,detail:`εt = ${pos.et.toFixed(6)} ≥ εty + 0.003 = ${pos.limit.toFixed(6)} · RC 9.3.3.1`},{name:'負彎矩 RC 拉力控制',ok:neg.tensionControlled,detail:`εt = ${neg.et.toFixed(6)} ≥ ${neg.limit.toFixed(6)}`});if(!pos.tensionControlled||!neg.tensionControlled)g.errors.push('RC 子斷面非拉力控制，須調整斷面或配筋');const ratios=[p.mp/pos.capacity,p.mn/neg.capacity,sp.rs,sp.rr,sn.rs,sn.rr];const valid=g.errors.length===0;const status=!valid?'不符合適用條件':Math.max(...ratios)>1?'強度不足':p.seismic||!p.shored?'需補充檢核':'本頁檢核通過';return {pos,neg,sp,sn,g,ratios,status,valid,maxRatio:Math.max(...ratios)};}
function design(p){const candidates=[],audit=[];for(const bar of ['D22','D25','D29','D32','D36'])for(let n=1;n<=3;n++){const db=BARS[bar][0],edge=p.cover+BARS[p.stirrup][0]+db/2+.2,gap=Math.max(2.5,1.25*p.agg),layers=[];for(let k=0;k<n;k++){const y=edge+k*(db+gap);layers.push({n:2,bar,y,x1:edge,x2:p.b-edge},{n:2,bar,y:p.h-y,x1:edge,x2:p.b-edge});}const q={...clone(p),mode:'layers',layers};try{const r=calculate(q);audit.push({bar,n,input:q,result:r,accepted:r.valid&&r.maxRatio<=1});if(r.valid&&r.maxRatio<=1)candidates.push({bar,n,As:2*n*BARS[bar][1],layers,r});}catch(error){audit.push({bar,n,input:q,accepted:false,error:error.message});}}
const output=candidates.sort((a,b)=>a.As-b.As||a.n-b.n).slice(0,5);output.audit=audit;return output;}
root.SRC={BARS,defaults,bars,rectangles,block,flex,shear,geometry,validate,calculate,design};if(typeof module!=='undefined')module.exports=root.SRC;
})(typeof globalThis!=='undefined'?globalThis:this);


