(function(){'use strict';let busy=false,audit=[];const style=document.querySelector('style');if(!style.textContent.includes('.src-execution'))style.textContent+='.src-execution{overflow-wrap:anywhere}.src-execution table{min-width:960px;table-layout:fixed}.src-execution td{vertical-align:top}.src-execution pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 system-ui}.src-execution details{border:1px solid #d5e0e7;padding:12px;margin:12px 0;border-radius:7px}@media print{.src-execution details>div{display:block!important}}';
const btn=$('word-export')||document.createElement('button');btn.id='word-export';btn.textContent='匯出 Word 計算書';if(!btn.isConnected)$('print').insertAdjacentElement('afterend',btn);const note=$('word-status')||document.createElement('span');note.id='word-status';note.setAttribute('role','status');note.textContent='';if(!note.isConnected)btn.insertAdjacentElement('afterend',note);
const json=x=>JSON.stringify(x,null,2),str=x=>String(x??''),table=(title,headers,rows,note='')=>({title,headers,rows:rows.map(r=>r.map(str)),note,source:'本次SRC原引擎实际運算；座標cm、面積cm²、應力kgf/cm²、內力kgf、第一矩cm³、力矩kgf·cm，最終轉tf/tf·m'});
function histories(r){let out=[];for(const [name,f]of[['正彎矩',r.pos],['負彎矩',r.neg]]){out.push(table(name+'90次實際二分狀態',['迭代/界限/分支','混凝土實際扣除與合力','逐支鋼筋實際狀態'],f.trace.map(t=>[json({k:t.k,lo:t.lo,hi:t.hi,c:t.c,a:t.state.a,N:t.N,branch:t.branch}),json(t.state.con),json(t.state.rs)]),'每列保存同一次state(c)。con：A/Q/F/M、grossA/grossQ、鋼骨矩形及钢筋圓段deductions；rs：x/y/A/db/eps/stress/F。固定90次，N>0縮hi，否則縮lo；沒有提前停止。'));out.push(table(name+'初始與最終邊界',['位置','實際狀態'],[['初始lo',json(f.bounds.lo)],['初始hi',json(f.bounds.hi)],['最終',json({lo:f.bounds.finalLo,hi:f.bounds.finalHi,c:f.c,N:f.N})]]));}
out.push(table('逐對鋼筋/鋼骨淨距候選',['鋼筋/鋼骨','dx/dy','gap'],r.g.barSteelCandidates.map(q=>[json({bar:q.bar,rectangle:q.rectangle}),json({dx:q.dx,dy:q.dy}),q.gap]),'dx/dy=max(距離,0)；gap=hypot(dx,dy)-db/2；全部取min再比max(2.5,1.25agg)。'));
out.push(table('逐對鋼筋淨距候選',['支號/座標','gap/req/same','通過'],r.g.barPairCandidates.map(q=>[json({i:q.i,j:q.j,u:q.u,v:q.v}),json({gap:q.gap,req:q.req,same:q.same}),q.ok]),'same=abs(yi-yj)<.01；同層req=max(2.5,dbi,dbj,4agg/3)，異層max(2.5,1.25agg)；gap>=req-1e-8。'));
out.push(table('剪力實際候選與容量', ['方向','原引擎各中間值'], [['正向',json(r.sp)],['負向',json(r.sn)]], 'Av=原BARS面積×legs；Vr=min(vrRaw,capR)；Vfr=min(vfrRaw,vfrLimit)；Vrc=min(normal,friction)；alpha=Ms/M；需求分配ds=V alpha/dr=V(1-alpha)；capacity=min(steelEquivalent,rcEquivalent)。完整原式與代入見原剪力章節。'));out.push(table('幾何門檻與原候選',['項目','值'],Object.entries(r.g.raw).map(([k,v])=>[k,typeof v==='object'?json(v):v]),'原SRC表3.4-1：grade490的fl/wl上限20/91，400為23/107；各保護層最小值及箍筋/材料/錨定/拉力控制依原checks。'));
if(audit.length)out.push(table('實際全部配筋搜尋候選',['號數/層數/實際輸入','實際容量/比值/錯誤','入選'],audit.map(a=>[json({bar:a.bar,n:a.n,layers:a.input.layers}),a.error||json({pos:a.result.pos.capacity,neg:a.result.neg.capacity,maxRatio:a.result.maxRatio,valid:a.result.valid,errors:a.result.g.errors,cPos:a.result.pos.c,cNeg:a.result.neg.c}),a.accepted]),'D22/D25/D29/D32/D36各1~3層，共15個實際calculate；有效且maxRatio<=1才入選。按As再n升序，顯示前5。'));return out;}
function show(){if(!result)return;const host=document.createElement('div');host.className='src-execution calc-card';host.innerHTML='<h3>同引擎完整迭代及幾何候選</h3><p>各二分點保留真正求解的混凝土圓段扣除、逐支應變/應力/內力；數字保持完整浮點精度。單位與符號見原計算書。</p>'+histories(result).map(t=>'<details><summary>'+esc(t.title)+'（'+t.rows.length+'列）</summary><div><p>'+esc(t.note)+'</p><div class="table-wrap"><table><thead><tr>'+t.headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+t.rows.map(row=>'<tr>'+row.map(x=>'<td><pre>'+esc(x)+'</pre></td>').join('')+'</tr>').join('')+'</tbody></table></div></div></details>').join('');$('process-content').append(host);}
const oldProcess=process;process=function(){oldProcess();show();};const oldRun=run;run=function(){audit=[];try{return oldRun();}finally{btn.disabled=busy||!result;}};const oldDesign=SRC.design;SRC.design=function(q){const cs=oldDesign(q);audit=cs.audit||[];return cs;};
function snapshot(){if(!result)throw Error('請先修正無效輸入並完成計算。');process();let inputs=Object.values(specs).flat().map(f=>({label:f[1]+' ['+f[0]+']',value:p[f[0]],unit:f[2]}));for(const k of['anchored','shored','seismic','mode'])inputs.push({label:k,value:p[k],unit:'條件'});inputs.push({label:'逐支鋼筋本次座標/號數/A/db',value:json(SRC.bars(p)),unit:'cm、cm²'});const cards=[...$('process-content').querySelectorAll('.calc-card')].filter(c=>!c.classList.contains('src-execution'));const steps=cards.map(c=>{const copy=c.cloneNode(true);copy.querySelectorAll('table,h3').forEach(e=>e.remove());return {title:c.querySelector('h3')?.textContent||'計算',formula:copy.textContent,substitution:'本次輸入與SRC.calculate同一結果；各式有實際代入值，附表保留逐支/迭代明細。',result:result.status,condition:'原RC子斷面+鋼骨強度疊加及適用限制；工程檢核不符仍可輸出診斷，無效輸入禁止輸出。',source:'原SRC計算書各章節、原內建鋼筋表'}});const tables=cards.flatMap(c=>[...c.querySelectorAll('table')].map((t,i)=>{let rows=[...t.querySelectorAll('tr')].map(row=>[...row.children].map(x=>x.textContent));return rows.length?table(c.querySelector('h3')?.textContent+' 表'+(i+1),rows[0],rows.slice(1)):null}).filter(Boolean));tables.push(...histories(result));tables.push(table('原內建鋼筋資料表',['列鍵/號數','db cm','A cm²'],Object.entries(SRC.BARS).map(([k,v])=>[k,...v]),'按本次號數讀取原BARS同一列db/A，無修正；manual採輸入A/db。'));return structuredClone({valid:true,stale:false,title:'SRC梁詳細計算書',summary:result.status+'；正負彎矩各90次實際求解、全部幾何候選與剪力分擔。圖示='+direction,inputs,steps,tables,diagram:{svg:$('drawing').outerHTML.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '),width:520,height:520*440/Number($('drawing').getAttribute('viewBox').split(' ')[2]),caption:'本次'+(direction==='positive'?'正':'負')+'彎矩截面、RC中性軸與混凝土壓力區、實際鋼骨與鋼筋配置。'},conclusions:[...result.g.checks.map(c=>c.name+'：'+(c.ok?'通過':'不符')+'；'+c.detail),...result.g.warnings,'狀態='+result.status+'；最大D/C='+result.maxRatio,'施工支撐、接頭、錨定、撓度及耐震細節依原限制另核。']});}
btn.onclick=async()=>{if(busy)return;try{const r=snapshot();busy=true;btn.disabled=true;note.textContent='正在產生完整Word…';await CalculationDocx.download(r,'SRC梁_詳細計算書.docx');note.textContent='Word已產生，保留匯出開始時的輸入、迭代與圖。';}catch(e){note.textContent=e.message;notify(e.message);}finally{busy=false;btn.disabled=!result;}};const oldOffline=$('offline').onclick;$('offline').onclick=()=>{const disabled=btn.disabled,text=note.textContent;btn.disabled=false;note.textContent='';try{oldOffline();}finally{btn.disabled=disabled;note.textContent=text;}};window.SRCExecution={snapshot,getResult:()=>result,getAudit:()=>audit};btn.disabled=!result;if(result&&!$('process').hidden)process();
})();
