const assert = require('node:assert/strict');
const path = require('node:path');
const {chromium} = require('playwright');
const SRC = require('./engine.js');
(async () => {
  const p = SRC.defaults();
  const r = SRC.calculate(p);
  for (const f of [r.pos, r.neg]) {
    assert.equal(f.trace.length, 90);
    assert(f.trace[0].N > 0);
    assert(Math.abs(f.trace.at(-1).N) < 1e-4);
    assert(Math.abs(f.con.grossA - f.con.deductions.reduce((s,x)=>s+x.A,0) - f.con.A) < 1e-9);
    assert(Math.abs(f.con.grossQ - f.con.deductions.reduce((s,x)=>s+x.Q,0) - f.con.Q) < 1e-8);
    assert.equal(f.con.deductions.filter(x=>x.kind==='bar'&&x.A>0).length,2);
  }
  const browser = await chromium.launch({headless:true,executablePath:'/root/.cache/hyperframes/chrome/chrome-headless-shell/linux-152.0.7977.30/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:1512,height:982}});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('file://'+path.resolve('src-beam/index.html'));
  await page.locator('[data-view="process"]').click();
  let content = await page.locator('#process-content').innerText();
  for(const term of ['12.085600946','10.272760804','497.3520402','87.925268','145.168081','63.234577','84.070336','逐支主筋應變','負彎矩','中性軸 c 的數值求解']) assert(content.includes(term),term);
  assert(!/NaN|undefined|Infinity/.test(content));
  assert.equal(await page.locator('.all-iterations').count(),2);
  await page.locator('.all-iterations summary').first().click();
  assert.equal(await page.locator('.all-iterations').first().locator('tbody tr').count(),90);
  await page.locator('.all-iterations summary').first().click();
  await page.screenshot({path:'src-beam/detail-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  await page.locator('.bar-detail-table').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:'src-beam/detail-mobile.png'});
  await page.setViewportSize({width:800,height:1000});
  await page.emulateMedia({media:'print'});
  assert(await page.locator('#process').isVisible());
  const printLayout=await page.locator('.bar-detail-table').first().evaluate(t=>({table:t.getBoundingClientRect().width,parent:t.parentElement.getBoundingClientRect().width}));
  assert(printLayout.table<=printLayout.parent+1,JSON.stringify(printLayout));
  await page.locator('.bar-detail-table').first().scrollIntoViewIfNeeded();
  await page.screenshot({path:'src-beam/detail-print.png'});
  await page.pdf({path:'src-beam/detail-print-qa.pdf',format:'A4',margin:{top:'12mm',right:'12mm',bottom:'12mm',left:'12mm'},printBackground:true});
  await page.emulateMedia({media:'screen'});
  await page.setViewportSize({width:1512,height:982});
  await page.locator('[data-view="analysis"]').click();
  await page.locator('#anchored').uncheck();
  await page.locator('[data-view="process"]').click();
  content=await page.locator('#process-content').innerText();
  assert(content.includes('0 tf-m（未確認主筋錨定'));
  assert(content.includes('66.035340'));
  await page.locator('#example').click();
  await page.locator('[data-view="analysis"]').click();
  await page.locator('#mp').fill('200');
  await page.locator('[data-view="process"]').click();
  content=await page.locator('#process-content').innerText();
  assert(content.includes('200.000000 / 145.168081'));
  assert(content.includes('強度不足'));
  await page.locator('[data-view="analysis"]').click();
  await page.locator('#fc').fill('');
  await page.locator('[data-view="process"]').click();
  assert((await page.locator('#process-content').innerText()).includes('輸入無效'));
  assert.equal(errors.length,0,errors.join('\n'));
  await browser.close();
  console.log('Detailed report passed: trace, block deductions, example values, 90-row expansion, mobile, print, anchorage, overload, invalid inputs.');
})().catch(e=>{console.error(e);process.exit(1)});

