const assert=require('assert'),fs=require('fs'),S=require('./engine'),ref=require('./independent-reference.json');const tests=[];let failures=0;const clone=x=>JSON.parse(JSON.stringify(x));const test=(name,fn)=>{try{const x=fn();tests.push({name,expected:x?.expected||'應符合定義',actual:x?.actual||'結果符合',pass:true})}catch(e){failures++;tests.push({name,expected:'應符合定義',actual:e.message,pass:false})}};const near=(name,value,expected,tol=1e-7)=>test(name,()=>{assert(Math.abs(value-expected)<=tol,`${value} vs ${expected}`);return {expected:expected.toFixed(8),actual:value.toFixed(8)+'；差 '+Math.abs(value-expected).toExponential(2)}});let p=S.defaults(),r=S.calculate(p);
near('H 鋼 Z：分塊一次矩手算',r.pos.Z,ref.Z);near('鋼骨標稱彎矩 Fys Z',r.pos.Ms,ref.Ms);near('RC c：0.001 cm 切片積分獨立解',r.pos.c,ref.c,1e-5);near('RC Mnrc：獨立切片積分',r.pos.Mr,ref.Mr,1e-5);near('SRC 折減抗彎強度',r.pos.capacity,ref.capacity,1e-5);near('鋼骨剪力：全深度 Aw',r.sp.Vsteel,ref.Vs);near('RC 混凝土剪力單位係數',r.sp.Vc,ref.Vc);near('箍筋剪力 Av Fyh d/s',r.sp.Vr,ref.Vr);near('剪力摩擦獨立公式',r.sp.friction,ref.friction);near('RC 設計剪力較小值',r.sp.cr,ref.rcShearCapacity);near('RC 有效深度為受拉面主筋形心',r.pos.d,69);near('對稱斷面正負容量一致',r.pos.capacity,r.neg.capacity);near('RC 軸力平衡殘差',r.pos.N,0,1e-6);
test('分層與逐支輸入結果一致',()=>{let q=clone(p);q.bars=S.bars(q);q.mode='manual';assert(Math.abs(S.calculate(q).pos.capacity-r.pos.capacity)<1e-9)});
test('不對稱配筋可分別求正負強度',()=>{let q=clone(p);q.layers[3].bar='D25';const z=S.calculate(q);assert(Math.abs(z.pos.capacity-z.neg.capacity)>1)});
test('負彎矩反轉：鏡射後等於原正彎矩',()=>{let q=clone(p);q.mode='manual';q.bars=S.bars(p).map((b,i)=>({...b,A:i>3?b.A*.8:b.A,y:p.h-b.y}));const z=S.flex(q,true);let orig=clone(q);orig.bars=orig.bars.map(b=>({...b,y:p.h-b.y}));assert(Math.abs(z.Mr-S.flex(orig).Mr)<1e-9)});
test('剪力分配守恆',()=>{assert(Math.abs(r.sp.ds+r.sp.dr-p.vp)<1e-9)});
test('剪力摩擦成為控制模式',()=>{let q=clone(p);q.mu=.35;q.Avf=0;const z=S.calculate(q);assert(z.sp.Vrc===z.sp.friction);assert(z.sp.friction<z.sp.normal)});
test('箍筋貢獻上限 2.12 √fc′ bd',()=>{const q={...p,legs:12,s:.01,Avf:0};const z=S.shear(q,r.pos,35);assert(Math.abs(z.Vr-2.12*Math.sqrt(p.fc)*p.b*r.pos.d/1000)<1e-7)});
test('超額需求顯示強度不足',()=>{let q=clone(p);q.mp=200;assert(S.calculate(q).status==='強度不足')});
test('鋼骨保護層不足不可顯示通過',()=>{let q=clone(p);q.hs=60;assert(!S.calculate(q).valid)});
test('鋼筋與鋼骨碰撞檢查',()=>{let q=clone(p);q.layers[0].y=16;q.layers[0].x1=20;q.layers[0].x2=30;assert(!S.calculate(q).g.checks.find(c=>c.name==='主筋至鋼骨淨距').ok)});
test('箍筋間距低於 7.5 cm 不通過',()=>{let q=clone(p);q.s=5;assert(!S.calculate(q).valid)});
test('鋼材超出 SRC 強度範圍不通過',()=>{let q=clone(p);q.Fy=4200;assert(!S.calculate(q).valid)});
test('未錨定主筋不計入 RC 抗彎',()=>{let q=clone(p);q.anchored=false;let z=S.calculate(q);assert(z.pos.Mr===0&&Math.abs(z.pos.capacity-.9*z.pos.Ms)<1e-9&&!z.valid)});
test('耐震用途顯示需補充檢核',()=>{let q=clone(p);q.seismic=true;assert(S.calculate(q).status==='需補充檢核')});
test('未充分施工支撐顯示需補充檢核',()=>{let q=clone(p);q.shored=false;assert(S.calculate(q).status==='需補充檢核')});
for(const [name,mutate]of [['空白材料參數',q=>q.fc=NaN],['零腹板厚',q=>q.tw=0],['非整數主筋支數',q=>q.layers[0].n=2.5],['鋼骨位於斷面外',q=>q.xs=2],['Avf 超過 Av',q=>q.Avf=5],['負值需求',q=>q.mp=-1],['主筋位於混凝土外',q=>q.layers[0].x1=-2]])test(name+'會阻擋',()=>{let q=clone(p);mutate(q);assert.throws(()=>S.calculate(q))});
test('配筋候選皆符合強度與構造條件',()=>{const cs=S.design(p);assert(cs.length);for(const c of cs){assert(c.r.valid&&c.r.maxRatio<=1);assert(c.As>0)}});
fs.writeFileSync('src-beam/verification.json',JSON.stringify(tests,null,2));console.log(`${tests.length} tests, ${failures} failures`);if(failures)console.log(tests.filter(t=>!t.pass));process.exitCode=failures?1:0;
