/* TW 112, corrigendum 113. Canonical units cm, kgf, kgf-cm.
   Conservative screening of rectangular groups; no baseplate contact solution. */
(function(root){
'use strict';
const VERSION='1.0.0';
const TYPES={bolt:'預埋擴頭螺栓',stud:'預埋擴頭錨釘',hook:'預埋 J／L 螺栓',torque:'後置膨脹（扭力控制）',displacement:'後置膨脹（位移控制）',undercut:'後置擴底',screw:'後置螺紋',adhesive:'後置黏結'};
const DEFAULT={name:'四支 M20 預埋擴頭螺栓・靜力範例',type:'bolt',fc:280,ha:40,da:2,AsN:2.45,AsV:2.45,fy:2400,fu:4000,ductile:true,hef:20,Ab:8,eh:8,headWidth:4,tipExtra:1.5,nx:2,ny:2,sx:20,sy:20,cL:25,cR:25,cB:25,cT:25,cracked:true,supp:false,edgeRebar:0,torqued:true,cover:4,aggregate:2.5,grout:false,leMode:'full',category:1,np:0,tauCr:0,tauUn:0,cac:0,prodS:0,prodC:0,prodH:0,prodMinHef:0,prodMaxHef:0,qualified:false,report:'',seismic:false,seisQualified:false,seisPath:false,plasticHinge:false,sustained:0,age:28,mode:'global',N:8,Mx:0.3,My:0.2,Vx:1.2,Vy:0.6,Tz:0.1,manual:[]};
const METRIC={12:0.843,14:1.15,16:1.57,18:1.92,20:2.45,22:3.03,24:3.53,27:4.59,30:5.61,33:6.94,36:8.17};
const sum=(a,f)=>a.reduce((s,x)=>s+f(x),0),min=a=>Math.min(...a),max=a=>Math.max(...a),near=(a,b)=>Math.abs(a-b)<1e-7;
function points(p){let a=[];for(let j=0;j<p.ny;j++)for(let i=0;i<p.nx;i++)a.push({id:a.length+1,x:(i-(p.nx-1)/2)*p.sx,y:(j-(p.ny-1)/2)*p.sy});return a;}
function bounds(p){return {L:-(p.nx-1)*p.sx/2-p.cL,R:(p.nx-1)*p.sx/2+p.cR,B:-(p.ny-1)*p.sy/2-p.cB,T:(p.ny-1)*p.sy/2+p.cT};}
function unionArea(rects){const xs=[...new Set(rects.flatMap(r=>[r[0],r[1]]))].sort((a,b)=>a-b);let a=0;for(let i=1;i<xs.length;i++){const mid=(xs[i-1]+xs[i])/2,ys=rects.filter(r=>r[0]<mid&&r[1]>mid).map(r=>[r[2],r[3]]).sort((a,b)=>a[0]-b[0]);let length=0,end=-Infinity;for(const [lo,hi]of ys){length+=Math.max(0,hi-Math.max(lo,end));end=Math.max(end,hi);}a+=(xs[i]-xs[i-1])*length;}return a;}
function unionLength(intervals){let end=-Infinity,n=0;for(const [lo,hi]of intervals.sort((a,b)=>a[0]-b[0])){n+=Math.max(0,hi-Math.max(lo,end));end=Math.max(end,hi);}return n;}
function projected(g,r,b){return unionArea(g.map(a=>[Math.max(b.L,a.x-r),Math.min(b.R,a.x+r),Math.max(b.B,a.y-r),Math.min(b.T,a.y+r)]));}
function groupData(g,b,weight){const W=sum(g,weight),xc=sum(g,a=>a.x)/g.length,yc=sum(g,a=>a.y)/g.length;return {W,ex:W>0?Math.abs(sum(g,a=>a.x*weight(a))/W-xc):0,ey:W>0?Math.abs(sum(g,a=>a.y*weight(a))/W-yc):0,c:min(g.flatMap(a=>[a.x-b.L,b.R-a.x,a.y-b.B,b.T-a.y]))};}
function factors(p){const cast=['bolt','stud','hook'].includes(p.type),cat=p.category;return {cast,steelN:p.ductile?.75:.65,steelV:p.ductile?.65:.60,conN:cast?(p.supp?.75:.70):([0,.65,.55,.45][cat]+(p.supp?.10:0)),conV:p.supp?.75:.70,pull:cast?.70:[0,.65,.55,.45][cat],pry:.70};}
function criticalDistance(p){return p.cac>0?p.cac:(p.type==='adhesive'?2:p.type==='undercut'?2.5:4)*p.hef;}
function tensileConcrete(p,g,b,weight){const f=factors(p),d=groupData(g,b,weight),r=1.5*p.hef,A=projected(g,r,b),A0=9*p.hef**2,k=f.cast?10:7,deep=['bolt','stud'].includes(p.type)&&p.hef>=28&&p.hef<=63.5,Nb=deep?5.8*Math.sqrt(p.fc)*p.hef**(5/3):k*Math.sqrt(p.fc)*p.hef**1.5;
const ec=1/(1+d.ex/r)/(1+d.ey/r),ed=Math.min(1,.7+.3*d.c/r),c=p.cracked?1:(f.cast?1.25:1.4),cac=criticalDistance(p),cp=!f.cast&&!p.cracked&&!p.supp?Math.min(1,Math.max(d.c/cac,r/cac)):1;
return {nominal:A/A0*ec*ed*c*cp*Nb,A,A0,Nb,ec,ed,c,cp,ex:d.ex,ey:d.ey,ca:d.c,hef:p.hef};}
function adhesive(p,g,b,weight){if(!(p.tauCr>0&&p.tauUn>0))return null;const d=groupData(g,b,weight),r=10*p.da*Math.sqrt(p.tauUn/77),A=projected(g,r,b),A0=4*r*r,ec=1/(1+d.ex/r)/(1+d.ey/r),ed=Math.min(1,.7+.3*d.c/r),cac=criticalDistance(p),cp=!p.cracked&&!p.supp?Math.min(1,Math.max(d.c/cac,r/cac)):1,Nba=(p.cracked?p.tauCr:p.tauUn)*Math.PI*p.da*p.hef;return {nominal:A/A0*ec*ed*cp*Nba,A,A0,Nba,ec,ed,cp,cNa:r,ca:d.c};}
function edgeCapacity(p,g,b,edge){const xaxis=edge==='L'||edge==='R',s=(edge==='L'||edge==='B')?-1:1,coord=a=>xaxis?a.x:a.y,trans=a=>xaxis?a.y:a.x,dist=a=>edge==='L'?a.x-b.L:edge==='R'?b.R-a.x:edge==='B'?a.y-b.B:b.T-a.y,ca=min(g.map(dist)),front=g.filter(a=>near(dist(a),ca)),lo=xaxis?b.B:b.L,hi=xaxis?b.T:b.R,side=Math.min(min(front.map(trans))-lo,hi-max(front.map(trans))),r=1.5*ca;
const width=unionLength(front.map(a=>[Math.max(lo,trans(a)-r),Math.min(hi,trans(a)+r)])),A=width*Math.min(r,p.ha),A0=4.5*ca*ca,le=Math.min(p.leMode==='short'?2*p.da:p.hef,8*p.da),Vb=Math.min(1.86*(le/p.da)**.2*Math.sqrt(p.da),3.8)*Math.sqrt(p.fc)*ca**1.5;
const W=sum(g,a=>a.V),center=sum(front,trans)/front.length,ex=W>0?Math.abs(sum(g,a=>trans(a)*a.V)/W-center):0,ec=1/(1+ex/r),normal=g.map(a=>s*(xaxis?a.vx:a.vy)),outward=normal.some(v=>v>1e-8),parallel=normal.every(v=>Math.abs(v)<1e-8),ed=parallel?1:Math.min(1,.7+.3*side/r),c=p.cracked?([1,1.2,1.4][p.edgeRebar]):1.4,h=Math.max(1,Math.sqrt(r/p.ha)),mult=parallel?2:1;
return {nominal:A/A0*ec*ed*c*h*mult*Vb,A,A0,Vb,ec,ed,c,h,le,ca,side,edge,front:front.map(a=>a.id),active:outward||parallel,conservative:g.length>front.length||(!parallel&&g.some(a=>Math.abs(xaxis?a.vy:a.vx)>1e-8)),narrow:side<r&&(hi-max(front.map(trans)))<r&&(min(front.map(trans))-lo)<r&&p.ha<r};}
function calculate(input){const p={...DEFAULT,...input},errors=[],pending=[],notes=[];const numeric=['fc','ha','da','AsN','AsV','fy','fu','hef','Ab','eh','headWidth','tipExtra','nx','ny','sx','sy','cL','cR','cB','cT','cover','aggregate','category','np','tauCr','tauUn','cac','prodS','prodC','prodH','prodMinHef','prodMaxHef','sustained','age','N','Mx','My','Vx','Vy','Tz','edgeRebar'];for(const k of numeric){p[k]=Number(p[k]);if(!Number.isFinite(p[k]))errors.push(k+' 必須是有限數字');}
if(!TYPES[p.type])errors.push('未知錨栓型式');if(!['global','manual'].includes(p.mode))errors.push('未知受力模式');for(const k of ['fc','ha','da','AsN','AsV','fy','fu','hef','cL','cR','cB','cT','cover','aggregate'])if(p[k]<=0)errors.push(k+' 必須大於 0');for(const k of ['np','tauCr','tauUn','cac','prodS','prodC','prodH','prodMinHef','prodMaxHef','headWidth','tipExtra'])if(p[k]<0)errors.push(k+' 不得為負值');if(![1,2,3].includes(p.category)||![0,1,2].includes(p.edgeRebar))errors.push('分類參數無效');if(!Number.isInteger(p.nx)||!Number.isInteger(p.ny)||p.nx<1||p.ny<1||p.nx>3||p.ny>3)errors.push('每方向支數須為 1～3 整數');if((p.nx>1&&p.sx<=0)||(p.ny>1&&p.sy<=0))errors.push('多支配置間距須大於 0');if(p.hef>=p.ha)errors.push('有效埋深須小於構材厚度');if(p.da>10)errors.push('直徑超過 10 cm，超出第 17.3.2 節');if(p.sustained<0||p.sustained>1)errors.push('持續拉力比例須為 0～1');if(p.fu<p.fy)errors.push('fu 不得小於 fy');if(p.mode==='global'&&p.N<0)errors.push('整組模式只適用軸拉力；軸壓力請用含接觸分析的逐支受力');if(p.age<0)errors.push('齡期不得小於 0');if(errors.length)return {p,errors,pending,notes,rows:[],anchors:[],status:'輸入錯誤'};
const f=factors(p),b=bounds(p),a=points(p),n=a.length,XX=sum(a,q=>q.x*q.x),YY=sum(a,q=>q.y*q.y),J=XX+YY;
if(p.mode==='global'){
 if((Math.abs(p.Mx)>1e-10&&YY===0)||(Math.abs(p.My)>1e-10&&XX===0)||(Math.abs(p.Tz)>1e-10&&J===0))errors.push('此配置無法抵抗指定彎矩／扭矩');
 for(const q of a){q.rawN=p.N*1000/n+(YY?p.Mx*100000*q.y/YY:0)+(XX?p.My*100000*q.x/XX:0);q.N=Math.max(0,q.rawN);q.vx=p.Vx*1000/n-(J?p.Tz*100000*q.y/J:0);q.vy=p.Vy*1000/n+(J?p.Tz*100000*q.x/J:0);q.Ns=q.N*p.sustained;}
 if(a.some(q=>q.rawN<-1e-6))pending.push('部分錨栓線性分配為壓力：本模型無底板接觸平衡解。顯示的截斷拉力僅為診斷值，不可用於設計；改為逐支受力模式輸入經接觸分析之結果。');
}else{
 if(!Array.isArray(p.manual)||p.manual.length!==n)errors.push('逐支受力資料數量須與錨栓配置一致');
 for(let i=0;i<n;i++){const m=p.manual[i]||{};for(const k of ['N','vx','vy','Ns'])if(!Number.isFinite(Number(m[k])))errors.push('A'+(i+1)+' 受力資料缺漏');a[i].N=Number(m.N)*1000;a[i].rawN=a[i].N;a[i].vx=Number(m.vx)*1000;a[i].vy=Number(m.vy)*1000;a[i].Ns=Number(m.Ns)*1000;if(a[i].N<0||a[i].Ns<0||a[i].Ns>a[i].N+1e-6)errors.push('A'+(i+1)+' 拉力須非負，持續拉力不得超過總拉力');}
 notes.push('逐支模式採用外部分析輸入之錨栓受力，基板壓力、平衡與剛性須由該分析確認；整組載重欄位不參與計算。');
}
if(errors.length)return {p,errors,pending,notes,rows:[],anchors:a,status:'輸入錯誤'};a.forEach(q=>q.V=Math.hypot(q.vx,q.vy));
const fcCap=f.cast?700:560;if(p.fc>fcCap)pending.push('fc′ 超過 '+fcCap+' kgf/cm²，需試驗驗證；容量暫按上限計算。');p.fc=Math.min(p.fc,fcCap);
if(!f.cast){if(!p.qualified||!p.report.trim())pending.push('後置式錨栓缺少已核對的產品認證報告編號／適用条件。');if(!(p.prodH>0&&p.prodMinHef>0&&p.prodMaxHef>0&&p.prodS>0&&p.prodC>0))pending.push('請補齊產品最小間距、邊距、厚度及埋深上下限。');}
if(p.type==='adhesive'&&p.age<21)errors.push('黏結式錨栓安裝時混凝土齡期須至少 21 日（17.2.2）');if(p.type==='adhesive'&&!(p.hef>=4*p.da&&p.hef<=20*p.da))errors.push('黏結式有效埋深須在 4da～20da（17.3.3）');if(p.type==='screw'&&!(p.hef>=Math.max(5*p.da,4)&&p.hef<=10*p.da))errors.push('螺紋錨栓埋深須符合 5da～10da 且至少 4 cm（17.3.4）');
if(['bolt','stud'].includes(p.type)&&p.Ab<=0)errors.push('擴頭淨承壓面積須大於 0');if(p.type==='hook'&&(p.eh<3*p.da||p.eh>4.5*p.da))errors.push('彎鉤有效伸出長度須介於 3da～4.5da');
if(p.plasticHinge)pending.push('塑鉸區地震錨栓超出第 17.10.2 節適用範圍');if(p.seismic){if(!p.cracked)pending.push('耐震案例採未開裂混凝土時須另有分析佐證');if(!p.seisPath)pending.push('尚未確認 17.10.5.3(d)／17.10.6.3(c) 的超額強度載重設計路徑：輸入須為已放大地震分量後的完整組合。');if(!f.cast&&!p.seisQualified)pending.push('後置式產品須具有適用的耐震認證。');}
const rows=[],reduceN=p.seismic?.75:1,fu=Math.min(p.fu,1.9*p.fy,8750),maxN=max(a.map(q=>q.N)),maxV=max(a.map(q=>q.V)),sumN=sum(a,q=>q.N),sumV=sum(a,q=>q.V);
function add(key,name,ref,demand,nominal,phi,detail={},kind='N'){const capacity=nominal===null?null:nominal*phi,ratio=capacity===null?null:capacity>0?demand/capacity:(demand>0?Infinity:0),r={key,name,ref,demand,nominal,phi,capacity,ratio,detail,kind};rows.push(r);return r;}
add('steelN','鋼材拉力','17.6.1.2',maxN,p.AsN*fu,f.steelN,{fuUsed:fu,As:p.AsN,anchor:a.find(q=>q.N===maxN)?.id});add('steelV','鋼材剪力','17.7.1.2',maxV,(p.type==='stud'?1:.6)*p.AsV*fu*(p.grout?.8:1),f.steelV,{fuUsed:fu,As:p.AsV,grout:p.grout},'V');
const active=a.filter(q=>q.N>1e-8),shearActive=a.filter(q=>q.V>1e-8);
function subsets(arr){const s=[];for(let mask=1;mask<2**arr.length;mask++)s.push(arr.filter((_,i)=>mask&(1<<i)));return s;}
const tg=subsets(active),vg=subsets(shearActive);let tensionWorst=null,bondWorst=null,pryWorst=null,edgeWorst=null;
function keep(old,demand,nominal,detail){const ratio=nominal>0?demand/nominal:(demand>0?Infinity:0);return !old||ratio>old.ratio?{ratio,demand,nominal,detail}:old;}
for(const g of tg){const t=tensileConcrete(p,g,b,q=>q.N),d=sum(g,q=>q.N);t.ids=g.map(q=>q.id);tensionWorst=keep(tensionWorst,d,t.nominal,t);const ad=p.type==='adhesive'?adhesive(p,g,b,q=>q.N):null;if(ad){ad.ids=t.ids;bondWorst=keep(bondWorst,d,ad.nominal,ad);} }
if(tensionWorst)add('breakoutN','混凝土拉破・群／單支包絡','17.6.2',tensionWorst.demand,tensionWorst.nominal,f.conN*reduceN,tensionWorst.detail);else add('breakoutN','混凝土拉破（無拉力）','17.6.2',0,0,f.conN*reduceN);
if(p.type==='adhesive'){
 if(bondWorst)add('bond','黏結握裹・群／單支包絡','17.6.5',bondWorst.demand,bondWorst.nominal,f.conN*reduceN,bondWorst.detail);else {add('bond','黏結握裹','17.6.5',sumN,sumN===0?0:null,f.conN*reduceN);if(sumN>0)pending.push('特徵握裹應力 τcr 和 τuncr 必須依產品報告輸入（包含實際溫度、濕度與載重條件）。');}
 const Nba=(p.cracked?p.tauCr:p.tauUn)*Math.PI*p.da*p.hef;add('sustained','黏結持續拉力・最大單支','17.5.2.2',max(a.map(q=>q.Ns)),Nba>0?Nba:(max(a.map(q=>q.Ns))===0?0:null),.55*f.conN,{Nba});
}else{const np=['bolt','stud'].includes(p.type)?8*p.Ab*p.fc:p.type==='hook'?.9*p.fc*p.eh*p.da:p.np>0?p.np:null;add('pullout','拔出・最大單支','17.6.3',maxN,np,f.pull*reduceN*(p.cracked?1:1.4),{Ab:p.Ab,eh:p.eh});if(np===null&&maxN>0)pending.push('機械式後置錨栓拔出強度 Np 缺漏，必須使用試驗／認證報告，不可用 8Abrgfc′ 代替。');}
if(['bolt','stud'].includes(p.type)){
 let worst=null;for(const q of active){const ds=[q.x-b.L,b.R-q.x,q.y-b.B,b.T-q.y],ca=min(ds);if(p.hef>2.5*ca){const idx=ds.indexOf(ca),other=idx<2?Math.min(ds[2],ds[3]):Math.min(ds[0],ds[1]);if(other<ca)pending.push('邊緣脹破雙邊幾何需專項分析');const corner=other<3*ca?(1+Math.max(1,other/ca))/4:1,ns=42.44*ca*Math.sqrt(p.Ab)*Math.sqrt(p.fc)*corner;worst=keep(worst,sumN,ns,{ca,other,corner,Ab:p.Ab,anchor:q.id,conservative:active.length>1});}}
 if(worst)add('sideface','邊緣脹破・保守單支容量對總拉力','17.6.4',worst.demand,worst.nominal,f.conN*reduceN,worst.detail);else add('sideface','邊緣脹破（hef ≤ 2.5ca，不控制）','17.6.4',0,0,f.conN*reduceN);
}
for(const g of vg){const t=tensileConcrete(p,g,b,q=>q.V),ad=p.type==='adhesive'?adhesive(p,g,b,q=>q.V):null,kcp=p.hef<6.5?1:2,nom=kcp*(p.type==='adhesive'?(ad?Math.min(t.nominal,ad.nominal):0):t.nominal),d=sum(g,q=>q.V);t.ids=g.map(q=>q.id);t.kcp=kcp;t.bondNominal=ad?.nominal;pryWorst=keep(pryWorst,d,nom,t);for(const e of ['L','R','B','T']){const v=edgeCapacity(p,g,b,e);if(v.active){v.ids=t.ids;edgeWorst=keep(edgeWorst,d,v.nominal,v);}}}
if(pryWorst){add('pry','剪力撬破・保守群／單支包絡','17.7.3',pryWorst.demand,p.type==='adhesive'&&!(p.tauCr>0&&p.tauUn>0)?null:pryWorst.nominal,f.pry,pryWorst.detail,'V');if(p.type==='adhesive'&&!(p.tauCr>0&&p.tauUn>0))pending.push('黏結式撬破需先取得握裹強度。');}else add('pry','剪力撬破（無剪力）','17.7.3',0,0,f.pry,{},'V');
if(edgeWorst)add('breakoutV','混凝土邊緣剪破・保守包絡','17.7.2',edgeWorst.demand,edgeWorst.nominal,f.conV,edgeWorst.detail,'V');else add('breakoutV','混凝土邊緣剪破（無剪力）','17.7.2',0,0,f.conV,{},'V');
let narrowN=false;for(const q of a){if([q.x-b.L,b.R-q.x,q.y-b.B,b.T-q.y].filter(c=>c<1.5*p.hef).length>=3)narrowN=true;}if(narrowN)pending.push('三面／四面近邊，須按 17.6.2.1.2 限制有效埋深重新建立投影面；本版不作完成判定。');if(edgeWorst?.detail.narrow)pending.push('狹窄薄構材須按 17.7.2.1.2 限制 ca1；本版不作完成判定。');
const minS=f.cast?(p.torqued?6:4)*p.da:(p.prodS>0?p.prodS:p.type==='screw'?Math.max(.6*p.hef,6*p.da):6*p.da),minC=f.cast?(p.torqued?Math.max(6*p.da,p.cover+Math.max(p.da,p.headWidth)/2):p.cover+Math.max(p.da,p.headWidth)/2):Math.max(p.cover+p.da/2,2*p.aggregate,p.prodC>0?p.prodC:({torque:8,displacement:10}[p.type]||6)*p.da),actualS=n===1?Infinity:Math.min(p.nx>1?p.sx:Infinity,p.ny>1?p.sy:Infinity),actualC=min([p.cL,p.cR,p.cB,p.cT]);
const geometry=[{name:'最小間距',actual:actualS,limit:minS,ok:actualS>=minS,ref:'表 17.9.2a／產品認證'},{name:'最小中心邊距',actual:actualC,limit:minC,ok:actualC>=minC,ref:'17.9.2／20.5.1'},{name:'構材最小厚度',actual:p.ha,limit:f.cast?p.hef+p.tipExtra+p.cover:(p.prodH>0?p.prodH:p.hef),ok:p.ha>=(f.cast?p.hef+p.tipExtra+p.cover:p.prodH>0?p.prodH:p.hef),ref:f.cast?'擴頭底部保護層':'產品認證'}];
if(!f.cast){geometry.push({name:'產品有效埋深下限',actual:p.hef,limit:p.prodMinHef,ok:p.prodMinHef>0?p.hef>=p.prodMinHef:null,ref:'產品認證'},{name:'產品有效埋深上限',actual:p.hef,limit:p.prodMaxHef,ok:p.prodMaxHef>0?p.hef<=p.prodMaxHef:null,ref:'產品認證'});if(['torque','displacement','undercut'].includes(p.type)&&p.prodH<=0)geometry.push({name:'有效埋深通則上限',actual:p.hef,limit:Math.max(2*p.ha/3,p.ha-10),ok:p.hef<=Math.max(2*p.ha/3,p.ha-10),ref:'17.9.4'});}
const nRows=rows.filter(r=>r.kind==='N'&&r.key!=='sustained'),vRows=rows.filter(r=>r.kind==='V'),nR=max(nRows.filter(r=>r.ratio!==null).map(r=>r.ratio)),vR=max(vRows.filter(r=>r.ratio!==null).map(r=>r.ratio)),interaction=(nR<=.2||vR<=.2)?Math.max(nR,vR):Math.max(nR,vR,(nR+vR)/1.2);
add('interaction','拉剪互制・包絡利用率','17.8.2／17.8.3',interaction,1,1,{rN:nR,rV:vR,rule:(nR<=.2||vR<=.2)?'一側 ≤ 0.2，可忽略互制；各自 ≤ 1':'rN + rV ≤ 1.2，且各自 ≤ 1'},'I');
if(geometry.some(g=>g.ok===false))notes.push('邊距／間距／厚度未符合，須修改配置。');notes.push('混凝土為常重；未採輕質修正。剪破採最近排錨栓的投影容量對所考量群的剪力絕對值總和；斜向載重採總剪力保守檢核，可能較專業軟體保守。');if(p.type==='adhesive')notes.push('握裹應力須為適用工况的認證設計特徵值；程式不自行套用表 17.6.5.2.5 之條件預設值。');notes.push('底板剛性、撬力、錨栓彎曲、焊接、混凝土構材整體承載與施工檢驗須另行確認。');
const failed=rows.some(r=>r.ratio!==null&&r.ratio>1+1e-8)||geometry.some(g=>g.ok===false),missing=rows.some(r=>r.ratio===null&&r.demand>0)||pending.length>0||geometry.some(g=>g.ok===null),status=errors.length?'輸入錯誤':failed?'已計算項目不符合':missing?'待補資料／專項檢核':'已計算項目符合';
return {version:VERSION,p,errors,pending:[...new Set(pending)],notes:[...new Set(notes)],rows,anchors:a,geometry,bounds:b,status,failed,missing,nR,vR,interaction,fuUsed:fu,factors:f,totalN:sumN,totalV:Math.hypot(sum(a,q=>q.vx),sum(a,q=>q.vy)),scalarV:sumV,combinations:tg.length+vg.length};
}
root.AnchorEngine={VERSION,TYPES,DEFAULT,METRIC,calculate,points,bounds,unionArea,tensileConcrete,adhesive,edgeCapacity,factors};
if(typeof module!=='undefined'&&module.exports)module.exports=root.AnchorEngine;
})(typeof globalThis!=='undefined'?globalThis:this);
