/* Actual-run records supplement the existing source-first UI. */
(()=>{
'use strict';
const records=new Map(),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unit=k=>['fy','fc'].includes(k)?'kgf/cm²':['cover','spacing','ktr','agg'].includes(k)?'cm':k==='percent'?'%':'';
const names={mode:'計算項目',bar:'鋼筋號數',fy:'降伏強度 fy',fc:'混凝土強度 f′c',context:'構件情境',cover:'淨保護層',spacing:'中心間距',ktr:'橫向鋼筋指數 Ktr',agg:'骨材最大粒徑',ratio:'As 配置／需求比',percent:'續接比例',top:'頂層水平鋼筋',epoxy:'環氧塗層',lightweight:'輕質混凝土',lapClass:'搭接等級',type:'彎鉤用途',angle:'彎鉤角度',seismic:'耐震尺寸',inward:'彎向內側',wrap:'箍住縱筋',core:'受圍束核心',direction:'彎向接頭內側',material:'耐震材料確認',standard:'標準彎鉤尺寸確認',position:'原圖鋼筋位置',kind:'查表項目',round:'向上進位單位（cm）',adoptDevelopment:'自訂保守伸展採用'};
const inputs=p=>Object.entries(p).map(([k,v])=>({label:names[k]||k,value:typeof v==='boolean'?(v?'是':'否'):String(v),unit:unit(k)}));
function diagram(value,label='L',other=''){
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 160" role="img" aria-label="當次長度與尺寸示意"><rect width="320" height="160" fill="#f3f7f5"/><path d="M25 60H290" stroke="#19624f" stroke-width="8"/><path d="M25 82V105M290 82V105M25 96H290" stroke="#79511b" stroke-width="2"/><text x="25" y="35" font-size="17" fill="#173b32">${escape(label)} = ${escape(value)} cm</text><text x="25" y="130" font-size="15" fill="#173b32">${escape(other||'長度定義示意，非施工配置圖')}</text></svg>`;
}
function mount(id,report){
 const container=$(id);if(!container)return;container.querySelector('.run-trace')?.remove();records.delete(id);
 if(!report)return;
 report=JSON.parse(JSON.stringify(report));records.set(id,report);
 const node=document.createElement('details');node.className='card calculation run-trace';node.open=true;
 node.innerHTML='<summary>本次詳細計算／查表記錄</summary>'+`<div style="overflow-wrap:anywhere"><h3>本次輸入與單位</h3>${report.inputs.map(i=>`<p>${escape(i.label)}：${escape(i.value)} ${escape(i.unit)}</p>`).join('')}${report.steps.map((s,i)=>`<div class="step"><span class="stepnum">${i+1}</span><div><strong>${escape(s.title)}</strong>${['formula','substitution','result','condition','source'].filter(k=>s[k]!=null&&s[k]!=='').map(k=>`<p style="white-space:pre-wrap">${escape(s[k])}${k==='result'&&s.unit?' '+escape(s.unit):''}</p>`).join('')}</div></div>`).join('')}<h3>結果／判定</h3>${report.conclusions.map(c=>`<p>${escape(c)}</p>`).join('')}${report.diagram.svg}<p>${escape(report.diagram.caption)}</p><button type="button" data-trace-export>匯出本次詳細 Word</button><p role="status" data-trace-status></p></div>`;
 node.querySelector('[data-trace-export]').onclick=async()=>{const status=node.querySelector('[data-trace-status]');try{if(!records.has(id)||!node.isConnected)throw Error('條件已更新，請重新計算。');const snapshot=JSON.parse(JSON.stringify(records.get(id)));status.textContent='製作當次報告中…';await CalculationDocx.download(snapshot,'鋼筋詳細計算_'+id+'.docx');status.textContent='已下載可編輯 Word 報告。';}catch(e){status.textContent=e.message;}};
 container.append(node);
}
function tableStep(t,fy,fc,bar){
 const rowIndex=t.rows.findIndex(r=>r.fy===+fy&&r.fc===+fc),col=t.columns.indexOf(bar),row=t.rows[rowIndex];
 if(!row||col<0)return null;
 return {title:'實際原圖表格定位與取值',formula:`SOURCE_TABLES[${t.id}].rows[${rowIndex}].values[${col}]`,substitution:`${t.source} → ${displaySourceName(t.name)} → fy ${fy} kgf/cm² → f′c ${t.fcLabel||fc} kgf/cm² → ${bar}\n欄序（1起算）：${col+1}；資料列序（1起算）：${rowIndex+1}\n完整欄名：${t.columns.join(' | ')}\n同一原始資料列：${row.values.join(' | ')} cm`,result:row.values[col],unit:'cm',condition:'原圖整數直接取值；不內插、不外推、不由公式反算。未自動套材料或配筋修正。',source:`${t.source}，2024.01.15；${t.conditions.join('；')}`};
}
function tableReport(title,p,t,steps,answer,label,extra=[]){return {title,summary:'原圖基準／參考紀錄，未判定本案設計適用性',inputs:inputs(p),steps,conclusions:[`本次取值／計算：${answer} cm。`,...extra,'材料、保護層、配筋、耐震與施工條件須由設計者另行檢核；此報告不宣稱合格。'],diagram:{svg:diagram(answer,label),width:320,height:160,caption:'本次長度定義示意（非比例施工圖）；原圖與必要條件完整保留。'}};}
const sourceOriginal=sourceRender;
sourceRender=function(){sourceOriginal();const p=sourceInputs(),t=SOURCE_TABLES.find(t=>t.id==='tension-class-b-splice-'+p.position),dev=SOURCE_TABLES.find(t=>t.id==='tension-development-'+p.position),a=tableStep(t,p.fy,p.fc,p.bar),b=tableStep(dev,p.fy,p.fc,p.bar);if(!a||!b){mount('sourceMainResult',null);return;}const {isA,unrounded:raw,answer}=globalThis.RebarSourceRun;mount('sourceMainResult',tableReport('RC02 搭接與伸展詳細紀錄',{...p,lapClass:isA?'A':'B',ratio:$('srcRatio').value,percent:$('srcPercent').value},t,[a,b,{title:'搭接分類與實際修正',formula:isA?'L = max(30, 原乙級表值 ÷ 1.3)':'L = 原乙級表值',substitution:isA?`max(30, ${a.result} ÷ 1.3)`:`L = ${a.result}`,result:raw,unit:'cm',condition:isA?`As比 ${$('srcRatio').value} ≥ 2；續接 ${$('srcPercent').value}% > 0 且 < 50；依原圖條件。`:'乙級為預設；不以取整後伸展值乘1.3。'},{title:'實際向上取整',formula:'ceil(L − 1e−10)',substitution:`ceil(${raw} − 1e−10)`,result:answer,unit:'cm',condition:'1e−10 為原程式避免整數浮點誤差的微量；未另改取整規則。'}],answer,'Lst',[`同組受拉伸展 Ld = ${b.result} cm（原表直接取值，與搭接等級分列）。`]))};
const columnOriginal=columnRender;
columnRender=function(){columnOriginal();const t=currentColumnTable(),p={bar:$('colBar').value,fy:+$('colFy').value,fc:+$('colFc').value,kind:$('colKind').value},s=tableStep(t,p.fy,p.fc,p.bar);mount('columnResult',s?tableReport(COLUMN_QUERIES[p.kind]+'詳細紀錄',p,t,[s,{title:'取整與修正',result:'保持原表整數，未另取整；未使用柱圍束、螺箍或超額配筋折減。',condition:p.kind==='compressionLap'?'f′c≥210 為原表適用範圍，不是近似或內插。':'原圖附註與本案適用性另核。'}],s.result,p.kind==='compressionDev'?'Ldc':'Lst／Lsc'):null)};
const rcOriginal=rcRender;
rcRender=function(){rcOriginal();const t=currentRcTable(),p={bar:$('rcBar').value,fy:+$('rcFy').value,fc:+$('rcFc').value,kind:$('rcKind').value},s=tableStep(t,p.fy,p.fc,p.bar);mount('rcResult',s?tableReport(RC03_MODES[p.kind]+'詳細紀錄',p,t,[s,{title:'修正與取整狀態',result:'原表整數直接保留；附註係數未自動連乘；最小值與上限已包含於原表，不反推其未公開公式。'}],s.result,'Ldh／Ldt',p.kind==='headed'?['RC11 尚未提供，設計採用保持鎖定；此為原圖參考值。']:[]):null)};
const lookupOriginal=renderLookup;
renderLookup=function(){lookupOriginal();const t=activeTable(),p={bar:$('lookupBar').value,fy:+$('lookupFy').value,fc:+$('lookupFc').value},s=tableStep(t,p.fy,p.fc,p.bar);mount('lookupResult',s?tableReport(t.source+' '+displaySourceName(t.name)+'詳細紀錄',p,t,[s,{title:'修正／上下限／取整',result:'保持原表整數，不另取整；附註修正未自動連乘；不以公式補原表未列值。'}],s.result,'原圖尺寸',t.category==='headed'?['RC11缺件，設計採用保持鎖定。']:[]):null)};
let actualGeneral=null,actualGeometry=null,actualSeismic=null;
const calculateOriginal=calculate;calculate=function(p){const r=calculateOriginal(p);actualGeneral={p:JSON.parse(JSON.stringify(p)),r};return r;};
const geometryEngineOriginal=calcGeometry;calcGeometry=function(p){const r=geometryEngineOriginal(p);actualGeometry={p:JSON.parse(JSON.stringify(p)),r};return r;};
const seismicEngineOriginal=calcSeismicHook;calcSeismicHook=function(p){const r=seismicEngineOriginal(p);actualSeismic={p:JSON.parse(JSON.stringify(p)),r};return r;};
const resultOriginal=renderResult;
renderResult=function(){const snapshot=lastResult?{p:JSON.parse(JSON.stringify({...state,lapClass})),r:lastResult}:null;resultOriginal();if(!snapshot||snapshot.r.errors.length){mount('result',null);return;}const {p,r}=snapshot,adopted=globalThis.RebarGeneralRun.adopted,rounded=globalThis.RebarGeneralRun.rounded;
 const steps=r.steps.map(s=>({title:s.name,formula:s.formula,substitution:s.substitution,result:s.value==null?'係數與條件見公式記錄':s.value,unit:s.value==null||['材料與基本參數','保護層與圍束'].includes(s.name)?'':'cm',source:r.clause}));
 steps.unshift({title:'輸入有效範圍與配置條件',result:`db=${r.d} cm；fy=${r.fy} kgf/cm²；f′c=${r.fc} kgf/cm²；λ=${r.lambda}`,condition:'原引擎檢核通過：一般非耐震非柱同徑；D10～D36；fy支援等級；210≤f′c≤700；幾何間距、必要Ktr、續接比例依所選模式檢查。'});
 if(p.mode==='tension'&&adoptDevelopment)steps.push({title:'自訂保守採用值',formula:'max(受拉伸展, 乙級搭接)',substitution:`max(${r.length}, ${actualGeneral.r.length})`,result:adopted,unit:'cm',condition:'自訂保守採用，不是規範伸展甲乙分類。'});
 steps.push({title:'實際向上取整',formula:'ceil((L − 1e−10) / 進位單位) × 進位單位',substitution:`ceil((${adopted} − 1e−10) / ${round}) × ${round}`,result:rounded,unit:'cm',condition:'計算中間值未四捨五入；畫面顯示格式與實際 Number 值分開。'});
 mount('result',{title:'進階鋼筋公式詳細計算紀錄',summary:MODES[p.mode],inputs:inputs({...p,round,adoptDevelopment}),steps,conclusions:[`${MODES[p.mode]} = ${rounded} cm；未取整 ${adopted} cm。`,...r.warnings,'非構件安全或法規合格證明。'],diagram:{svg:diagram(rounded,MODES[p.mode]),width:320,height:160,caption:'同次採用長度示意，完整原圖另由既有按鈕查閱。'}});
};
const geometryRunOriginal=geometryRun;geometryRun=function(){geometryRunOriginal();const a=actualGeometry;if(!a||a.r.errors.length){mount('geometryResult',null);return;}const {p,r}=a;mount('geometryResult',{title:'彎鉤尺寸詳細計算紀錄',inputs:inputs(p),steps:[{title:'公稱直徑',formula:'db = BARS[鋼筋號數]',substitution:`BARS[${p.bar}]`,result:r.db,unit:'cm',source:'CNS公稱直徑表（本工具BARS）'},{title:'最小彎曲內徑',formula:'D = 彎曲倍數 × db',substitution:`${r.bendFactor} × ${r.db}`,result:r.bend,unit:'cm',source:r.clause},{title:'最小直線尾長',formula:r.tailRule,result:r.tail,unit:'cm',condition:`本次用途=${p.type}，角度=${p.angle}°；必要耐震/彎向/包住縱筋確認按原引擎檢核。`},{title:'原圖橫向外包',result:r.a1===null?'本用途無對應A1原表':r.a1,unit:r.a1===null?'':'cm',source:'RC03 90°主筋 A1；不是伸展或彎曲內徑。'}],conclusions:[`D=${r.bend} cm；a=${r.tail} cm。未另取整。`,...r.warnings],diagram:{svg:diagram(r.bend,'D',`尾長 a = ${r.tail} cm`),width:320,height:160,caption:'本次尺寸符號；非施工彎曲配置圖。'}})};
const seismicRunOriginal=seismicRun;seismicRun=function(){seismicRunOriginal();const a=actualSeismic;if(!a||a.r.errors.length){mount('seismicResult',null);return;}const {p,r}=a,t=SOURCE_TABLES.find(t=>t.id==='seismic-hook'),s=tableStep(t,p.fy,p.fc,p.bar),rounded=globalThis.RebarSeismicRun.rounded,mismatch=globalThis.RebarSeismicRun.mismatch;mount('seismicResult',{title:'耐震90°彎鉤公式與原圖詳細紀錄',inputs:inputs(p),steps:[{title:'材料與強度上限',formula:'q=min(√f′c,26.5)',substitution:`min(√${r.fc},26.5)；db=${r.db}；λ=${r.lambda}`,result:r.q},{title:'公式計算',formula:'0.06fydb/(λq)',substitution:`0.06 × ${r.fy} × ${r.db} ÷ (${r.lambda} × ${r.q})`,result:r.raw,unit:'cm'},{title:'最小值控制',formula:'max(公式值, 鋼筋倍數最小值, 固定最小值)',substitution:`max(${r.raw},${r.barMin},${r.fixedMin})`,result:r.base,unit:'cm'},{title:'完整長度塗層修正',formula:'L = 基準長度 × 塗層係數',substitution:`${r.base} × ${r.epoxy}`,result:r.length,unit:'cm'},{title:'向上取整',formula:'ceil(L − 1e−10)',substitution:`ceil(${r.length} − 1e−10)`,result:rounded,unit:'cm'},...(s?[s]:[])],conclusions:[`公式 ${r.length} cm → ${rounded} cm；原圖 ${s?s.result:'未列'} cm。`,mismatch?'原圖與常重未塗層基準公式不同；設計採用保持鎖定，不採较短值。':'未宣稱完整接頭設計合格；材料不同時不作一對一判定。',...r.warnings],diagram:{svg:diagram(rounded,'公式 Ldh',`原圖 ${s?s.result:'未列'} cm（分列）`),width:320,height:160,caption:'公式與原圖分列，不以圖示解除設計限制。'}})};
for(const id of ['form','geomForm','seismicForm'])$(id).addEventListener('input',()=>{const target={form:'result',geomForm:'geometryResult',seismicForm:'seismicResult'}[id];records.delete(target);$(target).querySelector('.run-trace')?.remove();});
$('colBar').onchange=columnRender;$('colFc').onchange=columnRender;$('rcBar').onchange=rcRender;$('rcFc').onchange=rcRender;$('lookupFc').onchange=renderLookup;$('lookupBar').onchange=renderLookup;
sourceRender();columnRender();rcRender();renderLookup();compute();geometryRun();
})();
