const $=id=>document.getElementById(id);let result=null,legacyResult=null;let activeUnit=$('force-unit').value;let outputUnit=$('output-unit').value;const forceLabel=()=>activeUnit==='kgf'?'kg':activeUnit;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=(v,n=3)=>Number(v).toLocaleString('en-US',{maximumFractionDigits:n,minimumFractionDigits:n});
const fields={seg:['x₁','y₁','x₂','y₂'],loads:['x','y','z','Px','Py','Pz','Mx','My','Mz']};
function row(type,values){let tr=document.createElement('tr');values.forEach((v,i)=>{const td=document.createElement('td'),inp=document.createElement('input');inp.type='number';inp.step='any';inp.value=v;inp.setAttribute('aria-label',fields[type][i]+(type==='seg'?' cm':i<3?' cm':i<6?' '+forceLabel():' '+forceLabel()+'·m'));inp.title=fields[type][i]+(type==='seg'?'：焊線端點座標 cm，來源：接合詳圖':i<3?'：施力位置 cm，來源：接合詳圖':i<6?'：作用力 '+forceLabel()+'，來源：結構分析載重組合':'：附加力矩 '+forceLabel()+'·m，來源：結構分析載重組合');inp.addEventListener('input',calculate);td.append(inp);tr.append(td)});let td=document.createElement('td'),b=document.createElement('button');b.textContent='移除';b.className='remove';b.onclick=()=>{tr.remove();calculate()};td.append(b);tr.append(td);$(type).append(tr)}
function data(type){return [...$(type).rows].map(tr=>[...tr.querySelectorAll('input')].map(x=>x.value.trim()===''?NaN:Number(x.value)))}
function state(){return{version:1,forceUnit:'tf',displayUnit:activeUnit,outputUnit,basis:$('basis').value,circle:Number($('circle').value),method:$('method').value,F:Number($('F').value),w:Number($('w').value),t1:Number($('t1').value),t2:Number($('t2').value),endLoaded:$('endloaded').checked,seg:data('seg'),loads:WeldUnits.convertLoads(data('loads'),activeUnit,'tf'),inputLoads:data('loads')}}
function draw(r){const pts=r.seg.flatMap(a=>[[a.x/10,a.y/10],[a.X/10,a.Y/10]]);pts.push([r.cx/10,r.cy/10]);r.trace.s.loads.forEach(a=>pts.push([a[0],a[1]]));const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys),scale=Math.min(400/Math.max(maxx-minx,1),205/Math.max(maxy-miny,1)),X=x=>65+(x-minx)*scale,Y=y=>270-(y-miny)*scale;let svg='<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#d8e4ef" stroke-width=".5"/></pattern></defs><rect width="540" height="340" fill="url(#grid)"/><text x="22" y="25" fill="#546a82" font-size="13">平面 XY · +Z 朝向螢幕外</text>';
if(r.radius){svg+=`<circle cx="${X(0)}" cy="${Y(0)}" r="${r.radius/10*scale}" fill="none" stroke="#1d6790" stroke-width="5"/><text x="22" y="48" font-size="14">連續圓環 · 直徑 ${fmt(r.radius/5,1)} cm</text>`;}else r.seg.forEach((a,i)=>{let x=X(a.x/10),y=Y(a.y/10),xx=X(a.X/10),yy=Y(a.Y/10);svg+=`<line x1="${x}" y1="${y}" x2="${xx}" y2="${yy}" stroke="#1d6790" stroke-width="5" stroke-linecap="round"/><text x="${(x+xx)/2+8}" y="${(y+yy)/2-9}" font-size="14" fill="#223f5b">#${i+1} · ${fmt(a.l/10,1)} cm</text>`});svg+=`<circle cx="${X(r.cx/10)}" cy="${Y(r.cy/10)}" r="6" fill="#d99923"/><text x="${X(r.cx/10)+10}" y="${Y(r.cy/10)+20}" font-size="13">重心</text><circle cx="${X(r.critical.x)}" cy="${Y(r.critical.y)}" r="8" fill="none" stroke="#c4424d" stroke-width="3"/><text x="20" y="325" font-size="13" fill="#c4424d">紅圈：最大需求位置 · 金點：焊線重心</text>`;svg+=`<defs><marker id="load-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#8f4267"/></marker></defs>`;r.trace.s.loads.forEach((a,i)=>{const xx=X(a[0]),yy=Y(a[1]),mag=Math.hypot(a[3],a[4]),dx=mag?28*a[3]/mag:0,dy=mag?28*a[4]/mag:0;svg+=`<circle cx="${xx}" cy="${yy}" r="3" fill="#8f4267"/><text x="${xx-40}" y="${yy+24}" font-size="12" fill="#8f4267">P${i+1}${a[5]>0?' ⊙':a[5]<0?' ⊗':''}</text>`;if(mag)svg+=`<line x1="${xx-dx}" y1="${yy+dy}" x2="${xx}" y2="${yy}" stroke="#8f4267" stroke-width="2" marker-end="url(#load-arrow)"/>`;});svg+=`<text x="20" y="306" font-size="12">P編號對應本次載重表；箭頭為XY力方向，⊙為+Z／⊗為−Z</text>`;$('diagram').innerHTML=svg;}
function calculate(){result=null;$('export-docx').disabled=true;$('error').hidden=true;try{const s=state();result=WeldEngine.analyze(s);const r=result,u=WeldUnits.output(outputUnit),lineFactor=u.line,lineUnit=u.lineUnit;$('status').textContent=r.pass?'焊材與尺寸檢核符合':'焊材或尺寸檢核不符合';$('status').className=r.pass?'badge good':'badge bad';$('ratio').textContent=fmt(r.ratio);$('req').textContent=fmt(r.req,2)+' mm';$('q').textContent=fmt(r.critical.q/lineFactor)+' '+lineUnit;$('throat').textContent=fmt(r.throat)+' mm';$('meter').style.width=Math.min(100,r.ratio*100)+'%';$('meter').style.background=r.ratio<=1?'#277d6b':'#c4424d';$('checks').innerHTML=r.checks.map(c=>`<div class="check"><span>${esc(c.name)}</span><strong class="${c.ok?'good-text':'bad-text'}">${c.ok?'符合':'不符合'} · ${esc(c.value)}</strong></div>`).join('');$('details').innerHTML=`<p>基準：ASD 使用服務載重組合；LRFD 使用已係數化組合。程式不再乘載重係數。</p><div class="table-wrap"><table><tbody>${[['總有效焊長 L',r.L,'mm'],['重心 x̄',r.cx,'mm'],['重心 ȳ',r.cy,'mm'],['Ix',r.Ix,'mm³'],['Iy',r.Iy,'mm³'],['Ixy',r.Ixy,'mm³'],['J = Ix + Iy',r.J,'mm³'],['ΣPx',r.px/u.force,u.forceUnit],['ΣPy',r.py/u.force,u.forceUnit],['ΣPz',r.pz/u.force,u.forceUnit],['重心 Mx',r.mx/u.moment,u.momentUnit],['重心 My',r.my/u.moment,u.momentUnit],['重心 Mz',r.mz/u.moment,u.momentUnit],['可用焊材應力 fd',r.fd/u.stress,u.stressUnit],['單位長度容量 fd × te',r.capacity/lineFactor,lineUnit]].map(([n,v,u])=>`<tr><th>${n}</th><td>${fmt(v)}</td><td>${u}</td></tr>`).join('')}</tbody></table></div><p>最大需求：焊線 #${r.critical.i} 端點 ${r.radius?'環上控制點':r.critical.end}，(${fmt(r.critical.x)}, ${fmt(r.critical.y)}) cm。</p><p>下列公式以 N、mm、MPa 計算，結果再換算為所選單位；1 kgf/cm² = 0.0980665 MPa。<br>te = s / √2；ASD fd = 0.60 FEXX / 2；LRFD fd = 0.75 × 0.60 FEXX。<br>qx = Px/L − Mz(y−ȳ)/J；qy = Py/L + Mz(x−x̄)/J。<br>qz = Pz/L + A(x−x̄) + B(y−ȳ)。D = IxIy−Ixy²；A = (−MyIx−MxIxy)/D；B = (MxIy+MyIxy)/D。<br>qmax = max √(qx²+qy²+qz²)；所需焊腳 = qmax / (fd/√2)。</p><details><summary>每個焊線端點的需求</summary><div class="table-wrap"><table><thead><tr><th>焊線 / 端點</th><th>qx ${lineUnit}</th><th>qy ${lineUnit}</th><th>qz ${lineUnit}</th><th>合成 ${lineUnit}</th></tr></thead><tbody>${r.ends.map(e=>`<tr><td>${e.i} / ${e.end}</td><td>${fmt(e.qx/lineFactor)}</td><td>${fmt(e.qy/lineFactor)}</td><td>${fmt(e.qz/lineFactor)}</td><td>${fmt(e.q/lineFactor)}</td></tr>`).join('')}</tbody></table></div></details>`;draw(r);renderWeldTrace(r);$('export-docx').disabled=false;}catch(e){$('error').hidden=false;$('error').textContent=e.message;$('status').textContent='輸入無效 · 停止檢核';$('status').className='badge bad';['ratio','req','q','throat'].forEach(id=>$(id).textContent='—');$('checks').innerHTML='';$('details').innerHTML='';$('diagram').innerHTML='';$('meter').style.width='0%'}}
function preset(){const type=$('preset').value,L=Number($('L').value),K=Number($('K').value);if(!(L>0&&K>=0)){alert('L 必須 > 0，K 必須 ≥ 0');return}let ss;
switch(type){case '1':ss=[[0,0,0,L],[K,0,K,L]];break;case '2':ss=[[0,0,0,L],[0,0,0,L]];alert('雙面焊線請以實際間距輸入；不可用重疊線段倍增容量。已改用 K 作為間距。');ss=[[0,0,0,L],[K,0,K,L]];break;case '3':ss=[[0,0,L,0],[0,K,L,K]];break;case '4':ss=[[0,0,K,0],[K,0,K,L],[K,L,0,L],[0,L,0,0]];break;case '5':ss=[[0,0,L,0],[L,0,L,K],[L,K,0,K],[0,K,0,0]];break;case '6':case '7':ss=[[0,0,0,L],[0,L,K,L],[0,0,K,0]];break;case '8':case '9':ss=[[0,0,0,L],[0,L,K,L]];break;case 'circle':{let n=96,R=L/2;ss=Array.from({length:n},(_,i)=>[R*Math.cos(2*Math.PI*i/n),R*Math.sin(2*Math.PI*i/n),R*Math.cos(2*Math.PI*(i+1)/n),R*Math.sin(2*Math.PI*(i+1)/n)]);break}}
$('circle').value=type==='circle'?L:0;$('circle-note').hidden=type!=='circle';$('line-editor').hidden=type==='circle';
$('seg').innerHTML='';ss.forEach(a=>row('seg',a));calculate();}
function loadState(s){s=WeldUnits.restore(s);if(s.circle<0||s.circle>100000)throw Error('圓直徑無效');if(s.version!==1||!Array.isArray(s.seg)||!Array.isArray(s.loads)||s.seg.length>200||s.loads.length>100)throw Error('資料版本或列數無效');WeldEngine.analyze(s);switchUnit(s.displayUnit);setOutputUnit(s.outputUnit||'kgf');['basis','method','F','w','t1','t2'].forEach(k=>$(k).value=s[k]);$('circle').value=s.circle||0;$('circle-note').hidden=!s.circle;$('line-editor').hidden=!!s.circle;$('endloaded').checked=s.endLoaded===true;$('seg').innerHTML='';$('loads').innerHTML='';s.seg.forEach(a=>row('seg',a));WeldUnits.convertLoads(s.loads,'tf',activeUnit).forEach(a=>row('loads',a));calculate()}
$('load-example').onclick=()=>{loadState({version:1,displayUnit:activeUnit,outputUnit,basis:'TW',circle:0,method:'ASD',F:70,w:6,t1:12,t2:12,endLoaded:true,seg:[[0,0,0,30],[20,0,20,30]],loads:[[25,15,0,0,-10,0,0,0,0]]});$('preset').value='1';$('L').value=30;$('K').value=20;document.querySelector('[data-view="analysis"]').click();$('basis').focus();};
function download(content,name,type){let u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
$('add-seg').onclick=()=>{row('seg',[0,0,0,20]);calculate()};$('add-load').onclick=()=>{row('loads',[0,0,0,0,0,0,0,0,0]);calculate()};$('apply').onclick=preset;['basis','method','F','w','t1','t2','endloaded'].forEach(k=>$(k).addEventListener('input',calculate));$('export').onclick=()=>{if(!result){alert('請先修正輸入');return}download(JSON.stringify(state(),null,2),'焊接設計_輸入資料.json','application/json')};$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{let f=$('file').files[0];if(!f)return;if(f.size>1000000)throw Error('檔案需小於 1 MB');loadState(JSON.parse(await f.text()))}catch(e){alert(e.message)}$('file').value=''};$('print').onclick=()=>{if(!result){alert('請先修正輸入');return}window.print()};$('offline').onclick=()=>{const doc=document.documentElement.cloneNode(true),inputs=document.querySelectorAll('input'),clones=doc.querySelectorAll('input');inputs.forEach((v,i)=>{if(v.type!=='file')clones[i].setAttribute('value',v.value);if(v.checked)clones[i].setAttribute('checked','');else clones[i].removeAttribute('checked')});document.querySelectorAll('select').forEach((v,i)=>{const options=doc.querySelectorAll('select')[i].options;[...options].forEach((o,k)=>{o.toggleAttribute('selected',k===v.selectedIndex)})});download('<!doctype html>\n'+doc.outerHTML,'焊接分析設計_離線版.html','text/html;charset=utf-8')};
for(let b of document.querySelectorAll('[data-view]'))b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',String(x===b))});document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==b.dataset.view)};
function legacy(){legacyResult=null;$('export-legacy-docx').disabled=true;try{const val=id=>$(id).value.trim()===''?NaN:Number($(id).value),p={type:val('oldtype'),L:val('oldL'),K:val('oldK'),e:val('olde'),pv:val('oldPv')/WeldUnits.factor(activeUnit),ph:val('oldPh')/WeldUnits.factor(activeUnit),F:val('oldF'),displayUnit:activeUnit};legacyResult=LegacyEngine.analyze(p);const r=legacyResult;$('oldresult').innerHTML=`<p>a = ${fmt(r.a)}，k = ${fmt(r.k)}，C = ${fmt(r.C)}，Cθ = ${fmt(r.Ca)}</p><strong>原版需求焊腳 ${fmt(r.D)} mm</strong><p>僅重現附件查表公式，未作現行規範通過判定。尺寸需另在彈性分析頁檢核。</p>`;renderLegacyTrace(r);$('export-legacy-docx').disabled=false;}catch(e){$('oldresult').textContent=e.message;$('legacy-diagram').innerHTML='';}$('oldimage').src=LEGACY.images[Number($('oldtype').value)-1];}
['oldtype','oldL','oldK','olde','oldPv','oldPh','oldF'].forEach(k=>$(k).addEventListener('input',legacy));
// Restore current values when a downloaded HTML is opened, otherwise initialize examples.
if($('seg').rows.length){document.querySelectorAll('#seg tr,#loads tr').forEach(tr=>{tr.querySelectorAll('input').forEach(i=>i.addEventListener('input',calculate));tr.querySelector('button').onclick=()=>{tr.remove();calculate()}})}else{[[0,0,0,30],[20,0,20,30]].forEach(a=>row('seg',a));row('loads',[25,15,0,0,-10*WeldUnits.factor(activeUnit),0,0,0,0])}updateUnitLabels();calculate();legacy();

function updateUnitLabels(){
 document.querySelectorAll('[data-force-label]').forEach(e=>e.textContent=forceLabel());
 document.querySelectorAll('[data-moment-label]').forEach(e=>e.textContent=forceLabel()+'·m');
 document.querySelectorAll('#loads tr').forEach(tr=>tr.querySelectorAll('input').forEach((e,i)=>{if(i>=3){const u=forceLabel()+(i>=6?'·m':'');e.setAttribute('aria-label',fields.loads[i]+' '+u);e.title=fields.loads[i]+'：'+u+'，來源：結構分析載重組合';}}));
}
function switchUnit(next){
 const f=WeldUnits.factor(next)/WeldUnits.factor(activeUnit);
 document.querySelectorAll('#loads tr').forEach(tr=>tr.querySelectorAll('input').forEach((e,i)=>{if(i>=3&&e.value.trim()!=='')e.value=Number(e.value)*f;}));
 ['oldPv','oldPh'].forEach(id=>{if($(id).value.trim()!=='')$(id).value=Number($(id).value)*f;});
 activeUnit=next;$('force-unit').value=next;updateUnitLabels();
}
$('force-unit').onchange=()=>{switchUnit($('force-unit').value);calculate();legacy();};

function setOutputUnit(unit){WeldUnits.output(unit);outputUnit=unit;document.querySelectorAll('[data-output-unit]').forEach(e=>e.value=unit);}
document.querySelectorAll('[data-output-unit]').forEach(e=>e.onchange=()=>{setOutputUnit(e.value);calculate();});


$('export-docx').onclick=async()=>{try{if(!result)throw Error('請先修正輸入');const report=weldReport(weldSnapshot(result));await CalculationDocx.download(report,'焊接彈性分析詳細報告.docx');}catch(e){alert(e.message)}};
$('export-legacy-docx').onclick=async()=>{try{if(!legacyResult)throw Error('請先修正查表輸入');const report=legacyReport(structuredClone(legacyResult));await CalculationDocx.download(report,'焊接原版查表詳細報告.docx');}catch(e){alert(e.message)}};
