function weldSnapshot(r){return structuredClone({...r,diagramSvg:$('diagram').outerHTML});}
const weldNumber=v=>Number(v).toPrecision(12);
function weldReport(r){
 const s=r.trace.s,t=r.trace,n=weldNumber,steps=[],inputs=[],source=s.basis==='TW'?'鋼構造建築物鋼結構設計技術規範（99年版）第10.2節 https://glrs.moi.gov.tw/LawContent.aspx?id=GL000143':'ANSI/AISC 360-22 J2、J2.4、J2.5 https://www.aisc.org/aisc/explore-aisc/aisc-360/';
 const add=(title,formula,substitution,result,unit='',condition='',src=source)=>steps.push({title,formula,substitution,result,unit,condition,source:src});
 const simple={basis:['設計基準',''],method:['設計方法',''],F:['FEXX','ksi'],w:['等腳焊腳s','mm'],t1:['板厚t₁','mm'],t2:['板厚t₂','mm'],endLoaded:['端部受力長焊道',''],circle:['圓直徑','cm'],displayUnit:['輸入力單位',''],outputUnit:['顯示結果單位','']};
 Object.entries(simple).forEach(([k,[label,unit]])=>inputs.push({label,value:s[k]??'',unit}));
 (s.inputLoads||s.loads).forEach((row,i)=>row.forEach((value,j)=>inputs.push({label:`載重${i+1} ${['x','y','z','Px','Py','Pz','Mx','My','Mz'][j]}`,value,unit:j<3?'cm':j<6?(s.inputLoads?s.displayUnit:'tf'):(s.inputLoads?s.displayUnit+'·m':'tf·m')})));
 if(!r.radius)s.seg.forEach((row,i)=>row.forEach((value,j)=>inputs.push({label:`焊線${i+1} ${['x₁','y₁','x₂','y₂'][j]}`,value,unit:'cm'})));
 add('輸入與運算單位','座標cm×10→mm；tf×9806.65→N；tf·m×9806650→N·mm',`輸入顯示=${s.displayUnit||'tf'}；本次引擎載重統一tf／tf·m；kgf輸入先除1000，座標保持cm`,1,'','kg／公斤在本工具均代表公斤力kgf，非質量');
 if(r.radius){add('圓環解析幾何','R=直徑×5；L=2πR；Ix=Iy=πR³；Ixy=0；重心=(0,0)',`R=${s.circle}×5=${n(r.radius)}mm；L=2π×${n(r.radius)}=${n(r.L)}mm；Ix=Iy=π×${n(r.radius)}³=${n(r.Ix)}mm³`,r.J,'mm³','原快速配置的96弦段僅為預覽；實際群焊分析以圓環解析積分覆蓋幾何');}
 else{
  r.seg.forEach((a,i)=>{const q=t.inertias[i];add(`焊線${i+1}長度與中點`,'l=√[(X−x)²+(Y−y)²]；mx=(x+X)/2；my=(y+Y)/2',`端點cm×10→mm：(${a.x},${a.y})→(${a.X},${a.Y})；l=√[(${a.X}−${a.x})²+(${a.Y}−${a.y})²]；中點=(${n(a.mx)},${n(a.my)})`,a.l,'mm');add(`焊線${i+1}重心權重`,'Σl·mx；Σl·my；重心=Σl·m/L',`l·mx=${n(a.l)}×${n(a.mx)}=${n(a.l*a.mx)}；l·my=${n(a.l)}×${n(a.my)}=${n(a.l*a.my)}`,a.l,'mm','每條實體焊線只輸入一次；重疊及零長引擎拒絕');add(`焊線${i+1}慣性積貢獻`,'Ix=l(dy²/12+y²)；Iy=l(dx²/12+x²)；Ixy=l(dxdy/12+xy)',`dx=${q.dx}；dy=${q.dy}；x=mx−cx=${n(q.x)}；y=my−cy=${n(q.y)}；Ix=${n(a.l)}×(${q.dy}²/12+${n(q.y)}²)=${n(q.ix)}；Iy=${n(a.l)}×(${q.dx}²/12+${n(q.x)}²)=${n(q.iy)}；Ixy=${n(a.l)}×(${q.dx}×${q.dy}/12+${n(q.x)}×${n(q.y)})=${n(q.ixy)}`,q.Ixy,'mm³',`累計Ix=${n(q.Ix)}；Iy=${n(q.Iy)}；Ixy=${n(q.Ixy)}，均為單位喉厚线群慣性積`);});
  add('焊群重心與總長','L=Σl；cx=Σlmx/L；cy=Σlmy/L',`L=${r.seg.map(a=>n(a.l)).join('+')}=${n(r.L)}；cx=${n(r.seg.reduce((v,a)=>v+a.l*a.mx,0))}/${n(r.L)}=${n(r.cx)}；cy=${n(r.seg.reduce((v,a)=>v+a.l*a.my,0))}/${n(r.L)}`,r.L,'mm');
 }
 add('總慣性與耦合行列式','J=Ix+Iy；D=IxIy−Ixy²',`J=${n(r.Ix)}+${n(r.Iy)}=${n(r.J)}；D=${n(r.Ix)}×${n(r.Iy)}−${n(r.Ixy)}²`,t.D,'mm⁶','平面線焊群Ix/Iy/Ixy/J的單位為mm³');
 t.loads.forEach((a,i)=>{const orig=s.loads[i];add(`載重${i+1}力與偏心座標`,'X=xcm×10−cx；Y=ycm×10−cy；Z=zcm×10；F=tf×9806.65',`X=${orig[0]}×10−${n(r.cx)}=${n(a.x)}；Y=${orig[1]}×10−${n(r.cy)}=${n(a.y)}；Z=${orig[2]}×10=${n(a.z)}；Fx=${orig[3]}×9806.65=${n(a.fx)}；Fy=${orig[4]}×9806.65=${n(a.fy)}；Fz=${orig[5]}×9806.65=${n(a.fz)}`,a.pz,'N',`累計Px=${n(a.px)}；Py=${n(a.py)}；Pz=${n(a.pz)}`);add(`載重${i+1}重心矩`,'ΔMx=MX×9806650+YFz−ZFy；ΔMy=MY×9806650+ZFx−XFz；ΔMz=MZ×9806650+XFy−YFx',`ΔMx=${a.MX}×9806650+${n(a.y)}×${n(a.fz)}−${n(a.z)}×${n(a.fy)}=${n(a.dmx)}；ΔMy=${a.MY}×9806650+${n(a.z)}×${n(a.fx)}−${n(a.x)}×${n(a.fz)}=${n(a.dmy)}；ΔMz=${a.MZ}×9806650+${n(a.x)}×${n(a.fy)}−${n(a.y)}×${n(a.fx)}=${n(a.dmz)}`,a.mz,'N·mm',`累計Mx=${n(a.mx)}；My=${n(a.my)}；Mz=${n(a.mz)}；自由力矩與偏心力矩同時按本次輸入計入`);});
 if(t.branch==='full-inertia')add('完整面外彎曲係數','A=(−MyIx−MxIxy)/D；B=(MxIy+MyIxy)/D',`A=(−${n(r.my)}×${n(r.Ix)}−${n(r.mx)}×${n(r.Ixy)})/${n(t.D)}=${n(t.A)}；B=(${n(r.mx)}×${n(r.Iy)}+${n(r.my)}×${n(r.Ixy)})/${n(t.D)}`,t.B,'N/mm²',`分支D>1e−10×max(IxIy,1)；完整慣性積耦合`);
 else if(t.branch==='rank-deficient')add('共線退化幾何可抵抗分支','tr=Ix+Iy；A=(−MyIy+MxIxy)/tr²；B=(−MyIxy+MxIx)/tr²',`tr=${n(t.tr)}；A=(−${n(r.my)}×${n(r.Iy)}+${n(r.mx)}×${n(r.Ixy)})/${n(t.tr)}²=${n(t.A)}；B=(−${n(r.my)}×${n(r.Ixy)}+${n(r.mx)}×${n(r.Ix)})/${n(t.tr)}²`,t.B,'N/mm²','D≤1e−10×max(IxIy,1)；抵抗殘差須≤1e−7×max(1,hypot(Mx,My))，否則引擎拒絕');
 else add('無面外彎矩分支','若|Mx|+|My|≤1e−7則A=B=0',`|${n(r.mx)}|+|${n(r.my)}|≤1e−7`,0,'N/mm²','扭矩仍按J分析；J不足且|Mz|>1e−7拒絕');
 if(t.ring){add('圓環控制角搜尋','先取720點 t=iπ/360，再最佳取樣點±π/360三分搜尋70次',`最佳索引=${t.ring.bestIndex}；取樣q=${n(t.ring.sampledQ)}N/mm；初始角括區=[${t.ring.initialBracket.map(n).join(',')}]rad；最後=[${t.ring.finalBracket.map(n).join(',')}]rad`,t.ring.angle,'rad','連續圆環模型，不代表空間管交焊道；如實揭露現有控制點搜尋');add('圓環實際中間搜尋','a=lo+(hi−lo)/3；b=hi−(hi−lo)/3；qa<qb則lo=a，否則hi=b',t.ring.samples.map(q=>`第${q.iteration}次a=${n(q.a)}、b=${n(q.b)}、qa=${n(q.qa)}、qb=${n(q.qb)}、${q.branch}`).join('；'),t.ring.angle,'rad','顯示第1–3與68–70次實際取樣');}
 r.ends.forEach((e,index)=>{const {X,Y}=t.endOffsets[index];add(`焊線${e.i} ${r.radius?'圓環控制點':'端點'+e.end}線力`,'qx=Px/L−MzY/J；qy=Py/L+MzX/J；qz=Pz/L+AX+BY；q=√(qx²+qy²+qz²)',`X=${e.x}×10−${n(r.cx)}=${n(X)}；Y=${e.y}×10−${n(r.cy)}=${n(Y)}；qx=${n(r.px)}/${n(r.L)}−${n(r.mz)}×${n(Y)}/${n(r.J)}=${n(e.qx)}；qy=${n(r.py)}/${n(r.L)}+${n(r.mz)}×${n(X)}/${n(r.J)}=${n(e.qy)}；qz=${n(r.pz)}/${n(r.L)}+${n(t.A)}×${n(X)}+${n(t.B)}×${n(Y)}=${n(e.qz)}；q=√[${n(e.qx)}²+${n(e.qy)}²+${n(e.qz)}²]`,e.q,'N/mm',e.i===r.critical.i&&e.end===r.critical.end?'本次控制點（同值時原引擎選后者）':'實際檢查端點');});
 add('焊材強度與設計容量',s.method==='ASD'?'fd=0.60FEXX×6.894757293168/2':'fd=0.75×0.60FEXX×6.894757293168',`${t.factor}×${s.F}×6.894757293168`,r.fd,'MPa',`${s.method}：${s.method==='ASD'?'服務載重，Ω=2':'已係數化載重，φ=0.75'}；不再乘載重係數，未採方向強度增益`);
 add('喉厚與每長度容量','te=s/√2；容量=fd·te',`te=${s.w}/√2=${n(r.throat)}mm；${n(r.fd)}×${n(r.throat)}`,r.capacity,'N/mm');
 add('強度需求與利用率','s所需=qmax/(fd/√2)；ratio=qmax/容量',`qmax=${n(r.critical.q)}，焊線${r.critical.i}/端點${r.critical.end}；${n(r.critical.q)}/(${n(r.fd)}/√2)=${n(r.req)}mm；ratio=${n(r.critical.q)}/${n(r.capacity)}`,r.ratio,'','強度判定使用ratio≤1+1e−10；输出顯示取整不影响判定');
 add('最小焊腳控制','厚板=max(t₁,t₂)；≤6/≤12/≤19/>19 mm對應最小s=3/5/6/8mm',`厚板=max(${s.t1},${s.t2})=${t.thick}；本次最小=${r.min}；s=${s.w}`,r.min,'mm','較厚板保守包絡，不采薄板例外');
 add('最大板邊焊腳控制',s.basis==='TW'?'薄板<6時max=薄板，否則薄板−1.5mm':'薄板<6時max=薄板，否則薄板−2mm',`薄板=min(${s.t1},${s.t2})=${t.thin}；本次最大=${r.max}；s=${s.w}`,r.max,'mm','未採板邊滿焊例外');
 add('有效長與長焊道限制','每焊線l≥4s；端部受力且任一l>100s停止通過',`4s=4×${s.w}=${4*s.w}mm；100s=${100*s.w}mm；實際有效長=${r.radius?n(r.L):r.seg.map(a=>n(a.l)).join('/')}；long=${r.long}；endLoaded=${s.endLoaded}`,r.long?'長焊線':'一般有效長','','长焊道未自动折減；若超限需另分析不得用本次結果宣告通過');
 const out=WeldUnits.output(s.outputUnit||'kgf');add('本次顯示結果換算','需求顯示=qmax/結果線力係數',`${n(r.critical.q)}/${out.line}`,r.critical.q/out.line,out.lineUnit,'內部N/mm；顯示結果單位'+s.outputUnit+'；計算全精度，報告12位有效數字，畫面常用3位小數');
 const tables=[{title:'本次端點線力比較',headers:['焊線','端點','x cm','y cm','qx N/mm','qy N/mm','qz N/mm','q N/mm'],rows:r.ends.map(e=>[e.i,e.end,n(e.x),n(e.y),n(e.qx),n(e.qy),n(e.qz),n(e.q)]),source:'WeldEngine本次實際端點／圓環控制點',note:'表內數字顯示12位有效數字；判定使用完整精度。'},{title:'最小焊腳來源尺寸表',headers:['較厚板厚mm','最小焊腳mm'],rows:[['≤6',3],['>6且≤12',5],['>12且≤19',6],['>19',8]],source,note:'本工具保守共同尺寸檢核，不採較薄板例外或滿焊例外。'}];
 return {title:'焊接彈性分析詳細報告',summary:`${s.basis}／${s.method}，焊材與列出的尺寸${r.pass?'符合':'不符合'}。母材、局部偏心、疲勞、耐震、施工品質及接合部整體仍須另行檢核。`,valid:true,inputs,steps,tables,diagram:{svg:r.diagramSvg,width:540,height:340,caption:'本次XY焊線、重心、控制點及作用載重；座標cm，正Z朝螢幕外。'},conclusions:r.checks.map(c=>`${c.name}：${c.ok?'符合':'不符合'}；${c.value}`).concat(['單項結果不代表完整接合部設計完成。'])};
}
function legacyDiagram(r){const p=r.p,t=r.trace,n=weldNumber;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 540 650" role="img" aria-label="原配置圖及本次查表輸入"><rect width="540" height="650" fill="white"/><text x="16" y="25" font-size="16">附件第${p.type}型：L=${p.L}cm；K=${p.K}cm；e=${p.e}cm</text><text x="16" y="48" font-size="14">Pv=${p.pv}tf；Ph=${p.ph}tf；a=${n(r.a)}；k=${n(r.k)}</text><image href="${LEGACY.images[p.type-1]}" x="20" y="62" width="500" height="470" preserveAspectRatio="xMidYMid meet"/><text x="16" y="553" font-size="13">表型${p.type}：a列${t.i+1}/${t.i+2}；k欄${t.j+1}/${t.j+2}</text><text x="16" y="576" font-size="13">u=${n(t.u)}；v=${n(t.v)}；C=${n(r.C)}</text><text x="16" y="600" font-size="13">方向修正Cθ=${n(r.Ca)}；需求焊腳D=${n(r.D)}mm</text><text x="16" y="626" font-size="13">僅原版歷史模型比對，不作現行合格判定</text></svg>`;}
function legacyReport(r){
 const {p,trace:t}=r,n=weldNumber,steps=[],source=`附件Form1.vb cws() 第${p.type}型，LEGACY.tables[${p.type-1}]／原PNG配置圖；歷史比對用途，非現行認證`,add=(title,formula,substitution,result,unit='',condition='')=>steps.push({title,formula,substitution,result,unit,condition,source});
 const inputs=Object.entries(p).map(([label,value])=>({label,value,unit:['L','K','e'].includes(label)?'cm':['pv','ph'].includes(label)?'tf':label==='F'?'ksi':''}));
 add('輸入力換算','Pv/Ph(tf)=本次顯示值/單位係數',`顯示單位=${p.displayUnit}；係數=${WeldUnits.factor(p.displayUnit)}；Pv=${p.pv*WeldUnits.factor(p.displayUnit)}/${WeldUnits.factor(p.displayUnit)}=${p.pv}tf；Ph=${p.ph*WeldUnits.factor(p.displayUnit)}/${WeldUnits.factor(p.displayUnit)}`,p.pv,'tf','僅正向Pv、Ph；空值、負值或超範圍不匯出');
 add('幾何參數k',p.type===2?'第2型k固定0':'k=K/L',p.type===2?`第2型，K=${p.K}但查表k=0`:`${p.K}/${p.L}`,r.k,'','1–3、6–9型k表0–2；4–5型只用0–1');
 add('重心距離修正x',p.type<=5?'x=0':p.type<=7?'x=K²/(2K+L)':'x=K²/[2(K+L)]',p.type<=5?'第1–5型不作重心距修正':p.type<=7?`${p.K}²/(2×${p.K}+${p.L})`:`${p.K}²/[2×(${p.K}+${p.L})]`,t.x,'cm','此處x為距離cm，對應原圖重心距xL；a/k為無因次。');
 add('偏心無因次a',p.type===7||p.type===9?'a=(e+x)/L':p.type===6||p.type===8?'a=(e−x)/L':'a=e/L',`(${p.e}${[7,9].includes(p.type)?'+':[6,8].includes(p.type)?'−':'+0×'}${n(t.x)})/${p.L}`,r.a,'','6/8型減重心距，7/9型加；禁止a<0.06或a>3外插');
 add('本次夾取表列與欄','aᵢ≤a≤aᵢ₊₁；kⱼ≤k≤kⱼ₊₁',`型${p.type}；原表1起算列=${t.i+1}/${t.i+2}，a=${t.aRows.join('/')};欄=${t.j+1}/${t.j+2}，k=${t.kCols.join('/')}`,`${t.i+1}/${t.i+2}列；${t.j+1}/${t.j+2}欄`,'','含端點；落在共同邊界取第一個相符區間，禁止外插');
 add('雙線性座標權重','u=(a−aᵢ)/(aᵢ₊₁−aᵢ)；v=(k−kⱼ)/(kⱼ₊₁−kⱼ)',`u=(${n(r.a)}−${t.aRows[0]})/(${t.aRows[1]}−${t.aRows[0]})=${n(t.u)}；v=(${n(r.k)}−${t.kCols[0]})/(${t.kCols[1]}−${t.kCols[0]})`,t.v,'','u/v在0–1內）；沒有夾取超範圍值');
 add('四格原係數與權重','C₀₀、C₀₁、C₁₀、C₁₁；w=(1−u)(1−v)、(1−u)v、u(1−v)、uv',t.corners.map((c,i)=>`C${['00','01','10','11'][i]}=${c}；w=${n(t.weights[i])}`).join('；'),t.weights.reduce((a,b)=>a+b,0),'','四格均来自本次型式原係數表；權重總和1');
 add('實際雙線性內插','C=(1−u)[(1−v)C₀₀+vC₀₁]+u[(1−v)C₁₀+vC₁₁]',`(1−${n(t.u)})[(1−${n(t.v)})×${t.corners[0]}+${n(t.v)}×${t.corners[1]}]+${n(t.u)}[(1−${n(t.v)})×${t.corners[2]}+${n(t.v)}×${t.corners[3]}]`,r.C,'','C≤0或缺格停止，不進行現行規範判定');
 add('合力原換算及方向角','P=√(Pv²+Ph²)×2.2046；θ=atan2(Ph,Pv)',`√(${p.pv}²+${p.ph}²)×2.2046=${n(t.P)}；atan2(${p.ph},${p.pv})=${n(t.theta)}rad`,t.P,'kip（原常數）','2.2046為舊程式力換算常數，與現代SI彈性引擎分開，不無據更改');
 add('方向修正上限參考cmx','cmx=0.928×型式函數',`.928×${p.type<=3?'2':p.type<=5?`(2+2×${n(r.k)})`:p.type<=7?`(1+2×${n(r.k)})`:`(1+${n(r.k)})`}`,t.cmx,'');
 add('方向修正中間比AA','AA=max(1,cmx/C)',`max(1,${n(t.cmx)}/${n(r.C)})`,t.AA,'','保留原比值下限1');
 add('方向修正係數Cθ','Cθ=C×max[1,AA/(sinθ+AAcosθ)]',`${n(r.C)}×max[1,${n(t.AA)}/(sin(${n(t.theta)})+${n(t.AA)}cos(${n(t.theta)}))]`,r.Ca,'','正向載重，原方向增益模型；與彈性模型不合併');
 add('焊材分類修正C1','依FEXX列取C1：60/70/80/90/100/110→0.857/1/1.14/1.29/1.43/1.57',`本次E${p.F}列`,t.C1,'','原表離散係數，不做分類間內插');
 add('原需求焊腳完整換算','D=P/(CθC1L×0.3937)×25.4/16',`${n(t.P)}/(${n(r.Ca)}×${t.C1}×${p.L}×.3937)×25.4/16；分母=${n(t.denominator)}`,r.D,'mm','L cm→in以原常數.3937；原1/16in焊腳單位→mm乘25.4/16；無取整，僅歷史比對');
 const tables=[{title:`第${p.type}型本次查表四格來源`,headers:['原表列／a值',`第${t.j+1}欄 k=${t.kCols[0]}`,`第${t.j+2}欄 k=${t.kCols[1]}`],rows:[[`${t.i+1} / ${t.aRows[0]}`,t.corners[0],t.corners[1]],[`${t.i+2} / ${t.aRows[1]}`,t.corners[2],t.corners[3]]],source,note:'此四格直接取自同一次計算的原表；下表列出該型完整有效欄。'},{title:`附件第${p.type}型完整原係數表`,headers:['a / k',...t.kk],rows:t.aa.map((a,i)=>[a,...t.tab[i].slice(0,t.kk.length)]),source,note:'4/5型k僅0–1；其他型k0–2。圖示、a與k定義依原附件，不改表值。'},{title:'原焊材係數表',headers:['E分類','C1'],rows:[[60,.857],[70,1],[80,1.14],[90,1.29],[100,1.43],[110,1.57]],source}];
 return {title:'焊接原版查表詳細報告',summary:`附件第${p.type}型：原式需求焊腳${n(r.D)}mm。此報告只重現歷史圖表模型，未作現行合格判定。`,valid:true,inputs,steps,tables,diagram:{svg:legacyDiagram(r),width:540,height:650,caption:'原PNG配置圖完整保留；圖外文字標示本次L/K/e/Pv/Ph、夾取列欄和內插結果。'},conclusions:['原版查表比對，沒有現行規範合格結論。','尺寸、母材、整體接合、焊接品質與適用規範仍須另行檢核。']};
}
function traceHtml(report){return report.steps.map((s,i)=>`<details class="trace-step" ${i===0?'open':''}><summary>${i+1} ${esc(s.title)}</summary><p>${esc(s.formula)}</p><p>${esc(s.substitution)}</p><p>＝${esc(s.result)} ${esc(s.unit)}</p><p>${esc(s.condition)}</p><small>${esc(s.source)}</small></details>`).join('')+report.tables.map(t=>`<details><summary>${esc(t.title)}</summary><p>${esc(t.source||'')} ${esc(t.note||'')}</p><div class="table-wrap"><table><tr>${t.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr>${t.rows.map(row=>'<tr>'+row.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>').join('')}</table></div></details>`).join('');}
function renderWeldTrace(r){$('details').innerHTML+='<h3>本次完整運算代入</h3>'+traceHtml(weldReport(weldSnapshot(r)));}
function renderLegacyTrace(r){const report=legacyReport(structuredClone(r));$('oldresult').innerHTML+=traceHtml(report);$('legacy-diagram').innerHTML=report.diagram.svg;}
